package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arcczg generated by hbm2java
 */
@Entity
@Table(name="ARCCZG"
    ,schema="DESA46"
)
public class Arcczg  implements java.io.Serializable {


     private ArcczgId id;
     private String descripcion;

    public Arcczg() {
    }

	
    public Arcczg(ArcczgId id) {
        this.id = id;
    }
    public Arcczg(ArcczgId id, String descripcion) {
       this.id = id;
       this.descripcion = descripcion;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="zona", column=@Column(name="ZONA", nullable=false, length=5) ) } )
    public ArcczgId getId() {
        return this.id;
    }
    
    public void setId(ArcczgId id) {
        this.id = id;
    }

    
    @Column(name="DESCRIPCION", length=25)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


