package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arcctd generated by hbm2java
 */
@Entity
@Table(name="ARCCTD"
    ,schema="DESA46"
)
public class Arcctd  implements java.io.Serializable {


     private ArcctdId id;
     private String tipoMov;
     private String descripcion;
     private String afectaSaldo;
     private String cobroVendedor;
     private String conjuntar;
     private String cksDev;
     private String factura;
     private String ajuste;
     private String ctaContrapartida;
     private String formulario;
     private String afectaLibro;
     private String formularioCtrl;
     private String codDiario;
     private String comportamientoImp;
     private String cksPos;
     private String claseDoc;
     private String conceptoDefault;
     private String disminuyeComision;
     private String disminuyeComisionCob;
     private String giro;
     private String descuentoPp;
     private String ajusteVendedor;
     private BigDecimal factor;

    public Arcctd() {
    }

	
    public Arcctd(ArcctdId id) {
        this.id = id;
    }
    public Arcctd(ArcctdId id, String tipoMov, String descripcion, String afectaSaldo, String cobroVendedor, String conjuntar, String cksDev, String factura, String ajuste, String ctaContrapartida, String formulario, String afectaLibro, String formularioCtrl, String codDiario, String comportamientoImp, String cksPos, String claseDoc, String conceptoDefault, String disminuyeComision, String disminuyeComisionCob, String giro, String descuentoPp, String ajusteVendedor, BigDecimal factor) {
       this.id = id;
       this.tipoMov = tipoMov;
       this.descripcion = descripcion;
       this.afectaSaldo = afectaSaldo;
       this.cobroVendedor = cobroVendedor;
       this.conjuntar = conjuntar;
       this.cksDev = cksDev;
       this.factura = factura;
       this.ajuste = ajuste;
       this.ctaContrapartida = ctaContrapartida;
       this.formulario = formulario;
       this.afectaLibro = afectaLibro;
       this.formularioCtrl = formularioCtrl;
       this.codDiario = codDiario;
       this.comportamientoImp = comportamientoImp;
       this.cksPos = cksPos;
       this.claseDoc = claseDoc;
       this.conceptoDefault = conceptoDefault;
       this.disminuyeComision = disminuyeComision;
       this.disminuyeComisionCob = disminuyeComisionCob;
       this.giro = giro;
       this.descuentoPp = descuentoPp;
       this.ajusteVendedor = ajusteVendedor;
       this.factor = factor;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="tipo", column=@Column(name="TIPO", nullable=false, length=2) ) } )
    public ArcctdId getId() {
        return this.id;
    }
    
    public void setId(ArcctdId id) {
        this.id = id;
    }

    
    @Column(name="TIPO_MOV", length=1)
    public String getTipoMov() {
        return this.tipoMov;
    }
    
    public void setTipoMov(String tipoMov) {
        this.tipoMov = tipoMov;
    }

    
    @Column(name="DESCRIPCION", length=35)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="AFECTA_SALDO", length=1)
    public String getAfectaSaldo() {
        return this.afectaSaldo;
    }
    
    public void setAfectaSaldo(String afectaSaldo) {
        this.afectaSaldo = afectaSaldo;
    }

    
    @Column(name="COBRO_VENDEDOR", length=1)
    public String getCobroVendedor() {
        return this.cobroVendedor;
    }
    
    public void setCobroVendedor(String cobroVendedor) {
        this.cobroVendedor = cobroVendedor;
    }

    
    @Column(name="CONJUNTAR", length=1)
    public String getConjuntar() {
        return this.conjuntar;
    }
    
    public void setConjuntar(String conjuntar) {
        this.conjuntar = conjuntar;
    }

    
    @Column(name="CKS_DEV", length=1)
    public String getCksDev() {
        return this.cksDev;
    }
    
    public void setCksDev(String cksDev) {
        this.cksDev = cksDev;
    }

    
    @Column(name="FACTURA", length=1)
    public String getFactura() {
        return this.factura;
    }
    
    public void setFactura(String factura) {
        this.factura = factura;
    }

    
    @Column(name="AJUSTE", length=1)
    public String getAjuste() {
        return this.ajuste;
    }
    
    public void setAjuste(String ajuste) {
        this.ajuste = ajuste;
    }

    
    @Column(name="CTA_CONTRAPARTIDA", length=15)
    public String getCtaContrapartida() {
        return this.ctaContrapartida;
    }
    
    public void setCtaContrapartida(String ctaContrapartida) {
        this.ctaContrapartida = ctaContrapartida;
    }

    
    @Column(name="FORMULARIO", length=10)
    public String getFormulario() {
        return this.formulario;
    }
    
    public void setFormulario(String formulario) {
        this.formulario = formulario;
    }

    
    @Column(name="AFECTA_LIBRO", length=1)
    public String getAfectaLibro() {
        return this.afectaLibro;
    }
    
    public void setAfectaLibro(String afectaLibro) {
        this.afectaLibro = afectaLibro;
    }

    
    @Column(name="FORMULARIO_CTRL", length=10)
    public String getFormularioCtrl() {
        return this.formularioCtrl;
    }
    
    public void setFormularioCtrl(String formularioCtrl) {
        this.formularioCtrl = formularioCtrl;
    }

    
    @Column(name="COD_DIARIO", length=5)
    public String getCodDiario() {
        return this.codDiario;
    }
    
    public void setCodDiario(String codDiario) {
        this.codDiario = codDiario;
    }

    
    @Column(name="COMPORTAMIENTO_IMP", length=1)
    public String getComportamientoImp() {
        return this.comportamientoImp;
    }
    
    public void setComportamientoImp(String comportamientoImp) {
        this.comportamientoImp = comportamientoImp;
    }

    
    @Column(name="CKS_POS", length=1)
    public String getCksPos() {
        return this.cksPos;
    }
    
    public void setCksPos(String cksPos) {
        this.cksPos = cksPos;
    }

    
    @Column(name="CLASE_DOC", length=1)
    public String getClaseDoc() {
        return this.claseDoc;
    }
    
    public void setClaseDoc(String claseDoc) {
        this.claseDoc = claseDoc;
    }

    
    @Column(name="CONCEPTO_DEFAULT", length=2)
    public String getConceptoDefault() {
        return this.conceptoDefault;
    }
    
    public void setConceptoDefault(String conceptoDefault) {
        this.conceptoDefault = conceptoDefault;
    }

    
    @Column(name="DISMINUYE_COMISION", length=1)
    public String getDisminuyeComision() {
        return this.disminuyeComision;
    }
    
    public void setDisminuyeComision(String disminuyeComision) {
        this.disminuyeComision = disminuyeComision;
    }

    
    @Column(name="DISMINUYE_COMISION_COB", length=1)
    public String getDisminuyeComisionCob() {
        return this.disminuyeComisionCob;
    }
    
    public void setDisminuyeComisionCob(String disminuyeComisionCob) {
        this.disminuyeComisionCob = disminuyeComisionCob;
    }

    
    @Column(name="GIRO", length=1)
    public String getGiro() {
        return this.giro;
    }
    
    public void setGiro(String giro) {
        this.giro = giro;
    }

    
    @Column(name="DESCUENTO_PP", length=1)
    public String getDescuentoPp() {
        return this.descuentoPp;
    }
    
    public void setDescuentoPp(String descuentoPp) {
        this.descuentoPp = descuentoPp;
    }

    
    @Column(name="AJUSTE_VENDEDOR", length=1)
    public String getAjusteVendedor() {
        return this.ajusteVendedor;
    }
    
    public void setAjusteVendedor(String ajusteVendedor) {
        this.ajusteVendedor = ajusteVendedor;
    }

    
    @Column(name="FACTOR", precision=17)
    public BigDecimal getFactor() {
        return this.factor;
    }
    
    public void setFactor(BigDecimal factor) {
        this.factor = factor;
    }




}


