package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arccaux1 generated by hbm2java
 */
@Entity
@Table(name="ARCCAUX1"
    ,schema="DESA46"
)
public class Arccaux1  implements java.io.Serializable {


     private Arccaux1Id id;
     private BigDecimal saldo;
     private Date fecha;
     private Date fechaVence;
     private String moneda;
     private String ajusteONd;

    public Arccaux1() {
    }

	
    public Arccaux1(Arccaux1Id id) {
        this.id = id;
    }
    public Arccaux1(Arccaux1Id id, BigDecimal saldo, Date fecha, Date fechaVence, String moneda, String ajusteONd) {
       this.id = id;
       this.saldo = saldo;
       this.fecha = fecha;
       this.fechaVence = fechaVence;
       this.moneda = moneda;
       this.ajusteONd = ajusteONd;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="centro", column=@Column(name="CENTRO", nullable=false, length=2) ), 
        @AttributeOverride(name="tipoDoc", column=@Column(name="TIPO_DOC", nullable=false, length=2) ), 
        @AttributeOverride(name="periodo", column=@Column(name="PERIODO", nullable=false, length=4) ), 
        @AttributeOverride(name="ruta", column=@Column(name="RUTA", nullable=false, length=4) ), 
        @AttributeOverride(name="noDocu", column=@Column(name="NO_DOCU", nullable=false, length=12) ), 
        @AttributeOverride(name="grupo", column=@Column(name="GRUPO", nullable=false, length=2) ), 
        @AttributeOverride(name="noCliente", column=@Column(name="NO_CLIENTE", nullable=false, length=15) ) } )
    public Arccaux1Id getId() {
        return this.id;
    }
    
    public void setId(Arccaux1Id id) {
        this.id = id;
    }

    
    @Column(name="SALDO", precision=17)
    public BigDecimal getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(BigDecimal saldo) {
        this.saldo = saldo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", length=7)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_VENCE", length=7)
    public Date getFechaVence() {
        return this.fechaVence;
    }
    
    public void setFechaVence(Date fechaVence) {
        this.fechaVence = fechaVence;
    }

    
    @Column(name="MONEDA", length=1)
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }

    
    @Column(name="AJUSTE_O_ND", length=1)
    public String getAjusteONd() {
        return this.ajusteONd;
    }
    
    public void setAjusteONd(String ajusteONd) {
        this.ajusteONd = ajusteONd;
    }




}


