package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArccteId generated by hbm2java
 */
@Embeddable
public class ArccteId  implements java.io.Serializable {


     private String noCia;
     private String tipoDoc;
     private String codEstado;

    public ArccteId() {
    }

    public ArccteId(String noCia, String tipoDoc, String codEstado) {
       this.noCia = noCia;
       this.tipoDoc = tipoDoc;
       this.codEstado = codEstado;
    }
   


    @Column(name="NO_CIA", nullable=false, length=2)
    public String getNoCia() {
        return this.noCia;
    }
    
    public void setNoCia(String noCia) {
        this.noCia = noCia;
    }


    @Column(name="TIPO_DOC", nullable=false, length=2)
    public String getTipoDoc() {
        return this.tipoDoc;
    }
    
    public void setTipoDoc(String tipoDoc) {
        this.tipoDoc = tipoDoc;
    }


    @Column(name="COD_ESTADO", nullable=false, length=2)
    public String getCodEstado() {
        return this.codEstado;
    }
    
    public void setCodEstado(String codEstado) {
        this.codEstado = codEstado;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArccteId) ) return false;
		 ArccteId castOther = ( ArccteId ) other; 
         
		 return ( (this.getNoCia()==castOther.getNoCia()) || ( this.getNoCia()!=null && castOther.getNoCia()!=null && this.getNoCia().equals(castOther.getNoCia()) ) )
 && ( (this.getTipoDoc()==castOther.getTipoDoc()) || ( this.getTipoDoc()!=null && castOther.getTipoDoc()!=null && this.getTipoDoc().equals(castOther.getTipoDoc()) ) )
 && ( (this.getCodEstado()==castOther.getCodEstado()) || ( this.getCodEstado()!=null && castOther.getCodEstado()!=null && this.getCodEstado().equals(castOther.getCodEstado()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNoCia() == null ? 0 : this.getNoCia().hashCode() );
         result = 37 * result + ( getTipoDoc() == null ? 0 : this.getTipoDoc().hashCode() );
         result = 37 * result + ( getCodEstado() == null ? 0 : this.getCodEstado().hashCode() );
         return result;
   }   


}


