package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arccgr generated by hbm2java
 */
@Entity
@Table(name="ARCCGR"
    ,schema="DESA46"
)
public class Arccgr  implements java.io.Serializable {


     private ArccgrId id;
     private String moneda;
     private String descripcion;
     private String ctaCliente;
     private String ctaDpp;

    public Arccgr() {
    }

	
    public Arccgr(ArccgrId id) {
        this.id = id;
    }
    public Arccgr(ArccgrId id, String moneda, String descripcion, String ctaCliente, String ctaDpp) {
       this.id = id;
       this.moneda = moneda;
       this.descripcion = descripcion;
       this.ctaCliente = ctaCliente;
       this.ctaDpp = ctaDpp;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="grupo", column=@Column(name="GRUPO", nullable=false, length=2) ) } )
    public ArccgrId getId() {
        return this.id;
    }
    
    public void setId(ArccgrId id) {
        this.id = id;
    }

    
    @Column(name="MONEDA", length=1)
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }

    
    @Column(name="DESCRIPCION", length=25)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="CTA_CLIENTE", length=15)
    public String getCtaCliente() {
        return this.ctaCliente;
    }
    
    public void setCtaCliente(String ctaCliente) {
        this.ctaCliente = ctaCliente;
    }

    
    @Column(name="CTA_DPP", length=15)
    public String getCtaDpp() {
        return this.ctaDpp;
    }
    
    public void setCtaDpp(String ctaDpp) {
        this.ctaDpp = ctaDpp;
    }




}


