package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arcccc generated by hbm2java
 */
@Entity
@Table(name="ARCCCC"
    ,schema="DESA46"
)
public class Arcccc  implements java.io.Serializable {


     private ArccccId id;

    public Arcccc() {
    }

    public Arcccc(ArccccId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="grupo", column=@Column(name="GRUPO", nullable=false, length=2) ), 
        @AttributeOverride(name="noCliente", column=@Column(name="NO_CLIENTE", nullable=false, length=15) ), 
        @AttributeOverride(name="centro", column=@Column(name="CENTRO", nullable=false, length=2) ) } )
    public ArccccId getId() {
        return this.id;
    }
    
    public void setId(ArccccId id) {
        this.id = id;
    }




}


