package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arccru generated by hbm2java
 */
@Entity
@Table(name="ARCCRU"
    ,schema="DESA46"
)
public class Arccru  implements java.io.Serializable {


     private ArccruId id;
     private Date fechacreacion;
     private String tipogrupo;
     private String gruporuta;
     private String tiporuta;
     private BigDecimal presupuestado;
     private BigDecimal vendido;
     private String descripcion;
     private String centro;
     private String vendedor;
     private String ctaEfectivo;
     private String ctaDescFinanciero;
     private String tipo;
     private String factActualizaInv;
     private String cajeroActual;
     private Integer contTurnos;
     private Integer noCierreCaja;
     private String bodegaDef;
     private String tipoPrecioDef;
     private String noAutorizacionRenta;
     private Date FProceso;
     private String indCosteoEfectuado;
     private String tipoCajon;
     private String puertoCajon;
     private String puertoImpresora;
     private String secuenciaAbreCajon;
     private Date FUltCierre;
     private String indCortePapel;
     private Date tstamp;

    public Arccru() {
    }

	
    public Arccru(ArccruId id) {
        this.id = id;
    }
    public Arccru(ArccruId id, Date fechacreacion, String tipogrupo, String gruporuta, String tiporuta, BigDecimal presupuestado, BigDecimal vendido, String descripcion, String centro, String vendedor, String ctaEfectivo, String ctaDescFinanciero, String tipo, String factActualizaInv, String cajeroActual, Integer contTurnos, Integer noCierreCaja, String bodegaDef, String tipoPrecioDef, String noAutorizacionRenta, Date FProceso, String indCosteoEfectuado, String tipoCajon, String puertoCajon, String puertoImpresora, String secuenciaAbreCajon, Date FUltCierre, String indCortePapel, Date tstamp) {
       this.id = id;
       this.fechacreacion = fechacreacion;
       this.tipogrupo = tipogrupo;
       this.gruporuta = gruporuta;
       this.tiporuta = tiporuta;
       this.presupuestado = presupuestado;
       this.vendido = vendido;
       this.descripcion = descripcion;
       this.centro = centro;
       this.vendedor = vendedor;
       this.ctaEfectivo = ctaEfectivo;
       this.ctaDescFinanciero = ctaDescFinanciero;
       this.tipo = tipo;
       this.factActualizaInv = factActualizaInv;
       this.cajeroActual = cajeroActual;
       this.contTurnos = contTurnos;
       this.noCierreCaja = noCierreCaja;
       this.bodegaDef = bodegaDef;
       this.tipoPrecioDef = tipoPrecioDef;
       this.noAutorizacionRenta = noAutorizacionRenta;
       this.FProceso = FProceso;
       this.indCosteoEfectuado = indCosteoEfectuado;
       this.tipoCajon = tipoCajon;
       this.puertoCajon = puertoCajon;
       this.puertoImpresora = puertoImpresora;
       this.secuenciaAbreCajon = secuenciaAbreCajon;
       this.FUltCierre = FUltCierre;
       this.indCortePapel = indCortePapel;
       this.tstamp = tstamp;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="codigo", column=@Column(name="CODIGO", nullable=false, length=4) ) } )
    public ArccruId getId() {
        return this.id;
    }
    
    public void setId(ArccruId id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHACREACION", length=7)
    public Date getFechacreacion() {
        return this.fechacreacion;
    }
    
    public void setFechacreacion(Date fechacreacion) {
        this.fechacreacion = fechacreacion;
    }

    
    @Column(name="TIPOGRUPO", length=1)
    public String getTipogrupo() {
        return this.tipogrupo;
    }
    
    public void setTipogrupo(String tipogrupo) {
        this.tipogrupo = tipogrupo;
    }

    
    @Column(name="GRUPORUTA", length=4)
    public String getGruporuta() {
        return this.gruporuta;
    }
    
    public void setGruporuta(String gruporuta) {
        this.gruporuta = gruporuta;
    }

    
    @Column(name="TIPORUTA", length=1)
    public String getTiporuta() {
        return this.tiporuta;
    }
    
    public void setTiporuta(String tiporuta) {
        this.tiporuta = tiporuta;
    }

    
    @Column(name="PRESUPUESTADO", precision=17)
    public BigDecimal getPresupuestado() {
        return this.presupuestado;
    }
    
    public void setPresupuestado(BigDecimal presupuestado) {
        this.presupuestado = presupuestado;
    }

    
    @Column(name="VENDIDO", precision=17)
    public BigDecimal getVendido() {
        return this.vendido;
    }
    
    public void setVendido(BigDecimal vendido) {
        this.vendido = vendido;
    }

    
    @Column(name="DESCRIPCION", length=25)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="CENTRO", length=2)
    public String getCentro() {
        return this.centro;
    }
    
    public void setCentro(String centro) {
        this.centro = centro;
    }

    
    @Column(name="VENDEDOR", length=4)
    public String getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(String vendedor) {
        this.vendedor = vendedor;
    }

    
    @Column(name="CTA_EFECTIVO", length=15)
    public String getCtaEfectivo() {
        return this.ctaEfectivo;
    }
    
    public void setCtaEfectivo(String ctaEfectivo) {
        this.ctaEfectivo = ctaEfectivo;
    }

    
    @Column(name="CTA_DESC_FINANCIERO", length=15)
    public String getCtaDescFinanciero() {
        return this.ctaDescFinanciero;
    }
    
    public void setCtaDescFinanciero(String ctaDescFinanciero) {
        this.ctaDescFinanciero = ctaDescFinanciero;
    }

    
    @Column(name="TIPO", length=1)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="FACT_ACTUALIZA_INV", length=1)
    public String getFactActualizaInv() {
        return this.factActualizaInv;
    }
    
    public void setFactActualizaInv(String factActualizaInv) {
        this.factActualizaInv = factActualizaInv;
    }

    
    @Column(name="CAJERO_ACTUAL", length=4)
    public String getCajeroActual() {
        return this.cajeroActual;
    }
    
    public void setCajeroActual(String cajeroActual) {
        this.cajeroActual = cajeroActual;
    }

    
    @Column(name="CONT_TURNOS", precision=8, scale=0)
    public Integer getContTurnos() {
        return this.contTurnos;
    }
    
    public void setContTurnos(Integer contTurnos) {
        this.contTurnos = contTurnos;
    }

    
    @Column(name="NO_CIERRE_CAJA", precision=5, scale=0)
    public Integer getNoCierreCaja() {
        return this.noCierreCaja;
    }
    
    public void setNoCierreCaja(Integer noCierreCaja) {
        this.noCierreCaja = noCierreCaja;
    }

    
    @Column(name="BODEGA_DEF", length=4)
    public String getBodegaDef() {
        return this.bodegaDef;
    }
    
    public void setBodegaDef(String bodegaDef) {
        this.bodegaDef = bodegaDef;
    }

    
    @Column(name="TIPO_PRECIO_DEF", length=2)
    public String getTipoPrecioDef() {
        return this.tipoPrecioDef;
    }
    
    public void setTipoPrecioDef(String tipoPrecioDef) {
        this.tipoPrecioDef = tipoPrecioDef;
    }

    
    @Column(name="NO_AUTORIZACION_RENTA", length=20)
    public String getNoAutorizacionRenta() {
        return this.noAutorizacionRenta;
    }
    
    public void setNoAutorizacionRenta(String noAutorizacionRenta) {
        this.noAutorizacionRenta = noAutorizacionRenta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="F_PROCESO", length=7)
    public Date getFProceso() {
        return this.FProceso;
    }
    
    public void setFProceso(Date FProceso) {
        this.FProceso = FProceso;
    }

    
    @Column(name="IND_COSTEO_EFECTUADO", length=1)
    public String getIndCosteoEfectuado() {
        return this.indCosteoEfectuado;
    }
    
    public void setIndCosteoEfectuado(String indCosteoEfectuado) {
        this.indCosteoEfectuado = indCosteoEfectuado;
    }

    
    @Column(name="TIPO_CAJON", length=15)
    public String getTipoCajon() {
        return this.tipoCajon;
    }
    
    public void setTipoCajon(String tipoCajon) {
        this.tipoCajon = tipoCajon;
    }

    
    @Column(name="PUERTO_CAJON", length=30)
    public String getPuertoCajon() {
        return this.puertoCajon;
    }
    
    public void setPuertoCajon(String puertoCajon) {
        this.puertoCajon = puertoCajon;
    }

    
    @Column(name="PUERTO_IMPRESORA", length=30)
    public String getPuertoImpresora() {
        return this.puertoImpresora;
    }
    
    public void setPuertoImpresora(String puertoImpresora) {
        this.puertoImpresora = puertoImpresora;
    }

    
    @Column(name="SECUENCIA_ABRE_CAJON", length=20)
    public String getSecuenciaAbreCajon() {
        return this.secuenciaAbreCajon;
    }
    
    public void setSecuenciaAbreCajon(String secuenciaAbreCajon) {
        this.secuenciaAbreCajon = secuenciaAbreCajon;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="F_ULT_CIERRE", length=7)
    public Date getFUltCierre() {
        return this.FUltCierre;
    }
    
    public void setFUltCierre(Date FUltCierre) {
        this.FUltCierre = FUltCierre;
    }

    
    @Column(name="IND_CORTE_PAPEL", length=1)
    public String getIndCortePapel() {
        return this.indCortePapel;
    }
    
    public void setIndCortePapel(String indCortePapel) {
        this.indCortePapel = indCortePapel;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TSTAMP", length=7)
    public Date getTstamp() {
        return this.tstamp;
    }
    
    public void setTstamp(Date tstamp) {
        this.tstamp = tstamp;
    }




}


