package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arccmc generated by hbm2java
 */
@Entity
@Table(name="ARCCMC"
    ,schema="DESA46"
)
public class Arccmc  implements java.io.Serializable {


     private ArccmcId id;
     private String corporacion;
     private String codigoTercero;
     private String tipoCliente;
     private String nombre;
     private String alias;
     private String nombreComercial;
     private String direccion;
     private String apartado;
     private String noSoli;
     private Date fechaIngre;
     private String nombreEnc;
     private String cobrador;
     private String usaOrden;
     private String intereses;
     private String excentoImp;
     private String moneda;
     private BigDecimal saldoMax;
     private Date fechaMax;
     private BigDecimal tasaInt;
     private BigDecimal limiteCredi;
     private BigDecimal saldoAnte;
     private BigDecimal debitos;
     private BigDecimal creditos;
     private Date FUltCom;
     private Date FUltPago;
     private String telefono;
     private String telefono2;
     private String fax;
     private String email1;
     private String email2;
     private Date FCierre;
     private String motivo;
     private Short plazo;
     private BigDecimal descProntoPago;
     private String tipoIdTributario;
     private String cedula;
     private Short gracia;
     private BigDecimal objetivoventa;
     private String clase;
     private String oferta;
     private String condicioncheque;
     private Short diasCheque;
     private String balancefactura;
     private String zona;
     private String pais;
     private String provincia;
     private String canton;
     private String distrito;
     private String barrio;
     private Integer segCensal;
     private String tipoprecio;
     private String centro;
     private String FDelayi;
     private String FSpliti;
     private String FPrtupc;
     private Long cksDev;
     private BigDecimal mtoComp;
     private String clienteNacional;
     private String sector;
     private String actividad;
     private String condicionTributaria;
     private String nombreLargo;
     private String codClientePv;
     private BigDecimal porcDesc;
     private String chequeSeguro;
     private String dirDesp;
     private String st;
     private String cdescuento;
     private String suspendidosCxc;
     private BigDecimal porcRetIva;
     private BigDecimal porcRetIslr;
     private String formaPago;
     private String noComprobante;
     private String condicionPago;
     private BigDecimal saldoMaxRes;
     private BigDecimal limiteCrediRes;
     private BigDecimal saldoAnteRes;
     private BigDecimal debitosRes;
     private BigDecimal creditosRes;
     private BigDecimal objetivoventaRes;

    public Arccmc() {
    }

	
    public Arccmc(ArccmcId id) {
        this.id = id;
    }
    public Arccmc(ArccmcId id, String corporacion, String codigoTercero, String tipoCliente, String nombre, String alias, String nombreComercial, String direccion, String apartado, String noSoli, Date fechaIngre, String nombreEnc, String cobrador, String usaOrden, String intereses, String excentoImp, String moneda, BigDecimal saldoMax, Date fechaMax, BigDecimal tasaInt, BigDecimal limiteCredi, BigDecimal saldoAnte, BigDecimal debitos, BigDecimal creditos, Date FUltCom, Date FUltPago, String telefono, String telefono2, String fax, String email1, String email2, Date FCierre, String motivo, Short plazo, BigDecimal descProntoPago, String tipoIdTributario, String cedula, Short gracia, BigDecimal objetivoventa, String clase, String oferta, String condicioncheque, Short diasCheque, String balancefactura, String zona, String pais, String provincia, String canton, String distrito, String barrio, Integer segCensal, String tipoprecio, String centro, String FDelayi, String FSpliti, String FPrtupc, Long cksDev, BigDecimal mtoComp, String clienteNacional, String sector, String actividad, String condicionTributaria, String nombreLargo, String codClientePv, BigDecimal porcDesc, String chequeSeguro, String dirDesp, String st, String cdescuento, String suspendidosCxc, BigDecimal porcRetIva, BigDecimal porcRetIslr, String formaPago, String noComprobante, String condicionPago, BigDecimal saldoMaxRes, BigDecimal limiteCrediRes, BigDecimal saldoAnteRes, BigDecimal debitosRes, BigDecimal creditosRes, BigDecimal objetivoventaRes) {
       this.id = id;
       this.corporacion = corporacion;
       this.codigoTercero = codigoTercero;
       this.tipoCliente = tipoCliente;
       this.nombre = nombre;
       this.alias = alias;
       this.nombreComercial = nombreComercial;
       this.direccion = direccion;
       this.apartado = apartado;
       this.noSoli = noSoli;
       this.fechaIngre = fechaIngre;
       this.nombreEnc = nombreEnc;
       this.cobrador = cobrador;
       this.usaOrden = usaOrden;
       this.intereses = intereses;
       this.excentoImp = excentoImp;
       this.moneda = moneda;
       this.saldoMax = saldoMax;
       this.fechaMax = fechaMax;
       this.tasaInt = tasaInt;
       this.limiteCredi = limiteCredi;
       this.saldoAnte = saldoAnte;
       this.debitos = debitos;
       this.creditos = creditos;
       this.FUltCom = FUltCom;
       this.FUltPago = FUltPago;
       this.telefono = telefono;
       this.telefono2 = telefono2;
       this.fax = fax;
       this.email1 = email1;
       this.email2 = email2;
       this.FCierre = FCierre;
       this.motivo = motivo;
       this.plazo = plazo;
       this.descProntoPago = descProntoPago;
       this.tipoIdTributario = tipoIdTributario;
       this.cedula = cedula;
       this.gracia = gracia;
       this.objetivoventa = objetivoventa;
       this.clase = clase;
       this.oferta = oferta;
       this.condicioncheque = condicioncheque;
       this.diasCheque = diasCheque;
       this.balancefactura = balancefactura;
       this.zona = zona;
       this.pais = pais;
       this.provincia = provincia;
       this.canton = canton;
       this.distrito = distrito;
       this.barrio = barrio;
       this.segCensal = segCensal;
       this.tipoprecio = tipoprecio;
       this.centro = centro;
       this.FDelayi = FDelayi;
       this.FSpliti = FSpliti;
       this.FPrtupc = FPrtupc;
       this.cksDev = cksDev;
       this.mtoComp = mtoComp;
       this.clienteNacional = clienteNacional;
       this.sector = sector;
       this.actividad = actividad;
       this.condicionTributaria = condicionTributaria;
       this.nombreLargo = nombreLargo;
       this.codClientePv = codClientePv;
       this.porcDesc = porcDesc;
       this.chequeSeguro = chequeSeguro;
       this.dirDesp = dirDesp;
       this.st = st;
       this.cdescuento = cdescuento;
       this.suspendidosCxc = suspendidosCxc;
       this.porcRetIva = porcRetIva;
       this.porcRetIslr = porcRetIslr;
       this.formaPago = formaPago;
       this.noComprobante = noComprobante;
       this.condicionPago = condicionPago;
       this.saldoMaxRes = saldoMaxRes;
       this.limiteCrediRes = limiteCrediRes;
       this.saldoAnteRes = saldoAnteRes;
       this.debitosRes = debitosRes;
       this.creditosRes = creditosRes;
       this.objetivoventaRes = objetivoventaRes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="grupo", column=@Column(name="GRUPO", nullable=false, length=2) ), 
        @AttributeOverride(name="noCliente", column=@Column(name="NO_CLIENTE", nullable=false, length=15) ) } )
    public ArccmcId getId() {
        return this.id;
    }
    
    public void setId(ArccmcId id) {
        this.id = id;
    }

    
    @Column(name="CORPORACION", length=6)
    public String getCorporacion() {
        return this.corporacion;
    }
    
    public void setCorporacion(String corporacion) {
        this.corporacion = corporacion;
    }

    
    @Column(name="CODIGO_TERCERO", length=18)
    public String getCodigoTercero() {
        return this.codigoTercero;
    }
    
    public void setCodigoTercero(String codigoTercero) {
        this.codigoTercero = codigoTercero;
    }

    
    @Column(name="TIPO_CLIENTE", length=2)
    public String getTipoCliente() {
        return this.tipoCliente;
    }
    
    public void setTipoCliente(String tipoCliente) {
        this.tipoCliente = tipoCliente;
    }

    
    @Column(name="NOMBRE", length=40)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="ALIAS", length=40)
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }

    
    @Column(name="NOMBRE_COMERCIAL", length=40)
    public String getNombreComercial() {
        return this.nombreComercial;
    }
    
    public void setNombreComercial(String nombreComercial) {
        this.nombreComercial = nombreComercial;
    }

    
    @Column(name="DIRECCION", length=500)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="APARTADO", length=20)
    public String getApartado() {
        return this.apartado;
    }
    
    public void setApartado(String apartado) {
        this.apartado = apartado;
    }

    
    @Column(name="NO_SOLI", length=8)
    public String getNoSoli() {
        return this.noSoli;
    }
    
    public void setNoSoli(String noSoli) {
        this.noSoli = noSoli;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_INGRE", length=7)
    public Date getFechaIngre() {
        return this.fechaIngre;
    }
    
    public void setFechaIngre(Date fechaIngre) {
        this.fechaIngre = fechaIngre;
    }

    
    @Column(name="NOMBRE_ENC", length=25)
    public String getNombreEnc() {
        return this.nombreEnc;
    }
    
    public void setNombreEnc(String nombreEnc) {
        this.nombreEnc = nombreEnc;
    }

    
    @Column(name="COBRADOR", length=4)
    public String getCobrador() {
        return this.cobrador;
    }
    
    public void setCobrador(String cobrador) {
        this.cobrador = cobrador;
    }

    
    @Column(name="USA_ORDEN", length=1)
    public String getUsaOrden() {
        return this.usaOrden;
    }
    
    public void setUsaOrden(String usaOrden) {
        this.usaOrden = usaOrden;
    }

    
    @Column(name="INTERESES", length=1)
    public String getIntereses() {
        return this.intereses;
    }
    
    public void setIntereses(String intereses) {
        this.intereses = intereses;
    }

    
    @Column(name="EXCENTO_IMP", length=1)
    public String getExcentoImp() {
        return this.excentoImp;
    }
    
    public void setExcentoImp(String excentoImp) {
        this.excentoImp = excentoImp;
    }

    
    @Column(name="MONEDA", length=1)
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }

    
    @Column(name="SALDO_MAX", precision=17)
    public BigDecimal getSaldoMax() {
        return this.saldoMax;
    }
    
    public void setSaldoMax(BigDecimal saldoMax) {
        this.saldoMax = saldoMax;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_MAX", length=7)
    public Date getFechaMax() {
        return this.fechaMax;
    }
    
    public void setFechaMax(Date fechaMax) {
        this.fechaMax = fechaMax;
    }

    
    @Column(name="TASA_INT", precision=5)
    public BigDecimal getTasaInt() {
        return this.tasaInt;
    }
    
    public void setTasaInt(BigDecimal tasaInt) {
        this.tasaInt = tasaInt;
    }

    
    @Column(name="LIMITE_CREDI", precision=17)
    public BigDecimal getLimiteCredi() {
        return this.limiteCredi;
    }
    
    public void setLimiteCredi(BigDecimal limiteCredi) {
        this.limiteCredi = limiteCredi;
    }

    
    @Column(name="SALDO_ANTE", precision=17)
    public BigDecimal getSaldoAnte() {
        return this.saldoAnte;
    }
    
    public void setSaldoAnte(BigDecimal saldoAnte) {
        this.saldoAnte = saldoAnte;
    }

    
    @Column(name="DEBITOS", precision=17)
    public BigDecimal getDebitos() {
        return this.debitos;
    }
    
    public void setDebitos(BigDecimal debitos) {
        this.debitos = debitos;
    }

    
    @Column(name="CREDITOS", precision=17)
    public BigDecimal getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(BigDecimal creditos) {
        this.creditos = creditos;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="F_ULT_COM", length=7)
    public Date getFUltCom() {
        return this.FUltCom;
    }
    
    public void setFUltCom(Date FUltCom) {
        this.FUltCom = FUltCom;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="F_ULT_PAGO", length=7)
    public Date getFUltPago() {
        return this.FUltPago;
    }
    
    public void setFUltPago(Date FUltPago) {
        this.FUltPago = FUltPago;
    }

    
    @Column(name="TELEFONO", length=12)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="TELEFONO2", length=12)
    public String getTelefono2() {
        return this.telefono2;
    }
    
    public void setTelefono2(String telefono2) {
        this.telefono2 = telefono2;
    }

    
    @Column(name="FAX", length=12)
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    
    @Column(name="EMAIL1", length=40)
    public String getEmail1() {
        return this.email1;
    }
    
    public void setEmail1(String email1) {
        this.email1 = email1;
    }

    
    @Column(name="EMAIL2", length=40)
    public String getEmail2() {
        return this.email2;
    }
    
    public void setEmail2(String email2) {
        this.email2 = email2;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="F_CIERRE", length=7)
    public Date getFCierre() {
        return this.FCierre;
    }
    
    public void setFCierre(Date FCierre) {
        this.FCierre = FCierre;
    }

    
    @Column(name="MOTIVO", length=80)
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }

    
    @Column(name="PLAZO", precision=3, scale=0)
    public Short getPlazo() {
        return this.plazo;
    }
    
    public void setPlazo(Short plazo) {
        this.plazo = plazo;
    }

    
    @Column(name="DESC_PRONTO_PAGO", precision=4)
    public BigDecimal getDescProntoPago() {
        return this.descProntoPago;
    }
    
    public void setDescProntoPago(BigDecimal descProntoPago) {
        this.descProntoPago = descProntoPago;
    }

    
    @Column(name="TIPO_ID_TRIBUTARIO", length=1)
    public String getTipoIdTributario() {
        return this.tipoIdTributario;
    }
    
    public void setTipoIdTributario(String tipoIdTributario) {
        this.tipoIdTributario = tipoIdTributario;
    }

    
    @Column(name="CEDULA", length=15)
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }

    
    @Column(name="GRACIA", precision=3, scale=0)
    public Short getGracia() {
        return this.gracia;
    }
    
    public void setGracia(Short gracia) {
        this.gracia = gracia;
    }

    
    @Column(name="OBJETIVOVENTA", precision=17)
    public BigDecimal getObjetivoventa() {
        return this.objetivoventa;
    }
    
    public void setObjetivoventa(BigDecimal objetivoventa) {
        this.objetivoventa = objetivoventa;
    }

    
    @Column(name="CLASE", length=1)
    public String getClase() {
        return this.clase;
    }
    
    public void setClase(String clase) {
        this.clase = clase;
    }

    
    @Column(name="OFERTA", length=1)
    public String getOferta() {
        return this.oferta;
    }
    
    public void setOferta(String oferta) {
        this.oferta = oferta;
    }

    
    @Column(name="CONDICIONCHEQUE", length=1)
    public String getCondicioncheque() {
        return this.condicioncheque;
    }
    
    public void setCondicioncheque(String condicioncheque) {
        this.condicioncheque = condicioncheque;
    }

    
    @Column(name="DIAS_CHEQUE", precision=3, scale=0)
    public Short getDiasCheque() {
        return this.diasCheque;
    }
    
    public void setDiasCheque(Short diasCheque) {
        this.diasCheque = diasCheque;
    }

    
    @Column(name="BALANCEFACTURA", length=1)
    public String getBalancefactura() {
        return this.balancefactura;
    }
    
    public void setBalancefactura(String balancefactura) {
        this.balancefactura = balancefactura;
    }

    
    @Column(name="ZONA", length=5)
    public String getZona() {
        return this.zona;
    }
    
    public void setZona(String zona) {
        this.zona = zona;
    }

    
    @Column(name="PAIS", length=6)
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }

    
    @Column(name="PROVINCIA", length=6)
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }

    
    @Column(name="CANTON", length=6)
    public String getCanton() {
        return this.canton;
    }
    
    public void setCanton(String canton) {
        this.canton = canton;
    }

    
    @Column(name="DISTRITO", length=2)
    public String getDistrito() {
        return this.distrito;
    }
    
    public void setDistrito(String distrito) {
        this.distrito = distrito;
    }

    
    @Column(name="BARRIO", length=2)
    public String getBarrio() {
        return this.barrio;
    }
    
    public void setBarrio(String barrio) {
        this.barrio = barrio;
    }

    
    @Column(name="SEG_CENSAL", precision=6, scale=0)
    public Integer getSegCensal() {
        return this.segCensal;
    }
    
    public void setSegCensal(Integer segCensal) {
        this.segCensal = segCensal;
    }

    
    @Column(name="TIPOPRECIO", length=2)
    public String getTipoprecio() {
        return this.tipoprecio;
    }
    
    public void setTipoprecio(String tipoprecio) {
        this.tipoprecio = tipoprecio;
    }

    
    @Column(name="CENTRO", length=2)
    public String getCentro() {
        return this.centro;
    }
    
    public void setCentro(String centro) {
        this.centro = centro;
    }

    
    @Column(name="F_DELAYI", length=1)
    public String getFDelayi() {
        return this.FDelayi;
    }
    
    public void setFDelayi(String FDelayi) {
        this.FDelayi = FDelayi;
    }

    
    @Column(name="F_SPLITI", length=1)
    public String getFSpliti() {
        return this.FSpliti;
    }
    
    public void setFSpliti(String FSpliti) {
        this.FSpliti = FSpliti;
    }

    
    @Column(name="F_PRTUPC", length=1)
    public String getFPrtupc() {
        return this.FPrtupc;
    }
    
    public void setFPrtupc(String FPrtupc) {
        this.FPrtupc = FPrtupc;
    }

    
    @Column(name="CKS_DEV", precision=10, scale=0)
    public Long getCksDev() {
        return this.cksDev;
    }
    
    public void setCksDev(Long cksDev) {
        this.cksDev = cksDev;
    }

    
    @Column(name="MTO_COMP", precision=24)
    public BigDecimal getMtoComp() {
        return this.mtoComp;
    }
    
    public void setMtoComp(BigDecimal mtoComp) {
        this.mtoComp = mtoComp;
    }

    
    @Column(name="CLIENTE_NACIONAL", length=1)
    public String getClienteNacional() {
        return this.clienteNacional;
    }
    
    public void setClienteNacional(String clienteNacional) {
        this.clienteNacional = clienteNacional;
    }

    
    @Column(name="SECTOR", length=2)
    public String getSector() {
        return this.sector;
    }
    
    public void setSector(String sector) {
        this.sector = sector;
    }

    
    @Column(name="ACTIVIDAD", length=4)
    public String getActividad() {
        return this.actividad;
    }
    
    public void setActividad(String actividad) {
        this.actividad = actividad;
    }

    
    @Column(name="CONDICION_TRIBUTARIA", length=3)
    public String getCondicionTributaria() {
        return this.condicionTributaria;
    }
    
    public void setCondicionTributaria(String condicionTributaria) {
        this.condicionTributaria = condicionTributaria;
    }

    
    @Column(name="NOMBRE_LARGO", length=200)
    public String getNombreLargo() {
        return this.nombreLargo;
    }
    
    public void setNombreLargo(String nombreLargo) {
        this.nombreLargo = nombreLargo;
    }

    
    @Column(name="COD_CLIENTE_PV", length=15)
    public String getCodClientePv() {
        return this.codClientePv;
    }
    
    public void setCodClientePv(String codClientePv) {
        this.codClientePv = codClientePv;
    }

    
    @Column(name="PORC_DESC", precision=9)
    public BigDecimal getPorcDesc() {
        return this.porcDesc;
    }
    
    public void setPorcDesc(BigDecimal porcDesc) {
        this.porcDesc = porcDesc;
    }

    
    @Column(name="CHEQUE_SEGURO", length=1)
    public String getChequeSeguro() {
        return this.chequeSeguro;
    }
    
    public void setChequeSeguro(String chequeSeguro) {
        this.chequeSeguro = chequeSeguro;
    }

    
    @Column(name="DIR_DESP", length=800)
    public String getDirDesp() {
        return this.dirDesp;
    }
    
    public void setDirDesp(String dirDesp) {
        this.dirDesp = dirDesp;
    }

    
    @Column(name="ST", length=1)
    public String getSt() {
        return this.st;
    }
    
    public void setSt(String st) {
        this.st = st;
    }

    
    @Column(name="CDESCUENTO", length=3)
    public String getCdescuento() {
        return this.cdescuento;
    }
    
    public void setCdescuento(String cdescuento) {
        this.cdescuento = cdescuento;
    }

    
    @Column(name="SUSPENDIDOS_CXC", length=1)
    public String getSuspendidosCxc() {
        return this.suspendidosCxc;
    }
    
    public void setSuspendidosCxc(String suspendidosCxc) {
        this.suspendidosCxc = suspendidosCxc;
    }

    
    @Column(name="PORC_RET_IVA", precision=17)
    public BigDecimal getPorcRetIva() {
        return this.porcRetIva;
    }
    
    public void setPorcRetIva(BigDecimal porcRetIva) {
        this.porcRetIva = porcRetIva;
    }

    
    @Column(name="PORC_RET_ISLR", precision=17)
    public BigDecimal getPorcRetIslr() {
        return this.porcRetIslr;
    }
    
    public void setPorcRetIslr(BigDecimal porcRetIslr) {
        this.porcRetIslr = porcRetIslr;
    }

    
    @Column(name="FORMA_PAGO", length=50)
    public String getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(String formaPago) {
        this.formaPago = formaPago;
    }

    
    @Column(name="NO_COMPROBANTE", length=14)
    public String getNoComprobante() {
        return this.noComprobante;
    }
    
    public void setNoComprobante(String noComprobante) {
        this.noComprobante = noComprobante;
    }

    
    @Column(name="CONDICION_PAGO", length=100)
    public String getCondicionPago() {
        return this.condicionPago;
    }
    
    public void setCondicionPago(String condicionPago) {
        this.condicionPago = condicionPago;
    }

    
    @Column(name="SALDO_MAX_RES", precision=30)
    public BigDecimal getSaldoMaxRes() {
        return this.saldoMaxRes;
    }
    
    public void setSaldoMaxRes(BigDecimal saldoMaxRes) {
        this.saldoMaxRes = saldoMaxRes;
    }

    
    @Column(name="LIMITE_CREDI_RES", precision=30)
    public BigDecimal getLimiteCrediRes() {
        return this.limiteCrediRes;
    }
    
    public void setLimiteCrediRes(BigDecimal limiteCrediRes) {
        this.limiteCrediRes = limiteCrediRes;
    }

    
    @Column(name="SALDO_ANTE_RES", precision=30)
    public BigDecimal getSaldoAnteRes() {
        return this.saldoAnteRes;
    }
    
    public void setSaldoAnteRes(BigDecimal saldoAnteRes) {
        this.saldoAnteRes = saldoAnteRes;
    }

    
    @Column(name="DEBITOS_RES", precision=30)
    public BigDecimal getDebitosRes() {
        return this.debitosRes;
    }
    
    public void setDebitosRes(BigDecimal debitosRes) {
        this.debitosRes = debitosRes;
    }

    
    @Column(name="CREDITOS_RES", precision=30)
    public BigDecimal getCreditosRes() {
        return this.creditosRes;
    }
    
    public void setCreditosRes(BigDecimal creditosRes) {
        this.creditosRes = creditosRes;
    }

    
    @Column(name="OBJETIVOVENTA_RES", precision=30)
    public BigDecimal getObjetivoventaRes() {
        return this.objetivoventaRes;
    }
    
    public void setObjetivoventaRes(BigDecimal objetivoventaRes) {
        this.objetivoventaRes = objetivoventaRes;
    }




}


