package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arccck generated by hbm2java
 */
@Entity
@Table(name="ARCCCK"
    ,schema="DESA46"
)
public class Arccck  implements java.io.Serializable {


     private ArccckId id;
     private String centro;
     private String tipoDoc;
     private String grupo;
     private String noCliente;
     private String banco;
     private String noCheque;
     private String moneda;
     private BigDecimal monto;
     private String motivo;
     private Date fecha;
     private String estado;
     private String estadoNuevo;
     private String vendedor;
     private String cobradorOrig;
     private String noDocuCobro;
     private String tipoDocCobro;
     private String cobrador;
     private BigDecimal montoRes;

    public Arccck() {
    }

	
    public Arccck(ArccckId id) {
        this.id = id;
    }
    public Arccck(ArccckId id, String centro, String tipoDoc, String grupo, String noCliente, String banco, String noCheque, String moneda, BigDecimal monto, String motivo, Date fecha, String estado, String estadoNuevo, String vendedor, String cobradorOrig, String noDocuCobro, String tipoDocCobro, String cobrador, BigDecimal montoRes) {
       this.id = id;
       this.centro = centro;
       this.tipoDoc = tipoDoc;
       this.grupo = grupo;
       this.noCliente = noCliente;
       this.banco = banco;
       this.noCheque = noCheque;
       this.moneda = moneda;
       this.monto = monto;
       this.motivo = motivo;
       this.fecha = fecha;
       this.estado = estado;
       this.estadoNuevo = estadoNuevo;
       this.vendedor = vendedor;
       this.cobradorOrig = cobradorOrig;
       this.noDocuCobro = noDocuCobro;
       this.tipoDocCobro = tipoDocCobro;
       this.cobrador = cobrador;
       this.montoRes = montoRes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noDocu", column=@Column(name="NO_DOCU", nullable=false, length=12) ) } )
    public ArccckId getId() {
        return this.id;
    }
    
    public void setId(ArccckId id) {
        this.id = id;
    }

    
    @Column(name="CENTRO", length=2)
    public String getCentro() {
        return this.centro;
    }
    
    public void setCentro(String centro) {
        this.centro = centro;
    }

    
    @Column(name="TIPO_DOC", length=2)
    public String getTipoDoc() {
        return this.tipoDoc;
    }
    
    public void setTipoDoc(String tipoDoc) {
        this.tipoDoc = tipoDoc;
    }

    
    @Column(name="GRUPO", length=2)
    public String getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }

    
    @Column(name="NO_CLIENTE", length=15)
    public String getNoCliente() {
        return this.noCliente;
    }
    
    public void setNoCliente(String noCliente) {
        this.noCliente = noCliente;
    }

    
    @Column(name="BANCO", length=2)
    public String getBanco() {
        return this.banco;
    }
    
    public void setBanco(String banco) {
        this.banco = banco;
    }

    
    @Column(name="NO_CHEQUE", length=12)
    public String getNoCheque() {
        return this.noCheque;
    }
    
    public void setNoCheque(String noCheque) {
        this.noCheque = noCheque;
    }

    
    @Column(name="MONEDA", length=1)
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }

    
    @Column(name="MONTO", precision=17)
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

    
    @Column(name="MOTIVO", length=20)
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", length=7)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="ESTADO", length=1)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="ESTADO_NUEVO", length=1)
    public String getEstadoNuevo() {
        return this.estadoNuevo;
    }
    
    public void setEstadoNuevo(String estadoNuevo) {
        this.estadoNuevo = estadoNuevo;
    }

    
    @Column(name="VENDEDOR", length=4)
    public String getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(String vendedor) {
        this.vendedor = vendedor;
    }

    
    @Column(name="COBRADOR_ORIG", length=4)
    public String getCobradorOrig() {
        return this.cobradorOrig;
    }
    
    public void setCobradorOrig(String cobradorOrig) {
        this.cobradorOrig = cobradorOrig;
    }

    
    @Column(name="NO_DOCU_COBRO", length=12)
    public String getNoDocuCobro() {
        return this.noDocuCobro;
    }
    
    public void setNoDocuCobro(String noDocuCobro) {
        this.noDocuCobro = noDocuCobro;
    }

    
    @Column(name="TIPO_DOC_COBRO", length=2)
    public String getTipoDocCobro() {
        return this.tipoDocCobro;
    }
    
    public void setTipoDocCobro(String tipoDocCobro) {
        this.tipoDocCobro = tipoDocCobro;
    }

    
    @Column(name="COBRADOR", length=4)
    public String getCobrador() {
        return this.cobrador;
    }
    
    public void setCobrador(String cobrador) {
        this.cobrador = cobrador;
    }

    
    @Column(name="MONTO_RES", precision=30)
    public BigDecimal getMontoRes() {
        return this.montoRes;
    }
    
    public void setMontoRes(BigDecimal montoRes) {
        this.montoRes = montoRes;
    }




}


