package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arccte generated by hbm2java
 */
@Entity
@Table(name="ARCCTE"
    ,schema="DESA46"
)
public class Arccte  implements java.io.Serializable {


     private ArccteId id;
     private String descripcion;
     private String tipoEstado;

    public Arccte() {
    }

	
    public Arccte(ArccteId id) {
        this.id = id;
    }
    public Arccte(ArccteId id, String descripcion, String tipoEstado) {
       this.id = id;
       this.descripcion = descripcion;
       this.tipoEstado = tipoEstado;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="tipoDoc", column=@Column(name="TIPO_DOC", nullable=false, length=2) ), 
        @AttributeOverride(name="codEstado", column=@Column(name="COD_ESTADO", nullable=false, length=2) ) } )
    public ArccteId getId() {
        return this.id;
    }
    
    public void setId(ArccteId id) {
        this.id = id;
    }

    
    @Column(name="DESCRIPCION", length=20)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="TIPO_ESTADO", length=2)
    public String getTipoEstado() {
        return this.tipoEstado;
    }
    
    public void setTipoEstado(String tipoEstado) {
        this.tipoEstado = tipoEstado;
    }




}


