package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arccti generated by hbm2java
 */
@Entity
@Table(name="ARCCTI"
    ,schema="DESA46"
)
public class Arccti  implements java.io.Serializable {


     private ArcctiId id;
     private String noRefe;
     private BigDecimal porcentaje;
     private BigDecimal monto;
     private String codigoTercero;
     private BigDecimal base;
     private String comportamiento;
     private String aplicaCredFiscal;
     private String indImpRet;
     private String idSec;
     private String formaPago;
     private String claveImpRed;
     private BigDecimal porcImpRed;
     private BigDecimal montoImpRed;
     private BigDecimal montoImpOrg;
     private BigDecimal porcImpOrg;
     private BigDecimal montoRes;
     private BigDecimal baseRes;
     private BigDecimal montoImpRedRes;

    public Arccti() {
    }

	
    public Arccti(ArcctiId id) {
        this.id = id;
    }
    public Arccti(ArcctiId id, String noRefe, BigDecimal porcentaje, BigDecimal monto, String codigoTercero, BigDecimal base, String comportamiento, String aplicaCredFiscal, String indImpRet, String idSec, String formaPago, String claveImpRed, BigDecimal porcImpRed, BigDecimal montoImpRed, BigDecimal montoImpOrg, BigDecimal porcImpOrg, BigDecimal montoRes, BigDecimal baseRes, BigDecimal montoImpRedRes) {
       this.id = id;
       this.noRefe = noRefe;
       this.porcentaje = porcentaje;
       this.monto = monto;
       this.codigoTercero = codigoTercero;
       this.base = base;
       this.comportamiento = comportamiento;
       this.aplicaCredFiscal = aplicaCredFiscal;
       this.indImpRet = indImpRet;
       this.idSec = idSec;
       this.formaPago = formaPago;
       this.claveImpRed = claveImpRed;
       this.porcImpRed = porcImpRed;
       this.montoImpRed = montoImpRed;
       this.montoImpOrg = montoImpOrg;
       this.porcImpOrg = porcImpOrg;
       this.montoRes = montoRes;
       this.baseRes = baseRes;
       this.montoImpRedRes = montoImpRedRes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="grupo", column=@Column(name="GRUPO", nullable=false, length=2) ), 
        @AttributeOverride(name="noCliente", column=@Column(name="NO_CLIENTE", nullable=false, length=15) ), 
        @AttributeOverride(name="tipoDoc", column=@Column(name="TIPO_DOC", nullable=false, length=2) ), 
        @AttributeOverride(name="noDocu", column=@Column(name="NO_DOCU", nullable=false, length=12) ), 
        @AttributeOverride(name="clave", column=@Column(name="CLAVE", nullable=false, length=2) ) } )
    public ArcctiId getId() {
        return this.id;
    }
    
    public void setId(ArcctiId id) {
        this.id = id;
    }

    
    @Column(name="NO_REFE", length=12)
    public String getNoRefe() {
        return this.noRefe;
    }
    
    public void setNoRefe(String noRefe) {
        this.noRefe = noRefe;
    }

    
    @Column(name="PORCENTAJE", precision=4)
    public BigDecimal getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(BigDecimal porcentaje) {
        this.porcentaje = porcentaje;
    }

    
    @Column(name="MONTO", precision=17)
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

    
    @Column(name="CODIGO_TERCERO", length=18)
    public String getCodigoTercero() {
        return this.codigoTercero;
    }
    
    public void setCodigoTercero(String codigoTercero) {
        this.codigoTercero = codigoTercero;
    }

    
    @Column(name="BASE", precision=17)
    public BigDecimal getBase() {
        return this.base;
    }
    
    public void setBase(BigDecimal base) {
        this.base = base;
    }

    
    @Column(name="COMPORTAMIENTO", length=1)
    public String getComportamiento() {
        return this.comportamiento;
    }
    
    public void setComportamiento(String comportamiento) {
        this.comportamiento = comportamiento;
    }

    
    @Column(name="APLICA_CRED_FISCAL", length=1)
    public String getAplicaCredFiscal() {
        return this.aplicaCredFiscal;
    }
    
    public void setAplicaCredFiscal(String aplicaCredFiscal) {
        this.aplicaCredFiscal = aplicaCredFiscal;
    }

    
    @Column(name="IND_IMP_RET", length=1)
    public String getIndImpRet() {
        return this.indImpRet;
    }
    
    public void setIndImpRet(String indImpRet) {
        this.indImpRet = indImpRet;
    }

    
    @Column(name="ID_SEC", length=5)
    public String getIdSec() {
        return this.idSec;
    }
    
    public void setIdSec(String idSec) {
        this.idSec = idSec;
    }

    
    @Column(name="FORMA_PAGO", length=100)
    public String getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(String formaPago) {
        this.formaPago = formaPago;
    }

    
    @Column(name="CLAVE_IMP_RED", length=2)
    public String getClaveImpRed() {
        return this.claveImpRed;
    }
    
    public void setClaveImpRed(String claveImpRed) {
        this.claveImpRed = claveImpRed;
    }

    
    @Column(name="PORC_IMP_RED", precision=4)
    public BigDecimal getPorcImpRed() {
        return this.porcImpRed;
    }
    
    public void setPorcImpRed(BigDecimal porcImpRed) {
        this.porcImpRed = porcImpRed;
    }

    
    @Column(name="MONTO_IMP_RED", precision=17)
    public BigDecimal getMontoImpRed() {
        return this.montoImpRed;
    }
    
    public void setMontoImpRed(BigDecimal montoImpRed) {
        this.montoImpRed = montoImpRed;
    }

    
    @Column(name="MONTO_IMP_ORG", precision=17)
    public BigDecimal getMontoImpOrg() {
        return this.montoImpOrg;
    }
    
    public void setMontoImpOrg(BigDecimal montoImpOrg) {
        this.montoImpOrg = montoImpOrg;
    }

    
    @Column(name="PORC_IMP_ORG", precision=4)
    public BigDecimal getPorcImpOrg() {
        return this.porcImpOrg;
    }
    
    public void setPorcImpOrg(BigDecimal porcImpOrg) {
        this.porcImpOrg = porcImpOrg;
    }

    
    @Column(name="MONTO_RES", precision=30)
    public BigDecimal getMontoRes() {
        return this.montoRes;
    }
    
    public void setMontoRes(BigDecimal montoRes) {
        this.montoRes = montoRes;
    }

    
    @Column(name="BASE_RES", precision=30)
    public BigDecimal getBaseRes() {
        return this.baseRes;
    }
    
    public void setBaseRes(BigDecimal baseRes) {
        this.baseRes = baseRes;
    }

    
    @Column(name="MONTO_IMP_RED_RES", precision=30)
    public BigDecimal getMontoImpRedRes() {
        return this.montoImpRedRes;
    }
    
    public void setMontoImpRedRes(BigDecimal montoImpRedRes) {
        this.montoImpRedRes = montoImpRedRes;
    }




}


