package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ArccmcDir generated by hbm2java
 */
@Entity
@Table(name="ARCCMC_DIR"
    ,schema="DESA46"
)
public class ArccmcDir  implements java.io.Serializable {


     private ArccmcDirId id;
     private String direccion;
     private String telefono;
     private String telefono2;
     private String telefono3;
     private String fax;
     private String email1;
     private String email2;
     private String zona;
     private String pais;
     private String provincia;
     private String canton;
     private String distrito;
     private String barrio;

    public ArccmcDir() {
    }

	
    public ArccmcDir(ArccmcDirId id) {
        this.id = id;
    }
    public ArccmcDir(ArccmcDirId id, String direccion, String telefono, String telefono2, String telefono3, String fax, String email1, String email2, String zona, String pais, String provincia, String canton, String distrito, String barrio) {
       this.id = id;
       this.direccion = direccion;
       this.telefono = telefono;
       this.telefono2 = telefono2;
       this.telefono3 = telefono3;
       this.fax = fax;
       this.email1 = email1;
       this.email2 = email2;
       this.zona = zona;
       this.pais = pais;
       this.provincia = provincia;
       this.canton = canton;
       this.distrito = distrito;
       this.barrio = barrio;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="grupo", column=@Column(name="GRUPO", nullable=false, length=2) ), 
        @AttributeOverride(name="noCliente", column=@Column(name="NO_CLIENTE", nullable=false, length=15) ), 
        @AttributeOverride(name="codDesp", column=@Column(name="COD_DESP", nullable=false, precision=15, scale=0) ) } )
    public ArccmcDirId getId() {
        return this.id;
    }
    
    public void setId(ArccmcDirId id) {
        this.id = id;
    }

    
    @Column(name="DIRECCION", length=1000)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="TELEFONO", length=12)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="TELEFONO2", length=12)
    public String getTelefono2() {
        return this.telefono2;
    }
    
    public void setTelefono2(String telefono2) {
        this.telefono2 = telefono2;
    }

    
    @Column(name="TELEFONO3", length=12)
    public String getTelefono3() {
        return this.telefono3;
    }
    
    public void setTelefono3(String telefono3) {
        this.telefono3 = telefono3;
    }

    
    @Column(name="FAX", length=12)
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    
    @Column(name="EMAIL1", length=40)
    public String getEmail1() {
        return this.email1;
    }
    
    public void setEmail1(String email1) {
        this.email1 = email1;
    }

    
    @Column(name="EMAIL2", length=40)
    public String getEmail2() {
        return this.email2;
    }
    
    public void setEmail2(String email2) {
        this.email2 = email2;
    }

    
    @Column(name="ZONA", length=5)
    public String getZona() {
        return this.zona;
    }
    
    public void setZona(String zona) {
        this.zona = zona;
    }

    
    @Column(name="PAIS", length=6)
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }

    
    @Column(name="PROVINCIA", length=6)
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }

    
    @Column(name="CANTON", length=6)
    public String getCanton() {
        return this.canton;
    }
    
    public void setCanton(String canton) {
        this.canton = canton;
    }

    
    @Column(name="DISTRITO", length=2)
    public String getDistrito() {
        return this.distrito;
    }
    
    public void setDistrito(String distrito) {
        this.distrito = distrito;
    }

    
    @Column(name="BARRIO", length=2)
    public String getBarrio() {
        return this.barrio;
    }
    
    public void setBarrio(String barrio) {
        this.barrio = barrio;
    }




}


