package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arccar generated by hbm2java
 */
@Entity
@Table(name="ARCCAR"
    ,schema="DESA46"
)
public class Arccar  implements java.io.Serializable {


     private ArccarId id;
     private Integer secuencia;

    public Arccar() {
    }

	
    public Arccar(ArccarId id) {
        this.id = id;
    }
    public Arccar(ArccarId id, Integer secuencia) {
       this.id = id;
       this.secuencia = secuencia;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="ruta", column=@Column(name="RUTA", nullable=false, length=4) ), 
        @AttributeOverride(name="grupo", column=@Column(name="GRUPO", nullable=false, length=2) ), 
        @AttributeOverride(name="noCliente", column=@Column(name="NO_CLIENTE", nullable=false, length=15) ), 
        @AttributeOverride(name="diavisita", column=@Column(name="DIAVISITA", nullable=false, length=1) ) } )
    public ArccarId getId() {
        return this.id;
    }
    
    public void setId(ArccarId id) {
        this.id = id;
    }

    
    @Column(name="SECUENCIA", precision=5, scale=0)
    public Integer getSecuencia() {
        return this.secuencia;
    }
    
    public void setSecuencia(Integer secuencia) {
        this.secuencia = secuencia;
    }




}


