package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arccsc generated by hbm2java
 */
@Entity
@Table(name="ARCCSC"
    ,schema="DESA46"
)
public class Arccsc  implements java.io.Serializable {


     private ArccscId id;
     private Date fechaSoli;
     private String nombreEnc;
     private String telefono;
     private String fax;
     private String noAgente;
     private String ruta;
     private String zona;
     private BigDecimal limiteCredi;
     private Short plazo;
     private String refe1;
     private String telefono1;
     private String refe2;
     private String telefono2;
     private String refe3;
     private String telefono3;
     private String refe4;
     private String telefono4;
     private String refe5;
     private String telefono5;
     private String evaluacion;
     private String calificacion;
     private BigDecimal MSolicitado;
     private String aprobado;
     private String actualizado;
     private BigDecimal limiteCrediRes;
     private BigDecimal MSolicitadoRes;

    public Arccsc() {
    }

	
    public Arccsc(ArccscId id) {
        this.id = id;
    }
    public Arccsc(ArccscId id, Date fechaSoli, String nombreEnc, String telefono, String fax, String noAgente, String ruta, String zona, BigDecimal limiteCredi, Short plazo, String refe1, String telefono1, String refe2, String telefono2, String refe3, String telefono3, String refe4, String telefono4, String refe5, String telefono5, String evaluacion, String calificacion, BigDecimal MSolicitado, String aprobado, String actualizado, BigDecimal limiteCrediRes, BigDecimal MSolicitadoRes) {
       this.id = id;
       this.fechaSoli = fechaSoli;
       this.nombreEnc = nombreEnc;
       this.telefono = telefono;
       this.fax = fax;
       this.noAgente = noAgente;
       this.ruta = ruta;
       this.zona = zona;
       this.limiteCredi = limiteCredi;
       this.plazo = plazo;
       this.refe1 = refe1;
       this.telefono1 = telefono1;
       this.refe2 = refe2;
       this.telefono2 = telefono2;
       this.refe3 = refe3;
       this.telefono3 = telefono3;
       this.refe4 = refe4;
       this.telefono4 = telefono4;
       this.refe5 = refe5;
       this.telefono5 = telefono5;
       this.evaluacion = evaluacion;
       this.calificacion = calificacion;
       this.MSolicitado = MSolicitado;
       this.aprobado = aprobado;
       this.actualizado = actualizado;
       this.limiteCrediRes = limiteCrediRes;
       this.MSolicitadoRes = MSolicitadoRes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="grupo", column=@Column(name="GRUPO", nullable=false, length=2) ), 
        @AttributeOverride(name="noCliente", column=@Column(name="NO_CLIENTE", nullable=false, length=15) ), 
        @AttributeOverride(name="noSoli", column=@Column(name="NO_SOLI", nullable=false, length=8) ) } )
    public ArccscId getId() {
        return this.id;
    }
    
    public void setId(ArccscId id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_SOLI", length=7)
    public Date getFechaSoli() {
        return this.fechaSoli;
    }
    
    public void setFechaSoli(Date fechaSoli) {
        this.fechaSoli = fechaSoli;
    }

    
    @Column(name="NOMBRE_ENC", length=25)
    public String getNombreEnc() {
        return this.nombreEnc;
    }
    
    public void setNombreEnc(String nombreEnc) {
        this.nombreEnc = nombreEnc;
    }

    
    @Column(name="TELEFONO", length=8)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="FAX", length=8)
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    
    @Column(name="NO_AGENTE", length=4)
    public String getNoAgente() {
        return this.noAgente;
    }
    
    public void setNoAgente(String noAgente) {
        this.noAgente = noAgente;
    }

    
    @Column(name="RUTA", length=4)
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }

    
    @Column(name="ZONA", length=5)
    public String getZona() {
        return this.zona;
    }
    
    public void setZona(String zona) {
        this.zona = zona;
    }

    
    @Column(name="LIMITE_CREDI", precision=17)
    public BigDecimal getLimiteCredi() {
        return this.limiteCredi;
    }
    
    public void setLimiteCredi(BigDecimal limiteCredi) {
        this.limiteCredi = limiteCredi;
    }

    
    @Column(name="PLAZO", precision=3, scale=0)
    public Short getPlazo() {
        return this.plazo;
    }
    
    public void setPlazo(Short plazo) {
        this.plazo = plazo;
    }

    
    @Column(name="REFE_1", length=30)
    public String getRefe1() {
        return this.refe1;
    }
    
    public void setRefe1(String refe1) {
        this.refe1 = refe1;
    }

    
    @Column(name="TELEFONO_1", length=8)
    public String getTelefono1() {
        return this.telefono1;
    }
    
    public void setTelefono1(String telefono1) {
        this.telefono1 = telefono1;
    }

    
    @Column(name="REFE_2", length=30)
    public String getRefe2() {
        return this.refe2;
    }
    
    public void setRefe2(String refe2) {
        this.refe2 = refe2;
    }

    
    @Column(name="TELEFONO_2", length=8)
    public String getTelefono2() {
        return this.telefono2;
    }
    
    public void setTelefono2(String telefono2) {
        this.telefono2 = telefono2;
    }

    
    @Column(name="REFE_3", length=30)
    public String getRefe3() {
        return this.refe3;
    }
    
    public void setRefe3(String refe3) {
        this.refe3 = refe3;
    }

    
    @Column(name="TELEFONO_3", length=8)
    public String getTelefono3() {
        return this.telefono3;
    }
    
    public void setTelefono3(String telefono3) {
        this.telefono3 = telefono3;
    }

    
    @Column(name="REFE_4", length=30)
    public String getRefe4() {
        return this.refe4;
    }
    
    public void setRefe4(String refe4) {
        this.refe4 = refe4;
    }

    
    @Column(name="TELEFONO_4", length=8)
    public String getTelefono4() {
        return this.telefono4;
    }
    
    public void setTelefono4(String telefono4) {
        this.telefono4 = telefono4;
    }

    
    @Column(name="REFE_5", length=30)
    public String getRefe5() {
        return this.refe5;
    }
    
    public void setRefe5(String refe5) {
        this.refe5 = refe5;
    }

    
    @Column(name="TELEFONO_5", length=8)
    public String getTelefono5() {
        return this.telefono5;
    }
    
    public void setTelefono5(String telefono5) {
        this.telefono5 = telefono5;
    }

    
    @Column(name="EVALUACION", length=20)
    public String getEvaluacion() {
        return this.evaluacion;
    }
    
    public void setEvaluacion(String evaluacion) {
        this.evaluacion = evaluacion;
    }

    
    @Column(name="CALIFICACION", length=10)
    public String getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(String calificacion) {
        this.calificacion = calificacion;
    }

    
    @Column(name="M_SOLICITADO", precision=17)
    public BigDecimal getMSolicitado() {
        return this.MSolicitado;
    }
    
    public void setMSolicitado(BigDecimal MSolicitado) {
        this.MSolicitado = MSolicitado;
    }

    
    @Column(name="APROBADO", length=1)
    public String getAprobado() {
        return this.aprobado;
    }
    
    public void setAprobado(String aprobado) {
        this.aprobado = aprobado;
    }

    
    @Column(name="ACTUALIZADO", length=1)
    public String getActualizado() {
        return this.actualizado;
    }
    
    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }

    
    @Column(name="LIMITE_CREDI_RES", precision=30)
    public BigDecimal getLimiteCrediRes() {
        return this.limiteCrediRes;
    }
    
    public void setLimiteCrediRes(BigDecimal limiteCrediRes) {
        this.limiteCrediRes = limiteCrediRes;
    }

    
    @Column(name="M_SOLICITADO_RES", precision=30)
    public BigDecimal getMSolicitadoRes() {
        return this.MSolicitadoRes;
    }
    
    public void setMSolicitadoRes(BigDecimal MSolicitadoRes) {
        this.MSolicitadoRes = MSolicitadoRes;
    }




}


