package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arccer generated by hbm2java
 */
@Entity
@Table(name="ARCCER"
    ,schema="DESA46"
)
public class Arccer  implements java.io.Serializable {


     private ArccerId id;
     private String tipoDeRelacion;
     private Date fecha;
     private String hechoPor;
     private String cobrador;
     private String estado;
     private String observacion;

    public Arccer() {
    }

	
    public Arccer(ArccerId id) {
        this.id = id;
    }
    public Arccer(ArccerId id, String tipoDeRelacion, Date fecha, String hechoPor, String cobrador, String estado, String observacion) {
       this.id = id;
       this.tipoDeRelacion = tipoDeRelacion;
       this.fecha = fecha;
       this.hechoPor = hechoPor;
       this.cobrador = cobrador;
       this.estado = estado;
       this.observacion = observacion;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noRelacion", column=@Column(name="NO_RELACION", nullable=false, precision=14, scale=0) ) } )
    public ArccerId getId() {
        return this.id;
    }
    
    public void setId(ArccerId id) {
        this.id = id;
    }

    
    @Column(name="TIPO_DE_RELACION", length=2)
    public String getTipoDeRelacion() {
        return this.tipoDeRelacion;
    }
    
    public void setTipoDeRelacion(String tipoDeRelacion) {
        this.tipoDeRelacion = tipoDeRelacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", length=7)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="HECHO_POR", length=30)
    public String getHechoPor() {
        return this.hechoPor;
    }
    
    public void setHechoPor(String hechoPor) {
        this.hechoPor = hechoPor;
    }

    
    @Column(name="COBRADOR", length=4)
    public String getCobrador() {
        return this.cobrador;
    }
    
    public void setCobrador(String cobrador) {
        this.cobrador = cobrador;
    }

    
    @Column(name="ESTADO", length=1)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="OBSERVACION", length=250)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }




}


