package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arccud generated by hbm2java
 */
@Entity
@Table(name="ARCCUD"
    ,schema="DESA46"
)
public class Arccud  implements java.io.Serializable {


     private ArccudId id;

    public Arccud() {
    }

    public Arccud(ArccudId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="tipo", column=@Column(name="TIPO", nullable=false, length=2) ), 
        @AttributeOverride(name="usuario", column=@Column(name="USUARIO", nullable=false, length=30) ) } )
    public ArccudId getId() {
        return this.id;
    }
    
    public void setId(ArccudId id) {
        this.id = id;
    }




}


