package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arcctc generated by hbm2java
 */
@Entity
@Table(name="ARCCTC"
    ,schema="DESA46"
)
public class Arcctc  implements java.io.Serializable {


     private ArcctcId id;
     private String descripcion;
     private BigDecimal porcDesc;

    public Arcctc() {
    }

	
    public Arcctc(ArcctcId id) {
        this.id = id;
    }
    public Arcctc(ArcctcId id, String descripcion, BigDecimal porcDesc) {
       this.id = id;
       this.descripcion = descripcion;
       this.porcDesc = porcDesc;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="tipoCliente", column=@Column(name="TIPO_CLIENTE", nullable=false, length=2) ) } )
    public ArcctcId getId() {
        return this.id;
    }
    
    public void setId(ArcctcId id) {
        this.id = id;
    }

    
    @Column(name="DESCRIPCION", length=40)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="PORC_DESC", precision=5)
    public BigDecimal getPorcDesc() {
        return this.porcDesc;
    }
    
    public void setPorcDesc(BigDecimal porcDesc) {
        this.porcDesc = porcDesc;
    }




}


