package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArccscId generated by hbm2java
 */
@Embeddable
public class ArccscId  implements java.io.Serializable {


     private String grupo;
     private String noCliente;
     private String noSoli;

    public ArccscId() {
    }

    public ArccscId(String grupo, String noCliente, String noSoli) {
       this.grupo = grupo;
       this.noCliente = noCliente;
       this.noSoli = noSoli;
    }
   


    @Column(name="GRUPO", nullable=false, length=2)
    public String getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }


    @Column(name="NO_CLIENTE", nullable=false, length=15)
    public String getNoCliente() {
        return this.noCliente;
    }
    
    public void setNoCliente(String noCliente) {
        this.noCliente = noCliente;
    }


    @Column(name="NO_SOLI", nullable=false, length=8)
    public String getNoSoli() {
        return this.noSoli;
    }
    
    public void setNoSoli(String noSoli) {
        this.noSoli = noSoli;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArccscId) ) return false;
		 ArccscId castOther = ( ArccscId ) other; 
         
		 return ( (this.getGrupo()==castOther.getGrupo()) || ( this.getGrupo()!=null && castOther.getGrupo()!=null && this.getGrupo().equals(castOther.getGrupo()) ) )
 && ( (this.getNoCliente()==castOther.getNoCliente()) || ( this.getNoCliente()!=null && castOther.getNoCliente()!=null && this.getNoCliente().equals(castOther.getNoCliente()) ) )
 && ( (this.getNoSoli()==castOther.getNoSoli()) || ( this.getNoSoli()!=null && castOther.getNoSoli()!=null && this.getNoSoli().equals(castOther.getNoSoli()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getGrupo() == null ? 0 : this.getGrupo().hashCode() );
         result = 37 * result + ( getNoCliente() == null ? 0 : this.getNoCliente().hashCode() );
         result = 37 * result + ( getNoSoli() == null ? 0 : this.getNoSoli().hashCode() );
         return result;
   }   


}


