package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArcczgId generated by hbm2java
 */
@Embeddable
public class ArcczgId  implements java.io.Serializable {


     private String noCia;
     private String zona;

    public ArcczgId() {
    }

    public ArcczgId(String noCia, String zona) {
       this.noCia = noCia;
       this.zona = zona;
    }
   


    @Column(name="NO_CIA", nullable=false, length=2)
    public String getNoCia() {
        return this.noCia;
    }
    
    public void setNoCia(String noCia) {
        this.noCia = noCia;
    }


    @Column(name="ZONA", nullable=false, length=5)
    public String getZona() {
        return this.zona;
    }
    
    public void setZona(String zona) {
        this.zona = zona;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArcczgId) ) return false;
		 ArcczgId castOther = ( ArcczgId ) other; 
         
		 return ( (this.getNoCia()==castOther.getNoCia()) || ( this.getNoCia()!=null && castOther.getNoCia()!=null && this.getNoCia().equals(castOther.getNoCia()) ) )
 && ( (this.getZona()==castOther.getZona()) || ( this.getZona()!=null && castOther.getZona()!=null && this.getZona().equals(castOther.getZona()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNoCia() == null ? 0 : this.getNoCia().hashCode() );
         result = 37 * result + ( getZona() == null ? 0 : this.getZona().hashCode() );
         return result;
   }   


}


