package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArcghcTId generated by hbm2java
 */
@Embeddable
public class ArcghcTId  implements java.io.Serializable {


     private String noCia;
     private short ano;
     private byte mes;
     private String cuenta;
     private String codigoTercero;

    public ArcghcTId() {
    }

    public ArcghcTId(String noCia, short ano, byte mes, String cuenta, String codigoTercero) {
       this.noCia = noCia;
       this.ano = ano;
       this.mes = mes;
       this.cuenta = cuenta;
       this.codigoTercero = codigoTercero;
    }
   


    @Column(name="NO_CIA", nullable=false, length=2)
    public String getNoCia() {
        return this.noCia;
    }
    
    public void setNoCia(String noCia) {
        this.noCia = noCia;
    }


    @Column(name="ANO", nullable=false, precision=4, scale=0)
    public short getAno() {
        return this.ano;
    }
    
    public void setAno(short ano) {
        this.ano = ano;
    }


    @Column(name="MES", nullable=false, precision=2, scale=0)
    public byte getMes() {
        return this.mes;
    }
    
    public void setMes(byte mes) {
        this.mes = mes;
    }


    @Column(name="CUENTA", nullable=false, length=15)
    public String getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }


    @Column(name="CODIGO_TERCERO", nullable=false, length=18)
    public String getCodigoTercero() {
        return this.codigoTercero;
    }
    
    public void setCodigoTercero(String codigoTercero) {
        this.codigoTercero = codigoTercero;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArcghcTId) ) return false;
		 ArcghcTId castOther = ( ArcghcTId ) other; 
         
		 return ( (this.getNoCia()==castOther.getNoCia()) || ( this.getNoCia()!=null && castOther.getNoCia()!=null && this.getNoCia().equals(castOther.getNoCia()) ) )
 && (this.getAno()==castOther.getAno())
 && (this.getMes()==castOther.getMes())
 && ( (this.getCuenta()==castOther.getCuenta()) || ( this.getCuenta()!=null && castOther.getCuenta()!=null && this.getCuenta().equals(castOther.getCuenta()) ) )
 && ( (this.getCodigoTercero()==castOther.getCodigoTercero()) || ( this.getCodigoTercero()!=null && castOther.getCodigoTercero()!=null && this.getCodigoTercero().equals(castOther.getCodigoTercero()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNoCia() == null ? 0 : this.getNoCia().hashCode() );
         result = 37 * result + this.getAno();
         result = 37 * result + this.getMes();
         result = 37 * result + ( getCuenta() == null ? 0 : this.getCuenta().hashCode() );
         result = 37 * result + ( getCodigoTercero() == null ? 0 : this.getCodigoTercero().hashCode() );
         return result;
   }   


}


