package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arcgtc generated by hbm2java
 */
@Entity
@Table(name="ARCGTC"
    ,schema="DESA46"
)
public class Arcgtc  implements java.io.Serializable {


     private ArcgtcId id;
     private BigDecimal tipoCambio;
     private BigDecimal tipoCambioVenta;
     private Date tstamp;

    public Arcgtc() {
    }

	
    public Arcgtc(ArcgtcId id) {
        this.id = id;
    }
    public Arcgtc(ArcgtcId id, BigDecimal tipoCambio, BigDecimal tipoCambioVenta, Date tstamp) {
       this.id = id;
       this.tipoCambio = tipoCambio;
       this.tipoCambioVenta = tipoCambioVenta;
       this.tstamp = tstamp;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="claseCambio", column=@Column(name="CLASE_CAMBIO", nullable=false, length=3) ), 
        @AttributeOverride(name="fecha", column=@Column(name="FECHA", nullable=false, length=7) ) } )
    public ArcgtcId getId() {
        return this.id;
    }
    
    public void setId(ArcgtcId id) {
        this.id = id;
    }

    
    @Column(name="TIPO_CAMBIO", precision=17, scale=4)
    public BigDecimal getTipoCambio() {
        return this.tipoCambio;
    }
    
    public void setTipoCambio(BigDecimal tipoCambio) {
        this.tipoCambio = tipoCambio;
    }

    
    @Column(name="TIPO_CAMBIO_VENTA", precision=17, scale=4)
    public BigDecimal getTipoCambioVenta() {
        return this.tipoCambioVenta;
    }
    
    public void setTipoCambioVenta(BigDecimal tipoCambioVenta) {
        this.tipoCambioVenta = tipoCambioVenta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TSTAMP", length=7)
    public Date getTstamp() {
        return this.tstamp;
    }
    
    public void setTstamp(Date tstamp) {
        this.tstamp = tstamp;
    }




}


