package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arcgcb generated by hbm2java
 */
@Entity
@Table(name="ARCGCB"
    ,schema="DESA46"
)
public class Arcgcb  implements java.io.Serializable {


     private ArcgcbId id;

    public Arcgcb() {
    }

    public Arcgcb(ArcgcbId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="codBalance", column=@Column(name="COD_BALANCE", nullable=false, length=2) ), 
        @AttributeOverride(name="cuenta", column=@Column(name="CUENTA", nullable=false, length=15) ) } )
    public ArcgcbId getId() {
        return this.id;
    }
    
    public void setId(ArcgcbId id) {
        this.id = id;
    }




}


