package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arcglimp generated by hbm2java
 */
@Entity
@Table(name="ARCGLIMP"
    ,schema="DESA46"
)
public class Arcglimp  implements java.io.Serializable {


     private ArcglimpId id;
     private String codigoTercero;
     private String sector;
     private String actividad;
     private String pais;
     private String provincia;
     private String canton;
     private BigDecimal porcentaje;
     private BigDecimal base;
     private Date fecha;
     private BigDecimal monto;
     private String idSec;
     private String indImpRet;
     private String aplicaCredFiscal;
     private String comportamiento;
     private BigDecimal baseRes;
     private BigDecimal montoRes;

    public Arcglimp() {
    }

	
    public Arcglimp(ArcglimpId id) {
        this.id = id;
    }
    public Arcglimp(ArcglimpId id, String codigoTercero, String sector, String actividad, String pais, String provincia, String canton, BigDecimal porcentaje, BigDecimal base, Date fecha, BigDecimal monto, String idSec, String indImpRet, String aplicaCredFiscal, String comportamiento, BigDecimal baseRes, BigDecimal montoRes) {
       this.id = id;
       this.codigoTercero = codigoTercero;
       this.sector = sector;
       this.actividad = actividad;
       this.pais = pais;
       this.provincia = provincia;
       this.canton = canton;
       this.porcentaje = porcentaje;
       this.base = base;
       this.fecha = fecha;
       this.monto = monto;
       this.idSec = idSec;
       this.indImpRet = indImpRet;
       this.aplicaCredFiscal = aplicaCredFiscal;
       this.comportamiento = comportamiento;
       this.baseRes = baseRes;
       this.montoRes = montoRes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noTransa", column=@Column(name="NO_TRANSA", nullable=false, length=12) ), 
        @AttributeOverride(name="clave", column=@Column(name="CLAVE", nullable=false, length=2) ), 
        @AttributeOverride(name="noRefe", column=@Column(name="NO_REFE", nullable=false, length=12) ) } )
    public ArcglimpId getId() {
        return this.id;
    }
    
    public void setId(ArcglimpId id) {
        this.id = id;
    }

    
    @Column(name="CODIGO_TERCERO", length=18)
    public String getCodigoTercero() {
        return this.codigoTercero;
    }
    
    public void setCodigoTercero(String codigoTercero) {
        this.codigoTercero = codigoTercero;
    }

    
    @Column(name="SECTOR", length=2)
    public String getSector() {
        return this.sector;
    }
    
    public void setSector(String sector) {
        this.sector = sector;
    }

    
    @Column(name="ACTIVIDAD", length=4)
    public String getActividad() {
        return this.actividad;
    }
    
    public void setActividad(String actividad) {
        this.actividad = actividad;
    }

    
    @Column(name="PAIS", length=6)
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }

    
    @Column(name="PROVINCIA", length=6)
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }

    
    @Column(name="CANTON", length=6)
    public String getCanton() {
        return this.canton;
    }
    
    public void setCanton(String canton) {
        this.canton = canton;
    }

    
    @Column(name="PORCENTAJE", precision=7, scale=4)
    public BigDecimal getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(BigDecimal porcentaje) {
        this.porcentaje = porcentaje;
    }

    
    @Column(name="BASE", precision=17)
    public BigDecimal getBase() {
        return this.base;
    }
    
    public void setBase(BigDecimal base) {
        this.base = base;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", length=7)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="MONTO", precision=17)
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

    
    @Column(name="ID_SEC", length=5)
    public String getIdSec() {
        return this.idSec;
    }
    
    public void setIdSec(String idSec) {
        this.idSec = idSec;
    }

    
    @Column(name="IND_IMP_RET", length=1)
    public String getIndImpRet() {
        return this.indImpRet;
    }
    
    public void setIndImpRet(String indImpRet) {
        this.indImpRet = indImpRet;
    }

    
    @Column(name="APLICA_CRED_FISCAL", length=1)
    public String getAplicaCredFiscal() {
        return this.aplicaCredFiscal;
    }
    
    public void setAplicaCredFiscal(String aplicaCredFiscal) {
        this.aplicaCredFiscal = aplicaCredFiscal;
    }

    
    @Column(name="COMPORTAMIENTO", length=1)
    public String getComportamiento() {
        return this.comportamiento;
    }
    
    public void setComportamiento(String comportamiento) {
        this.comportamiento = comportamiento;
    }

    
    @Column(name="BASE_RES", precision=30)
    public BigDecimal getBaseRes() {
        return this.baseRes;
    }
    
    public void setBaseRes(BigDecimal baseRes) {
        this.baseRes = baseRes;
    }

    
    @Column(name="MONTO_RES", precision=30)
    public BigDecimal getMontoRes() {
        return this.montoRes;
    }
    
    public void setMontoRes(BigDecimal montoRes) {
        this.montoRes = montoRes;
    }




}


