package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ArcghcT generated by hbm2java
 */
@Entity
@Table(name="ARCGHC_T"
    ,schema="DESA46"
)
public class ArcghcT  implements java.io.Serializable {


     private ArcghcTId id;
     private Integer periodo;
     private BigDecimal movimiento;
     private BigDecimal movDb;
     private BigDecimal movCr;
     private BigDecimal saldo;
     private BigDecimal movDbDol;
     private BigDecimal movCrDol;
     private BigDecimal saldoDol;
     private BigDecimal movimientoRes;
     private BigDecimal movDbRes;
     private BigDecimal movCrRes;
     private BigDecimal saldoRes;

    public ArcghcT() {
    }

	
    public ArcghcT(ArcghcTId id) {
        this.id = id;
    }
    public ArcghcT(ArcghcTId id, Integer periodo, BigDecimal movimiento, BigDecimal movDb, BigDecimal movCr, BigDecimal saldo, BigDecimal movDbDol, BigDecimal movCrDol, BigDecimal saldoDol, BigDecimal movimientoRes, BigDecimal movDbRes, BigDecimal movCrRes, BigDecimal saldoRes) {
       this.id = id;
       this.periodo = periodo;
       this.movimiento = movimiento;
       this.movDb = movDb;
       this.movCr = movCr;
       this.saldo = saldo;
       this.movDbDol = movDbDol;
       this.movCrDol = movCrDol;
       this.saldoDol = saldoDol;
       this.movimientoRes = movimientoRes;
       this.movDbRes = movDbRes;
       this.movCrRes = movCrRes;
       this.saldoRes = saldoRes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="ano", column=@Column(name="ANO", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="mes", column=@Column(name="MES", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="cuenta", column=@Column(name="CUENTA", nullable=false, length=15) ), 
        @AttributeOverride(name="codigoTercero", column=@Column(name="CODIGO_TERCERO", nullable=false, length=18) ) } )
    public ArcghcTId getId() {
        return this.id;
    }
    
    public void setId(ArcghcTId id) {
        this.id = id;
    }

    
    @Column(name="PERIODO", precision=6, scale=0)
    public Integer getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Integer periodo) {
        this.periodo = periodo;
    }

    
    @Column(name="MOVIMIENTO", precision=17)
    public BigDecimal getMovimiento() {
        return this.movimiento;
    }
    
    public void setMovimiento(BigDecimal movimiento) {
        this.movimiento = movimiento;
    }

    
    @Column(name="MOV_DB", precision=17)
    public BigDecimal getMovDb() {
        return this.movDb;
    }
    
    public void setMovDb(BigDecimal movDb) {
        this.movDb = movDb;
    }

    
    @Column(name="MOV_CR", precision=17)
    public BigDecimal getMovCr() {
        return this.movCr;
    }
    
    public void setMovCr(BigDecimal movCr) {
        this.movCr = movCr;
    }

    
    @Column(name="SALDO", precision=17)
    public BigDecimal getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(BigDecimal saldo) {
        this.saldo = saldo;
    }

    
    @Column(name="MOV_DB_DOL", precision=17)
    public BigDecimal getMovDbDol() {
        return this.movDbDol;
    }
    
    public void setMovDbDol(BigDecimal movDbDol) {
        this.movDbDol = movDbDol;
    }

    
    @Column(name="MOV_CR_DOL", precision=17)
    public BigDecimal getMovCrDol() {
        return this.movCrDol;
    }
    
    public void setMovCrDol(BigDecimal movCrDol) {
        this.movCrDol = movCrDol;
    }

    
    @Column(name="SALDO_DOL", precision=17)
    public BigDecimal getSaldoDol() {
        return this.saldoDol;
    }
    
    public void setSaldoDol(BigDecimal saldoDol) {
        this.saldoDol = saldoDol;
    }

    
    @Column(name="MOVIMIENTO_RES", precision=30)
    public BigDecimal getMovimientoRes() {
        return this.movimientoRes;
    }
    
    public void setMovimientoRes(BigDecimal movimientoRes) {
        this.movimientoRes = movimientoRes;
    }

    
    @Column(name="MOV_DB_RES", precision=30)
    public BigDecimal getMovDbRes() {
        return this.movDbRes;
    }
    
    public void setMovDbRes(BigDecimal movDbRes) {
        this.movDbRes = movDbRes;
    }

    
    @Column(name="MOV_CR_RES", precision=30)
    public BigDecimal getMovCrRes() {
        return this.movCrRes;
    }
    
    public void setMovCrRes(BigDecimal movCrRes) {
        this.movCrRes = movCrRes;
    }

    
    @Column(name="SALDO_RES", precision=30)
    public BigDecimal getSaldoRes() {
        return this.saldoRes;
    }
    
    public void setSaldoRes(BigDecimal saldoRes) {
        this.saldoRes = saldoRes;
    }




}


