package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arcgae generated by hbm2java
 */
@Entity
@Table(name="ARCGAE"
    ,schema="DESA46"
)
public class Arcgae  implements java.io.Serializable {


     private ArcgaeId id;
     private Short ano;
     private Byte mes;
     private String impreso;
     private Date fecha;
     private String descri1;
     private String estado;
     private String autorizado;
     private String origen;
     private BigDecimal TDebitos;
     private BigDecimal TCreditos;
     private String codDiario;
     private String TCambCV;
     private BigDecimal tipoCambio;
     private String tipoComprobante;
     private String noComprobante;
     private String anulado;
     private String centrod;
     private String centrof;
     private String corporativo;
     private Date tstamp;

    public Arcgae() {
    }

	
    public Arcgae(ArcgaeId id) {
        this.id = id;
    }
    public Arcgae(ArcgaeId id, Short ano, Byte mes, String impreso, Date fecha, String descri1, String estado, String autorizado, String origen, BigDecimal TDebitos, BigDecimal TCreditos, String codDiario, String TCambCV, BigDecimal tipoCambio, String tipoComprobante, String noComprobante, String anulado, String centrod, String centrof, String corporativo, Date tstamp) {
       this.id = id;
       this.ano = ano;
       this.mes = mes;
       this.impreso = impreso;
       this.fecha = fecha;
       this.descri1 = descri1;
       this.estado = estado;
       this.autorizado = autorizado;
       this.origen = origen;
       this.TDebitos = TDebitos;
       this.TCreditos = TCreditos;
       this.codDiario = codDiario;
       this.TCambCV = TCambCV;
       this.tipoCambio = tipoCambio;
       this.tipoComprobante = tipoComprobante;
       this.noComprobante = noComprobante;
       this.anulado = anulado;
       this.centrod = centrod;
       this.centrof = centrof;
       this.corporativo = corporativo;
       this.tstamp = tstamp;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noAsiento", column=@Column(name="NO_ASIENTO", nullable=false, length=12) ), 
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ) } )
    public ArcgaeId getId() {
        return this.id;
    }
    
    public void setId(ArcgaeId id) {
        this.id = id;
    }

    
    @Column(name="ANO", precision=4, scale=0)
    public Short getAno() {
        return this.ano;
    }
    
    public void setAno(Short ano) {
        this.ano = ano;
    }

    
    @Column(name="MES", precision=2, scale=0)
    public Byte getMes() {
        return this.mes;
    }
    
    public void setMes(Byte mes) {
        this.mes = mes;
    }

    
    @Column(name="IMPRESO", length=1)
    public String getImpreso() {
        return this.impreso;
    }
    
    public void setImpreso(String impreso) {
        this.impreso = impreso;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", length=7)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="DESCRI1", length=240)
    public String getDescri1() {
        return this.descri1;
    }
    
    public void setDescri1(String descri1) {
        this.descri1 = descri1;
    }

    
    @Column(name="ESTADO", length=1)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="AUTORIZADO", length=1)
    public String getAutorizado() {
        return this.autorizado;
    }
    
    public void setAutorizado(String autorizado) {
        this.autorizado = autorizado;
    }

    
    @Column(name="ORIGEN", length=2)
    public String getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(String origen) {
        this.origen = origen;
    }

    
    @Column(name="T_DEBITOS", precision=17)
    public BigDecimal getTDebitos() {
        return this.TDebitos;
    }
    
    public void setTDebitos(BigDecimal TDebitos) {
        this.TDebitos = TDebitos;
    }

    
    @Column(name="T_CREDITOS", precision=17)
    public BigDecimal getTCreditos() {
        return this.TCreditos;
    }
    
    public void setTCreditos(BigDecimal TCreditos) {
        this.TCreditos = TCreditos;
    }

    
    @Column(name="COD_DIARIO", length=5)
    public String getCodDiario() {
        return this.codDiario;
    }
    
    public void setCodDiario(String codDiario) {
        this.codDiario = codDiario;
    }

    
    @Column(name="T_CAMB_C_V", length=1)
    public String getTCambCV() {
        return this.TCambCV;
    }
    
    public void setTCambCV(String TCambCV) {
        this.TCambCV = TCambCV;
    }

    
    @Column(name="TIPO_CAMBIO", precision=17, scale=4)
    public BigDecimal getTipoCambio() {
        return this.tipoCambio;
    }
    
    public void setTipoCambio(BigDecimal tipoCambio) {
        this.tipoCambio = tipoCambio;
    }

    
    @Column(name="TIPO_COMPROBANTE", length=1)
    public String getTipoComprobante() {
        return this.tipoComprobante;
    }
    
    public void setTipoComprobante(String tipoComprobante) {
        this.tipoComprobante = tipoComprobante;
    }

    
    @Column(name="NO_COMPROBANTE", length=12)
    public String getNoComprobante() {
        return this.noComprobante;
    }
    
    public void setNoComprobante(String noComprobante) {
        this.noComprobante = noComprobante;
    }

    
    @Column(name="ANULADO", length=1)
    public String getAnulado() {
        return this.anulado;
    }
    
    public void setAnulado(String anulado) {
        this.anulado = anulado;
    }

    
    @Column(name="CENTROD", length=2)
    public String getCentrod() {
        return this.centrod;
    }
    
    public void setCentrod(String centrod) {
        this.centrod = centrod;
    }

    
    @Column(name="CENTROF", length=4)
    public String getCentrof() {
        return this.centrof;
    }
    
    public void setCentrof(String centrof) {
        this.centrof = centrof;
    }

    
    @Column(name="CORPORATIVO", length=1)
    public String getCorporativo() {
        return this.corporativo;
    }
    
    public void setCorporativo(String corporativo) {
        this.corporativo = corporativo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TSTAMP", length=7)
    public Date getTstamp() {
        return this.tstamp;
    }
    
    public void setTstamp(Date tstamp) {
        this.tstamp = tstamp;
    }




}


