package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arcgmm generated by hbm2java
 */
@Entity
@Table(name="ARCGMM"
    ,schema="DESA46"
)
public class Arcgmm  implements java.io.Serializable {


     private ArcgmmId id;
     private Integer periodo;
     private String cc1;
     private String cc2;
     private String cc3;
     private Date fecha;
     private String noDocu;
     private String moneda;
     private BigDecimal monto;
     private BigDecimal tipoCambio;
     private BigDecimal montoDol;
     private String tipo;
     private String descri;
     private String codDiario;
     private String tipoComprobante;
     private String noComprobante;
     private String codigoTercero;
     private String lineaAjustePrecision;
     private BigDecimal montoRes;

    public Arcgmm() {
    }

	
    public Arcgmm(ArcgmmId id) {
        this.id = id;
    }
    public Arcgmm(ArcgmmId id, Integer periodo, String cc1, String cc2, String cc3, Date fecha, String noDocu, String moneda, BigDecimal monto, BigDecimal tipoCambio, BigDecimal montoDol, String tipo, String descri, String codDiario, String tipoComprobante, String noComprobante, String codigoTercero, String lineaAjustePrecision, BigDecimal montoRes) {
       this.id = id;
       this.periodo = periodo;
       this.cc1 = cc1;
       this.cc2 = cc2;
       this.cc3 = cc3;
       this.fecha = fecha;
       this.noDocu = noDocu;
       this.moneda = moneda;
       this.monto = monto;
       this.tipoCambio = tipoCambio;
       this.montoDol = montoDol;
       this.tipo = tipo;
       this.descri = descri;
       this.codDiario = codDiario;
       this.tipoComprobante = tipoComprobante;
       this.noComprobante = noComprobante;
       this.codigoTercero = codigoTercero;
       this.lineaAjustePrecision = lineaAjustePrecision;
       this.montoRes = montoRes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="cuenta", column=@Column(name="CUENTA", nullable=false, length=15) ), 
        @AttributeOverride(name="noAsiento", column=@Column(name="NO_ASIENTO", nullable=false, length=12) ), 
        @AttributeOverride(name="ano", column=@Column(name="ANO", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="mes", column=@Column(name="MES", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="noLinea", column=@Column(name="NO_LINEA", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ) } )
    public ArcgmmId getId() {
        return this.id;
    }
    
    public void setId(ArcgmmId id) {
        this.id = id;
    }

    
    @Column(name="PERIODO", precision=6, scale=0)
    public Integer getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Integer periodo) {
        this.periodo = periodo;
    }

    
    @Column(name="CC_1", length=3)
    public String getCc1() {
        return this.cc1;
    }
    
    public void setCc1(String cc1) {
        this.cc1 = cc1;
    }

    
    @Column(name="CC_2", length=3)
    public String getCc2() {
        return this.cc2;
    }
    
    public void setCc2(String cc2) {
        this.cc2 = cc2;
    }

    
    @Column(name="CC_3", length=3)
    public String getCc3() {
        return this.cc3;
    }
    
    public void setCc3(String cc3) {
        this.cc3 = cc3;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", length=7)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="NO_DOCU", length=12)
    public String getNoDocu() {
        return this.noDocu;
    }
    
    public void setNoDocu(String noDocu) {
        this.noDocu = noDocu;
    }

    
    @Column(name="MONEDA", length=1)
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }

    
    @Column(name="MONTO", precision=17)
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

    
    @Column(name="TIPO_CAMBIO", precision=17, scale=4)
    public BigDecimal getTipoCambio() {
        return this.tipoCambio;
    }
    
    public void setTipoCambio(BigDecimal tipoCambio) {
        this.tipoCambio = tipoCambio;
    }

    
    @Column(name="MONTO_DOL", precision=17)
    public BigDecimal getMontoDol() {
        return this.montoDol;
    }
    
    public void setMontoDol(BigDecimal montoDol) {
        this.montoDol = montoDol;
    }

    
    @Column(name="TIPO", length=1)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="DESCRI", length=30)
    public String getDescri() {
        return this.descri;
    }
    
    public void setDescri(String descri) {
        this.descri = descri;
    }

    
    @Column(name="COD_DIARIO", length=5)
    public String getCodDiario() {
        return this.codDiario;
    }
    
    public void setCodDiario(String codDiario) {
        this.codDiario = codDiario;
    }

    
    @Column(name="TIPO_COMPROBANTE", length=1)
    public String getTipoComprobante() {
        return this.tipoComprobante;
    }
    
    public void setTipoComprobante(String tipoComprobante) {
        this.tipoComprobante = tipoComprobante;
    }

    
    @Column(name="NO_COMPROBANTE", length=12)
    public String getNoComprobante() {
        return this.noComprobante;
    }
    
    public void setNoComprobante(String noComprobante) {
        this.noComprobante = noComprobante;
    }

    
    @Column(name="CODIGO_TERCERO", length=18)
    public String getCodigoTercero() {
        return this.codigoTercero;
    }
    
    public void setCodigoTercero(String codigoTercero) {
        this.codigoTercero = codigoTercero;
    }

    
    @Column(name="LINEA_AJUSTE_PRECISION", length=1)
    public String getLineaAjustePrecision() {
        return this.lineaAjustePrecision;
    }
    
    public void setLineaAjustePrecision(String lineaAjustePrecision) {
        this.lineaAjustePrecision = lineaAjustePrecision;
    }

    
    @Column(name="MONTO_RES", precision=30)
    public BigDecimal getMontoRes() {
        return this.montoRes;
    }
    
    public void setMontoRes(BigDecimal montoRes) {
        this.montoRes = montoRes;
    }




}


