package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arcgimp generated by hbm2java
 */
@Entity
@Table(name="ARCGIMP"
    ,schema="DESA46"
)
public class Arcgimp  implements java.io.Serializable {


     private ArcgimpId id;
     private String grupo;
     private String descripcion;
     private String sectorizable;
     private Boolean columna;
     private String indRetencion;
     private String certificado;
     private Short diasCredFiscal;
     private String afecta;
     private BigDecimal baseMinima;
     private BigDecimal porcentaje;
     private String cuenta;
     private String incluido;
     private String especial;
     private String cuentaPuente;
     private Short prioridad;
     private String noRet;
     private String descripcionLarga;
     private String centroCosto;

    public Arcgimp() {
    }

	
    public Arcgimp(ArcgimpId id) {
        this.id = id;
    }
    public Arcgimp(ArcgimpId id, String grupo, String descripcion, String sectorizable, Boolean columna, String indRetencion, String certificado, Short diasCredFiscal, String afecta, BigDecimal baseMinima, BigDecimal porcentaje, String cuenta, String incluido, String especial, String cuentaPuente, Short prioridad, String noRet, String descripcionLarga, String centroCosto) {
       this.id = id;
       this.grupo = grupo;
       this.descripcion = descripcion;
       this.sectorizable = sectorizable;
       this.columna = columna;
       this.indRetencion = indRetencion;
       this.certificado = certificado;
       this.diasCredFiscal = diasCredFiscal;
       this.afecta = afecta;
       this.baseMinima = baseMinima;
       this.porcentaje = porcentaje;
       this.cuenta = cuenta;
       this.incluido = incluido;
       this.especial = especial;
       this.cuentaPuente = cuentaPuente;
       this.prioridad = prioridad;
       this.noRet = noRet;
       this.descripcionLarga = descripcionLarga;
       this.centroCosto = centroCosto;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="clave", column=@Column(name="CLAVE", nullable=false, length=2) ), 
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ) } )
    public ArcgimpId getId() {
        return this.id;
    }
    
    public void setId(ArcgimpId id) {
        this.id = id;
    }

    
    @Column(name="GRUPO", length=5)
    public String getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }

    
    @Column(name="DESCRIPCION", length=20)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="SECTORIZABLE", length=1)
    public String getSectorizable() {
        return this.sectorizable;
    }
    
    public void setSectorizable(String sectorizable) {
        this.sectorizable = sectorizable;
    }

    
    @Column(name="COLUMNA", precision=1, scale=0)
    public Boolean getColumna() {
        return this.columna;
    }
    
    public void setColumna(Boolean columna) {
        this.columna = columna;
    }

    
    @Column(name="IND_RETENCION", length=1)
    public String getIndRetencion() {
        return this.indRetencion;
    }
    
    public void setIndRetencion(String indRetencion) {
        this.indRetencion = indRetencion;
    }

    
    @Column(name="CERTIFICADO", length=1)
    public String getCertificado() {
        return this.certificado;
    }
    
    public void setCertificado(String certificado) {
        this.certificado = certificado;
    }

    
    @Column(name="DIAS_CRED_FISCAL", precision=4, scale=0)
    public Short getDiasCredFiscal() {
        return this.diasCredFiscal;
    }
    
    public void setDiasCredFiscal(Short diasCredFiscal) {
        this.diasCredFiscal = diasCredFiscal;
    }

    
    @Column(name="AFECTA", length=1)
    public String getAfecta() {
        return this.afecta;
    }
    
    public void setAfecta(String afecta) {
        this.afecta = afecta;
    }

    
    @Column(name="BASE_MINIMA")
    public BigDecimal getBaseMinima() {
        return this.baseMinima;
    }
    
    public void setBaseMinima(BigDecimal baseMinima) {
        this.baseMinima = baseMinima;
    }

    
    @Column(name="PORCENTAJE", precision=7, scale=4)
    public BigDecimal getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(BigDecimal porcentaje) {
        this.porcentaje = porcentaje;
    }

    
    @Column(name="CUENTA", length=15)
    public String getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }

    
    @Column(name="INCLUIDO", length=1)
    public String getIncluido() {
        return this.incluido;
    }
    
    public void setIncluido(String incluido) {
        this.incluido = incluido;
    }

    
    @Column(name="ESPECIAL", length=1)
    public String getEspecial() {
        return this.especial;
    }
    
    public void setEspecial(String especial) {
        this.especial = especial;
    }

    
    @Column(name="CUENTA_PUENTE", length=15)
    public String getCuentaPuente() {
        return this.cuentaPuente;
    }
    
    public void setCuentaPuente(String cuentaPuente) {
        this.cuentaPuente = cuentaPuente;
    }

    
    @Column(name="PRIORIDAD", precision=3, scale=0)
    public Short getPrioridad() {
        return this.prioridad;
    }
    
    public void setPrioridad(Short prioridad) {
        this.prioridad = prioridad;
    }

    
    @Column(name="NO_RET", length=4)
    public String getNoRet() {
        return this.noRet;
    }
    
    public void setNoRet(String noRet) {
        this.noRet = noRet;
    }

    
    @Column(name="DESCRIPCION_LARGA", length=500)
    public String getDescripcionLarga() {
        return this.descripcionLarga;
    }
    
    public void setDescripcionLarga(String descripcionLarga) {
        this.descripcionLarga = descripcionLarga;
    }

    
    @Column(name="CENTRO_COSTO", length=9)
    public String getCentroCosto() {
        return this.centroCosto;
    }
    
    public void setCentroCosto(String centroCosto) {
        this.centroCosto = centroCosto;
    }




}


