package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arcgcd generated by hbm2java
 */
@Entity
@Table(name="ARCGCD"
    ,schema="DESA46"
)
public class Arcgcd  implements java.io.Serializable {


     private ArcgcdId id;
     private String descripcion;

    public Arcgcd() {
    }

	
    public Arcgcd(ArcgcdId id) {
        this.id = id;
    }
    public Arcgcd(ArcgcdId id, String descripcion) {
       this.id = id;
       this.descripcion = descripcion;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="codDiario", column=@Column(name="COD_DIARIO", nullable=false, length=5) ) } )
    public ArcgcdId getId() {
        return this.id;
    }
    
    public void setId(ArcgcdId id) {
        this.id = id;
    }

    
    @Column(name="DESCRIPCION", length=20)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


