package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arcggrl generated by hbm2java
 */
@Entity
@Table(name="ARCGGRL"
    ,schema="DESA46"
)
public class Arcggrl  implements java.io.Serializable {


     private ArcggrlId id;
     private Boolean colMonto;
     private String descrip;
     private String total;
     private String campo;
     private String signo;
     private String vn;
     private BigDecimal m1;
     private BigDecimal m2;
     private BigDecimal m3;
     private BigDecimal m4;
     private BigDecimal m5;
     private BigDecimal m6;
     private BigDecimal m7;
     private BigDecimal m8;
     private BigDecimal m9;
     private BigDecimal m10;
     private BigDecimal m11;
     private BigDecimal m12;
     private BigDecimal m1Res;
     private BigDecimal m2Res;
     private BigDecimal m3Res;
     private BigDecimal m4Res;
     private BigDecimal m5Res;
     private BigDecimal m6Res;
     private BigDecimal m7Res;
     private BigDecimal m8Res;
     private BigDecimal m9Res;
     private BigDecimal m10Res;
     private BigDecimal m11Res;
     private BigDecimal m12Res;

    public Arcggrl() {
    }

	
    public Arcggrl(ArcggrlId id) {
        this.id = id;
    }
    public Arcggrl(ArcggrlId id, Boolean colMonto, String descrip, String total, String campo, String signo, String vn, BigDecimal m1, BigDecimal m2, BigDecimal m3, BigDecimal m4, BigDecimal m5, BigDecimal m6, BigDecimal m7, BigDecimal m8, BigDecimal m9, BigDecimal m10, BigDecimal m11, BigDecimal m12, BigDecimal m1Res, BigDecimal m2Res, BigDecimal m3Res, BigDecimal m4Res, BigDecimal m5Res, BigDecimal m6Res, BigDecimal m7Res, BigDecimal m8Res, BigDecimal m9Res, BigDecimal m10Res, BigDecimal m11Res, BigDecimal m12Res) {
       this.id = id;
       this.colMonto = colMonto;
       this.descrip = descrip;
       this.total = total;
       this.campo = campo;
       this.signo = signo;
       this.vn = vn;
       this.m1 = m1;
       this.m2 = m2;
       this.m3 = m3;
       this.m4 = m4;
       this.m5 = m5;
       this.m6 = m6;
       this.m7 = m7;
       this.m8 = m8;
       this.m9 = m9;
       this.m10 = m10;
       this.m11 = m11;
       this.m12 = m12;
       this.m1Res = m1Res;
       this.m2Res = m2Res;
       this.m3Res = m3Res;
       this.m4Res = m4Res;
       this.m5Res = m5Res;
       this.m6Res = m6Res;
       this.m7Res = m7Res;
       this.m8Res = m8Res;
       this.m9Res = m9Res;
       this.m10Res = m10Res;
       this.m11Res = m11Res;
       this.m12Res = m12Res;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="rep", column=@Column(name="REP", nullable=false, precision=3, scale=0) ), 
        @AttributeOverride(name="linea", column=@Column(name="LINEA", nullable=false, precision=4, scale=0) ) } )
    public ArcggrlId getId() {
        return this.id;
    }
    
    public void setId(ArcggrlId id) {
        this.id = id;
    }

    
    @Column(name="COL_MONTO", precision=1, scale=0)
    public Boolean getColMonto() {
        return this.colMonto;
    }
    
    public void setColMonto(Boolean colMonto) {
        this.colMonto = colMonto;
    }

    
    @Column(name="DESCRIP", length=30)
    public String getDescrip() {
        return this.descrip;
    }
    
    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }

    
    @Column(name="TOTAL", length=3)
    public String getTotal() {
        return this.total;
    }
    
    public void setTotal(String total) {
        this.total = total;
    }

    
    @Column(name="CAMPO", length=3)
    public String getCampo() {
        return this.campo;
    }
    
    public void setCampo(String campo) {
        this.campo = campo;
    }

    
    @Column(name="SIGNO", length=1)
    public String getSigno() {
        return this.signo;
    }
    
    public void setSigno(String signo) {
        this.signo = signo;
    }

    
    @Column(name="VN", length=1)
    public String getVn() {
        return this.vn;
    }
    
    public void setVn(String vn) {
        this.vn = vn;
    }

    
    @Column(name="M1", precision=17)
    public BigDecimal getM1() {
        return this.m1;
    }
    
    public void setM1(BigDecimal m1) {
        this.m1 = m1;
    }

    
    @Column(name="M2", precision=17)
    public BigDecimal getM2() {
        return this.m2;
    }
    
    public void setM2(BigDecimal m2) {
        this.m2 = m2;
    }

    
    @Column(name="M3", precision=17)
    public BigDecimal getM3() {
        return this.m3;
    }
    
    public void setM3(BigDecimal m3) {
        this.m3 = m3;
    }

    
    @Column(name="M4", precision=17)
    public BigDecimal getM4() {
        return this.m4;
    }
    
    public void setM4(BigDecimal m4) {
        this.m4 = m4;
    }

    
    @Column(name="M5", precision=17)
    public BigDecimal getM5() {
        return this.m5;
    }
    
    public void setM5(BigDecimal m5) {
        this.m5 = m5;
    }

    
    @Column(name="M6", precision=17)
    public BigDecimal getM6() {
        return this.m6;
    }
    
    public void setM6(BigDecimal m6) {
        this.m6 = m6;
    }

    
    @Column(name="M7", precision=17)
    public BigDecimal getM7() {
        return this.m7;
    }
    
    public void setM7(BigDecimal m7) {
        this.m7 = m7;
    }

    
    @Column(name="M8", precision=17)
    public BigDecimal getM8() {
        return this.m8;
    }
    
    public void setM8(BigDecimal m8) {
        this.m8 = m8;
    }

    
    @Column(name="M9", precision=17)
    public BigDecimal getM9() {
        return this.m9;
    }
    
    public void setM9(BigDecimal m9) {
        this.m9 = m9;
    }

    
    @Column(name="M10", precision=17)
    public BigDecimal getM10() {
        return this.m10;
    }
    
    public void setM10(BigDecimal m10) {
        this.m10 = m10;
    }

    
    @Column(name="M11", precision=17)
    public BigDecimal getM11() {
        return this.m11;
    }
    
    public void setM11(BigDecimal m11) {
        this.m11 = m11;
    }

    
    @Column(name="M12", precision=17)
    public BigDecimal getM12() {
        return this.m12;
    }
    
    public void setM12(BigDecimal m12) {
        this.m12 = m12;
    }

    
    @Column(name="M1_RES", precision=30)
    public BigDecimal getM1Res() {
        return this.m1Res;
    }
    
    public void setM1Res(BigDecimal m1Res) {
        this.m1Res = m1Res;
    }

    
    @Column(name="M2_RES", precision=30)
    public BigDecimal getM2Res() {
        return this.m2Res;
    }
    
    public void setM2Res(BigDecimal m2Res) {
        this.m2Res = m2Res;
    }

    
    @Column(name="M3_RES", precision=30)
    public BigDecimal getM3Res() {
        return this.m3Res;
    }
    
    public void setM3Res(BigDecimal m3Res) {
        this.m3Res = m3Res;
    }

    
    @Column(name="M4_RES", precision=30)
    public BigDecimal getM4Res() {
        return this.m4Res;
    }
    
    public void setM4Res(BigDecimal m4Res) {
        this.m4Res = m4Res;
    }

    
    @Column(name="M5_RES", precision=30)
    public BigDecimal getM5Res() {
        return this.m5Res;
    }
    
    public void setM5Res(BigDecimal m5Res) {
        this.m5Res = m5Res;
    }

    
    @Column(name="M6_RES", precision=30)
    public BigDecimal getM6Res() {
        return this.m6Res;
    }
    
    public void setM6Res(BigDecimal m6Res) {
        this.m6Res = m6Res;
    }

    
    @Column(name="M7_RES", precision=30)
    public BigDecimal getM7Res() {
        return this.m7Res;
    }
    
    public void setM7Res(BigDecimal m7Res) {
        this.m7Res = m7Res;
    }

    
    @Column(name="M8_RES", precision=30)
    public BigDecimal getM8Res() {
        return this.m8Res;
    }
    
    public void setM8Res(BigDecimal m8Res) {
        this.m8Res = m8Res;
    }

    
    @Column(name="M9_RES", precision=30)
    public BigDecimal getM9Res() {
        return this.m9Res;
    }
    
    public void setM9Res(BigDecimal m9Res) {
        this.m9Res = m9Res;
    }

    
    @Column(name="M10_RES", precision=30)
    public BigDecimal getM10Res() {
        return this.m10Res;
    }
    
    public void setM10Res(BigDecimal m10Res) {
        this.m10Res = m10Res;
    }

    
    @Column(name="M11_RES", precision=30)
    public BigDecimal getM11Res() {
        return this.m11Res;
    }
    
    public void setM11Res(BigDecimal m11Res) {
        this.m11Res = m11Res;
    }

    
    @Column(name="M12_RES", precision=30)
    public BigDecimal getM12Res() {
        return this.m12Res;
    }
    
    public void setM12Res(BigDecimal m12Res) {
        this.m12Res = m12Res;
    }




}


