package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArcgctCId generated by hbm2java
 */
@Embeddable
public class ArcgctCId  implements java.io.Serializable {


     private String noCia;
     private String modulo;
     private String subModulo;

    public ArcgctCId() {
    }

    public ArcgctCId(String noCia, String modulo, String subModulo) {
       this.noCia = noCia;
       this.modulo = modulo;
       this.subModulo = subModulo;
    }
   


    @Column(name="NO_CIA", nullable=false, length=2)
    public String getNoCia() {
        return this.noCia;
    }
    
    public void setNoCia(String noCia) {
        this.noCia = noCia;
    }


    @Column(name="MODULO", nullable=false, length=20)
    public String getModulo() {
        return this.modulo;
    }
    
    public void setModulo(String modulo) {
        this.modulo = modulo;
    }


    @Column(name="SUB_MODULO", nullable=false, length=15)
    public String getSubModulo() {
        return this.subModulo;
    }
    
    public void setSubModulo(String subModulo) {
        this.subModulo = subModulo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArcgctCId) ) return false;
		 ArcgctCId castOther = ( ArcgctCId ) other; 
         
		 return ( (this.getNoCia()==castOther.getNoCia()) || ( this.getNoCia()!=null && castOther.getNoCia()!=null && this.getNoCia().equals(castOther.getNoCia()) ) )
 && ( (this.getModulo()==castOther.getModulo()) || ( this.getModulo()!=null && castOther.getModulo()!=null && this.getModulo().equals(castOther.getModulo()) ) )
 && ( (this.getSubModulo()==castOther.getSubModulo()) || ( this.getSubModulo()!=null && castOther.getSubModulo()!=null && this.getSubModulo().equals(castOther.getSubModulo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNoCia() == null ? 0 : this.getNoCia().hashCode() );
         result = 37 * result + ( getModulo() == null ? 0 : this.getModulo().hashCode() );
         result = 37 * result + ( getSubModulo() == null ? 0 : this.getSubModulo().hashCode() );
         return result;
   }   


}


