package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arcgms generated by hbm2java
 */
@Entity
@Table(name="ARCGMS"
    ,schema="DESA46"
)
public class Arcgms  implements java.io.Serializable {


     private ArcgmsId id;
     private String descri;
     private String tipo;
     private String clase;
     private String indMov;
     private String indPresup;
     private String presupCambio;
     private BigDecimal debitos;
     private BigDecimal creditos;
     private BigDecimal saldoPerAnt;
     private BigDecimal saldoMesAnt;
     private String descri1;
     private String moneda;
     private String activa;
     private Date FInactiva;
     private BigDecimal saldoPerAntDol;
     private BigDecimal saldoMesAntDol;
     private BigDecimal debitosDol;
     private BigDecimal creditosDol;
     private String permisoCon;
     private String permisoChe;
     private String permisoCxp;
     private String permisoPla;
     private String permisoAfijo;
     private String permisoInv;
     private String permisoAprov;
     private String permisoFact;
     private String permisoCxc;
     private String permisoCch;
     private String permisoTpmInv;
     private String permisoTpmCom;
     private String permisoTpmC2p;
     private String monetaria;
     private String ajustable;
     private String aceptaCc;
     private BigDecimal creditosPend;
     private BigDecimal debitosPend;
     private String usadoEn;
     private String compartido;
     private String tcambioConversion;
     private String padre;
     private Boolean nivel;
     private String indTercero;
     private String ctaAjusteInflacion;
     private String ctaCorreccion;
     private String codAjuste;
     private String descriLarga;
     private String naturaleza;
     private String permisoImp;
     private BigDecimal debitosRes;
     private BigDecimal creditosRes;
     private BigDecimal saldoPerAntRes;
     private BigDecimal saldoMesAntRes;

    public Arcgms() {
    }

	
    public Arcgms(ArcgmsId id) {
        this.id = id;
    }
    public Arcgms(ArcgmsId id, String descri, String tipo, String clase, String indMov, String indPresup, String presupCambio, BigDecimal debitos, BigDecimal creditos, BigDecimal saldoPerAnt, BigDecimal saldoMesAnt, String descri1, String moneda, String activa, Date FInactiva, BigDecimal saldoPerAntDol, BigDecimal saldoMesAntDol, BigDecimal debitosDol, BigDecimal creditosDol, String permisoCon, String permisoChe, String permisoCxp, String permisoPla, String permisoAfijo, String permisoInv, String permisoAprov, String permisoFact, String permisoCxc, String permisoCch, String permisoTpmInv, String permisoTpmCom, String permisoTpmC2p, String monetaria, String ajustable, String aceptaCc, BigDecimal creditosPend, BigDecimal debitosPend, String usadoEn, String compartido, String tcambioConversion, String padre, Boolean nivel, String indTercero, String ctaAjusteInflacion, String ctaCorreccion, String codAjuste, String descriLarga, String naturaleza, String permisoImp, BigDecimal debitosRes, BigDecimal creditosRes, BigDecimal saldoPerAntRes, BigDecimal saldoMesAntRes) {
       this.id = id;
       this.descri = descri;
       this.tipo = tipo;
       this.clase = clase;
       this.indMov = indMov;
       this.indPresup = indPresup;
       this.presupCambio = presupCambio;
       this.debitos = debitos;
       this.creditos = creditos;
       this.saldoPerAnt = saldoPerAnt;
       this.saldoMesAnt = saldoMesAnt;
       this.descri1 = descri1;
       this.moneda = moneda;
       this.activa = activa;
       this.FInactiva = FInactiva;
       this.saldoPerAntDol = saldoPerAntDol;
       this.saldoMesAntDol = saldoMesAntDol;
       this.debitosDol = debitosDol;
       this.creditosDol = creditosDol;
       this.permisoCon = permisoCon;
       this.permisoChe = permisoChe;
       this.permisoCxp = permisoCxp;
       this.permisoPla = permisoPla;
       this.permisoAfijo = permisoAfijo;
       this.permisoInv = permisoInv;
       this.permisoAprov = permisoAprov;
       this.permisoFact = permisoFact;
       this.permisoCxc = permisoCxc;
       this.permisoCch = permisoCch;
       this.permisoTpmInv = permisoTpmInv;
       this.permisoTpmCom = permisoTpmCom;
       this.permisoTpmC2p = permisoTpmC2p;
       this.monetaria = monetaria;
       this.ajustable = ajustable;
       this.aceptaCc = aceptaCc;
       this.creditosPend = creditosPend;
       this.debitosPend = debitosPend;
       this.usadoEn = usadoEn;
       this.compartido = compartido;
       this.tcambioConversion = tcambioConversion;
       this.padre = padre;
       this.nivel = nivel;
       this.indTercero = indTercero;
       this.ctaAjusteInflacion = ctaAjusteInflacion;
       this.ctaCorreccion = ctaCorreccion;
       this.codAjuste = codAjuste;
       this.descriLarga = descriLarga;
       this.naturaleza = naturaleza;
       this.permisoImp = permisoImp;
       this.debitosRes = debitosRes;
       this.creditosRes = creditosRes;
       this.saldoPerAntRes = saldoPerAntRes;
       this.saldoMesAntRes = saldoMesAntRes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="cuenta", column=@Column(name="CUENTA", nullable=false, length=15) ), 
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ) } )
    public ArcgmsId getId() {
        return this.id;
    }
    
    public void setId(ArcgmsId id) {
        this.id = id;
    }

    
    @Column(name="DESCRI", length=35)
    public String getDescri() {
        return this.descri;
    }
    
    public void setDescri(String descri) {
        this.descri = descri;
    }

    
    @Column(name="TIPO", length=2)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="CLASE", length=1)
    public String getClase() {
        return this.clase;
    }
    
    public void setClase(String clase) {
        this.clase = clase;
    }

    
    @Column(name="IND_MOV", length=1)
    public String getIndMov() {
        return this.indMov;
    }
    
    public void setIndMov(String indMov) {
        this.indMov = indMov;
    }

    
    @Column(name="IND_PRESUP", length=1)
    public String getIndPresup() {
        return this.indPresup;
    }
    
    public void setIndPresup(String indPresup) {
        this.indPresup = indPresup;
    }

    
    @Column(name="PRESUP_CAMBIO", length=1)
    public String getPresupCambio() {
        return this.presupCambio;
    }
    
    public void setPresupCambio(String presupCambio) {
        this.presupCambio = presupCambio;
    }

    
    @Column(name="DEBITOS", precision=17)
    public BigDecimal getDebitos() {
        return this.debitos;
    }
    
    public void setDebitos(BigDecimal debitos) {
        this.debitos = debitos;
    }

    
    @Column(name="CREDITOS", precision=17)
    public BigDecimal getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(BigDecimal creditos) {
        this.creditos = creditos;
    }

    
    @Column(name="SALDO_PER_ANT", precision=17)
    public BigDecimal getSaldoPerAnt() {
        return this.saldoPerAnt;
    }
    
    public void setSaldoPerAnt(BigDecimal saldoPerAnt) {
        this.saldoPerAnt = saldoPerAnt;
    }

    
    @Column(name="SALDO_MES_ANT", precision=17)
    public BigDecimal getSaldoMesAnt() {
        return this.saldoMesAnt;
    }
    
    public void setSaldoMesAnt(BigDecimal saldoMesAnt) {
        this.saldoMesAnt = saldoMesAnt;
    }

    
    @Column(name="DESCRI_1", length=800)
    public String getDescri1() {
        return this.descri1;
    }
    
    public void setDescri1(String descri1) {
        this.descri1 = descri1;
    }

    
    @Column(name="MONEDA", length=1)
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }

    
    @Column(name="ACTIVA", length=1)
    public String getActiva() {
        return this.activa;
    }
    
    public void setActiva(String activa) {
        this.activa = activa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="F_INACTIVA", length=7)
    public Date getFInactiva() {
        return this.FInactiva;
    }
    
    public void setFInactiva(Date FInactiva) {
        this.FInactiva = FInactiva;
    }

    
    @Column(name="SALDO_PER_ANT_DOL", precision=17)
    public BigDecimal getSaldoPerAntDol() {
        return this.saldoPerAntDol;
    }
    
    public void setSaldoPerAntDol(BigDecimal saldoPerAntDol) {
        this.saldoPerAntDol = saldoPerAntDol;
    }

    
    @Column(name="SALDO_MES_ANT_DOL", precision=17)
    public BigDecimal getSaldoMesAntDol() {
        return this.saldoMesAntDol;
    }
    
    public void setSaldoMesAntDol(BigDecimal saldoMesAntDol) {
        this.saldoMesAntDol = saldoMesAntDol;
    }

    
    @Column(name="DEBITOS_DOL", precision=17)
    public BigDecimal getDebitosDol() {
        return this.debitosDol;
    }
    
    public void setDebitosDol(BigDecimal debitosDol) {
        this.debitosDol = debitosDol;
    }

    
    @Column(name="CREDITOS_DOL", precision=17)
    public BigDecimal getCreditosDol() {
        return this.creditosDol;
    }
    
    public void setCreditosDol(BigDecimal creditosDol) {
        this.creditosDol = creditosDol;
    }

    
    @Column(name="PERMISO_CON", length=1)
    public String getPermisoCon() {
        return this.permisoCon;
    }
    
    public void setPermisoCon(String permisoCon) {
        this.permisoCon = permisoCon;
    }

    
    @Column(name="PERMISO_CHE", length=1)
    public String getPermisoChe() {
        return this.permisoChe;
    }
    
    public void setPermisoChe(String permisoChe) {
        this.permisoChe = permisoChe;
    }

    
    @Column(name="PERMISO_CXP", length=1)
    public String getPermisoCxp() {
        return this.permisoCxp;
    }
    
    public void setPermisoCxp(String permisoCxp) {
        this.permisoCxp = permisoCxp;
    }

    
    @Column(name="PERMISO_PLA", length=1)
    public String getPermisoPla() {
        return this.permisoPla;
    }
    
    public void setPermisoPla(String permisoPla) {
        this.permisoPla = permisoPla;
    }

    
    @Column(name="PERMISO_AFIJO", length=1)
    public String getPermisoAfijo() {
        return this.permisoAfijo;
    }
    
    public void setPermisoAfijo(String permisoAfijo) {
        this.permisoAfijo = permisoAfijo;
    }

    
    @Column(name="PERMISO_INV", length=1)
    public String getPermisoInv() {
        return this.permisoInv;
    }
    
    public void setPermisoInv(String permisoInv) {
        this.permisoInv = permisoInv;
    }

    
    @Column(name="PERMISO_APROV", length=1)
    public String getPermisoAprov() {
        return this.permisoAprov;
    }
    
    public void setPermisoAprov(String permisoAprov) {
        this.permisoAprov = permisoAprov;
    }

    
    @Column(name="PERMISO_FACT", length=1)
    public String getPermisoFact() {
        return this.permisoFact;
    }
    
    public void setPermisoFact(String permisoFact) {
        this.permisoFact = permisoFact;
    }

    
    @Column(name="PERMISO_CXC", length=1)
    public String getPermisoCxc() {
        return this.permisoCxc;
    }
    
    public void setPermisoCxc(String permisoCxc) {
        this.permisoCxc = permisoCxc;
    }

    
    @Column(name="PERMISO_CCH", length=2)
    public String getPermisoCch() {
        return this.permisoCch;
    }
    
    public void setPermisoCch(String permisoCch) {
        this.permisoCch = permisoCch;
    }

    
    @Column(name="PERMISO_TPM_INV", length=1)
    public String getPermisoTpmInv() {
        return this.permisoTpmInv;
    }
    
    public void setPermisoTpmInv(String permisoTpmInv) {
        this.permisoTpmInv = permisoTpmInv;
    }

    
    @Column(name="PERMISO_TPM_COM", length=1)
    public String getPermisoTpmCom() {
        return this.permisoTpmCom;
    }
    
    public void setPermisoTpmCom(String permisoTpmCom) {
        this.permisoTpmCom = permisoTpmCom;
    }

    
    @Column(name="PERMISO_TPM_C2P", length=1)
    public String getPermisoTpmC2p() {
        return this.permisoTpmC2p;
    }
    
    public void setPermisoTpmC2p(String permisoTpmC2p) {
        this.permisoTpmC2p = permisoTpmC2p;
    }

    
    @Column(name="MONETARIA", length=1)
    public String getMonetaria() {
        return this.monetaria;
    }
    
    public void setMonetaria(String monetaria) {
        this.monetaria = monetaria;
    }

    
    @Column(name="AJUSTABLE", length=1)
    public String getAjustable() {
        return this.ajustable;
    }
    
    public void setAjustable(String ajustable) {
        this.ajustable = ajustable;
    }

    
    @Column(name="ACEPTA_CC", length=1)
    public String getAceptaCc() {
        return this.aceptaCc;
    }
    
    public void setAceptaCc(String aceptaCc) {
        this.aceptaCc = aceptaCc;
    }

    
    @Column(name="CREDITOS_PEND", precision=17)
    public BigDecimal getCreditosPend() {
        return this.creditosPend;
    }
    
    public void setCreditosPend(BigDecimal creditosPend) {
        this.creditosPend = creditosPend;
    }

    
    @Column(name="DEBITOS_PEND", precision=17)
    public BigDecimal getDebitosPend() {
        return this.debitosPend;
    }
    
    public void setDebitosPend(BigDecimal debitosPend) {
        this.debitosPend = debitosPend;
    }

    
    @Column(name="USADO_EN", length=2)
    public String getUsadoEn() {
        return this.usadoEn;
    }
    
    public void setUsadoEn(String usadoEn) {
        this.usadoEn = usadoEn;
    }

    
    @Column(name="COMPARTIDO", length=1)
    public String getCompartido() {
        return this.compartido;
    }
    
    public void setCompartido(String compartido) {
        this.compartido = compartido;
    }

    
    @Column(name="TCAMBIO_CONVERSION", length=1)
    public String getTcambioConversion() {
        return this.tcambioConversion;
    }
    
    public void setTcambioConversion(String tcambioConversion) {
        this.tcambioConversion = tcambioConversion;
    }

    
    @Column(name="PADRE", length=15)
    public String getPadre() {
        return this.padre;
    }
    
    public void setPadre(String padre) {
        this.padre = padre;
    }

    
    @Column(name="NIVEL", precision=1, scale=0)
    public Boolean getNivel() {
        return this.nivel;
    }
    
    public void setNivel(Boolean nivel) {
        this.nivel = nivel;
    }

    
    @Column(name="IND_TERCERO", length=1)
    public String getIndTercero() {
        return this.indTercero;
    }
    
    public void setIndTercero(String indTercero) {
        this.indTercero = indTercero;
    }

    
    @Column(name="CTA_AJUSTE_INFLACION", length=15)
    public String getCtaAjusteInflacion() {
        return this.ctaAjusteInflacion;
    }
    
    public void setCtaAjusteInflacion(String ctaAjusteInflacion) {
        this.ctaAjusteInflacion = ctaAjusteInflacion;
    }

    
    @Column(name="CTA_CORRECCION", length=15)
    public String getCtaCorreccion() {
        return this.ctaCorreccion;
    }
    
    public void setCtaCorreccion(String ctaCorreccion) {
        this.ctaCorreccion = ctaCorreccion;
    }

    
    @Column(name="COD_AJUSTE", length=5)
    public String getCodAjuste() {
        return this.codAjuste;
    }
    
    public void setCodAjuste(String codAjuste) {
        this.codAjuste = codAjuste;
    }

    
    @Column(name="DESCRI_LARGA", length=100)
    public String getDescriLarga() {
        return this.descriLarga;
    }
    
    public void setDescriLarga(String descriLarga) {
        this.descriLarga = descriLarga;
    }

    
    @Column(name="NATURALEZA", length=1)
    public String getNaturaleza() {
        return this.naturaleza;
    }
    
    public void setNaturaleza(String naturaleza) {
        this.naturaleza = naturaleza;
    }

    
    @Column(name="PERMISO_IMP", length=1)
    public String getPermisoImp() {
        return this.permisoImp;
    }
    
    public void setPermisoImp(String permisoImp) {
        this.permisoImp = permisoImp;
    }

    
    @Column(name="DEBITOS_RES", precision=30)
    public BigDecimal getDebitosRes() {
        return this.debitosRes;
    }
    
    public void setDebitosRes(BigDecimal debitosRes) {
        this.debitosRes = debitosRes;
    }

    
    @Column(name="CREDITOS_RES", precision=30)
    public BigDecimal getCreditosRes() {
        return this.creditosRes;
    }
    
    public void setCreditosRes(BigDecimal creditosRes) {
        this.creditosRes = creditosRes;
    }

    
    @Column(name="SALDO_PER_ANT_RES", precision=30)
    public BigDecimal getSaldoPerAntRes() {
        return this.saldoPerAntRes;
    }
    
    public void setSaldoPerAntRes(BigDecimal saldoPerAntRes) {
        this.saldoPerAntRes = saldoPerAntRes;
    }

    
    @Column(name="SALDO_MES_ANT_RES", precision=30)
    public BigDecimal getSaldoMesAntRes() {
        return this.saldoMesAntRes;
    }
    
    public void setSaldoMesAntRes(BigDecimal saldoMesAntRes) {
        this.saldoMesAntRes = saldoMesAntRes;
    }




}


