package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arcgmc generated by hbm2java
 */
@Entity
@Table(name="ARCGMC"
    ,schema="DESA46"
)
public class Arcgmc  implements java.io.Serializable {


     private String noCia;
     private String nombre;
     private Short anoProce;
     private Byte mesProce;
     private Byte mesCierre;
     private String aceptaTasasCamb;
     private BigDecimal bandaTasasCamb;
     private String monedaFunc;
     private String monRegCont;
     private String promedio;
     private String repre;
     private String direccion;
     private String aceptaTercero;
     private String codigoTercero;
     private String tipoIdTributario;
     private String idTributario;
     private String condicionTributaria;
     private String claseCambio;
     private String usaCtasAux;
     private String ccCualquierNivel;
     private String formatoCta;
     private String ctaUnd;
     private String ctaPerdidas;
     private String ctaUndAjuste;
     private String ctaPerdidasAjuste;
     private String ctaAjusteNom;
     private String ctaAjusteDol;
     private String ctaUCHist;
     private String ctaPCHist;
     private String ctaUCCte;
     private String ctaPCCte;
     private String codDiarioDifcam;
     private Date FUDifcambio;
     private String noAsientoDifcam;
     private String ctaUd;
     private String ctaPd;
     private String firma1;
     private String firma2;
     private String formIngreso;
     private String formEgreso;
     private String formTraspaso;
     private String indicadorUtilidad;
     private String indicadorCierrep;
     private String indicadorDifCam;
     private String indicadorCcDistbs;
     private String cierreFiscal;
     private Date fechaLc;
     private Date fechaLv;
     private Date fechaLd;
     private Date tstamp;
     private String ciaConsolidada;
     private String nombreLargo;
     private String ccoUnd;
     private String ccoPerdidas;
     private String ccoUndAjuste;
     private String ccoPerdidasAjuste;
     private String ccoAjusteNom;
     private String ccoAjusteDol;
     private String ccoUCHist;
     private String ccoPCHist;
     private String ccoUCCte;
     private String ccoPCCte;
     private String ccoUd;
     private String ccoPd;
     private String dirDespacho;
     private String telefono;
     private String correoCompras;

    public Arcgmc() {
    }

	
    public Arcgmc(String noCia) {
        this.noCia = noCia;
    }
    public Arcgmc(String noCia, String nombre, Short anoProce, Byte mesProce, Byte mesCierre, String aceptaTasasCamb, BigDecimal bandaTasasCamb, String monedaFunc, String monRegCont, String promedio, String repre, String direccion, String aceptaTercero, String codigoTercero, String tipoIdTributario, String idTributario, String condicionTributaria, String claseCambio, String usaCtasAux, String ccCualquierNivel, String formatoCta, String ctaUnd, String ctaPerdidas, String ctaUndAjuste, String ctaPerdidasAjuste, String ctaAjusteNom, String ctaAjusteDol, String ctaUCHist, String ctaPCHist, String ctaUCCte, String ctaPCCte, String codDiarioDifcam, Date FUDifcambio, String noAsientoDifcam, String ctaUd, String ctaPd, String firma1, String firma2, String formIngreso, String formEgreso, String formTraspaso, String indicadorUtilidad, String indicadorCierrep, String indicadorDifCam, String indicadorCcDistbs, String cierreFiscal, Date fechaLc, Date fechaLv, Date fechaLd, Date tstamp, String ciaConsolidada, String nombreLargo, String ccoUnd, String ccoPerdidas, String ccoUndAjuste, String ccoPerdidasAjuste, String ccoAjusteNom, String ccoAjusteDol, String ccoUCHist, String ccoPCHist, String ccoUCCte, String ccoPCCte, String ccoUd, String ccoPd, String dirDespacho, String telefono, String correoCompras) {
       this.noCia = noCia;
       this.nombre = nombre;
       this.anoProce = anoProce;
       this.mesProce = mesProce;
       this.mesCierre = mesCierre;
       this.aceptaTasasCamb = aceptaTasasCamb;
       this.bandaTasasCamb = bandaTasasCamb;
       this.monedaFunc = monedaFunc;
       this.monRegCont = monRegCont;
       this.promedio = promedio;
       this.repre = repre;
       this.direccion = direccion;
       this.aceptaTercero = aceptaTercero;
       this.codigoTercero = codigoTercero;
       this.tipoIdTributario = tipoIdTributario;
       this.idTributario = idTributario;
       this.condicionTributaria = condicionTributaria;
       this.claseCambio = claseCambio;
       this.usaCtasAux = usaCtasAux;
       this.ccCualquierNivel = ccCualquierNivel;
       this.formatoCta = formatoCta;
       this.ctaUnd = ctaUnd;
       this.ctaPerdidas = ctaPerdidas;
       this.ctaUndAjuste = ctaUndAjuste;
       this.ctaPerdidasAjuste = ctaPerdidasAjuste;
       this.ctaAjusteNom = ctaAjusteNom;
       this.ctaAjusteDol = ctaAjusteDol;
       this.ctaUCHist = ctaUCHist;
       this.ctaPCHist = ctaPCHist;
       this.ctaUCCte = ctaUCCte;
       this.ctaPCCte = ctaPCCte;
       this.codDiarioDifcam = codDiarioDifcam;
       this.FUDifcambio = FUDifcambio;
       this.noAsientoDifcam = noAsientoDifcam;
       this.ctaUd = ctaUd;
       this.ctaPd = ctaPd;
       this.firma1 = firma1;
       this.firma2 = firma2;
       this.formIngreso = formIngreso;
       this.formEgreso = formEgreso;
       this.formTraspaso = formTraspaso;
       this.indicadorUtilidad = indicadorUtilidad;
       this.indicadorCierrep = indicadorCierrep;
       this.indicadorDifCam = indicadorDifCam;
       this.indicadorCcDistbs = indicadorCcDistbs;
       this.cierreFiscal = cierreFiscal;
       this.fechaLc = fechaLc;
       this.fechaLv = fechaLv;
       this.fechaLd = fechaLd;
       this.tstamp = tstamp;
       this.ciaConsolidada = ciaConsolidada;
       this.nombreLargo = nombreLargo;
       this.ccoUnd = ccoUnd;
       this.ccoPerdidas = ccoPerdidas;
       this.ccoUndAjuste = ccoUndAjuste;
       this.ccoPerdidasAjuste = ccoPerdidasAjuste;
       this.ccoAjusteNom = ccoAjusteNom;
       this.ccoAjusteDol = ccoAjusteDol;
       this.ccoUCHist = ccoUCHist;
       this.ccoPCHist = ccoPCHist;
       this.ccoUCCte = ccoUCCte;
       this.ccoPCCte = ccoPCCte;
       this.ccoUd = ccoUd;
       this.ccoPd = ccoPd;
       this.dirDespacho = dirDespacho;
       this.telefono = telefono;
       this.correoCompras = correoCompras;
    }
   
     @Id 

    
    @Column(name="NO_CIA", unique=true, nullable=false, length=2)
    public String getNoCia() {
        return this.noCia;
    }
    
    public void setNoCia(String noCia) {
        this.noCia = noCia;
    }

    
    @Column(name="NOMBRE", length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="ANO_PROCE", precision=4, scale=0)
    public Short getAnoProce() {
        return this.anoProce;
    }
    
    public void setAnoProce(Short anoProce) {
        this.anoProce = anoProce;
    }

    
    @Column(name="MES_PROCE", precision=2, scale=0)
    public Byte getMesProce() {
        return this.mesProce;
    }
    
    public void setMesProce(Byte mesProce) {
        this.mesProce = mesProce;
    }

    
    @Column(name="MES_CIERRE", precision=2, scale=0)
    public Byte getMesCierre() {
        return this.mesCierre;
    }
    
    public void setMesCierre(Byte mesCierre) {
        this.mesCierre = mesCierre;
    }

    
    @Column(name="ACEPTA_TASAS_CAMB", length=1)
    public String getAceptaTasasCamb() {
        return this.aceptaTasasCamb;
    }
    
    public void setAceptaTasasCamb(String aceptaTasasCamb) {
        this.aceptaTasasCamb = aceptaTasasCamb;
    }

    
    @Column(name="BANDA_TASAS_CAMB", precision=9)
    public BigDecimal getBandaTasasCamb() {
        return this.bandaTasasCamb;
    }
    
    public void setBandaTasasCamb(BigDecimal bandaTasasCamb) {
        this.bandaTasasCamb = bandaTasasCamb;
    }

    
    @Column(name="MONEDA_FUNC", length=1)
    public String getMonedaFunc() {
        return this.monedaFunc;
    }
    
    public void setMonedaFunc(String monedaFunc) {
        this.monedaFunc = monedaFunc;
    }

    
    @Column(name="MON_REG_CONT", length=3)
    public String getMonRegCont() {
        return this.monRegCont;
    }
    
    public void setMonRegCont(String monRegCont) {
        this.monRegCont = monRegCont;
    }

    
    @Column(name="PROMEDIO", length=1)
    public String getPromedio() {
        return this.promedio;
    }
    
    public void setPromedio(String promedio) {
        this.promedio = promedio;
    }

    
    @Column(name="REPRE", length=30)
    public String getRepre() {
        return this.repre;
    }
    
    public void setRepre(String repre) {
        this.repre = repre;
    }

    
    @Column(name="DIRECCION", length=200)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="ACEPTA_TERCERO", length=1)
    public String getAceptaTercero() {
        return this.aceptaTercero;
    }
    
    public void setAceptaTercero(String aceptaTercero) {
        this.aceptaTercero = aceptaTercero;
    }

    
    @Column(name="CODIGO_TERCERO", length=18)
    public String getCodigoTercero() {
        return this.codigoTercero;
    }
    
    public void setCodigoTercero(String codigoTercero) {
        this.codigoTercero = codigoTercero;
    }

    
    @Column(name="TIPO_ID_TRIBUTARIO", length=1)
    public String getTipoIdTributario() {
        return this.tipoIdTributario;
    }
    
    public void setTipoIdTributario(String tipoIdTributario) {
        this.tipoIdTributario = tipoIdTributario;
    }

    
    @Column(name="ID_TRIBUTARIO", length=15)
    public String getIdTributario() {
        return this.idTributario;
    }
    
    public void setIdTributario(String idTributario) {
        this.idTributario = idTributario;
    }

    
    @Column(name="CONDICION_TRIBUTARIA", length=3)
    public String getCondicionTributaria() {
        return this.condicionTributaria;
    }
    
    public void setCondicionTributaria(String condicionTributaria) {
        this.condicionTributaria = condicionTributaria;
    }

    
    @Column(name="CLASE_CAMBIO", length=3)
    public String getClaseCambio() {
        return this.claseCambio;
    }
    
    public void setClaseCambio(String claseCambio) {
        this.claseCambio = claseCambio;
    }

    
    @Column(name="USA_CTAS_AUX", length=1)
    public String getUsaCtasAux() {
        return this.usaCtasAux;
    }
    
    public void setUsaCtasAux(String usaCtasAux) {
        this.usaCtasAux = usaCtasAux;
    }

    
    @Column(name="CC_CUALQUIER_NIVEL", length=1)
    public String getCcCualquierNivel() {
        return this.ccCualquierNivel;
    }
    
    public void setCcCualquierNivel(String ccCualquierNivel) {
        this.ccCualquierNivel = ccCualquierNivel;
    }

    
    @Column(name="FORMATO_CTA", length=30)
    public String getFormatoCta() {
        return this.formatoCta;
    }
    
    public void setFormatoCta(String formatoCta) {
        this.formatoCta = formatoCta;
    }

    
    @Column(name="CTA_UND", length=15)
    public String getCtaUnd() {
        return this.ctaUnd;
    }
    
    public void setCtaUnd(String ctaUnd) {
        this.ctaUnd = ctaUnd;
    }

    
    @Column(name="CTA_PERDIDAS", length=15)
    public String getCtaPerdidas() {
        return this.ctaPerdidas;
    }
    
    public void setCtaPerdidas(String ctaPerdidas) {
        this.ctaPerdidas = ctaPerdidas;
    }

    
    @Column(name="CTA_UND_AJUSTE", length=15)
    public String getCtaUndAjuste() {
        return this.ctaUndAjuste;
    }
    
    public void setCtaUndAjuste(String ctaUndAjuste) {
        this.ctaUndAjuste = ctaUndAjuste;
    }

    
    @Column(name="CTA_PERDIDAS_AJUSTE", length=15)
    public String getCtaPerdidasAjuste() {
        return this.ctaPerdidasAjuste;
    }
    
    public void setCtaPerdidasAjuste(String ctaPerdidasAjuste) {
        this.ctaPerdidasAjuste = ctaPerdidasAjuste;
    }

    
    @Column(name="CTA_AJUSTE_NOM", length=15)
    public String getCtaAjusteNom() {
        return this.ctaAjusteNom;
    }
    
    public void setCtaAjusteNom(String ctaAjusteNom) {
        this.ctaAjusteNom = ctaAjusteNom;
    }

    
    @Column(name="CTA_AJUSTE_DOL", length=15)
    public String getCtaAjusteDol() {
        return this.ctaAjusteDol;
    }
    
    public void setCtaAjusteDol(String ctaAjusteDol) {
        this.ctaAjusteDol = ctaAjusteDol;
    }

    
    @Column(name="CTA_U_C_HIST", length=15)
    public String getCtaUCHist() {
        return this.ctaUCHist;
    }
    
    public void setCtaUCHist(String ctaUCHist) {
        this.ctaUCHist = ctaUCHist;
    }

    
    @Column(name="CTA_P_C_HIST", length=15)
    public String getCtaPCHist() {
        return this.ctaPCHist;
    }
    
    public void setCtaPCHist(String ctaPCHist) {
        this.ctaPCHist = ctaPCHist;
    }

    
    @Column(name="CTA_U_C_CTE", length=15)
    public String getCtaUCCte() {
        return this.ctaUCCte;
    }
    
    public void setCtaUCCte(String ctaUCCte) {
        this.ctaUCCte = ctaUCCte;
    }

    
    @Column(name="CTA_P_C_CTE", length=15)
    public String getCtaPCCte() {
        return this.ctaPCCte;
    }
    
    public void setCtaPCCte(String ctaPCCte) {
        this.ctaPCCte = ctaPCCte;
    }

    
    @Column(name="COD_DIARIO_DIFCAM", length=5)
    public String getCodDiarioDifcam() {
        return this.codDiarioDifcam;
    }
    
    public void setCodDiarioDifcam(String codDiarioDifcam) {
        this.codDiarioDifcam = codDiarioDifcam;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="F_U_DIFCAMBIO", length=7)
    public Date getFUDifcambio() {
        return this.FUDifcambio;
    }
    
    public void setFUDifcambio(Date FUDifcambio) {
        this.FUDifcambio = FUDifcambio;
    }

    
    @Column(name="NO_ASIENTO_DIFCAM", length=12)
    public String getNoAsientoDifcam() {
        return this.noAsientoDifcam;
    }
    
    public void setNoAsientoDifcam(String noAsientoDifcam) {
        this.noAsientoDifcam = noAsientoDifcam;
    }

    
    @Column(name="CTA_UD", length=15)
    public String getCtaUd() {
        return this.ctaUd;
    }
    
    public void setCtaUd(String ctaUd) {
        this.ctaUd = ctaUd;
    }

    
    @Column(name="CTA_PD", length=15)
    public String getCtaPd() {
        return this.ctaPd;
    }
    
    public void setCtaPd(String ctaPd) {
        this.ctaPd = ctaPd;
    }

    
    @Column(name="FIRMA_1", length=15)
    public String getFirma1() {
        return this.firma1;
    }
    
    public void setFirma1(String firma1) {
        this.firma1 = firma1;
    }

    
    @Column(name="FIRMA_2", length=15)
    public String getFirma2() {
        return this.firma2;
    }
    
    public void setFirma2(String firma2) {
        this.firma2 = firma2;
    }

    
    @Column(name="FORM_INGRESO", length=10)
    public String getFormIngreso() {
        return this.formIngreso;
    }
    
    public void setFormIngreso(String formIngreso) {
        this.formIngreso = formIngreso;
    }

    
    @Column(name="FORM_EGRESO", length=10)
    public String getFormEgreso() {
        return this.formEgreso;
    }
    
    public void setFormEgreso(String formEgreso) {
        this.formEgreso = formEgreso;
    }

    
    @Column(name="FORM_TRASPASO", length=10)
    public String getFormTraspaso() {
        return this.formTraspaso;
    }
    
    public void setFormTraspaso(String formTraspaso) {
        this.formTraspaso = formTraspaso;
    }

    
    @Column(name="INDICADOR_UTILIDAD", length=1)
    public String getIndicadorUtilidad() {
        return this.indicadorUtilidad;
    }
    
    public void setIndicadorUtilidad(String indicadorUtilidad) {
        this.indicadorUtilidad = indicadorUtilidad;
    }

    
    @Column(name="INDICADOR_CIERREP", length=1)
    public String getIndicadorCierrep() {
        return this.indicadorCierrep;
    }
    
    public void setIndicadorCierrep(String indicadorCierrep) {
        this.indicadorCierrep = indicadorCierrep;
    }

    
    @Column(name="INDICADOR_DIF_CAM", length=1)
    public String getIndicadorDifCam() {
        return this.indicadorDifCam;
    }
    
    public void setIndicadorDifCam(String indicadorDifCam) {
        this.indicadorDifCam = indicadorDifCam;
    }

    
    @Column(name="INDICADOR_CC_DISTBS", length=1)
    public String getIndicadorCcDistbs() {
        return this.indicadorCcDistbs;
    }
    
    public void setIndicadorCcDistbs(String indicadorCcDistbs) {
        this.indicadorCcDistbs = indicadorCcDistbs;
    }

    
    @Column(name="CIERRE_FISCAL", length=1)
    public String getCierreFiscal() {
        return this.cierreFiscal;
    }
    
    public void setCierreFiscal(String cierreFiscal) {
        this.cierreFiscal = cierreFiscal;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_LC", length=7)
    public Date getFechaLc() {
        return this.fechaLc;
    }
    
    public void setFechaLc(Date fechaLc) {
        this.fechaLc = fechaLc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_LV", length=7)
    public Date getFechaLv() {
        return this.fechaLv;
    }
    
    public void setFechaLv(Date fechaLv) {
        this.fechaLv = fechaLv;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_LD", length=7)
    public Date getFechaLd() {
        return this.fechaLd;
    }
    
    public void setFechaLd(Date fechaLd) {
        this.fechaLd = fechaLd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TSTAMP", length=7)
    public Date getTstamp() {
        return this.tstamp;
    }
    
    public void setTstamp(Date tstamp) {
        this.tstamp = tstamp;
    }

    
    @Column(name="CIA_CONSOLIDADA", length=1)
    public String getCiaConsolidada() {
        return this.ciaConsolidada;
    }
    
    public void setCiaConsolidada(String ciaConsolidada) {
        this.ciaConsolidada = ciaConsolidada;
    }

    
    @Column(name="NOMBRE_LARGO", length=300)
    public String getNombreLargo() {
        return this.nombreLargo;
    }
    
    public void setNombreLargo(String nombreLargo) {
        this.nombreLargo = nombreLargo;
    }

    
    @Column(name="CCO_UND", length=9)
    public String getCcoUnd() {
        return this.ccoUnd;
    }
    
    public void setCcoUnd(String ccoUnd) {
        this.ccoUnd = ccoUnd;
    }

    
    @Column(name="CCO_PERDIDAS", length=9)
    public String getCcoPerdidas() {
        return this.ccoPerdidas;
    }
    
    public void setCcoPerdidas(String ccoPerdidas) {
        this.ccoPerdidas = ccoPerdidas;
    }

    
    @Column(name="CCO_UND_AJUSTE", length=9)
    public String getCcoUndAjuste() {
        return this.ccoUndAjuste;
    }
    
    public void setCcoUndAjuste(String ccoUndAjuste) {
        this.ccoUndAjuste = ccoUndAjuste;
    }

    
    @Column(name="CCO_PERDIDAS_AJUSTE", length=9)
    public String getCcoPerdidasAjuste() {
        return this.ccoPerdidasAjuste;
    }
    
    public void setCcoPerdidasAjuste(String ccoPerdidasAjuste) {
        this.ccoPerdidasAjuste = ccoPerdidasAjuste;
    }

    
    @Column(name="CCO_AJUSTE_NOM", length=9)
    public String getCcoAjusteNom() {
        return this.ccoAjusteNom;
    }
    
    public void setCcoAjusteNom(String ccoAjusteNom) {
        this.ccoAjusteNom = ccoAjusteNom;
    }

    
    @Column(name="CCO_AJUSTE_DOL", length=9)
    public String getCcoAjusteDol() {
        return this.ccoAjusteDol;
    }
    
    public void setCcoAjusteDol(String ccoAjusteDol) {
        this.ccoAjusteDol = ccoAjusteDol;
    }

    
    @Column(name="CCO_U_C_HIST", length=9)
    public String getCcoUCHist() {
        return this.ccoUCHist;
    }
    
    public void setCcoUCHist(String ccoUCHist) {
        this.ccoUCHist = ccoUCHist;
    }

    
    @Column(name="CCO_P_C_HIST", length=9)
    public String getCcoPCHist() {
        return this.ccoPCHist;
    }
    
    public void setCcoPCHist(String ccoPCHist) {
        this.ccoPCHist = ccoPCHist;
    }

    
    @Column(name="CCO_U_C_CTE", length=9)
    public String getCcoUCCte() {
        return this.ccoUCCte;
    }
    
    public void setCcoUCCte(String ccoUCCte) {
        this.ccoUCCte = ccoUCCte;
    }

    
    @Column(name="CCO_P_C_CTE", length=9)
    public String getCcoPCCte() {
        return this.ccoPCCte;
    }
    
    public void setCcoPCCte(String ccoPCCte) {
        this.ccoPCCte = ccoPCCte;
    }

    
    @Column(name="CCO_UD", length=9)
    public String getCcoUd() {
        return this.ccoUd;
    }
    
    public void setCcoUd(String ccoUd) {
        this.ccoUd = ccoUd;
    }

    
    @Column(name="CCO_PD", length=9)
    public String getCcoPd() {
        return this.ccoPd;
    }
    
    public void setCcoPd(String ccoPd) {
        this.ccoPd = ccoPd;
    }

    
    @Column(name="DIR_DESPACHO", length=1000)
    public String getDirDespacho() {
        return this.dirDespacho;
    }
    
    public void setDirDespacho(String dirDespacho) {
        this.dirDespacho = dirDespacho;
    }

    
    @Column(name="TELEFONO", length=100)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="CORREO_COMPRAS", length=500)
    public String getCorreoCompras() {
        return this.correoCompras;
    }
    
    public void setCorreoCompras(String correoCompras) {
        this.correoCompras = correoCompras;
    }




}


