package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arcgied generated by hbm2java
 */
@Entity
@Table(name="ARCGIED"
    ,schema="DESA46"
)
public class Arcgied  implements java.io.Serializable {


     private ArcgiedId id;
     private BigDecimal valor;
     private String modificable;
     private String procesadoConta;
     private String procesadoActivos;

    public Arcgied() {
    }

	
    public Arcgied(ArcgiedId id) {
        this.id = id;
    }
    public Arcgied(ArcgiedId id, BigDecimal valor, String modificable, String procesadoConta, String procesadoActivos) {
       this.id = id;
       this.valor = valor;
       this.modificable = modificable;
       this.procesadoConta = procesadoConta;
       this.procesadoActivos = procesadoActivos;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="codigo", column=@Column(name="CODIGO", nullable=false, length=3) ), 
        @AttributeOverride(name="fecha", column=@Column(name="FECHA", nullable=false, length=7) ) } )
    public ArcgiedId getId() {
        return this.id;
    }
    
    public void setId(ArcgiedId id) {
        this.id = id;
    }

    
    @Column(name="VALOR", precision=17, scale=4)
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

    
    @Column(name="MODIFICABLE", length=1)
    public String getModificable() {
        return this.modificable;
    }
    
    public void setModificable(String modificable) {
        this.modificable = modificable;
    }

    
    @Column(name="PROCESADO_CONTA", length=1)
    public String getProcesadoConta() {
        return this.procesadoConta;
    }
    
    public void setProcesadoConta(String procesadoConta) {
        this.procesadoConta = procesadoConta;
    }

    
    @Column(name="PROCESADO_ACTIVOS", length=1)
    public String getProcesadoActivos() {
        return this.procesadoActivos;
    }
    
    public void setProcesadoActivos(String procesadoActivos) {
        this.procesadoActivos = procesadoActivos;
    }




}


