package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ArcgmsC generated by hbm2java
 */
@Entity
@Table(name="ARCGMS_C"
    ,schema="DESA46"
)
public class ArcgmsC  implements java.io.Serializable {


     private ArcgmsCId id;
     private String tipo;
     private String clase;
     private String monetaria;
     private String ajustable;
     private String moneda;
     private BigDecimal saldoPerAnt;
     private BigDecimal saldoMesAnt;
     private BigDecimal debitos;
     private BigDecimal creditos;
     private BigDecimal saldoPerAntDol;
     private BigDecimal saldoMesAntDol;
     private BigDecimal debitosDol;
     private BigDecimal creditosDol;
     private Boolean nivel;
     private BigDecimal debitosRes;
     private BigDecimal creditosRes;
     private BigDecimal saldoPerAntRes;
     private BigDecimal saldoMesAntRes;

    public ArcgmsC() {
    }

	
    public ArcgmsC(ArcgmsCId id) {
        this.id = id;
    }
    public ArcgmsC(ArcgmsCId id, String tipo, String clase, String monetaria, String ajustable, String moneda, BigDecimal saldoPerAnt, BigDecimal saldoMesAnt, BigDecimal debitos, BigDecimal creditos, BigDecimal saldoPerAntDol, BigDecimal saldoMesAntDol, BigDecimal debitosDol, BigDecimal creditosDol, Boolean nivel, BigDecimal debitosRes, BigDecimal creditosRes, BigDecimal saldoPerAntRes, BigDecimal saldoMesAntRes) {
       this.id = id;
       this.tipo = tipo;
       this.clase = clase;
       this.monetaria = monetaria;
       this.ajustable = ajustable;
       this.moneda = moneda;
       this.saldoPerAnt = saldoPerAnt;
       this.saldoMesAnt = saldoMesAnt;
       this.debitos = debitos;
       this.creditos = creditos;
       this.saldoPerAntDol = saldoPerAntDol;
       this.saldoMesAntDol = saldoMesAntDol;
       this.debitosDol = debitosDol;
       this.creditosDol = creditosDol;
       this.nivel = nivel;
       this.debitosRes = debitosRes;
       this.creditosRes = creditosRes;
       this.saldoPerAntRes = saldoPerAntRes;
       this.saldoMesAntRes = saldoMesAntRes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="cc1", column=@Column(name="CC_1", nullable=false, length=3) ), 
        @AttributeOverride(name="cc2", column=@Column(name="CC_2", nullable=false, length=3) ), 
        @AttributeOverride(name="cc3", column=@Column(name="CC_3", nullable=false, length=3) ), 
        @AttributeOverride(name="cuenta", column=@Column(name="CUENTA", nullable=false, length=15) ), 
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ) } )
    public ArcgmsCId getId() {
        return this.id;
    }
    
    public void setId(ArcgmsCId id) {
        this.id = id;
    }

    
    @Column(name="TIPO", length=2)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="CLASE", length=1)
    public String getClase() {
        return this.clase;
    }
    
    public void setClase(String clase) {
        this.clase = clase;
    }

    
    @Column(name="MONETARIA", length=1)
    public String getMonetaria() {
        return this.monetaria;
    }
    
    public void setMonetaria(String monetaria) {
        this.monetaria = monetaria;
    }

    
    @Column(name="AJUSTABLE", length=1)
    public String getAjustable() {
        return this.ajustable;
    }
    
    public void setAjustable(String ajustable) {
        this.ajustable = ajustable;
    }

    
    @Column(name="MONEDA", length=1)
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }

    
    @Column(name="SALDO_PER_ANT", precision=17)
    public BigDecimal getSaldoPerAnt() {
        return this.saldoPerAnt;
    }
    
    public void setSaldoPerAnt(BigDecimal saldoPerAnt) {
        this.saldoPerAnt = saldoPerAnt;
    }

    
    @Column(name="SALDO_MES_ANT", precision=17)
    public BigDecimal getSaldoMesAnt() {
        return this.saldoMesAnt;
    }
    
    public void setSaldoMesAnt(BigDecimal saldoMesAnt) {
        this.saldoMesAnt = saldoMesAnt;
    }

    
    @Column(name="DEBITOS", precision=17)
    public BigDecimal getDebitos() {
        return this.debitos;
    }
    
    public void setDebitos(BigDecimal debitos) {
        this.debitos = debitos;
    }

    
    @Column(name="CREDITOS", precision=17)
    public BigDecimal getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(BigDecimal creditos) {
        this.creditos = creditos;
    }

    
    @Column(name="SALDO_PER_ANT_DOL", precision=17)
    public BigDecimal getSaldoPerAntDol() {
        return this.saldoPerAntDol;
    }
    
    public void setSaldoPerAntDol(BigDecimal saldoPerAntDol) {
        this.saldoPerAntDol = saldoPerAntDol;
    }

    
    @Column(name="SALDO_MES_ANT_DOL", precision=17)
    public BigDecimal getSaldoMesAntDol() {
        return this.saldoMesAntDol;
    }
    
    public void setSaldoMesAntDol(BigDecimal saldoMesAntDol) {
        this.saldoMesAntDol = saldoMesAntDol;
    }

    
    @Column(name="DEBITOS_DOL", precision=17)
    public BigDecimal getDebitosDol() {
        return this.debitosDol;
    }
    
    public void setDebitosDol(BigDecimal debitosDol) {
        this.debitosDol = debitosDol;
    }

    
    @Column(name="CREDITOS_DOL", precision=17)
    public BigDecimal getCreditosDol() {
        return this.creditosDol;
    }
    
    public void setCreditosDol(BigDecimal creditosDol) {
        this.creditosDol = creditosDol;
    }

    
    @Column(name="NIVEL", precision=1, scale=0)
    public Boolean getNivel() {
        return this.nivel;
    }
    
    public void setNivel(Boolean nivel) {
        this.nivel = nivel;
    }

    
    @Column(name="DEBITOS_RES", precision=30)
    public BigDecimal getDebitosRes() {
        return this.debitosRes;
    }
    
    public void setDebitosRes(BigDecimal debitosRes) {
        this.debitosRes = debitosRes;
    }

    
    @Column(name="CREDITOS_RES", precision=30)
    public BigDecimal getCreditosRes() {
        return this.creditosRes;
    }
    
    public void setCreditosRes(BigDecimal creditosRes) {
        this.creditosRes = creditosRes;
    }

    
    @Column(name="SALDO_PER_ANT_RES", precision=30)
    public BigDecimal getSaldoPerAntRes() {
        return this.saldoPerAntRes;
    }
    
    public void setSaldoPerAntRes(BigDecimal saldoPerAntRes) {
        this.saldoPerAntRes = saldoPerAntRes;
    }

    
    @Column(name="SALDO_MES_ANT_RES", precision=30)
    public BigDecimal getSaldoMesAntRes() {
        return this.saldoMesAntRes;
    }
    
    public void setSaldoMesAntRes(BigDecimal saldoMesAntRes) {
        this.saldoMesAntRes = saldoMesAntRes;
    }




}


