package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArcglveAnu generated by hbm2java
 */
@Entity
@Table(name="ARCGLVE_ANU"
    ,schema="DESA46"
)
public class ArcglveAnu  implements java.io.Serializable {


     private ArcglveAnuId id;
     private Date fecha;
     private String descripcionAnu;
     private Short ano;
     private Byte mes;
     private Long nro;

    public ArcglveAnu() {
    }

	
    public ArcglveAnu(ArcglveAnuId id) {
        this.id = id;
    }
    public ArcglveAnu(ArcglveAnuId id, Date fecha, String descripcionAnu, Short ano, Byte mes, Long nro) {
       this.id = id;
       this.fecha = fecha;
       this.descripcionAnu = descripcionAnu;
       this.ano = ano;
       this.mes = mes;
       this.nro = nro;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noControl", column=@Column(name="NO_CONTROL", nullable=false, length=12) ) } )
    public ArcglveAnuId getId() {
        return this.id;
    }
    
    public void setId(ArcglveAnuId id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", length=7)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="DESCRIPCION_ANU", length=200)
    public String getDescripcionAnu() {
        return this.descripcionAnu;
    }
    
    public void setDescripcionAnu(String descripcionAnu) {
        this.descripcionAnu = descripcionAnu;
    }

    
    @Column(name="ANO", precision=4, scale=0)
    public Short getAno() {
        return this.ano;
    }
    
    public void setAno(Short ano) {
        this.ano = ano;
    }

    
    @Column(name="MES", precision=2, scale=0)
    public Byte getMes() {
        return this.mes;
    }
    
    public void setMes(Byte mes) {
        this.mes = mes;
    }

    
    @Column(name="NRO", precision=17, scale=0)
    public Long getNro() {
        return this.nro;
    }
    
    public void setNro(Long nro) {
        this.nro = nro;
    }




}


