package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArcgmmId generated by hbm2java
 */
@Embeddable
public class ArcgmmId  implements java.io.Serializable {


     private String cuenta;
     private String noAsiento;
     private short ano;
     private byte mes;
     private short noLinea;
     private String noCia;

    public ArcgmmId() {
    }

    public ArcgmmId(String cuenta, String noAsiento, short ano, byte mes, short noLinea, String noCia) {
       this.cuenta = cuenta;
       this.noAsiento = noAsiento;
       this.ano = ano;
       this.mes = mes;
       this.noLinea = noLinea;
       this.noCia = noCia;
    }
   


    @Column(name="CUENTA", nullable=false, length=15)
    public String getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }


    @Column(name="NO_ASIENTO", nullable=false, length=12)
    public String getNoAsiento() {
        return this.noAsiento;
    }
    
    public void setNoAsiento(String noAsiento) {
        this.noAsiento = noAsiento;
    }


    @Column(name="ANO", nullable=false, precision=4, scale=0)
    public short getAno() {
        return this.ano;
    }
    
    public void setAno(short ano) {
        this.ano = ano;
    }


    @Column(name="MES", nullable=false, precision=2, scale=0)
    public byte getMes() {
        return this.mes;
    }
    
    public void setMes(byte mes) {
        this.mes = mes;
    }


    @Column(name="NO_LINEA", nullable=false, precision=4, scale=0)
    public short getNoLinea() {
        return this.noLinea;
    }
    
    public void setNoLinea(short noLinea) {
        this.noLinea = noLinea;
    }


    @Column(name="NO_CIA", nullable=false, length=2)
    public String getNoCia() {
        return this.noCia;
    }
    
    public void setNoCia(String noCia) {
        this.noCia = noCia;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArcgmmId) ) return false;
		 ArcgmmId castOther = ( ArcgmmId ) other; 
         
		 return ( (this.getCuenta()==castOther.getCuenta()) || ( this.getCuenta()!=null && castOther.getCuenta()!=null && this.getCuenta().equals(castOther.getCuenta()) ) )
 && ( (this.getNoAsiento()==castOther.getNoAsiento()) || ( this.getNoAsiento()!=null && castOther.getNoAsiento()!=null && this.getNoAsiento().equals(castOther.getNoAsiento()) ) )
 && (this.getAno()==castOther.getAno())
 && (this.getMes()==castOther.getMes())
 && (this.getNoLinea()==castOther.getNoLinea())
 && ( (this.getNoCia()==castOther.getNoCia()) || ( this.getNoCia()!=null && castOther.getNoCia()!=null && this.getNoCia().equals(castOther.getNoCia()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCuenta() == null ? 0 : this.getCuenta().hashCode() );
         result = 37 * result + ( getNoAsiento() == null ? 0 : this.getNoAsiento().hashCode() );
         result = 37 * result + this.getAno();
         result = 37 * result + this.getMes();
         result = 37 * result + this.getNoLinea();
         result = 37 * result + ( getNoCia() == null ? 0 : this.getNoCia().hashCode() );
         return result;
   }   


}


