package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArcggrlId generated by hbm2java
 */
@Embeddable
public class ArcggrlId  implements java.io.Serializable {


     private short rep;
     private short linea;

    public ArcggrlId() {
    }

    public ArcggrlId(short rep, short linea) {
       this.rep = rep;
       this.linea = linea;
    }
   


    @Column(name="REP", nullable=false, precision=3, scale=0)
    public short getRep() {
        return this.rep;
    }
    
    public void setRep(short rep) {
        this.rep = rep;
    }


    @Column(name="LINEA", nullable=false, precision=4, scale=0)
    public short getLinea() {
        return this.linea;
    }
    
    public void setLinea(short linea) {
        this.linea = linea;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArcggrlId) ) return false;
		 ArcggrlId castOther = ( ArcggrlId ) other; 
         
		 return (this.getRep()==castOther.getRep())
 && (this.getLinea()==castOther.getLinea());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRep();
         result = 37 * result + this.getLinea();
         return result;
   }   


}


