package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArcgmbId generated by hbm2java
 */
@Embeddable
public class ArcgmbId  implements java.io.Serializable {


     private String noCia;
     private String codBalance;

    public ArcgmbId() {
    }

    public ArcgmbId(String noCia, String codBalance) {
       this.noCia = noCia;
       this.codBalance = codBalance;
    }
   


    @Column(name="NO_CIA", nullable=false, length=2)
    public String getNoCia() {
        return this.noCia;
    }
    
    public void setNoCia(String noCia) {
        this.noCia = noCia;
    }


    @Column(name="COD_BALANCE", nullable=false, length=2)
    public String getCodBalance() {
        return this.codBalance;
    }
    
    public void setCodBalance(String codBalance) {
        this.codBalance = codBalance;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArcgmbId) ) return false;
		 ArcgmbId castOther = ( ArcgmbId ) other; 
         
		 return ( (this.getNoCia()==castOther.getNoCia()) || ( this.getNoCia()!=null && castOther.getNoCia()!=null && this.getNoCia().equals(castOther.getNoCia()) ) )
 && ( (this.getCodBalance()==castOther.getCodBalance()) || ( this.getCodBalance()!=null && castOther.getCodBalance()!=null && this.getCodBalance().equals(castOther.getCodBalance()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNoCia() == null ? 0 : this.getNoCia().hashCode() );
         result = 37 * result + ( getCodBalance() == null ? 0 : this.getCodBalance().hashCode() );
         return result;
   }   


}


