package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arcgmb generated by hbm2java
 */
@Entity
@Table(name="ARCGMB"
    ,schema="DESA46"
)
public class Arcgmb  implements java.io.Serializable {


     private ArcgmbId id;
     private String descripcion;
     private String creadoPor;
     private Date fechaCreacion;

    public Arcgmb() {
    }

	
    public Arcgmb(ArcgmbId id) {
        this.id = id;
    }
    public Arcgmb(ArcgmbId id, String descripcion, String creadoPor, Date fechaCreacion) {
       this.id = id;
       this.descripcion = descripcion;
       this.creadoPor = creadoPor;
       this.fechaCreacion = fechaCreacion;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="codBalance", column=@Column(name="COD_BALANCE", nullable=false, length=2) ) } )
    public ArcgmbId getId() {
        return this.id;
    }
    
    public void setId(ArcgmbId id) {
        this.id = id;
    }

    
    @Column(name="DESCRIPCION", length=80)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="CREADO_POR", length=20)
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_CREACION", length=7)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }




}


