package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arcglve generated by hbm2java
 */
@Entity
@Table(name="ARCGLVE"
    ,schema="DESA46"
)
public class Arcglve  implements java.io.Serializable {


     private ArcglveId id;
     private String punto;
     private String noFisico;
     private String serieFisico;
     private Short ano;
     private Byte mes;
     private Date fecha;
     private String nombre;
     private BigDecimal valorExp;
     private BigDecimal valorGravado;
     private BigDecimal valorExento;
     private BigDecimal valorImp1;
     private BigDecimal valorImp2;
     private BigDecimal valorImp3;
     private BigDecimal valorImp4;
     private BigDecimal valorImp5;
     private BigDecimal valorImp6;
     private BigDecimal total;
     private String idTributario;
     private String codigoTercero;
     private BigDecimal valorExpRes;
     private BigDecimal valorGravadoRes;
     private BigDecimal valorExentoRes;
     private BigDecimal valorImp1Res;
     private BigDecimal valorImp2Res;
     private BigDecimal valorImp3Res;
     private BigDecimal valorImp4Res;
     private BigDecimal valorImp5Res;
     private BigDecimal valorImp6Res;
     private BigDecimal totalRes;

    public Arcglve() {
    }

	
    public Arcglve(ArcglveId id) {
        this.id = id;
    }
    public Arcglve(ArcglveId id, String punto, String noFisico, String serieFisico, Short ano, Byte mes, Date fecha, String nombre, BigDecimal valorExp, BigDecimal valorGravado, BigDecimal valorExento, BigDecimal valorImp1, BigDecimal valorImp2, BigDecimal valorImp3, BigDecimal valorImp4, BigDecimal valorImp5, BigDecimal valorImp6, BigDecimal total, String idTributario, String codigoTercero, BigDecimal valorExpRes, BigDecimal valorGravadoRes, BigDecimal valorExentoRes, BigDecimal valorImp1Res, BigDecimal valorImp2Res, BigDecimal valorImp3Res, BigDecimal valorImp4Res, BigDecimal valorImp5Res, BigDecimal valorImp6Res, BigDecimal totalRes) {
       this.id = id;
       this.punto = punto;
       this.noFisico = noFisico;
       this.serieFisico = serieFisico;
       this.ano = ano;
       this.mes = mes;
       this.fecha = fecha;
       this.nombre = nombre;
       this.valorExp = valorExp;
       this.valorGravado = valorGravado;
       this.valorExento = valorExento;
       this.valorImp1 = valorImp1;
       this.valorImp2 = valorImp2;
       this.valorImp3 = valorImp3;
       this.valorImp4 = valorImp4;
       this.valorImp5 = valorImp5;
       this.valorImp6 = valorImp6;
       this.total = total;
       this.idTributario = idTributario;
       this.codigoTercero = codigoTercero;
       this.valorExpRes = valorExpRes;
       this.valorGravadoRes = valorGravadoRes;
       this.valorExentoRes = valorExentoRes;
       this.valorImp1Res = valorImp1Res;
       this.valorImp2Res = valorImp2Res;
       this.valorImp3Res = valorImp3Res;
       this.valorImp4Res = valorImp4Res;
       this.valorImp5Res = valorImp5Res;
       this.valorImp6Res = valorImp6Res;
       this.totalRes = totalRes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="tipoDoc", column=@Column(name="TIPO_DOC", nullable=false, length=2) ), 
        @AttributeOverride(name="noDocu", column=@Column(name="NO_DOCU", nullable=false, length=12) ) } )
    public ArcglveId getId() {
        return this.id;
    }
    
    public void setId(ArcglveId id) {
        this.id = id;
    }

    
    @Column(name="PUNTO", length=2)
    public String getPunto() {
        return this.punto;
    }
    
    public void setPunto(String punto) {
        this.punto = punto;
    }

    
    @Column(name="NO_FISICO", length=12)
    public String getNoFisico() {
        return this.noFisico;
    }
    
    public void setNoFisico(String noFisico) {
        this.noFisico = noFisico;
    }

    
    @Column(name="SERIE_FISICO", length=15)
    public String getSerieFisico() {
        return this.serieFisico;
    }
    
    public void setSerieFisico(String serieFisico) {
        this.serieFisico = serieFisico;
    }

    
    @Column(name="ANO", precision=4, scale=0)
    public Short getAno() {
        return this.ano;
    }
    
    public void setAno(Short ano) {
        this.ano = ano;
    }

    
    @Column(name="MES", precision=2, scale=0)
    public Byte getMes() {
        return this.mes;
    }
    
    public void setMes(Byte mes) {
        this.mes = mes;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", length=7)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="NOMBRE", length=80)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="VALOR_EXP", precision=17)
    public BigDecimal getValorExp() {
        return this.valorExp;
    }
    
    public void setValorExp(BigDecimal valorExp) {
        this.valorExp = valorExp;
    }

    
    @Column(name="VALOR_GRAVADO", precision=17)
    public BigDecimal getValorGravado() {
        return this.valorGravado;
    }
    
    public void setValorGravado(BigDecimal valorGravado) {
        this.valorGravado = valorGravado;
    }

    
    @Column(name="VALOR_EXENTO", precision=17)
    public BigDecimal getValorExento() {
        return this.valorExento;
    }
    
    public void setValorExento(BigDecimal valorExento) {
        this.valorExento = valorExento;
    }

    
    @Column(name="VALOR_IMP1", precision=17)
    public BigDecimal getValorImp1() {
        return this.valorImp1;
    }
    
    public void setValorImp1(BigDecimal valorImp1) {
        this.valorImp1 = valorImp1;
    }

    
    @Column(name="VALOR_IMP2", precision=17)
    public BigDecimal getValorImp2() {
        return this.valorImp2;
    }
    
    public void setValorImp2(BigDecimal valorImp2) {
        this.valorImp2 = valorImp2;
    }

    
    @Column(name="VALOR_IMP3", precision=17)
    public BigDecimal getValorImp3() {
        return this.valorImp3;
    }
    
    public void setValorImp3(BigDecimal valorImp3) {
        this.valorImp3 = valorImp3;
    }

    
    @Column(name="VALOR_IMP4", precision=17)
    public BigDecimal getValorImp4() {
        return this.valorImp4;
    }
    
    public void setValorImp4(BigDecimal valorImp4) {
        this.valorImp4 = valorImp4;
    }

    
    @Column(name="VALOR_IMP5", precision=17)
    public BigDecimal getValorImp5() {
        return this.valorImp5;
    }
    
    public void setValorImp5(BigDecimal valorImp5) {
        this.valorImp5 = valorImp5;
    }

    
    @Column(name="VALOR_IMP6", precision=17)
    public BigDecimal getValorImp6() {
        return this.valorImp6;
    }
    
    public void setValorImp6(BigDecimal valorImp6) {
        this.valorImp6 = valorImp6;
    }

    
    @Column(name="TOTAL", precision=17)
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    
    @Column(name="ID_TRIBUTARIO", length=15)
    public String getIdTributario() {
        return this.idTributario;
    }
    
    public void setIdTributario(String idTributario) {
        this.idTributario = idTributario;
    }

    
    @Column(name="CODIGO_TERCERO", length=18)
    public String getCodigoTercero() {
        return this.codigoTercero;
    }
    
    public void setCodigoTercero(String codigoTercero) {
        this.codigoTercero = codigoTercero;
    }

    
    @Column(name="VALOR_EXP_RES", precision=30)
    public BigDecimal getValorExpRes() {
        return this.valorExpRes;
    }
    
    public void setValorExpRes(BigDecimal valorExpRes) {
        this.valorExpRes = valorExpRes;
    }

    
    @Column(name="VALOR_GRAVADO_RES", precision=30)
    public BigDecimal getValorGravadoRes() {
        return this.valorGravadoRes;
    }
    
    public void setValorGravadoRes(BigDecimal valorGravadoRes) {
        this.valorGravadoRes = valorGravadoRes;
    }

    
    @Column(name="VALOR_EXENTO_RES", precision=30)
    public BigDecimal getValorExentoRes() {
        return this.valorExentoRes;
    }
    
    public void setValorExentoRes(BigDecimal valorExentoRes) {
        this.valorExentoRes = valorExentoRes;
    }

    
    @Column(name="VALOR_IMP1_RES", precision=30)
    public BigDecimal getValorImp1Res() {
        return this.valorImp1Res;
    }
    
    public void setValorImp1Res(BigDecimal valorImp1Res) {
        this.valorImp1Res = valorImp1Res;
    }

    
    @Column(name="VALOR_IMP2_RES", precision=30)
    public BigDecimal getValorImp2Res() {
        return this.valorImp2Res;
    }
    
    public void setValorImp2Res(BigDecimal valorImp2Res) {
        this.valorImp2Res = valorImp2Res;
    }

    
    @Column(name="VALOR_IMP3_RES", precision=30)
    public BigDecimal getValorImp3Res() {
        return this.valorImp3Res;
    }
    
    public void setValorImp3Res(BigDecimal valorImp3Res) {
        this.valorImp3Res = valorImp3Res;
    }

    
    @Column(name="VALOR_IMP4_RES", precision=30)
    public BigDecimal getValorImp4Res() {
        return this.valorImp4Res;
    }
    
    public void setValorImp4Res(BigDecimal valorImp4Res) {
        this.valorImp4Res = valorImp4Res;
    }

    
    @Column(name="VALOR_IMP5_RES", precision=30)
    public BigDecimal getValorImp5Res() {
        return this.valorImp5Res;
    }
    
    public void setValorImp5Res(BigDecimal valorImp5Res) {
        this.valorImp5Res = valorImp5Res;
    }

    
    @Column(name="VALOR_IMP6_RES", precision=30)
    public BigDecimal getValorImp6Res() {
        return this.valorImp6Res;
    }
    
    public void setValorImp6Res(BigDecimal valorImp6Res) {
        this.valorImp6Res = valorImp6Res;
    }

    
    @Column(name="TOTAL_RES", precision=30)
    public BigDecimal getTotalRes() {
        return this.totalRes;
    }
    
    public void setTotalRes(BigDecimal totalRes) {
        this.totalRes = totalRes;
    }




}


