package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Arcgceco generated by hbm2java
 */
@Entity
@Table(name="ARCGCECO"
    ,schema="DESA46"
    , uniqueConstraints = @UniqueConstraint(columnNames={"NO_CIA", "CENTRO"}) 
)
public class Arcgceco  implements java.io.Serializable {


     private ArcgcecoId id;
     private String descripCc;
     private String encargadoCc;
     private String centro;
     private String ultimoNivel;

    public Arcgceco() {
    }

	
    public Arcgceco(ArcgcecoId id) {
        this.id = id;
    }
    public Arcgceco(ArcgcecoId id, String descripCc, String encargadoCc, String centro, String ultimoNivel) {
       this.id = id;
       this.descripCc = descripCc;
       this.encargadoCc = encargadoCc;
       this.centro = centro;
       this.ultimoNivel = ultimoNivel;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="cc1", column=@Column(name="CC_1", nullable=false, length=3) ), 
        @AttributeOverride(name="cc2", column=@Column(name="CC_2", nullable=false, length=3) ), 
        @AttributeOverride(name="cc3", column=@Column(name="CC_3", nullable=false, length=3) ) } )
    public ArcgcecoId getId() {
        return this.id;
    }
    
    public void setId(ArcgcecoId id) {
        this.id = id;
    }

    
    @Column(name="DESCRIP_CC", length=40)
    public String getDescripCc() {
        return this.descripCc;
    }
    
    public void setDescripCc(String descripCc) {
        this.descripCc = descripCc;
    }

    
    @Column(name="ENCARGADO_CC", length=30)
    public String getEncargadoCc() {
        return this.encargadoCc;
    }
    
    public void setEncargadoCc(String encargadoCc) {
        this.encargadoCc = encargadoCc;
    }

    
    @Column(name="CENTRO", length=9)
    public String getCentro() {
        return this.centro;
    }
    
    public void setCentro(String centro) {
        this.centro = centro;
    }

    
    @Column(name="ULTIMO_NIVEL", length=1)
    public String getUltimoNivel() {
        return this.ultimoNivel;
    }
    
    public void setUltimoNivel(String ultimoNivel) {
        this.ultimoNivel = ultimoNivel;
    }




}


