package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arcggi generated by hbm2java
 */
@Entity
@Table(name="ARCGGI"
    ,schema="DESA46"
)
public class Arcggi  implements java.io.Serializable {


     private ArcggiId id;
     private String descripcion;

    public Arcggi() {
    }

	
    public Arcggi(ArcggiId id) {
        this.id = id;
    }
    public Arcggi(ArcggiId id, String descripcion) {
       this.id = id;
       this.descripcion = descripcion;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="codigoGrupo", column=@Column(name="CODIGO_GRUPO", nullable=false, length=5) ) } )
    public ArcggiId getId() {
        return this.id;
    }
    
    public void setId(ArcggiId id) {
        this.id = id;
    }

    
    @Column(name="DESCRIPCION", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


