package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArckrdId generated by hbm2java
 */
@Embeddable
public class ArckrdId  implements java.io.Serializable {


     private String noCia;
     private int noSecuencia;
     private String noRefe;

    public ArckrdId() {
    }

    public ArckrdId(String noCia, int noSecuencia, String noRefe) {
       this.noCia = noCia;
       this.noSecuencia = noSecuencia;
       this.noRefe = noRefe;
    }
   


    @Column(name="NO_CIA", nullable=false, length=2)
    public String getNoCia() {
        return this.noCia;
    }
    
    public void setNoCia(String noCia) {
        this.noCia = noCia;
    }


    @Column(name="NO_SECUENCIA", nullable=false, precision=8, scale=0)
    public int getNoSecuencia() {
        return this.noSecuencia;
    }
    
    public void setNoSecuencia(int noSecuencia) {
        this.noSecuencia = noSecuencia;
    }


    @Column(name="NO_REFE", nullable=false, length=8)
    public String getNoRefe() {
        return this.noRefe;
    }
    
    public void setNoRefe(String noRefe) {
        this.noRefe = noRefe;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArckrdId) ) return false;
		 ArckrdId castOther = ( ArckrdId ) other; 
         
		 return ( (this.getNoCia()==castOther.getNoCia()) || ( this.getNoCia()!=null && castOther.getNoCia()!=null && this.getNoCia().equals(castOther.getNoCia()) ) )
 && (this.getNoSecuencia()==castOther.getNoSecuencia())
 && ( (this.getNoRefe()==castOther.getNoRefe()) || ( this.getNoRefe()!=null && castOther.getNoRefe()!=null && this.getNoRefe().equals(castOther.getNoRefe()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNoCia() == null ? 0 : this.getNoCia().hashCode() );
         result = 37 * result + this.getNoSecuencia();
         result = 37 * result + ( getNoRefe() == null ? 0 : this.getNoRefe().hashCode() );
         return result;
   }   


}


