package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arckcrh generated by hbm2java
 */
@Entity
@Table(name="ARCKCRH"
    ,schema="DESA46"
)
public class Arckcrh  implements java.io.Serializable {


     private ArckcrhId id;
     private BigDecimal actCia;
     private BigDecimal actBco;
     private BigDecimal cheTr;
     private BigDecimal depTr;
     private BigDecimal salBanco;
     private BigDecimal creTr;
     private BigDecimal debTr;
     private BigDecimal crePr;
     private BigDecimal debPr;
     private BigDecimal chePr;
     private BigDecimal depPr;
     private BigDecimal adeb;
     private BigDecimal acre;
     private BigDecimal dife;
     private BigDecimal salCia;
     private BigDecimal actCiaRes;
     private BigDecimal actBcoRes;
     private BigDecimal cheTrRes;
     private BigDecimal depTrRes;
     private BigDecimal salBancoRes;
     private BigDecimal creTrRes;
     private BigDecimal debTrRes;
     private BigDecimal crePrRes;
     private BigDecimal debPrRes;
     private BigDecimal chePrRes;
     private BigDecimal depPrRes;
     private BigDecimal adebRes;
     private BigDecimal acreRes;
     private BigDecimal difeRes;
     private BigDecimal salCiaRes;

    public Arckcrh() {
    }

	
    public Arckcrh(ArckcrhId id) {
        this.id = id;
    }
    public Arckcrh(ArckcrhId id, BigDecimal actCia, BigDecimal actBco, BigDecimal cheTr, BigDecimal depTr, BigDecimal salBanco, BigDecimal creTr, BigDecimal debTr, BigDecimal crePr, BigDecimal debPr, BigDecimal chePr, BigDecimal depPr, BigDecimal adeb, BigDecimal acre, BigDecimal dife, BigDecimal salCia, BigDecimal actCiaRes, BigDecimal actBcoRes, BigDecimal cheTrRes, BigDecimal depTrRes, BigDecimal salBancoRes, BigDecimal creTrRes, BigDecimal debTrRes, BigDecimal crePrRes, BigDecimal debPrRes, BigDecimal chePrRes, BigDecimal depPrRes, BigDecimal adebRes, BigDecimal acreRes, BigDecimal difeRes, BigDecimal salCiaRes) {
       this.id = id;
       this.actCia = actCia;
       this.actBco = actBco;
       this.cheTr = cheTr;
       this.depTr = depTr;
       this.salBanco = salBanco;
       this.creTr = creTr;
       this.debTr = debTr;
       this.crePr = crePr;
       this.debPr = debPr;
       this.chePr = chePr;
       this.depPr = depPr;
       this.adeb = adeb;
       this.acre = acre;
       this.dife = dife;
       this.salCia = salCia;
       this.actCiaRes = actCiaRes;
       this.actBcoRes = actBcoRes;
       this.cheTrRes = cheTrRes;
       this.depTrRes = depTrRes;
       this.salBancoRes = salBancoRes;
       this.creTrRes = creTrRes;
       this.debTrRes = debTrRes;
       this.crePrRes = crePrRes;
       this.debPrRes = debPrRes;
       this.chePrRes = chePrRes;
       this.depPrRes = depPrRes;
       this.adebRes = adebRes;
       this.acreRes = acreRes;
       this.difeRes = difeRes;
       this.salCiaRes = salCiaRes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCta", column=@Column(name="NO_CTA", nullable=false, length=15) ), 
        @AttributeOverride(name="ano", column=@Column(name="ANO", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="mes", column=@Column(name="MES", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ) } )
    public ArckcrhId getId() {
        return this.id;
    }
    
    public void setId(ArckcrhId id) {
        this.id = id;
    }

    
    @Column(name="ACT_CIA", precision=17)
    public BigDecimal getActCia() {
        return this.actCia;
    }
    
    public void setActCia(BigDecimal actCia) {
        this.actCia = actCia;
    }

    
    @Column(name="ACT_BCO", precision=17)
    public BigDecimal getActBco() {
        return this.actBco;
    }
    
    public void setActBco(BigDecimal actBco) {
        this.actBco = actBco;
    }

    
    @Column(name="CHE_TR", precision=17)
    public BigDecimal getCheTr() {
        return this.cheTr;
    }
    
    public void setCheTr(BigDecimal cheTr) {
        this.cheTr = cheTr;
    }

    
    @Column(name="DEP_TR", precision=17)
    public BigDecimal getDepTr() {
        return this.depTr;
    }
    
    public void setDepTr(BigDecimal depTr) {
        this.depTr = depTr;
    }

    
    @Column(name="SAL_BANCO", precision=17)
    public BigDecimal getSalBanco() {
        return this.salBanco;
    }
    
    public void setSalBanco(BigDecimal salBanco) {
        this.salBanco = salBanco;
    }

    
    @Column(name="CRE_TR", precision=17)
    public BigDecimal getCreTr() {
        return this.creTr;
    }
    
    public void setCreTr(BigDecimal creTr) {
        this.creTr = creTr;
    }

    
    @Column(name="DEB_TR", precision=17)
    public BigDecimal getDebTr() {
        return this.debTr;
    }
    
    public void setDebTr(BigDecimal debTr) {
        this.debTr = debTr;
    }

    
    @Column(name="CRE_PR", precision=17)
    public BigDecimal getCrePr() {
        return this.crePr;
    }
    
    public void setCrePr(BigDecimal crePr) {
        this.crePr = crePr;
    }

    
    @Column(name="DEB_PR", precision=17)
    public BigDecimal getDebPr() {
        return this.debPr;
    }
    
    public void setDebPr(BigDecimal debPr) {
        this.debPr = debPr;
    }

    
    @Column(name="CHE_PR", precision=17)
    public BigDecimal getChePr() {
        return this.chePr;
    }
    
    public void setChePr(BigDecimal chePr) {
        this.chePr = chePr;
    }

    
    @Column(name="DEP_PR", precision=17)
    public BigDecimal getDepPr() {
        return this.depPr;
    }
    
    public void setDepPr(BigDecimal depPr) {
        this.depPr = depPr;
    }

    
    @Column(name="ADEB", precision=17)
    public BigDecimal getAdeb() {
        return this.adeb;
    }
    
    public void setAdeb(BigDecimal adeb) {
        this.adeb = adeb;
    }

    
    @Column(name="ACRE", precision=17)
    public BigDecimal getAcre() {
        return this.acre;
    }
    
    public void setAcre(BigDecimal acre) {
        this.acre = acre;
    }

    
    @Column(name="DIFE", precision=17)
    public BigDecimal getDife() {
        return this.dife;
    }
    
    public void setDife(BigDecimal dife) {
        this.dife = dife;
    }

    
    @Column(name="SAL_CIA", precision=17)
    public BigDecimal getSalCia() {
        return this.salCia;
    }
    
    public void setSalCia(BigDecimal salCia) {
        this.salCia = salCia;
    }

    
    @Column(name="ACT_CIA_RES", precision=30)
    public BigDecimal getActCiaRes() {
        return this.actCiaRes;
    }
    
    public void setActCiaRes(BigDecimal actCiaRes) {
        this.actCiaRes = actCiaRes;
    }

    
    @Column(name="ACT_BCO_RES", precision=30)
    public BigDecimal getActBcoRes() {
        return this.actBcoRes;
    }
    
    public void setActBcoRes(BigDecimal actBcoRes) {
        this.actBcoRes = actBcoRes;
    }

    
    @Column(name="CHE_TR_RES", precision=30)
    public BigDecimal getCheTrRes() {
        return this.cheTrRes;
    }
    
    public void setCheTrRes(BigDecimal cheTrRes) {
        this.cheTrRes = cheTrRes;
    }

    
    @Column(name="DEP_TR_RES", precision=30)
    public BigDecimal getDepTrRes() {
        return this.depTrRes;
    }
    
    public void setDepTrRes(BigDecimal depTrRes) {
        this.depTrRes = depTrRes;
    }

    
    @Column(name="SAL_BANCO_RES", precision=30)
    public BigDecimal getSalBancoRes() {
        return this.salBancoRes;
    }
    
    public void setSalBancoRes(BigDecimal salBancoRes) {
        this.salBancoRes = salBancoRes;
    }

    
    @Column(name="CRE_TR_RES", precision=30)
    public BigDecimal getCreTrRes() {
        return this.creTrRes;
    }
    
    public void setCreTrRes(BigDecimal creTrRes) {
        this.creTrRes = creTrRes;
    }

    
    @Column(name="DEB_TR_RES", precision=30)
    public BigDecimal getDebTrRes() {
        return this.debTrRes;
    }
    
    public void setDebTrRes(BigDecimal debTrRes) {
        this.debTrRes = debTrRes;
    }

    
    @Column(name="CRE_PR_RES", precision=30)
    public BigDecimal getCrePrRes() {
        return this.crePrRes;
    }
    
    public void setCrePrRes(BigDecimal crePrRes) {
        this.crePrRes = crePrRes;
    }

    
    @Column(name="DEB_PR_RES", precision=30)
    public BigDecimal getDebPrRes() {
        return this.debPrRes;
    }
    
    public void setDebPrRes(BigDecimal debPrRes) {
        this.debPrRes = debPrRes;
    }

    
    @Column(name="CHE_PR_RES", precision=30)
    public BigDecimal getChePrRes() {
        return this.chePrRes;
    }
    
    public void setChePrRes(BigDecimal chePrRes) {
        this.chePrRes = chePrRes;
    }

    
    @Column(name="DEP_PR_RES", precision=30)
    public BigDecimal getDepPrRes() {
        return this.depPrRes;
    }
    
    public void setDepPrRes(BigDecimal depPrRes) {
        this.depPrRes = depPrRes;
    }

    
    @Column(name="ADEB_RES", precision=30)
    public BigDecimal getAdebRes() {
        return this.adebRes;
    }
    
    public void setAdebRes(BigDecimal adebRes) {
        this.adebRes = adebRes;
    }

    
    @Column(name="ACRE_RES", precision=30)
    public BigDecimal getAcreRes() {
        return this.acreRes;
    }
    
    public void setAcreRes(BigDecimal acreRes) {
        this.acreRes = acreRes;
    }

    
    @Column(name="DIFE_RES", precision=30)
    public BigDecimal getDifeRes() {
        return this.difeRes;
    }
    
    public void setDifeRes(BigDecimal difeRes) {
        this.difeRes = difeRes;
    }

    
    @Column(name="SAL_CIA_RES", precision=30)
    public BigDecimal getSalCiaRes() {
        return this.salCiaRes;
    }
    
    public void setSalCiaRes(BigDecimal salCiaRes) {
        this.salCiaRes = salCiaRes;
    }




}


