package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arckcaee generated by hbm2java
 */
@Entity
@Table(name="ARCKCAEE"
    ,schema="DESA46"
)
public class Arckcaee  implements java.io.Serializable {


     private ArckcaeeId id;
     private String noCta;
     private String proce;
     private String tipoDoc;
     private Short ano;
     private Byte mes;
     private String tipoAjuste;

    public Arckcaee() {
    }

	
    public Arckcaee(ArckcaeeId id) {
        this.id = id;
    }
    public Arckcaee(ArckcaeeId id, String noCta, String proce, String tipoDoc, Short ano, Byte mes, String tipoAjuste) {
       this.id = id;
       this.noCta = noCta;
       this.proce = proce;
       this.tipoDoc = tipoDoc;
       this.ano = ano;
       this.mes = mes;
       this.tipoAjuste = tipoAjuste;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noDocu", column=@Column(name="NO_DOCU", nullable=false, precision=8, scale=0) ) } )
    public ArckcaeeId getId() {
        return this.id;
    }
    
    public void setId(ArckcaeeId id) {
        this.id = id;
    }

    
    @Column(name="NO_CTA", length=15)
    public String getNoCta() {
        return this.noCta;
    }
    
    public void setNoCta(String noCta) {
        this.noCta = noCta;
    }

    
    @Column(name="PROCE", length=1)
    public String getProce() {
        return this.proce;
    }
    
    public void setProce(String proce) {
        this.proce = proce;
    }

    
    @Column(name="TIPO_DOC", length=2)
    public String getTipoDoc() {
        return this.tipoDoc;
    }
    
    public void setTipoDoc(String tipoDoc) {
        this.tipoDoc = tipoDoc;
    }

    
    @Column(name="ANO", precision=4, scale=0)
    public Short getAno() {
        return this.ano;
    }
    
    public void setAno(Short ano) {
        this.ano = ano;
    }

    
    @Column(name="MES", precision=2, scale=0)
    public Byte getMes() {
        return this.mes;
    }
    
    public void setMes(Byte mes) {
        this.mes = mes;
    }

    
    @Column(name="TIPO_AJUSTE", length=2)
    public String getTipoAjuste() {
        return this.tipoAjuste;
    }
    
    public void setTipoAjuste(String tipoAjuste) {
        this.tipoAjuste = tipoAjuste;
    }




}


