package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arckhc generated by hbm2java
 */
@Entity
@Table(name="ARCKHC"
    ,schema="DESA46"
)
public class Arckhc  implements java.io.Serializable {


     private ArckhcId id;
     private BigDecimal cheMes;
     private BigDecimal cheAnulmesant;
     private BigDecimal depMes;
     private BigDecimal debMes;
     private BigDecimal creMes;
     private BigDecimal saldoFinC;
     private BigDecimal saldoFinB;
     private String saldoConciliado;
     private BigDecimal cheMesRes;
     private BigDecimal cheAnulmesantRes;
     private BigDecimal depMesRes;
     private BigDecimal debMesRes;
     private BigDecimal creMesRes;
     private BigDecimal saldoFinCRes;
     private BigDecimal saldoFinBRes;

    public Arckhc() {
    }

	
    public Arckhc(ArckhcId id) {
        this.id = id;
    }
    public Arckhc(ArckhcId id, BigDecimal cheMes, BigDecimal cheAnulmesant, BigDecimal depMes, BigDecimal debMes, BigDecimal creMes, BigDecimal saldoFinC, BigDecimal saldoFinB, String saldoConciliado, BigDecimal cheMesRes, BigDecimal cheAnulmesantRes, BigDecimal depMesRes, BigDecimal debMesRes, BigDecimal creMesRes, BigDecimal saldoFinCRes, BigDecimal saldoFinBRes) {
       this.id = id;
       this.cheMes = cheMes;
       this.cheAnulmesant = cheAnulmesant;
       this.depMes = depMes;
       this.debMes = debMes;
       this.creMes = creMes;
       this.saldoFinC = saldoFinC;
       this.saldoFinB = saldoFinB;
       this.saldoConciliado = saldoConciliado;
       this.cheMesRes = cheMesRes;
       this.cheAnulmesantRes = cheAnulmesantRes;
       this.depMesRes = depMesRes;
       this.debMesRes = debMesRes;
       this.creMesRes = creMesRes;
       this.saldoFinCRes = saldoFinCRes;
       this.saldoFinBRes = saldoFinBRes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noCta", column=@Column(name="NO_CTA", nullable=false, length=15) ), 
        @AttributeOverride(name="ano", column=@Column(name="ANO", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="mes", column=@Column(name="MES", nullable=false, precision=2, scale=0) ) } )
    public ArckhcId getId() {
        return this.id;
    }
    
    public void setId(ArckhcId id) {
        this.id = id;
    }

    
    @Column(name="CHE_MES", precision=17)
    public BigDecimal getCheMes() {
        return this.cheMes;
    }
    
    public void setCheMes(BigDecimal cheMes) {
        this.cheMes = cheMes;
    }

    
    @Column(name="CHE_ANULMESANT", precision=17)
    public BigDecimal getCheAnulmesant() {
        return this.cheAnulmesant;
    }
    
    public void setCheAnulmesant(BigDecimal cheAnulmesant) {
        this.cheAnulmesant = cheAnulmesant;
    }

    
    @Column(name="DEP_MES", precision=17)
    public BigDecimal getDepMes() {
        return this.depMes;
    }
    
    public void setDepMes(BigDecimal depMes) {
        this.depMes = depMes;
    }

    
    @Column(name="DEB_MES", precision=17)
    public BigDecimal getDebMes() {
        return this.debMes;
    }
    
    public void setDebMes(BigDecimal debMes) {
        this.debMes = debMes;
    }

    
    @Column(name="CRE_MES", precision=17)
    public BigDecimal getCreMes() {
        return this.creMes;
    }
    
    public void setCreMes(BigDecimal creMes) {
        this.creMes = creMes;
    }

    
    @Column(name="SALDO_FIN_C", precision=17)
    public BigDecimal getSaldoFinC() {
        return this.saldoFinC;
    }
    
    public void setSaldoFinC(BigDecimal saldoFinC) {
        this.saldoFinC = saldoFinC;
    }

    
    @Column(name="SALDO_FIN_B", precision=17)
    public BigDecimal getSaldoFinB() {
        return this.saldoFinB;
    }
    
    public void setSaldoFinB(BigDecimal saldoFinB) {
        this.saldoFinB = saldoFinB;
    }

    
    @Column(name="SALDO_CONCILIADO", length=1)
    public String getSaldoConciliado() {
        return this.saldoConciliado;
    }
    
    public void setSaldoConciliado(String saldoConciliado) {
        this.saldoConciliado = saldoConciliado;
    }

    
    @Column(name="CHE_MES_RES", precision=30)
    public BigDecimal getCheMesRes() {
        return this.cheMesRes;
    }
    
    public void setCheMesRes(BigDecimal cheMesRes) {
        this.cheMesRes = cheMesRes;
    }

    
    @Column(name="CHE_ANULMESANT_RES", precision=30)
    public BigDecimal getCheAnulmesantRes() {
        return this.cheAnulmesantRes;
    }
    
    public void setCheAnulmesantRes(BigDecimal cheAnulmesantRes) {
        this.cheAnulmesantRes = cheAnulmesantRes;
    }

    
    @Column(name="DEP_MES_RES", precision=30)
    public BigDecimal getDepMesRes() {
        return this.depMesRes;
    }
    
    public void setDepMesRes(BigDecimal depMesRes) {
        this.depMesRes = depMesRes;
    }

    
    @Column(name="DEB_MES_RES", precision=30)
    public BigDecimal getDebMesRes() {
        return this.debMesRes;
    }
    
    public void setDebMesRes(BigDecimal debMesRes) {
        this.debMesRes = debMesRes;
    }

    
    @Column(name="CRE_MES_RES", precision=30)
    public BigDecimal getCreMesRes() {
        return this.creMesRes;
    }
    
    public void setCreMesRes(BigDecimal creMesRes) {
        this.creMesRes = creMesRes;
    }

    
    @Column(name="SALDO_FIN_C_RES", precision=30)
    public BigDecimal getSaldoFinCRes() {
        return this.saldoFinCRes;
    }
    
    public void setSaldoFinCRes(BigDecimal saldoFinCRes) {
        this.saldoFinCRes = saldoFinCRes;
    }

    
    @Column(name="SALDO_FIN_B_RES", precision=30)
    public BigDecimal getSaldoFinBRes() {
        return this.saldoFinBRes;
    }
    
    public void setSaldoFinBRes(BigDecimal saldoFinBRes) {
        this.saldoFinBRes = saldoFinBRes;
    }




}


