package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arckmc generated by hbm2java
 */
@Entity
@Table(name="ARCKMC"
    ,schema="DESA46"
)
public class Arckmc  implements java.io.Serializable {


     private ArckmcId id;
     private String banco;
     private String moneda;
     private Short anoProc;
     private Byte mesProc;
     private String conciliada;
     private Short ultAnoConcil;
     private Byte ultMesConcil;
     private Short anoIni;
     private Byte mesIni;
     private BigDecimal salCiaIni;
     private BigDecimal salMesAnt;
     private BigDecimal salMesAntB;
     private BigDecimal salDiaAnt;
     private BigDecimal cheMes;
     private BigDecimal cheMesB;
     private BigDecimal cheDia;
     private BigDecimal cheAnulmesant;
     private BigDecimal depMes;
     private BigDecimal depMesB;
     private BigDecimal depDia;
     private BigDecimal debMes;
     private BigDecimal debMesB;
     private BigDecimal debDia;
     private BigDecimal creMes;
     private BigDecimal creMesB;
     private BigDecimal creDia;
     private String noCuenta;
     private String cuentaComision;
     private String observ;
     private String codDiariom;
     private BigDecimal saldoNominal;
     private Date diaCierre;
     private String formulario;
     private String formularioTr;
     private BigDecimal salCiaIniRes;
     private BigDecimal salMesAntRes;
     private BigDecimal salMesAntBRes;
     private BigDecimal salDiaAntRes;
     private BigDecimal cheMesRes;
     private BigDecimal cheMesBRes;
     private BigDecimal cheDiaRes;
     private BigDecimal cheAnulmesantRes;
     private BigDecimal depMesRes;
     private BigDecimal depMesBRes;
     private BigDecimal depDiaRes;
     private BigDecimal debMesRes;
     private BigDecimal debMesBRes;
     private BigDecimal debDiaRes;
     private BigDecimal creMesRes;
     private BigDecimal creMesBRes;
     private BigDecimal creDiaRes;
     private BigDecimal saldoNominalRes;

    public Arckmc() {
    }

	
    public Arckmc(ArckmcId id) {
        this.id = id;
    }
    public Arckmc(ArckmcId id, String banco, String moneda, Short anoProc, Byte mesProc, String conciliada, Short ultAnoConcil, Byte ultMesConcil, Short anoIni, Byte mesIni, BigDecimal salCiaIni, BigDecimal salMesAnt, BigDecimal salMesAntB, BigDecimal salDiaAnt, BigDecimal cheMes, BigDecimal cheMesB, BigDecimal cheDia, BigDecimal cheAnulmesant, BigDecimal depMes, BigDecimal depMesB, BigDecimal depDia, BigDecimal debMes, BigDecimal debMesB, BigDecimal debDia, BigDecimal creMes, BigDecimal creMesB, BigDecimal creDia, String noCuenta, String cuentaComision, String observ, String codDiariom, BigDecimal saldoNominal, Date diaCierre, String formulario, String formularioTr, BigDecimal salCiaIniRes, BigDecimal salMesAntRes, BigDecimal salMesAntBRes, BigDecimal salDiaAntRes, BigDecimal cheMesRes, BigDecimal cheMesBRes, BigDecimal cheDiaRes, BigDecimal cheAnulmesantRes, BigDecimal depMesRes, BigDecimal depMesBRes, BigDecimal depDiaRes, BigDecimal debMesRes, BigDecimal debMesBRes, BigDecimal debDiaRes, BigDecimal creMesRes, BigDecimal creMesBRes, BigDecimal creDiaRes, BigDecimal saldoNominalRes) {
       this.id = id;
       this.banco = banco;
       this.moneda = moneda;
       this.anoProc = anoProc;
       this.mesProc = mesProc;
       this.conciliada = conciliada;
       this.ultAnoConcil = ultAnoConcil;
       this.ultMesConcil = ultMesConcil;
       this.anoIni = anoIni;
       this.mesIni = mesIni;
       this.salCiaIni = salCiaIni;
       this.salMesAnt = salMesAnt;
       this.salMesAntB = salMesAntB;
       this.salDiaAnt = salDiaAnt;
       this.cheMes = cheMes;
       this.cheMesB = cheMesB;
       this.cheDia = cheDia;
       this.cheAnulmesant = cheAnulmesant;
       this.depMes = depMes;
       this.depMesB = depMesB;
       this.depDia = depDia;
       this.debMes = debMes;
       this.debMesB = debMesB;
       this.debDia = debDia;
       this.creMes = creMes;
       this.creMesB = creMesB;
       this.creDia = creDia;
       this.noCuenta = noCuenta;
       this.cuentaComision = cuentaComision;
       this.observ = observ;
       this.codDiariom = codDiariom;
       this.saldoNominal = saldoNominal;
       this.diaCierre = diaCierre;
       this.formulario = formulario;
       this.formularioTr = formularioTr;
       this.salCiaIniRes = salCiaIniRes;
       this.salMesAntRes = salMesAntRes;
       this.salMesAntBRes = salMesAntBRes;
       this.salDiaAntRes = salDiaAntRes;
       this.cheMesRes = cheMesRes;
       this.cheMesBRes = cheMesBRes;
       this.cheDiaRes = cheDiaRes;
       this.cheAnulmesantRes = cheAnulmesantRes;
       this.depMesRes = depMesRes;
       this.depMesBRes = depMesBRes;
       this.depDiaRes = depDiaRes;
       this.debMesRes = debMesRes;
       this.debMesBRes = debMesBRes;
       this.debDiaRes = debDiaRes;
       this.creMesRes = creMesRes;
       this.creMesBRes = creMesBRes;
       this.creDiaRes = creDiaRes;
       this.saldoNominalRes = saldoNominalRes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCta", column=@Column(name="NO_CTA", nullable=false, length=15) ), 
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ) } )
    public ArckmcId getId() {
        return this.id;
    }
    
    public void setId(ArckmcId id) {
        this.id = id;
    }

    
    @Column(name="BANCO", length=2)
    public String getBanco() {
        return this.banco;
    }
    
    public void setBanco(String banco) {
        this.banco = banco;
    }

    
    @Column(name="MONEDA", length=1)
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }

    
    @Column(name="ANO_PROC", precision=4, scale=0)
    public Short getAnoProc() {
        return this.anoProc;
    }
    
    public void setAnoProc(Short anoProc) {
        this.anoProc = anoProc;
    }

    
    @Column(name="MES_PROC", precision=2, scale=0)
    public Byte getMesProc() {
        return this.mesProc;
    }
    
    public void setMesProc(Byte mesProc) {
        this.mesProc = mesProc;
    }

    
    @Column(name="CONCILIADA", length=1)
    public String getConciliada() {
        return this.conciliada;
    }
    
    public void setConciliada(String conciliada) {
        this.conciliada = conciliada;
    }

    
    @Column(name="ULT_ANO_CONCIL", precision=4, scale=0)
    public Short getUltAnoConcil() {
        return this.ultAnoConcil;
    }
    
    public void setUltAnoConcil(Short ultAnoConcil) {
        this.ultAnoConcil = ultAnoConcil;
    }

    
    @Column(name="ULT_MES_CONCIL", precision=2, scale=0)
    public Byte getUltMesConcil() {
        return this.ultMesConcil;
    }
    
    public void setUltMesConcil(Byte ultMesConcil) {
        this.ultMesConcil = ultMesConcil;
    }

    
    @Column(name="ANO_INI", precision=4, scale=0)
    public Short getAnoIni() {
        return this.anoIni;
    }
    
    public void setAnoIni(Short anoIni) {
        this.anoIni = anoIni;
    }

    
    @Column(name="MES_INI", precision=2, scale=0)
    public Byte getMesIni() {
        return this.mesIni;
    }
    
    public void setMesIni(Byte mesIni) {
        this.mesIni = mesIni;
    }

    
    @Column(name="SAL_CIA_INI", precision=17)
    public BigDecimal getSalCiaIni() {
        return this.salCiaIni;
    }
    
    public void setSalCiaIni(BigDecimal salCiaIni) {
        this.salCiaIni = salCiaIni;
    }

    
    @Column(name="SAL_MES_ANT", precision=17)
    public BigDecimal getSalMesAnt() {
        return this.salMesAnt;
    }
    
    public void setSalMesAnt(BigDecimal salMesAnt) {
        this.salMesAnt = salMesAnt;
    }

    
    @Column(name="SAL_MES_ANT_B", precision=17)
    public BigDecimal getSalMesAntB() {
        return this.salMesAntB;
    }
    
    public void setSalMesAntB(BigDecimal salMesAntB) {
        this.salMesAntB = salMesAntB;
    }

    
    @Column(name="SAL_DIA_ANT", precision=17)
    public BigDecimal getSalDiaAnt() {
        return this.salDiaAnt;
    }
    
    public void setSalDiaAnt(BigDecimal salDiaAnt) {
        this.salDiaAnt = salDiaAnt;
    }

    
    @Column(name="CHE_MES", precision=17)
    public BigDecimal getCheMes() {
        return this.cheMes;
    }
    
    public void setCheMes(BigDecimal cheMes) {
        this.cheMes = cheMes;
    }

    
    @Column(name="CHE_MES_B", precision=17)
    public BigDecimal getCheMesB() {
        return this.cheMesB;
    }
    
    public void setCheMesB(BigDecimal cheMesB) {
        this.cheMesB = cheMesB;
    }

    
    @Column(name="CHE_DIA", precision=17)
    public BigDecimal getCheDia() {
        return this.cheDia;
    }
    
    public void setCheDia(BigDecimal cheDia) {
        this.cheDia = cheDia;
    }

    
    @Column(name="CHE_ANULMESANT", precision=17)
    public BigDecimal getCheAnulmesant() {
        return this.cheAnulmesant;
    }
    
    public void setCheAnulmesant(BigDecimal cheAnulmesant) {
        this.cheAnulmesant = cheAnulmesant;
    }

    
    @Column(name="DEP_MES", precision=17)
    public BigDecimal getDepMes() {
        return this.depMes;
    }
    
    public void setDepMes(BigDecimal depMes) {
        this.depMes = depMes;
    }

    
    @Column(name="DEP_MES_B", precision=17)
    public BigDecimal getDepMesB() {
        return this.depMesB;
    }
    
    public void setDepMesB(BigDecimal depMesB) {
        this.depMesB = depMesB;
    }

    
    @Column(name="DEP_DIA", precision=17)
    public BigDecimal getDepDia() {
        return this.depDia;
    }
    
    public void setDepDia(BigDecimal depDia) {
        this.depDia = depDia;
    }

    
    @Column(name="DEB_MES", precision=17)
    public BigDecimal getDebMes() {
        return this.debMes;
    }
    
    public void setDebMes(BigDecimal debMes) {
        this.debMes = debMes;
    }

    
    @Column(name="DEB_MES_B", precision=17)
    public BigDecimal getDebMesB() {
        return this.debMesB;
    }
    
    public void setDebMesB(BigDecimal debMesB) {
        this.debMesB = debMesB;
    }

    
    @Column(name="DEB_DIA", precision=17)
    public BigDecimal getDebDia() {
        return this.debDia;
    }
    
    public void setDebDia(BigDecimal debDia) {
        this.debDia = debDia;
    }

    
    @Column(name="CRE_MES", precision=17)
    public BigDecimal getCreMes() {
        return this.creMes;
    }
    
    public void setCreMes(BigDecimal creMes) {
        this.creMes = creMes;
    }

    
    @Column(name="CRE_MES_B", precision=17)
    public BigDecimal getCreMesB() {
        return this.creMesB;
    }
    
    public void setCreMesB(BigDecimal creMesB) {
        this.creMesB = creMesB;
    }

    
    @Column(name="CRE_DIA", precision=17)
    public BigDecimal getCreDia() {
        return this.creDia;
    }
    
    public void setCreDia(BigDecimal creDia) {
        this.creDia = creDia;
    }

    
    @Column(name="NO_CUENTA", length=15)
    public String getNoCuenta() {
        return this.noCuenta;
    }
    
    public void setNoCuenta(String noCuenta) {
        this.noCuenta = noCuenta;
    }

    
    @Column(name="CUENTA_COMISION", length=15)
    public String getCuentaComision() {
        return this.cuentaComision;
    }
    
    public void setCuentaComision(String cuentaComision) {
        this.cuentaComision = cuentaComision;
    }

    
    @Column(name="OBSERV", length=240)
    public String getObserv() {
        return this.observ;
    }
    
    public void setObserv(String observ) {
        this.observ = observ;
    }

    
    @Column(name="COD_DIARIOM", length=5)
    public String getCodDiariom() {
        return this.codDiariom;
    }
    
    public void setCodDiariom(String codDiariom) {
        this.codDiariom = codDiariom;
    }

    
    @Column(name="SALDO_NOMINAL", precision=17)
    public BigDecimal getSaldoNominal() {
        return this.saldoNominal;
    }
    
    public void setSaldoNominal(BigDecimal saldoNominal) {
        this.saldoNominal = saldoNominal;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DIA_CIERRE", length=7)
    public Date getDiaCierre() {
        return this.diaCierre;
    }
    
    public void setDiaCierre(Date diaCierre) {
        this.diaCierre = diaCierre;
    }

    
    @Column(name="FORMULARIO", length=10)
    public String getFormulario() {
        return this.formulario;
    }
    
    public void setFormulario(String formulario) {
        this.formulario = formulario;
    }

    
    @Column(name="FORMULARIO_TR", length=10)
    public String getFormularioTr() {
        return this.formularioTr;
    }
    
    public void setFormularioTr(String formularioTr) {
        this.formularioTr = formularioTr;
    }

    
    @Column(name="SAL_CIA_INI_RES", precision=30)
    public BigDecimal getSalCiaIniRes() {
        return this.salCiaIniRes;
    }
    
    public void setSalCiaIniRes(BigDecimal salCiaIniRes) {
        this.salCiaIniRes = salCiaIniRes;
    }

    
    @Column(name="SAL_MES_ANT_RES", precision=30)
    public BigDecimal getSalMesAntRes() {
        return this.salMesAntRes;
    }
    
    public void setSalMesAntRes(BigDecimal salMesAntRes) {
        this.salMesAntRes = salMesAntRes;
    }

    
    @Column(name="SAL_MES_ANT_B_RES", precision=30)
    public BigDecimal getSalMesAntBRes() {
        return this.salMesAntBRes;
    }
    
    public void setSalMesAntBRes(BigDecimal salMesAntBRes) {
        this.salMesAntBRes = salMesAntBRes;
    }

    
    @Column(name="SAL_DIA_ANT_RES", precision=30)
    public BigDecimal getSalDiaAntRes() {
        return this.salDiaAntRes;
    }
    
    public void setSalDiaAntRes(BigDecimal salDiaAntRes) {
        this.salDiaAntRes = salDiaAntRes;
    }

    
    @Column(name="CHE_MES_RES", precision=30)
    public BigDecimal getCheMesRes() {
        return this.cheMesRes;
    }
    
    public void setCheMesRes(BigDecimal cheMesRes) {
        this.cheMesRes = cheMesRes;
    }

    
    @Column(name="CHE_MES_B_RES", precision=30)
    public BigDecimal getCheMesBRes() {
        return this.cheMesBRes;
    }
    
    public void setCheMesBRes(BigDecimal cheMesBRes) {
        this.cheMesBRes = cheMesBRes;
    }

    
    @Column(name="CHE_DIA_RES", precision=30)
    public BigDecimal getCheDiaRes() {
        return this.cheDiaRes;
    }
    
    public void setCheDiaRes(BigDecimal cheDiaRes) {
        this.cheDiaRes = cheDiaRes;
    }

    
    @Column(name="CHE_ANULMESANT_RES", precision=30)
    public BigDecimal getCheAnulmesantRes() {
        return this.cheAnulmesantRes;
    }
    
    public void setCheAnulmesantRes(BigDecimal cheAnulmesantRes) {
        this.cheAnulmesantRes = cheAnulmesantRes;
    }

    
    @Column(name="DEP_MES_RES", precision=30)
    public BigDecimal getDepMesRes() {
        return this.depMesRes;
    }
    
    public void setDepMesRes(BigDecimal depMesRes) {
        this.depMesRes = depMesRes;
    }

    
    @Column(name="DEP_MES_B_RES", precision=30)
    public BigDecimal getDepMesBRes() {
        return this.depMesBRes;
    }
    
    public void setDepMesBRes(BigDecimal depMesBRes) {
        this.depMesBRes = depMesBRes;
    }

    
    @Column(name="DEP_DIA_RES", precision=30)
    public BigDecimal getDepDiaRes() {
        return this.depDiaRes;
    }
    
    public void setDepDiaRes(BigDecimal depDiaRes) {
        this.depDiaRes = depDiaRes;
    }

    
    @Column(name="DEB_MES_RES", precision=30)
    public BigDecimal getDebMesRes() {
        return this.debMesRes;
    }
    
    public void setDebMesRes(BigDecimal debMesRes) {
        this.debMesRes = debMesRes;
    }

    
    @Column(name="DEB_MES_B_RES", precision=30)
    public BigDecimal getDebMesBRes() {
        return this.debMesBRes;
    }
    
    public void setDebMesBRes(BigDecimal debMesBRes) {
        this.debMesBRes = debMesBRes;
    }

    
    @Column(name="DEB_DIA_RES", precision=30)
    public BigDecimal getDebDiaRes() {
        return this.debDiaRes;
    }
    
    public void setDebDiaRes(BigDecimal debDiaRes) {
        this.debDiaRes = debDiaRes;
    }

    
    @Column(name="CRE_MES_RES", precision=30)
    public BigDecimal getCreMesRes() {
        return this.creMesRes;
    }
    
    public void setCreMesRes(BigDecimal creMesRes) {
        this.creMesRes = creMesRes;
    }

    
    @Column(name="CRE_MES_B_RES", precision=30)
    public BigDecimal getCreMesBRes() {
        return this.creMesBRes;
    }
    
    public void setCreMesBRes(BigDecimal creMesBRes) {
        this.creMesBRes = creMesBRes;
    }

    
    @Column(name="CRE_DIA_RES", precision=30)
    public BigDecimal getCreDiaRes() {
        return this.creDiaRes;
    }
    
    public void setCreDiaRes(BigDecimal creDiaRes) {
        this.creDiaRes = creDiaRes;
    }

    
    @Column(name="SALDO_NOMINAL_RES", precision=30)
    public BigDecimal getSaldoNominalRes() {
        return this.saldoNominalRes;
    }
    
    public void setSaldoNominalRes(BigDecimal saldoNominalRes) {
        this.saldoNominalRes = saldoNominalRes;
    }




}


