package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arckcnch generated by hbm2java
 */
@Entity
@Table(name="ARCKCNCH"
    ,schema="DESA46"
)
public class Arckcnc  implements java.io.Serializable {


     private ArckcncId id;
     private String noCta;
     private String procedencia;
     private String tipoDoc;
     private Date fecha;
     private String beneficiario;
     private BigDecimal monto;
     private String mensaje;
     private BigDecimal montoBco;
     private BigDecimal difere;
     private String codMsg;
     private BigDecimal montoRes;
     private BigDecimal montoBcoRes;

    public Arckcnc() {
    }

	
    public Arckcnc(ArckcncId id) {
        this.id = id;
    }
    public Arckcnc(ArckcncId id, String noCta, String procedencia, String tipoDoc, Date fecha, String beneficiario, BigDecimal monto, String mensaje, BigDecimal montoBco, BigDecimal difere, String codMsg, BigDecimal montoRes , BigDecimal montoBcoRes) {
       this.id = id;
       this.noCta = noCta;
       this.procedencia = procedencia;
       this.tipoDoc = tipoDoc;
       this.fecha = fecha;
       this.beneficiario = beneficiario;
       this.monto = monto;
       this.mensaje = mensaje;
       this.montoBco = montoBco;
       this.difere = difere;
       this.codMsg = codMsg;
       this.montoRes = montoRes;
       this.montoBcoRes = montoBcoRes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noDocu", column=@Column(name="NO_DOCU", nullable=false, precision=8, scale=0) )} )
    public ArckcncId getId() {
        return this.id;
    }
    
    public void setId(ArckcncId id) {
        this.id = id;
    }

    
    @Column(name="NO_CTA", length=15)
    public String getNoCta() {
        return this.noCta;
    }
    
    public void setNoCta(String noCta) {
        this.noCta = noCta;
    }

    
    @Column(name="PROCEDENCIA", length=1)
    public String getProcedencia() {
        return this.procedencia;
    }
    
    public void setProcedencia(String procedencia) {
        this.procedencia = procedencia;
    }

    
    @Column(name="TIPO_DOC", length=2)
    public String getTipoDoc() {
        return this.tipoDoc;
    }
    
    public void setTipoDoc(String tipoDoc) {
        this.tipoDoc = tipoDoc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", length=7)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="BENEFICIARIO", length=60)
    public String getBeneficiario() {
        return this.beneficiario;
    }
    
    public void setBeneficiario(String beneficiario) {
        this.beneficiario = beneficiario;
    }

    
    @Column(name="MONTO", precision=17)
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

    
    @Column(name="MENSAJE", length=20)
    public String getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }

    
    @Column(name="MONTO_BCO", precision=17)
    public BigDecimal getMontoBco() {
        return this.montoBco;
    }
    
    public void setMontoBco(BigDecimal montoBco) {
        this.montoBco = montoBco;
    }

    
    @Column(name="DIFERE", precision=17)
    public BigDecimal getDifere() {
        return this.difere;
    }
    
    public void setDifere(BigDecimal difere) {
        this.difere = difere;
    }

    
    @Column(name="COD_MSG", length=5)
    public String getCodMsg() {
        return this.codMsg;
    }
    
    public void setCodMsg(String codMsg) {
        this.codMsg = codMsg;
    }

    
    @Column(name="MONTO_RES", precision=30)
    public BigDecimal getMontoRes() {
        return this.montoRes;
    }
    
    public void setMontoRes(BigDecimal montoRes) {
        this.montoRes = montoRes;
    }

    public BigDecimal getMontoBcoRes() {
        return montoBcoRes;
    }

    public void setMontoBcoRes(BigDecimal montoBcoRes) {
        this.montoBcoRes = montoBcoRes;
    }


}


