package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ArcktbCta generated by hbm2java
 */
@Entity
@Table(name="ARCKTB_CTA"
    ,schema="DESA46"
)
public class ArcktbCta  implements java.io.Serializable {


     private ArcktbCtaId id;
     private String descri;
     private String centro;
     private String cuenta;

    public ArcktbCta() {
    }

	
    public ArcktbCta(ArcktbCtaId id) {
        this.id = id;
    }
    public ArcktbCta(ArcktbCtaId id, String descri, String centro, String cuenta) {
       this.id = id;
       this.descri = descri;
       this.centro = centro;
       this.cuenta = cuenta;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noCta", column=@Column(name="NO_CTA", nullable=false, length=15) ), 
        @AttributeOverride(name="tipoMovExt", column=@Column(name="TIPO_MOV_EXT", nullable=false, length=30) ) } )
    public ArcktbCtaId getId() {
        return this.id;
    }
    
    public void setId(ArcktbCtaId id) {
        this.id = id;
    }

    
    @Column(name="DESCRI", length=500)
    public String getDescri() {
        return this.descri;
    }
    
    public void setDescri(String descri) {
        this.descri = descri;
    }

    
    @Column(name="CENTRO", length=9)
    public String getCentro() {
        return this.centro;
    }
    
    public void setCentro(String centro) {
        this.centro = centro;
    }

    
    @Column(name="CUENTA", length=15)
    public String getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }




}


