package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArckccId generated by hbm2java
 */
@Embeddable
public class ArckccId  implements java.io.Serializable {


     private int noDocuR;
     private short ano;
     private byte mes;
     private String noCia;
     private int noDocu;

    public ArckccId() {
    }

    public ArckccId(int noDocuR, short ano, byte mes, String noCia, int noDocu) {
       this.noDocuR = noDocuR;
       this.ano = ano;
       this.mes = mes;
       this.noCia = noCia;
       this.noDocu = noDocu;
    }
   


    @Column(name="NO_DOCU_R", nullable=false, precision=8, scale=0)
    public int getNoDocuR() {
        return this.noDocuR;
    }
    
    public void setNoDocuR(int noDocuR) {
        this.noDocuR = noDocuR;
    }


    @Column(name="ANO", nullable=false, precision=4, scale=0)
    public short getAno() {
        return this.ano;
    }
    
    public void setAno(short ano) {
        this.ano = ano;
    }


    @Column(name="MES", nullable=false, precision=2, scale=0)
    public byte getMes() {
        return this.mes;
    }
    
    public void setMes(byte mes) {
        this.mes = mes;
    }


    @Column(name="NO_CIA", nullable=false, length=2)
    public String getNoCia() {
        return this.noCia;
    }
    
    public void setNoCia(String noCia) {
        this.noCia = noCia;
    }


    @Column(name="NO_DOCU", nullable=false, precision=8, scale=0)
    public int getNoDocu() {
        return this.noDocu;
    }
    
    public void setNoDocu(int noDocu) {
        this.noDocu = noDocu;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArckccId) ) return false;
		 ArckccId castOther = ( ArckccId ) other; 
         
		 return (this.getNoDocuR()==castOther.getNoDocuR())
 && (this.getAno()==castOther.getAno())
 && (this.getMes()==castOther.getMes())
 && ( (this.getNoCia()==castOther.getNoCia()) || ( this.getNoCia()!=null && castOther.getNoCia()!=null && this.getNoCia().equals(castOther.getNoCia()) ) )
 && (this.getNoDocu()==castOther.getNoDocu());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNoDocuR();
         result = 37 * result + this.getAno();
         result = 37 * result + this.getMes();
         result = 37 * result + ( getNoCia() == null ? 0 : this.getNoCia().hashCode() );
         result = 37 * result + this.getNoDocu();
         return result;
   }   


}


