package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arckdb generated by hbm2java
 */
@Entity
@Table(name="ARCKDB"
    ,schema="DESA46"
)
public class Arckdb  implements java.io.Serializable {


     private ArckdbId id;
     private String tipoDocc;
     private String formaConciliacion;

    public Arckdb() {
    }

	
    public Arckdb(ArckdbId id) {
        this.id = id;
    }
    public Arckdb(ArckdbId id, String tipoDocc, String formaConciliacion) {
       this.id = id;
       this.tipoDocc = tipoDocc;
       this.formaConciliacion = formaConciliacion;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="banco", column=@Column(name="BANCO", nullable=false, length=2) ), 
        @AttributeOverride(name="tipoDocb", column=@Column(name="TIPO_DOCB", nullable=false, length=10) ) } )
    public ArckdbId getId() {
        return this.id;
    }
    
    public void setId(ArckdbId id) {
        this.id = id;
    }

    
    @Column(name="TIPO_DOCC", length=2)
    public String getTipoDocc() {
        return this.tipoDocc;
    }
    
    public void setTipoDocc(String tipoDocc) {
        this.tipoDocc = tipoDocc;
    }

    
    @Column(name="FORMA_CONCILIACION", length=1)
    public String getFormaConciliacion() {
        return this.formaConciliacion;
    }
    
    public void setFormaConciliacion(String formaConciliacion) {
        this.formaConciliacion = formaConciliacion;
    }




}


