package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Arcpmd generated by hbm2java
 */
@Entity
@Table(name="ARCPMD"
    ,schema="DESA46"
    , uniqueConstraints = @UniqueConstraint(columnNames={"NO_PROVE", "TIPO_DOC", "NO_FISICO", "SERIE_FISICO", "NO_CTA", "NO_CIA"}) 
)
public class Arcpmd  implements java.io.Serializable {


     private ArcpmdId id;
     private String noProve;
     private String tipoDoc;
     private String indAct;
     private String noFisico;
     private String serieFisico;
     private String indOtromov;
     private Date fecha;
     private BigDecimal subtotal;
     private BigDecimal monto;
     private BigDecimal saldo;
     private BigDecimal gravado;
     private BigDecimal excentos;
     private BigDecimal descuento;
     private BigDecimal totRefer;
     private BigDecimal totDb;
     private BigDecimal totCr;
     private Date fechaVence;
     private BigDecimal descC;
     private String noOrden;
     private BigDecimal descP;
     private Short plazoC;
     private Short plazoP;
     private String bloqueado;
     private String motivo;
     private String moneda;
     private BigDecimal tipoCambio;
     private BigDecimal tipoHist;
     private BigDecimal montoNominal;
     private BigDecimal saldoNominal;
     private String noCta;
     private String noSecuencia;
     private String TCambCV;
     private String detalle;
     private String indOtrosMeses;
     private Date fechaDocumento;
     private Date fechaVenceOriginal;
     private Byte cantProrrogas;
     private String origen;
     private Long numeroCtrl;
     private String anulado;
     private String usuarioAnula;
     private String motivoAnula;
     private String codEstado;
     private String indEstadoVencido;
     private Short anoAnulado;
     private Byte mesAnulado;
     private BigDecimal totDpp;
     private String monedaFisico;
     private BigDecimal montoFisico;
     private BigDecimal totImp;
     private BigDecimal totRet;
     private BigDecimal totImpEspecial;
     private String codDiario;
     private BigDecimal porctImp;
     private String compRetIva;
     private String numRetIva;
     private String mesRet;
     private String anoRet;
     private BigDecimal porcRetIva;
     private BigDecimal montRetIva;
     private String stRetIva;
     private Date fechaRi;
     private Date fechaTc;
     private String stRetDecl;
     private BigDecimal tempSald;
     private Long nro;
     private BigDecimal subtotalRes;
     private BigDecimal montoRes;
     private BigDecimal saldoRes;
     private BigDecimal gravadoRes;
     private BigDecimal excentosRes;
     private BigDecimal descuentoRes;
     private BigDecimal totReferRes;
     private BigDecimal totDbRes;
     private BigDecimal totCrRes;
     private BigDecimal montoFisicoRes;
     private BigDecimal totImpRes;
     private BigDecimal totRetRes;
     private BigDecimal montRetIvaRes;
     private BigDecimal tempSaldRes;

    public Arcpmd() {
    }

	
    public Arcpmd(ArcpmdId id) {
        this.id = id;
    }
    public Arcpmd(ArcpmdId id, String noProve, String tipoDoc, String indAct, String noFisico, String serieFisico, String indOtromov, Date fecha, BigDecimal subtotal, BigDecimal monto, BigDecimal saldo, BigDecimal gravado, BigDecimal excentos, BigDecimal descuento, BigDecimal totRefer, BigDecimal totDb, BigDecimal totCr, Date fechaVence, BigDecimal descC, String noOrden, BigDecimal descP, Short plazoC, Short plazoP, String bloqueado, String motivo, String moneda, BigDecimal tipoCambio, BigDecimal tipoHist, BigDecimal montoNominal, BigDecimal saldoNominal, String noCta, String noSecuencia, String TCambCV, String detalle, String indOtrosMeses, Date fechaDocumento, Date fechaVenceOriginal, Byte cantProrrogas, String origen, Long numeroCtrl, String anulado, String usuarioAnula, String motivoAnula, String codEstado, String indEstadoVencido, Short anoAnulado, Byte mesAnulado, BigDecimal totDpp, String monedaFisico, BigDecimal montoFisico, BigDecimal totImp, BigDecimal totRet, BigDecimal totImpEspecial, String codDiario, BigDecimal porctImp, String compRetIva, String numRetIva, String mesRet, String anoRet, BigDecimal porcRetIva, BigDecimal montRetIva, String stRetIva, Date fechaRi, Date fechaTc, String stRetDecl, BigDecimal tempSald, Long nro, BigDecimal subtotalRes, BigDecimal montoRes, BigDecimal saldoRes, BigDecimal gravadoRes, BigDecimal excentosRes, BigDecimal descuentoRes, BigDecimal totReferRes, BigDecimal totDbRes, BigDecimal totCrRes, BigDecimal montoFisicoRes, BigDecimal totImpRes, BigDecimal totRetRes, BigDecimal montRetIvaRes, BigDecimal tempSaldRes) {
       this.id = id;
       this.noProve = noProve;
       this.tipoDoc = tipoDoc;
       this.indAct = indAct;
       this.noFisico = noFisico;
       this.serieFisico = serieFisico;
       this.indOtromov = indOtromov;
       this.fecha = fecha;
       this.subtotal = subtotal;
       this.monto = monto;
       this.saldo = saldo;
       this.gravado = gravado;
       this.excentos = excentos;
       this.descuento = descuento;
       this.totRefer = totRefer;
       this.totDb = totDb;
       this.totCr = totCr;
       this.fechaVence = fechaVence;
       this.descC = descC;
       this.noOrden = noOrden;
       this.descP = descP;
       this.plazoC = plazoC;
       this.plazoP = plazoP;
       this.bloqueado = bloqueado;
       this.motivo = motivo;
       this.moneda = moneda;
       this.tipoCambio = tipoCambio;
       this.tipoHist = tipoHist;
       this.montoNominal = montoNominal;
       this.saldoNominal = saldoNominal;
       this.noCta = noCta;
       this.noSecuencia = noSecuencia;
       this.TCambCV = TCambCV;
       this.detalle = detalle;
       this.indOtrosMeses = indOtrosMeses;
       this.fechaDocumento = fechaDocumento;
       this.fechaVenceOriginal = fechaVenceOriginal;
       this.cantProrrogas = cantProrrogas;
       this.origen = origen;
       this.numeroCtrl = numeroCtrl;
       this.anulado = anulado;
       this.usuarioAnula = usuarioAnula;
       this.motivoAnula = motivoAnula;
       this.codEstado = codEstado;
       this.indEstadoVencido = indEstadoVencido;
       this.anoAnulado = anoAnulado;
       this.mesAnulado = mesAnulado;
       this.totDpp = totDpp;
       this.monedaFisico = monedaFisico;
       this.montoFisico = montoFisico;
       this.totImp = totImp;
       this.totRet = totRet;
       this.totImpEspecial = totImpEspecial;
       this.codDiario = codDiario;
       this.porctImp = porctImp;
       this.compRetIva = compRetIva;
       this.numRetIva = numRetIva;
       this.mesRet = mesRet;
       this.anoRet = anoRet;
       this.porcRetIva = porcRetIva;
       this.montRetIva = montRetIva;
       this.stRetIva = stRetIva;
       this.fechaRi = fechaRi;
       this.fechaTc = fechaTc;
       this.stRetDecl = stRetDecl;
       this.tempSald = tempSald;
       this.nro = nro;
       this.subtotalRes = subtotalRes;
       this.montoRes = montoRes;
       this.saldoRes = saldoRes;
       this.gravadoRes = gravadoRes;
       this.excentosRes = excentosRes;
       this.descuentoRes = descuentoRes;
       this.totReferRes = totReferRes;
       this.totDbRes = totDbRes;
       this.totCrRes = totCrRes;
       this.montoFisicoRes = montoFisicoRes;
       this.totImpRes = totImpRes;
       this.totRetRes = totRetRes;
       this.montRetIvaRes = montRetIvaRes;
       this.tempSaldRes = tempSaldRes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noDocu", column=@Column(name="NO_DOCU", nullable=false, length=8) ) } )
    public ArcpmdId getId() {
        return this.id;
    }
    
    public void setId(ArcpmdId id) {
        this.id = id;
    }

    
    @Column(name="NO_PROVE", length=15)
    public String getNoProve() {
        return this.noProve;
    }
    
    public void setNoProve(String noProve) {
        this.noProve = noProve;
    }

    
    @Column(name="TIPO_DOC", length=2)
    public String getTipoDoc() {
        return this.tipoDoc;
    }
    
    public void setTipoDoc(String tipoDoc) {
        this.tipoDoc = tipoDoc;
    }

    
    @Column(name="IND_ACT", length=1)
    public String getIndAct() {
        return this.indAct;
    }
    
    public void setIndAct(String indAct) {
        this.indAct = indAct;
    }

    
    @Column(name="NO_FISICO", length=30)
    public String getNoFisico() {
        return this.noFisico;
    }
    
    public void setNoFisico(String noFisico) {
        this.noFisico = noFisico;
    }

    
    @Column(name="SERIE_FISICO", length=50)
    public String getSerieFisico() {
        return this.serieFisico;
    }
    
    public void setSerieFisico(String serieFisico) {
        this.serieFisico = serieFisico;
    }

    
    @Column(name="IND_OTROMOV", length=1)
    public String getIndOtromov() {
        return this.indOtromov;
    }
    
    public void setIndOtromov(String indOtromov) {
        this.indOtromov = indOtromov;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", length=7)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="SUBTOTAL", precision=17)
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }

    
    @Column(name="MONTO", precision=17)
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

    
    @Column(name="SALDO", precision=17)
    public BigDecimal getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(BigDecimal saldo) {
        this.saldo = saldo;
    }

    
    @Column(name="GRAVADO", precision=17)
    public BigDecimal getGravado() {
        return this.gravado;
    }
    
    public void setGravado(BigDecimal gravado) {
        this.gravado = gravado;
    }

    
    @Column(name="EXCENTOS", precision=17)
    public BigDecimal getExcentos() {
        return this.excentos;
    }
    
    public void setExcentos(BigDecimal excentos) {
        this.excentos = excentos;
    }

    
    @Column(name="DESCUENTO", precision=17)
    public BigDecimal getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(BigDecimal descuento) {
        this.descuento = descuento;
    }

    
    @Column(name="TOT_REFER", precision=17)
    public BigDecimal getTotRefer() {
        return this.totRefer;
    }
    
    public void setTotRefer(BigDecimal totRefer) {
        this.totRefer = totRefer;
    }

    
    @Column(name="TOT_DB", precision=17)
    public BigDecimal getTotDb() {
        return this.totDb;
    }
    
    public void setTotDb(BigDecimal totDb) {
        this.totDb = totDb;
    }

    
    @Column(name="TOT_CR", precision=17)
    public BigDecimal getTotCr() {
        return this.totCr;
    }
    
    public void setTotCr(BigDecimal totCr) {
        this.totCr = totCr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_VENCE", length=7)
    public Date getFechaVence() {
        return this.fechaVence;
    }
    
    public void setFechaVence(Date fechaVence) {
        this.fechaVence = fechaVence;
    }

    
    @Column(name="DESC_C", precision=5)
    public BigDecimal getDescC() {
        return this.descC;
    }
    
    public void setDescC(BigDecimal descC) {
        this.descC = descC;
    }

    
    @Column(name="NO_ORDEN", length=8)
    public String getNoOrden() {
        return this.noOrden;
    }
    
    public void setNoOrden(String noOrden) {
        this.noOrden = noOrden;
    }

    
    @Column(name="DESC_P", precision=5)
    public BigDecimal getDescP() {
        return this.descP;
    }
    
    public void setDescP(BigDecimal descP) {
        this.descP = descP;
    }

    
    @Column(name="PLAZO_C", precision=3, scale=0)
    public Short getPlazoC() {
        return this.plazoC;
    }
    
    public void setPlazoC(Short plazoC) {
        this.plazoC = plazoC;
    }

    
    @Column(name="PLAZO_P", precision=3, scale=0)
    public Short getPlazoP() {
        return this.plazoP;
    }
    
    public void setPlazoP(Short plazoP) {
        this.plazoP = plazoP;
    }

    
    @Column(name="BLOQUEADO", length=1)
    public String getBloqueado() {
        return this.bloqueado;
    }
    
    public void setBloqueado(String bloqueado) {
        this.bloqueado = bloqueado;
    }

    
    @Column(name="MOTIVO", length=30)
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }

    
    @Column(name="MONEDA", length=1)
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }

    
    @Column(name="TIPO_CAMBIO", precision=17, scale=4)
    public BigDecimal getTipoCambio() {
        return this.tipoCambio;
    }
    
    public void setTipoCambio(BigDecimal tipoCambio) {
        this.tipoCambio = tipoCambio;
    }

    
    @Column(name="TIPO_HIST", precision=7)
    public BigDecimal getTipoHist() {
        return this.tipoHist;
    }
    
    public void setTipoHist(BigDecimal tipoHist) {
        this.tipoHist = tipoHist;
    }

    
    @Column(name="MONTO_NOMINAL", precision=17)
    public BigDecimal getMontoNominal() {
        return this.montoNominal;
    }
    
    public void setMontoNominal(BigDecimal montoNominal) {
        this.montoNominal = montoNominal;
    }

    
    @Column(name="SALDO_NOMINAL", precision=17)
    public BigDecimal getSaldoNominal() {
        return this.saldoNominal;
    }
    
    public void setSaldoNominal(BigDecimal saldoNominal) {
        this.saldoNominal = saldoNominal;
    }

    
    @Column(name="NO_CTA", length=15)
    public String getNoCta() {
        return this.noCta;
    }
    
    public void setNoCta(String noCta) {
        this.noCta = noCta;
    }

    
    @Column(name="NO_SECUENCIA", length=8)
    public String getNoSecuencia() {
        return this.noSecuencia;
    }
    
    public void setNoSecuencia(String noSecuencia) {
        this.noSecuencia = noSecuencia;
    }

    
    @Column(name="T_CAMB_C_V", length=1)
    public String getTCambCV() {
        return this.TCambCV;
    }
    
    public void setTCambCV(String TCambCV) {
        this.TCambCV = TCambCV;
    }

    
    @Column(name="DETALLE", length=100)
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }

    
    @Column(name="IND_OTROS_MESES", length=1)
    public String getIndOtrosMeses() {
        return this.indOtrosMeses;
    }
    
    public void setIndOtrosMeses(String indOtrosMeses) {
        this.indOtrosMeses = indOtrosMeses;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_DOCUMENTO", length=7)
    public Date getFechaDocumento() {
        return this.fechaDocumento;
    }
    
    public void setFechaDocumento(Date fechaDocumento) {
        this.fechaDocumento = fechaDocumento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_VENCE_ORIGINAL", length=7)
    public Date getFechaVenceOriginal() {
        return this.fechaVenceOriginal;
    }
    
    public void setFechaVenceOriginal(Date fechaVenceOriginal) {
        this.fechaVenceOriginal = fechaVenceOriginal;
    }

    
    @Column(name="CANT_PRORROGAS", precision=2, scale=0)
    public Byte getCantProrrogas() {
        return this.cantProrrogas;
    }
    
    public void setCantProrrogas(Byte cantProrrogas) {
        this.cantProrrogas = cantProrrogas;
    }

    
    @Column(name="ORIGEN", length=2)
    public String getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(String origen) {
        this.origen = origen;
    }

    
    @Column(name="NUMERO_CTRL", precision=10, scale=0)
    public Long getNumeroCtrl() {
        return this.numeroCtrl;
    }
    
    public void setNumeroCtrl(Long numeroCtrl) {
        this.numeroCtrl = numeroCtrl;
    }

    
    @Column(name="ANULADO", length=1)
    public String getAnulado() {
        return this.anulado;
    }
    
    public void setAnulado(String anulado) {
        this.anulado = anulado;
    }

    
    @Column(name="USUARIO_ANULA", length=30)
    public String getUsuarioAnula() {
        return this.usuarioAnula;
    }
    
    public void setUsuarioAnula(String usuarioAnula) {
        this.usuarioAnula = usuarioAnula;
    }

    
    @Column(name="MOTIVO_ANULA", length=80)
    public String getMotivoAnula() {
        return this.motivoAnula;
    }
    
    public void setMotivoAnula(String motivoAnula) {
        this.motivoAnula = motivoAnula;
    }

    
    @Column(name="COD_ESTADO", length=2)
    public String getCodEstado() {
        return this.codEstado;
    }
    
    public void setCodEstado(String codEstado) {
        this.codEstado = codEstado;
    }

    
    @Column(name="IND_ESTADO_VENCIDO", length=1)
    public String getIndEstadoVencido() {
        return this.indEstadoVencido;
    }
    
    public void setIndEstadoVencido(String indEstadoVencido) {
        this.indEstadoVencido = indEstadoVencido;
    }

    
    @Column(name="ANO_ANULADO", precision=4, scale=0)
    public Short getAnoAnulado() {
        return this.anoAnulado;
    }
    
    public void setAnoAnulado(Short anoAnulado) {
        this.anoAnulado = anoAnulado;
    }

    
    @Column(name="MES_ANULADO", precision=2, scale=0)
    public Byte getMesAnulado() {
        return this.mesAnulado;
    }
    
    public void setMesAnulado(Byte mesAnulado) {
        this.mesAnulado = mesAnulado;
    }

    
    @Column(name="TOT_DPP", precision=17)
    public BigDecimal getTotDpp() {
        return this.totDpp;
    }
    
    public void setTotDpp(BigDecimal totDpp) {
        this.totDpp = totDpp;
    }

    
    @Column(name="MONEDA_FISICO", length=1)
    public String getMonedaFisico() {
        return this.monedaFisico;
    }
    
    public void setMonedaFisico(String monedaFisico) {
        this.monedaFisico = monedaFisico;
    }

    
    @Column(name="MONTO_FISICO", precision=17)
    public BigDecimal getMontoFisico() {
        return this.montoFisico;
    }
    
    public void setMontoFisico(BigDecimal montoFisico) {
        this.montoFisico = montoFisico;
    }

    
    @Column(name="TOT_IMP", precision=17)
    public BigDecimal getTotImp() {
        return this.totImp;
    }
    
    public void setTotImp(BigDecimal totImp) {
        this.totImp = totImp;
    }

    
    @Column(name="TOT_RET", precision=17)
    public BigDecimal getTotRet() {
        return this.totRet;
    }
    
    public void setTotRet(BigDecimal totRet) {
        this.totRet = totRet;
    }

    
    @Column(name="TOT_IMP_ESPECIAL", precision=17)
    public BigDecimal getTotImpEspecial() {
        return this.totImpEspecial;
    }
    
    public void setTotImpEspecial(BigDecimal totImpEspecial) {
        this.totImpEspecial = totImpEspecial;
    }

    
    @Column(name="COD_DIARIO", length=5)
    public String getCodDiario() {
        return this.codDiario;
    }
    
    public void setCodDiario(String codDiario) {
        this.codDiario = codDiario;
    }

    
    @Column(name="PORCT_IMP", precision=17)
    public BigDecimal getPorctImp() {
        return this.porctImp;
    }
    
    public void setPorctImp(BigDecimal porctImp) {
        this.porctImp = porctImp;
    }

    
    @Column(name="COMP_RET_IVA", length=15)
    public String getCompRetIva() {
        return this.compRetIva;
    }
    
    public void setCompRetIva(String compRetIva) {
        this.compRetIva = compRetIva;
    }

    
    @Column(name="NUM_RET_IVA", length=15)
    public String getNumRetIva() {
        return this.numRetIva;
    }
    
    public void setNumRetIva(String numRetIva) {
        this.numRetIva = numRetIva;
    }

    
    @Column(name="MES_RET", length=3)
    public String getMesRet() {
        return this.mesRet;
    }
    
    public void setMesRet(String mesRet) {
        this.mesRet = mesRet;
    }

    
    @Column(name="ANO_RET", length=5)
    public String getAnoRet() {
        return this.anoRet;
    }
    
    public void setAnoRet(String anoRet) {
        this.anoRet = anoRet;
    }

    
    @Column(name="PORC_RET_IVA", precision=17)
    public BigDecimal getPorcRetIva() {
        return this.porcRetIva;
    }
    
    public void setPorcRetIva(BigDecimal porcRetIva) {
        this.porcRetIva = porcRetIva;
    }

    
    @Column(name="MONT_RET_IVA", precision=17)
    public BigDecimal getMontRetIva() {
        return this.montRetIva;
    }
    
    public void setMontRetIva(BigDecimal montRetIva) {
        this.montRetIva = montRetIva;
    }

    
    @Column(name="ST_RET_IVA", length=1)
    public String getStRetIva() {
        return this.stRetIva;
    }
    
    public void setStRetIva(String stRetIva) {
        this.stRetIva = stRetIva;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_RI", length=7)
    public Date getFechaRi() {
        return this.fechaRi;
    }
    
    public void setFechaRi(Date fechaRi) {
        this.fechaRi = fechaRi;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_TC", length=7)
    public Date getFechaTc() {
        return this.fechaTc;
    }
    
    public void setFechaTc(Date fechaTc) {
        this.fechaTc = fechaTc;
    }

    
    @Column(name="ST_RET_DECL", length=1)
    public String getStRetDecl() {
        return this.stRetDecl;
    }
    
    public void setStRetDecl(String stRetDecl) {
        this.stRetDecl = stRetDecl;
    }

    
    @Column(name="TEMP_SALD", precision=17)
    public BigDecimal getTempSald() {
        return this.tempSald;
    }
    
    public void setTempSald(BigDecimal tempSald) {
        this.tempSald = tempSald;
    }

    
    @Column(name="NRO", precision=17, scale=0)
    public Long getNro() {
        return this.nro;
    }
    
    public void setNro(Long nro) {
        this.nro = nro;
    }

    
    @Column(name="SUBTOTAL_RES", precision=30)
    public BigDecimal getSubtotalRes() {
        return this.subtotalRes;
    }
    
    public void setSubtotalRes(BigDecimal subtotalRes) {
        this.subtotalRes = subtotalRes;
    }

    
    @Column(name="MONTO_RES", precision=30)
    public BigDecimal getMontoRes() {
        return this.montoRes;
    }
    
    public void setMontoRes(BigDecimal montoRes) {
        this.montoRes = montoRes;
    }

    
    @Column(name="SALDO_RES", precision=30)
    public BigDecimal getSaldoRes() {
        return this.saldoRes;
    }
    
    public void setSaldoRes(BigDecimal saldoRes) {
        this.saldoRes = saldoRes;
    }

    
    @Column(name="GRAVADO_RES", precision=30)
    public BigDecimal getGravadoRes() {
        return this.gravadoRes;
    }
    
    public void setGravadoRes(BigDecimal gravadoRes) {
        this.gravadoRes = gravadoRes;
    }

    
    @Column(name="EXCENTOS_RES", precision=30)
    public BigDecimal getExcentosRes() {
        return this.excentosRes;
    }
    
    public void setExcentosRes(BigDecimal excentosRes) {
        this.excentosRes = excentosRes;
    }

    
    @Column(name="DESCUENTO_RES", precision=30)
    public BigDecimal getDescuentoRes() {
        return this.descuentoRes;
    }
    
    public void setDescuentoRes(BigDecimal descuentoRes) {
        this.descuentoRes = descuentoRes;
    }

    
    @Column(name="TOT_REFER_RES", precision=30)
    public BigDecimal getTotReferRes() {
        return this.totReferRes;
    }
    
    public void setTotReferRes(BigDecimal totReferRes) {
        this.totReferRes = totReferRes;
    }

    
    @Column(name="TOT_DB_RES", precision=30)
    public BigDecimal getTotDbRes() {
        return this.totDbRes;
    }
    
    public void setTotDbRes(BigDecimal totDbRes) {
        this.totDbRes = totDbRes;
    }

    
    @Column(name="TOT_CR_RES", precision=30)
    public BigDecimal getTotCrRes() {
        return this.totCrRes;
    }
    
    public void setTotCrRes(BigDecimal totCrRes) {
        this.totCrRes = totCrRes;
    }

    
    @Column(name="MONTO_FISICO_RES", precision=30)
    public BigDecimal getMontoFisicoRes() {
        return this.montoFisicoRes;
    }
    
    public void setMontoFisicoRes(BigDecimal montoFisicoRes) {
        this.montoFisicoRes = montoFisicoRes;
    }

    
    @Column(name="TOT_IMP_RES", precision=30)
    public BigDecimal getTotImpRes() {
        return this.totImpRes;
    }
    
    public void setTotImpRes(BigDecimal totImpRes) {
        this.totImpRes = totImpRes;
    }

    
    @Column(name="TOT_RET_RES", precision=30)
    public BigDecimal getTotRetRes() {
        return this.totRetRes;
    }
    
    public void setTotRetRes(BigDecimal totRetRes) {
        this.totRetRes = totRetRes;
    }

    
    @Column(name="MONT_RET_IVA_RES", precision=30)
    public BigDecimal getMontRetIvaRes() {
        return this.montRetIvaRes;
    }
    
    public void setMontRetIvaRes(BigDecimal montRetIvaRes) {
        this.montRetIvaRes = montRetIvaRes;
    }

    
    @Column(name="TEMP_SALD_RES", precision=30)
    public BigDecimal getTempSaldRes() {
        return this.tempSaldRes;
    }
    
    public void setTempSaldRes(BigDecimal tempSaldRes) {
        this.tempSaldRes = tempSaldRes;
    }




}


