package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arcpgr generated by hbm2java
 */
@Entity
@Table(name="ARCPGR"
    ,schema="DESA46"
)
public class Arcpgr  implements java.io.Serializable {


     private ArcpgrId id;
     private String moneda;
     private String descripcion;
     private String ctaProve;
     private String ctaDpp;
     private String centroProve;
     private String centroDpp;
     private String centroRetiva;
     private String ctaRetiva;

    public Arcpgr() {
    }

	
    public Arcpgr(ArcpgrId id) {
        this.id = id;
    }
    public Arcpgr(ArcpgrId id, String moneda, String descripcion, String ctaProve, String ctaDpp, String centroProve, String centroDpp, String centroRetiva, String ctaRetiva) {
       this.id = id;
       this.moneda = moneda;
       this.descripcion = descripcion;
       this.ctaProve = ctaProve;
       this.ctaDpp = ctaDpp;
       this.centroProve = centroProve;
       this.centroDpp = centroDpp;
       this.centroRetiva = centroRetiva;
       this.ctaRetiva = ctaRetiva;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="grupo", column=@Column(name="GRUPO", nullable=false, length=2) ) } )
    public ArcpgrId getId() {
        return this.id;
    }
    
    public void setId(ArcpgrId id) {
        this.id = id;
    }

    
    @Column(name="MONEDA", length=1)
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }

    
    @Column(name="DESCRIPCION", length=25)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="CTA_PROVE", length=15)
    public String getCtaProve() {
        return this.ctaProve;
    }
    
    public void setCtaProve(String ctaProve) {
        this.ctaProve = ctaProve;
    }

    
    @Column(name="CTA_DPP", length=15)
    public String getCtaDpp() {
        return this.ctaDpp;
    }
    
    public void setCtaDpp(String ctaDpp) {
        this.ctaDpp = ctaDpp;
    }

    
    @Column(name="CENTRO_PROVE", length=9)
    public String getCentroProve() {
        return this.centroProve;
    }
    
    public void setCentroProve(String centroProve) {
        this.centroProve = centroProve;
    }

    
    @Column(name="CENTRO_DPP", length=9)
    public String getCentroDpp() {
        return this.centroDpp;
    }
    
    public void setCentroDpp(String centroDpp) {
        this.centroDpp = centroDpp;
    }

    
    @Column(name="CENTRO_RETIVA", length=9)
    public String getCentroRetiva() {
        return this.centroRetiva;
    }
    
    public void setCentroRetiva(String centroRetiva) {
        this.centroRetiva = centroRetiva;
    }

    
    @Column(name="CTA_RETIVA", length=9)
    public String getCtaRetiva() {
        return this.ctaRetiva;
    }
    
    public void setCtaRetiva(String ctaRetiva) {
        this.ctaRetiva = ctaRetiva;
    }




}


