package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArcppretId generated by hbm2java
 */
@Embeddable
public class ArcppretId  implements java.io.Serializable {


     private String clave;
     private String condicionTributaria;
     private BigDecimal desdePago;
     private BigDecimal hastaPago;

    public ArcppretId() {
    }

    public ArcppretId(String clave, String condicionTributaria, BigDecimal desdePago, BigDecimal hastaPago) {
       this.clave = clave;
       this.condicionTributaria = condicionTributaria;
       this.desdePago = desdePago;
       this.hastaPago = hastaPago;
    }
   


    @Column(name="CLAVE", nullable=false, length=2)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }


    @Column(name="CONDICION_TRIBUTARIA", nullable=false, length=3)
    public String getCondicionTributaria() {
        return this.condicionTributaria;
    }
    
    public void setCondicionTributaria(String condicionTributaria) {
        this.condicionTributaria = condicionTributaria;
    }


    @Column(name="DESDE_PAGO", nullable=false)
    public BigDecimal getDesdePago() {
        return this.desdePago;
    }
    
    public void setDesdePago(BigDecimal desdePago) {
        this.desdePago = desdePago;
    }


    @Column(name="HASTA_PAGO", nullable=false)
    public BigDecimal getHastaPago() {
        return this.hastaPago;
    }
    
    public void setHastaPago(BigDecimal hastaPago) {
        this.hastaPago = hastaPago;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArcppretId) ) return false;
		 ArcppretId castOther = ( ArcppretId ) other; 
         
		 return ( (this.getClave()==castOther.getClave()) || ( this.getClave()!=null && castOther.getClave()!=null && this.getClave().equals(castOther.getClave()) ) )
 && ( (this.getCondicionTributaria()==castOther.getCondicionTributaria()) || ( this.getCondicionTributaria()!=null && castOther.getCondicionTributaria()!=null && this.getCondicionTributaria().equals(castOther.getCondicionTributaria()) ) )
 && ( (this.getDesdePago()==castOther.getDesdePago()) || ( this.getDesdePago()!=null && castOther.getDesdePago()!=null && this.getDesdePago().equals(castOther.getDesdePago()) ) )
 && ( (this.getHastaPago()==castOther.getHastaPago()) || ( this.getHastaPago()!=null && castOther.getHastaPago()!=null && this.getHastaPago().equals(castOther.getHastaPago()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getClave() == null ? 0 : this.getClave().hashCode() );
         result = 37 * result + ( getCondicionTributaria() == null ? 0 : this.getCondicionTributaria().hashCode() );
         result = 37 * result + ( getDesdePago() == null ? 0 : this.getDesdePago().hashCode() );
         result = 37 * result + ( getHastaPago() == null ? 0 : this.getHastaPago().hashCode() );
         return result;
   }   


}


