package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arcpretap generated by hbm2java
 */
@Entity
@Table(name="ARCPRETAP"
    ,schema="DESA46"
)
public class Arcpretap  implements java.io.Serializable {


     private ArcpretapId id;
     private String noProve;
     private BigDecimal montoRetenido;
     private Date fecha;
     private BigDecimal tipoCambio;
     private String pagado;
     private String noDocuPago;
     private BigDecimal montoRetenidoRes;

    public Arcpretap() {
    }

	
    public Arcpretap(ArcpretapId id) {
        this.id = id;
    }
    public Arcpretap(ArcpretapId id, String noProve, BigDecimal montoRetenido, Date fecha, BigDecimal tipoCambio, String pagado, String noDocuPago, BigDecimal montoRetenidoRes) {
       this.id = id;
       this.noProve = noProve;
       this.montoRetenido = montoRetenido;
       this.fecha = fecha;
       this.tipoCambio = tipoCambio;
       this.pagado = pagado;
       this.noDocuPago = noDocuPago;
       this.montoRetenidoRes = montoRetenidoRes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noDocu", column=@Column(name="NO_DOCU", nullable=false, length=8) ), 
        @AttributeOverride(name="noRefe", column=@Column(name="NO_REFE", nullable=false, length=8) ), 
        @AttributeOverride(name="clave", column=@Column(name="CLAVE", nullable=false, length=2) ) } )
    public ArcpretapId getId() {
        return this.id;
    }
    
    public void setId(ArcpretapId id) {
        this.id = id;
    }

    
    @Column(name="NO_PROVE", length=15)
    public String getNoProve() {
        return this.noProve;
    }
    
    public void setNoProve(String noProve) {
        this.noProve = noProve;
    }

    
    @Column(name="MONTO_RETENIDO", precision=17)
    public BigDecimal getMontoRetenido() {
        return this.montoRetenido;
    }
    
    public void setMontoRetenido(BigDecimal montoRetenido) {
        this.montoRetenido = montoRetenido;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", length=7)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="TIPO_CAMBIO", precision=17, scale=4)
    public BigDecimal getTipoCambio() {
        return this.tipoCambio;
    }
    
    public void setTipoCambio(BigDecimal tipoCambio) {
        this.tipoCambio = tipoCambio;
    }

    
    @Column(name="PAGADO", length=1)
    public String getPagado() {
        return this.pagado;
    }
    
    public void setPagado(String pagado) {
        this.pagado = pagado;
    }

    
    @Column(name="NO_DOCU_PAGO", length=8)
    public String getNoDocuPago() {
        return this.noDocuPago;
    }
    
    public void setNoDocuPago(String noDocuPago) {
        this.noDocuPago = noDocuPago;
    }

    
    @Column(name="MONTO_RETENIDO_RES", precision=30)
    public BigDecimal getMontoRetenidoRes() {
        return this.montoRetenidoRes;
    }
    
    public void setMontoRetenidoRes(BigDecimal montoRetenidoRes) {
        this.montoRetenidoRes = montoRetenidoRes;
    }




}


