package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arcptd generated by hbm2java
 */
@Entity
@Table(name="ARCPTD"
    ,schema="DESA46"
)
public class Arcptd  implements java.io.Serializable {


     private ArcptdId id;
     private String descripcion;
     private String tipoMov;
     private String documento;
     private String afectaLibro;
     private String aceptaImpuestos;
     private String aceptaRetenciones;
     private String formularioCtrl;
     private String codDiario;
     private String comportamientoImp;
     private String tipoRetIva;
     private String modulo;

    public Arcptd() {
    }

	
    public Arcptd(ArcptdId id) {
        this.id = id;
    }
    public Arcptd(ArcptdId id, String descripcion, String tipoMov, String documento, String afectaLibro, String aceptaImpuestos, String aceptaRetenciones, String formularioCtrl, String codDiario, String comportamientoImp, String tipoRetIva, String modulo) {
       this.id = id;
       this.descripcion = descripcion;
       this.tipoMov = tipoMov;
       this.documento = documento;
       this.afectaLibro = afectaLibro;
       this.aceptaImpuestos = aceptaImpuestos;
       this.aceptaRetenciones = aceptaRetenciones;
       this.formularioCtrl = formularioCtrl;
       this.codDiario = codDiario;
       this.comportamientoImp = comportamientoImp;
       this.tipoRetIva = tipoRetIva;
       this.modulo = modulo;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="tipoDoc", column=@Column(name="TIPO_DOC", nullable=false, length=2) ) } )
    public ArcptdId getId() {
        return this.id;
    }
    
    public void setId(ArcptdId id) {
        this.id = id;
    }

    
    @Column(name="DESCRIPCION", length=30)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="TIPO_MOV", length=1)
    public String getTipoMov() {
        return this.tipoMov;
    }
    
    public void setTipoMov(String tipoMov) {
        this.tipoMov = tipoMov;
    }

    
    @Column(name="DOCUMENTO", length=1)
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }

    
    @Column(name="AFECTA_LIBRO", length=1)
    public String getAfectaLibro() {
        return this.afectaLibro;
    }
    
    public void setAfectaLibro(String afectaLibro) {
        this.afectaLibro = afectaLibro;
    }

    
    @Column(name="ACEPTA_IMPUESTOS", length=1)
    public String getAceptaImpuestos() {
        return this.aceptaImpuestos;
    }
    
    public void setAceptaImpuestos(String aceptaImpuestos) {
        this.aceptaImpuestos = aceptaImpuestos;
    }

    
    @Column(name="ACEPTA_RETENCIONES", length=1)
    public String getAceptaRetenciones() {
        return this.aceptaRetenciones;
    }
    
    public void setAceptaRetenciones(String aceptaRetenciones) {
        this.aceptaRetenciones = aceptaRetenciones;
    }

    
    @Column(name="FORMULARIO_CTRL", length=10)
    public String getFormularioCtrl() {
        return this.formularioCtrl;
    }
    
    public void setFormularioCtrl(String formularioCtrl) {
        this.formularioCtrl = formularioCtrl;
    }

    
    @Column(name="COD_DIARIO", length=5)
    public String getCodDiario() {
        return this.codDiario;
    }
    
    public void setCodDiario(String codDiario) {
        this.codDiario = codDiario;
    }

    
    @Column(name="COMPORTAMIENTO_IMP", length=1)
    public String getComportamientoImp() {
        return this.comportamientoImp;
    }
    
    public void setComportamientoImp(String comportamientoImp) {
        this.comportamientoImp = comportamientoImp;
    }

    
    @Column(name="TIPO_RET_IVA", length=2)
    public String getTipoRetIva() {
        return this.tipoRetIva;
    }
    
    public void setTipoRetIva(String tipoRetIva) {
        this.tipoRetIva = tipoRetIva;
    }

    
    @Column(name="MODULO", length=10)
    public String getModulo() {
        return this.modulo;
    }
    
    public void setModulo(String modulo) {
        this.modulo = modulo;
    }




}


