package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arcppret generated by hbm2java
 */
@Entity
@Table(name="ARCPPRET"
    ,schema="DESA46"
)
public class Arcppret  implements java.io.Serializable {


     private ArcppretId id;
     private BigDecimal baseImponible;
     private BigDecimal porcentaje;
     private BigDecimal sustraendo;

    public Arcppret() {
    }

	
    public Arcppret(ArcppretId id) {
        this.id = id;
    }
    public Arcppret(ArcppretId id, BigDecimal baseImponible, BigDecimal porcentaje, BigDecimal sustraendo) {
       this.id = id;
       this.baseImponible = baseImponible;
       this.porcentaje = porcentaje;
       this.sustraendo = sustraendo;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="clave", column=@Column(name="CLAVE", nullable=false, length=2) ), 
        @AttributeOverride(name="condicionTributaria", column=@Column(name="CONDICION_TRIBUTARIA", nullable=false, length=3) ), 
        @AttributeOverride(name="desdePago", column=@Column(name="DESDE_PAGO", nullable=false) ), 
        @AttributeOverride(name="hastaPago", column=@Column(name="HASTA_PAGO", nullable=false) ) } )
    public ArcppretId getId() {
        return this.id;
    }
    
    public void setId(ArcppretId id) {
        this.id = id;
    }

    
    @Column(name="BASE_IMPONIBLE", precision=5)
    public BigDecimal getBaseImponible() {
        return this.baseImponible;
    }
    
    public void setBaseImponible(BigDecimal baseImponible) {
        this.baseImponible = baseImponible;
    }

    
    @Column(name="PORCENTAJE", precision=5)
    public BigDecimal getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(BigDecimal porcentaje) {
        this.porcentaje = porcentaje;
    }

    
    @Column(name="SUSTRAENDO")
    public BigDecimal getSustraendo() {
        return this.sustraendo;
    }
    
    public void setSustraendo(BigDecimal sustraendo) {
        this.sustraendo = sustraendo;
    }




}


