package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arcpsa generated by hbm2java
 */
@Entity
@Table(name="ARCPSA"
    ,schema="DESA46"
)
public class Arcpsa  implements java.io.Serializable {


     private ArcpsaId id;
     private BigDecimal saldoAnt;
     private BigDecimal debitos;
     private BigDecimal creditos;
     private BigDecimal saldoAntRes;
     private BigDecimal debitosRes;
     private BigDecimal creditosRes;

    public Arcpsa() {
    }

	
    public Arcpsa(ArcpsaId id) {
        this.id = id;
    }
    public Arcpsa(ArcpsaId id, BigDecimal saldoAnt, BigDecimal debitos, BigDecimal creditos, BigDecimal saldoAntRes, BigDecimal debitosRes, BigDecimal creditosRes) {
       this.id = id;
       this.saldoAnt = saldoAnt;
       this.debitos = debitos;
       this.creditos = creditos;
       this.saldoAntRes = saldoAntRes;
       this.debitosRes = debitosRes;
       this.creditosRes = creditosRes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noProve", column=@Column(name="NO_PROVE", nullable=false, length=15) ), 
        @AttributeOverride(name="ano", column=@Column(name="ANO", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="mes", column=@Column(name="MES", nullable=false, precision=2, scale=0) ) } )
    public ArcpsaId getId() {
        return this.id;
    }
    
    public void setId(ArcpsaId id) {
        this.id = id;
    }

    
    @Column(name="SALDO_ANT", precision=17)
    public BigDecimal getSaldoAnt() {
        return this.saldoAnt;
    }
    
    public void setSaldoAnt(BigDecimal saldoAnt) {
        this.saldoAnt = saldoAnt;
    }

    
    @Column(name="DEBITOS", precision=17)
    public BigDecimal getDebitos() {
        return this.debitos;
    }
    
    public void setDebitos(BigDecimal debitos) {
        this.debitos = debitos;
    }

    
    @Column(name="CREDITOS", precision=17)
    public BigDecimal getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(BigDecimal creditos) {
        this.creditos = creditos;
    }

    
    @Column(name="SALDO_ANT_RES", precision=30)
    public BigDecimal getSaldoAntRes() {
        return this.saldoAntRes;
    }
    
    public void setSaldoAntRes(BigDecimal saldoAntRes) {
        this.saldoAntRes = saldoAntRes;
    }

    
    @Column(name="DEBITOS_RES", precision=30)
    public BigDecimal getDebitosRes() {
        return this.debitosRes;
    }
    
    public void setDebitosRes(BigDecimal debitosRes) {
        this.debitosRes = debitosRes;
    }

    
    @Column(name="CREDITOS_RES", precision=30)
    public BigDecimal getCreditosRes() {
        return this.creditosRes;
    }
    
    public void setCreditosRes(BigDecimal creditosRes) {
        this.creditosRes = creditosRes;
    }




}


