package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arcpcbp generated by hbm2java
 */
@Entity
@Table(name="ARCPCBP"
    ,schema="DESA46"
)
public class Arcpcbp  implements java.io.Serializable {


     private ArcpcbpId id;

    public Arcpcbp() {
    }

    public Arcpcbp(ArcpcbpId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noProve", column=@Column(name="NO_PROVE", nullable=false, length=15) ), 
        @AttributeOverride(name="banco", column=@Column(name="BANCO", nullable=false, length=2) ), 
        @AttributeOverride(name="ctaBancaria", column=@Column(name="CTA_BANCARIA", nullable=false, length=20) ) } )
    public ArcpcbpId getId() {
        return this.id;
    }
    
    public void setId(ArcpcbpId id) {
        this.id = id;
    }




}


