package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arcprd generated by hbm2java
 */
@Entity
@Table(name="ARCPRD"
    ,schema="DESA46"
)
public class Arcprd  implements java.io.Serializable {


     private ArcprdId id;
     private BigDecimal monto;
     private BigDecimal descuentoPp;
     private String procedencia;
     private BigDecimal difCambiario;
     private BigDecimal montoRes;

    public Arcprd() {
    }

	
    public Arcprd(ArcprdId id) {
        this.id = id;
    }
    public Arcprd(ArcprdId id, BigDecimal monto, BigDecimal descuentoPp, String procedencia, BigDecimal difCambiario, BigDecimal montoRes) {
       this.id = id;
       this.monto = monto;
       this.descuentoPp = descuentoPp;
       this.procedencia = procedencia;
       this.difCambiario = difCambiario;
       this.montoRes = montoRes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noProve", column=@Column(name="NO_PROVE", nullable=false, length=15) ), 
        @AttributeOverride(name="tipoDoc", column=@Column(name="TIPO_DOC", nullable=false, length=2) ), 
        @AttributeOverride(name="noDocu", column=@Column(name="NO_DOCU", nullable=false, length=8) ), 
        @AttributeOverride(name="tipoRefe", column=@Column(name="TIPO_REFE", nullable=false, length=2) ), 
        @AttributeOverride(name="noRefe", column=@Column(name="NO_REFE", nullable=false, length=8) ) } )
    public ArcprdId getId() {
        return this.id;
    }
    
    public void setId(ArcprdId id) {
        this.id = id;
    }

    
    @Column(name="MONTO", precision=17)
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

    
    @Column(name="DESCUENTO_PP", precision=17)
    public BigDecimal getDescuentoPp() {
        return this.descuentoPp;
    }
    
    public void setDescuentoPp(BigDecimal descuentoPp) {
        this.descuentoPp = descuentoPp;
    }

    
    @Column(name="PROCEDENCIA", length=1)
    public String getProcedencia() {
        return this.procedencia;
    }
    
    public void setProcedencia(String procedencia) {
        this.procedencia = procedencia;
    }

    
    @Column(name="DIF_CAMBIARIO", precision=17)
    public BigDecimal getDifCambiario() {
        return this.difCambiario;
    }
    
    public void setDifCambiario(BigDecimal difCambiario) {
        this.difCambiario = difCambiario;
    }

    
    @Column(name="MONTO_RES", precision=30)
    public BigDecimal getMontoRes() {
        return this.montoRes;
    }
    
    public void setMontoRes(BigDecimal montoRes) {
        this.montoRes = montoRes;
    }




}


