package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arcpti generated by hbm2java
 */
@Entity
@Table(name="ARCPTI"
    ,schema="DESA46"
)
public class Arcpti  implements java.io.Serializable {


     private ArcptiId id;
     private BigDecimal porcentaje;
     private BigDecimal monto;
     private String indImpRet;
     private String aplicaCredFiscal;
     private BigDecimal base;
     private String codigoTercero;
     private String comportamiento;
     private String idSec;
     private Date fechaRet;
     private Long noRet;
     private String municipal;
     private String mesRet;
     private BigDecimal montoRes;
     private BigDecimal baseRes;

    public Arcpti() {
    }

	
    public Arcpti(ArcptiId id) {
        this.id = id;
    }
    public Arcpti(ArcptiId id, BigDecimal porcentaje, BigDecimal monto, String indImpRet, String aplicaCredFiscal, BigDecimal base, String codigoTercero, String comportamiento, String idSec, Date fechaRet, Long noRet, String municipal, String mesRet, BigDecimal montoRes, BigDecimal baseRes) {
       this.id = id;
       this.porcentaje = porcentaje;
       this.monto = monto;
       this.indImpRet = indImpRet;
       this.aplicaCredFiscal = aplicaCredFiscal;
       this.base = base;
       this.codigoTercero = codigoTercero;
       this.comportamiento = comportamiento;
       this.idSec = idSec;
       this.fechaRet = fechaRet;
       this.noRet = noRet;
       this.municipal = municipal;
       this.mesRet = mesRet;
       this.montoRes = montoRes;
       this.baseRes = baseRes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noProve", column=@Column(name="NO_PROVE", nullable=false, length=15) ), 
        @AttributeOverride(name="tipoDoc", column=@Column(name="TIPO_DOC", nullable=false, length=2) ), 
        @AttributeOverride(name="noDocu", column=@Column(name="NO_DOCU", nullable=false, length=8) ), 
        @AttributeOverride(name="clave", column=@Column(name="CLAVE", nullable=false, length=2) ), 
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noRefe", column=@Column(name="NO_REFE", nullable=false, length=8) ) } )
    public ArcptiId getId() {
        return this.id;
    }
    
    public void setId(ArcptiId id) {
        this.id = id;
    }

    
    @Column(name="PORCENTAJE", precision=4)
    public BigDecimal getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(BigDecimal porcentaje) {
        this.porcentaje = porcentaje;
    }

    
    @Column(name="MONTO", precision=17)
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

    
    @Column(name="IND_IMP_RET", length=1)
    public String getIndImpRet() {
        return this.indImpRet;
    }
    
    public void setIndImpRet(String indImpRet) {
        this.indImpRet = indImpRet;
    }

    
    @Column(name="APLICA_CRED_FISCAL", length=1)
    public String getAplicaCredFiscal() {
        return this.aplicaCredFiscal;
    }
    
    public void setAplicaCredFiscal(String aplicaCredFiscal) {
        this.aplicaCredFiscal = aplicaCredFiscal;
    }

    
    @Column(name="BASE", precision=17)
    public BigDecimal getBase() {
        return this.base;
    }
    
    public void setBase(BigDecimal base) {
        this.base = base;
    }

    
    @Column(name="CODIGO_TERCERO", length=18)
    public String getCodigoTercero() {
        return this.codigoTercero;
    }
    
    public void setCodigoTercero(String codigoTercero) {
        this.codigoTercero = codigoTercero;
    }

    
    @Column(name="COMPORTAMIENTO", length=1)
    public String getComportamiento() {
        return this.comportamiento;
    }
    
    public void setComportamiento(String comportamiento) {
        this.comportamiento = comportamiento;
    }

    
    @Column(name="ID_SEC", length=5)
    public String getIdSec() {
        return this.idSec;
    }
    
    public void setIdSec(String idSec) {
        this.idSec = idSec;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_RET", length=7)
    public Date getFechaRet() {
        return this.fechaRet;
    }
    
    public void setFechaRet(Date fechaRet) {
        this.fechaRet = fechaRet;
    }

    
    @Column(name="NO_RET", precision=10, scale=0)
    public Long getNoRet() {
        return this.noRet;
    }
    
    public void setNoRet(Long noRet) {
        this.noRet = noRet;
    }

    
    @Column(name="MUNICIPAL", length=20)
    public String getMunicipal() {
        return this.municipal;
    }
    
    public void setMunicipal(String municipal) {
        this.municipal = municipal;
    }

    
    @Column(name="MES_RET", length=2)
    public String getMesRet() {
        return this.mesRet;
    }
    
    public void setMesRet(String mesRet) {
        this.mesRet = mesRet;
    }

    
    @Column(name="MONTO_RES", precision=30)
    public BigDecimal getMontoRes() {
        return this.montoRes;
    }
    
    public void setMontoRes(BigDecimal montoRes) {
        this.montoRes = montoRes;
    }

    
    @Column(name="BASE_RES", precision=30)
    public BigDecimal getBaseRes() {
        return this.baseRes;
    }
    
    public void setBaseRes(BigDecimal baseRes) {
        this.baseRes = baseRes;
    }




}


