package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ArfagrCt generated by hbm2java
 */
@Entity
@Table(name="ARFAGR_CT"
    ,schema="DESA46"
)
public class ArfagrCt  implements java.io.Serializable {


     private ArfagrCtId id;
     private String centroCosto;
     private String cuenta;

    public ArfagrCt() {
    }

	
    public ArfagrCt(ArfagrCtId id) {
        this.id = id;
    }
    public ArfagrCt(ArfagrCtId id, String centroCosto, String cuenta) {
       this.id = id;
       this.centroCosto = centroCosto;
       this.cuenta = cuenta;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="tipoDoc", column=@Column(name="TIPO_DOC", nullable=false, length=2) ), 
        @AttributeOverride(name="clase", column=@Column(name="CLASE", nullable=false, length=4) ) } )
    public ArfagrCtId getId() {
        return this.id;
    }
    
    public void setId(ArfagrCtId id) {
        this.id = id;
    }

    
    @Column(name="CENTRO_COSTO", length=9)
    public String getCentroCosto() {
        return this.centroCosto;
    }
    
    public void setCentroCosto(String centroCosto) {
        this.centroCosto = centroCosto;
    }

    
    @Column(name="CUENTA", length=15)
    public String getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }




}


