package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arfaus generated by hbm2java
 */
@Entity
@Table(name="ARFAUS"
    ,schema="DESA46"
)
public class Arfaus  implements java.io.Serializable {


     private ArfausId id;
     private String centro;
     private String centrof;
     private String digFecha;
     private String tipoPrecio;
     private String tipoDoc;
     private String variarTd;
     private String variarTp;
     private String variarPr;
     private String variarPd;
     private String variarPp;
     private String variarFe;
     private String variarVe;
     private String variarBo;
     private String variarCo;
     private String bodega;
     private String vendedor;
     private String variarCentrof;
     private String factSino;
     private String regDevo;

    public Arfaus() {
    }

	
    public Arfaus(ArfausId id) {
        this.id = id;
    }
    public Arfaus(ArfausId id, String centro, String centrof, String digFecha, String tipoPrecio, String tipoDoc, String variarTd, String variarTp, String variarPr, String variarPd, String variarPp, String variarFe, String variarVe, String variarBo, String variarCo, String bodega, String vendedor, String variarCentrof, String factSino, String regDevo) {
       this.id = id;
       this.centro = centro;
       this.centrof = centrof;
       this.digFecha = digFecha;
       this.tipoPrecio = tipoPrecio;
       this.tipoDoc = tipoDoc;
       this.variarTd = variarTd;
       this.variarTp = variarTp;
       this.variarPr = variarPr;
       this.variarPd = variarPd;
       this.variarPp = variarPp;
       this.variarFe = variarFe;
       this.variarVe = variarVe;
       this.variarBo = variarBo;
       this.variarCo = variarCo;
       this.bodega = bodega;
       this.vendedor = vendedor;
       this.variarCentrof = variarCentrof;
       this.factSino = factSino;
       this.regDevo = regDevo;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="usuario", column=@Column(name="USUARIO", nullable=false, length=30) ) } )
    public ArfausId getId() {
        return this.id;
    }
    
    public void setId(ArfausId id) {
        this.id = id;
    }

    
    @Column(name="CENTRO", length=2)
    public String getCentro() {
        return this.centro;
    }
    
    public void setCentro(String centro) {
        this.centro = centro;
    }

    
    @Column(name="CENTROF", length=4)
    public String getCentrof() {
        return this.centrof;
    }
    
    public void setCentrof(String centrof) {
        this.centrof = centrof;
    }

    
    @Column(name="DIG_FECHA", length=1)
    public String getDigFecha() {
        return this.digFecha;
    }
    
    public void setDigFecha(String digFecha) {
        this.digFecha = digFecha;
    }

    
    @Column(name="TIPO_PRECIO", length=2)
    public String getTipoPrecio() {
        return this.tipoPrecio;
    }
    
    public void setTipoPrecio(String tipoPrecio) {
        this.tipoPrecio = tipoPrecio;
    }

    
    @Column(name="TIPO_DOC", length=2)
    public String getTipoDoc() {
        return this.tipoDoc;
    }
    
    public void setTipoDoc(String tipoDoc) {
        this.tipoDoc = tipoDoc;
    }

    
    @Column(name="VARIAR_TD", length=1)
    public String getVariarTd() {
        return this.variarTd;
    }
    
    public void setVariarTd(String variarTd) {
        this.variarTd = variarTd;
    }

    
    @Column(name="VARIAR_TP", length=1)
    public String getVariarTp() {
        return this.variarTp;
    }
    
    public void setVariarTp(String variarTp) {
        this.variarTp = variarTp;
    }

    
    @Column(name="VARIAR_PR", length=1)
    public String getVariarPr() {
        return this.variarPr;
    }
    
    public void setVariarPr(String variarPr) {
        this.variarPr = variarPr;
    }

    
    @Column(name="VARIAR_PD", length=1)
    public String getVariarPd() {
        return this.variarPd;
    }
    
    public void setVariarPd(String variarPd) {
        this.variarPd = variarPd;
    }

    
    @Column(name="VARIAR_PP", length=1)
    public String getVariarPp() {
        return this.variarPp;
    }
    
    public void setVariarPp(String variarPp) {
        this.variarPp = variarPp;
    }

    
    @Column(name="VARIAR_FE", length=1)
    public String getVariarFe() {
        return this.variarFe;
    }
    
    public void setVariarFe(String variarFe) {
        this.variarFe = variarFe;
    }

    
    @Column(name="VARIAR_VE", length=1)
    public String getVariarVe() {
        return this.variarVe;
    }
    
    public void setVariarVe(String variarVe) {
        this.variarVe = variarVe;
    }

    
    @Column(name="VARIAR_BO", length=1)
    public String getVariarBo() {
        return this.variarBo;
    }
    
    public void setVariarBo(String variarBo) {
        this.variarBo = variarBo;
    }

    
    @Column(name="VARIAR_CO", length=1)
    public String getVariarCo() {
        return this.variarCo;
    }
    
    public void setVariarCo(String variarCo) {
        this.variarCo = variarCo;
    }

    
    @Column(name="BODEGA", length=4)
    public String getBodega() {
        return this.bodega;
    }
    
    public void setBodega(String bodega) {
        this.bodega = bodega;
    }

    
    @Column(name="VENDEDOR", length=4)
    public String getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(String vendedor) {
        this.vendedor = vendedor;
    }

    
    @Column(name="VARIAR_CENTROF", length=1)
    public String getVariarCentrof() {
        return this.variarCentrof;
    }
    
    public void setVariarCentrof(String variarCentrof) {
        this.variarCentrof = variarCentrof;
    }

    
    @Column(name="FACT_SINO", length=1)
    public String getFactSino() {
        return this.factSino;
    }
    
    public void setFactSino(String factSino) {
        this.factSino = factSino;
    }

    
    @Column(name="REG_DEVO", length=1)
    public String getRegDevo() {
        return this.regDevo;
    }
    
    public void setRegDevo(String regDevo) {
        this.regDevo = regDevo;
    }




}


