package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arfafli generated by hbm2java
 */
@Entity
@Table(name="ARFAFLI"
    ,schema="DESA46"
)
public class Arfafli  implements java.io.Serializable {


     private ArfafliId id;
     private String tipoDoc;
     private BigDecimal porcImp;
     private BigDecimal montoImp;
     private String columna;
     private BigDecimal base;
     private String codigoTercero;
     private String comportamiento;
     private String aplicaCredFiscal;
     private String idSec;
     private String claveImpRed;
     private BigDecimal porcImpRed;
     private BigDecimal montoImpRed;
     private BigDecimal montoImpOrg;
     private BigDecimal porcImpOrg;
     private BigDecimal montoImpRes;
     private BigDecimal baseRes;
     private BigDecimal montoImpRedRes;

    public Arfafli() {
    }

	
    public Arfafli(ArfafliId id) {
        this.id = id;
    }
    public Arfafli(ArfafliId id, String tipoDoc, BigDecimal porcImp, BigDecimal montoImp, String columna, BigDecimal base, String codigoTercero, String comportamiento, String aplicaCredFiscal, String idSec, String claveImpRed, BigDecimal porcImpRed, BigDecimal montoImpRed, BigDecimal montoImpOrg, BigDecimal porcImpOrg, BigDecimal montoImpRes, BigDecimal baseRes, BigDecimal montoImpRedRes) {
       this.id = id;
       this.tipoDoc = tipoDoc;
       this.porcImp = porcImp;
       this.montoImp = montoImp;
       this.columna = columna;
       this.base = base;
       this.codigoTercero = codigoTercero;
       this.comportamiento = comportamiento;
       this.aplicaCredFiscal = aplicaCredFiscal;
       this.idSec = idSec;
       this.claveImpRed = claveImpRed;
       this.porcImpRed = porcImpRed;
       this.montoImpRed = montoImpRed;
       this.montoImpOrg = montoImpOrg;
       this.porcImpOrg = porcImpOrg;
       this.montoImpRes = montoImpRes;
       this.baseRes = baseRes;
       this.montoImpRedRes = montoImpRedRes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noFactu", column=@Column(name="NO_FACTU", nullable=false, length=12) ), 
        @AttributeOverride(name="noLinea", column=@Column(name="NO_LINEA", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="clave", column=@Column(name="CLAVE", nullable=false, length=2) ) } )
    public ArfafliId getId() {
        return this.id;
    }
    
    public void setId(ArfafliId id) {
        this.id = id;
    }

    
    @Column(name="TIPO_DOC", length=2)
    public String getTipoDoc() {
        return this.tipoDoc;
    }
    
    public void setTipoDoc(String tipoDoc) {
        this.tipoDoc = tipoDoc;
    }

    
    @Column(name="PORC_IMP", precision=4)
    public BigDecimal getPorcImp() {
        return this.porcImp;
    }
    
    public void setPorcImp(BigDecimal porcImp) {
        this.porcImp = porcImp;
    }

    
    @Column(name="MONTO_IMP", precision=17)
    public BigDecimal getMontoImp() {
        return this.montoImp;
    }
    
    public void setMontoImp(BigDecimal montoImp) {
        this.montoImp = montoImp;
    }

    
    @Column(name="COLUMNA", length=1)
    public String getColumna() {
        return this.columna;
    }
    
    public void setColumna(String columna) {
        this.columna = columna;
    }

    
    @Column(name="BASE", precision=17)
    public BigDecimal getBase() {
        return this.base;
    }
    
    public void setBase(BigDecimal base) {
        this.base = base;
    }

    
    @Column(name="CODIGO_TERCERO", length=18)
    public String getCodigoTercero() {
        return this.codigoTercero;
    }
    
    public void setCodigoTercero(String codigoTercero) {
        this.codigoTercero = codigoTercero;
    }

    
    @Column(name="COMPORTAMIENTO", length=1)
    public String getComportamiento() {
        return this.comportamiento;
    }
    
    public void setComportamiento(String comportamiento) {
        this.comportamiento = comportamiento;
    }

    
    @Column(name="APLICA_CRED_FISCAL", length=1)
    public String getAplicaCredFiscal() {
        return this.aplicaCredFiscal;
    }
    
    public void setAplicaCredFiscal(String aplicaCredFiscal) {
        this.aplicaCredFiscal = aplicaCredFiscal;
    }

    
    @Column(name="ID_SEC", length=5)
    public String getIdSec() {
        return this.idSec;
    }
    
    public void setIdSec(String idSec) {
        this.idSec = idSec;
    }

    
    @Column(name="CLAVE_IMP_RED", length=2)
    public String getClaveImpRed() {
        return this.claveImpRed;
    }
    
    public void setClaveImpRed(String claveImpRed) {
        this.claveImpRed = claveImpRed;
    }

    
    @Column(name="PORC_IMP_RED", precision=4)
    public BigDecimal getPorcImpRed() {
        return this.porcImpRed;
    }
    
    public void setPorcImpRed(BigDecimal porcImpRed) {
        this.porcImpRed = porcImpRed;
    }

    
    @Column(name="MONTO_IMP_RED", precision=17)
    public BigDecimal getMontoImpRed() {
        return this.montoImpRed;
    }
    
    public void setMontoImpRed(BigDecimal montoImpRed) {
        this.montoImpRed = montoImpRed;
    }

    
    @Column(name="MONTO_IMP_ORG", precision=17)
    public BigDecimal getMontoImpOrg() {
        return this.montoImpOrg;
    }
    
    public void setMontoImpOrg(BigDecimal montoImpOrg) {
        this.montoImpOrg = montoImpOrg;
    }

    
    @Column(name="PORC_IMP_ORG", precision=4)
    public BigDecimal getPorcImpOrg() {
        return this.porcImpOrg;
    }
    
    public void setPorcImpOrg(BigDecimal porcImpOrg) {
        this.porcImpOrg = porcImpOrg;
    }

    
    @Column(name="MONTO_IMP_RES", precision=30)
    public BigDecimal getMontoImpRes() {
        return this.montoImpRes;
    }
    
    public void setMontoImpRes(BigDecimal montoImpRes) {
        this.montoImpRes = montoImpRes;
    }

    
    @Column(name="BASE_RES", precision=30)
    public BigDecimal getBaseRes() {
        return this.baseRes;
    }
    
    public void setBaseRes(BigDecimal baseRes) {
        this.baseRes = baseRes;
    }

    
    @Column(name="MONTO_IMP_RED_RES", precision=30)
    public BigDecimal getMontoImpRedRes() {
        return this.montoImpRedRes;
    }
    
    public void setMontoImpRedRes(BigDecimal montoImpRedRes) {
        this.montoImpRedRes = montoImpRedRes;
    }




}


