package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ArfaflTa generated by hbm2java
 */
@Entity
@Table(name="ARFAFL_TA"
    ,schema="DESA46"
)
public class ArfaflTa  implements java.io.Serializable {


     private ArfaflTaId id;
     private BigDecimal cantidad;
     private BigDecimal cantDev;

    public ArfaflTa() {
    }

	
    public ArfaflTa(ArfaflTaId id) {
        this.id = id;
    }
    public ArfaflTa(ArfaflTaId id, BigDecimal cantidad, BigDecimal cantDev) {
       this.id = id;
       this.cantidad = cantidad;
       this.cantDev = cantDev;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noFactu", column=@Column(name="NO_FACTU", nullable=false, length=12) ), 
        @AttributeOverride(name="noLinea", column=@Column(name="NO_LINEA", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="talla", column=@Column(name="TALLA", nullable=false, precision=4, scale=1) ) } )
    public ArfaflTaId getId() {
        return this.id;
    }
    
    public void setId(ArfaflTaId id) {
        this.id = id;
    }

    
    @Column(name="CANTIDAD", precision=8)
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="CANT_DEV", precision=8)
    public BigDecimal getCantDev() {
        return this.cantDev;
    }
    
    public void setCantDev(BigDecimal cantDev) {
        this.cantDev = cantDev;
    }




}


