package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ArfaflcTah generated by hbm2java
 */
@Entity
@Table(name="ARFAFLC_TAH"
    ,schema="DESA46"
)
public class ArfaflcTah  implements java.io.Serializable {


     private ArfaflcTahId id;
     private BigDecimal cantidad;
     private BigDecimal cantAprobada;
     private BigDecimal cantFacturada;

    public ArfaflcTah() {
    }

	
    public ArfaflcTah(ArfaflcTahId id) {
        this.id = id;
    }
    public ArfaflcTah(ArfaflcTahId id, BigDecimal cantidad, BigDecimal cantAprobada, BigDecimal cantFacturada) {
       this.id = id;
       this.cantidad = cantidad;
       this.cantAprobada = cantAprobada;
       this.cantFacturada = cantFacturada;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", length=2) ), 
        @AttributeOverride(name="noFactu", column=@Column(name="NO_FACTU", length=19) ), 
        @AttributeOverride(name="noLinea", column=@Column(name="NO_LINEA", precision=5, scale=0) ), 
        @AttributeOverride(name="talla", column=@Column(name="TALLA", precision=4, scale=1) ) } )
    public ArfaflcTahId getId() {
        return this.id;
    }
    
    public void setId(ArfaflcTahId id) {
        this.id = id;
    }

    
    @Column(name="CANTIDAD", precision=8)
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="CANT_APROBADA", precision=8)
    public BigDecimal getCantAprobada() {
        return this.cantAprobada;
    }
    
    public void setCantAprobada(BigDecimal cantAprobada) {
        this.cantAprobada = cantAprobada;
    }

    
    @Column(name="CANT_FACTURADA", precision=8)
    public BigDecimal getCantFacturada() {
        return this.cantFacturada;
    }
    
    public void setCantFacturada(BigDecimal cantFacturada) {
        this.cantFacturada = cantFacturada;
    }




}


