package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arfaft generated by hbm2java
 */
@Entity
@Table(name="ARFAFT"
    ,schema="DESA46"
)
public class Arfaft  implements java.io.Serializable {


     private ArfaftId id;
     private String formulario;

    public Arfaft() {
    }

	
    public Arfaft(ArfaftId id) {
        this.id = id;
    }
    public Arfaft(ArfaftId id, String formulario) {
       this.id = id;
       this.formulario = formulario;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="centrod", column=@Column(name="CENTROD", nullable=false, length=2) ), 
        @AttributeOverride(name="centrof", column=@Column(name="CENTROF", nullable=false, length=4) ), 
        @AttributeOverride(name="tipoDoc", column=@Column(name="TIPO_DOC", nullable=false, length=2) ) } )
    public ArfaftId getId() {
        return this.id;
    }
    
    public void setId(ArfaftId id) {
        this.id = id;
    }

    
    @Column(name="FORMULARIO", length=10)
    public String getFormulario() {
        return this.formulario;
    }
    
    public void setFormulario(String formulario) {
        this.formulario = formulario;
    }




}


