package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArfafeId generated by hbm2java
 */
@Embeddable
public class ArfafeId  implements java.io.Serializable {


     private String noCia;
     private String noFactu;

    public ArfafeId() {
    }

    public ArfafeId(String noCia, String noFactu) {
       this.noCia = noCia;
       this.noFactu = noFactu;
    }
   


    @Column(name="NO_CIA", nullable=false, length=2)
    public String getNoCia() {
        return this.noCia;
    }
    
    public void setNoCia(String noCia) {
        this.noCia = noCia;
    }


    @Column(name="NO_FACTU", nullable=false, length=12)
    public String getNoFactu() {
        return this.noFactu;
    }
    
    public void setNoFactu(String noFactu) {
        this.noFactu = noFactu;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArfafeId) ) return false;
		 ArfafeId castOther = ( ArfafeId ) other; 
         
		 return ( (this.getNoCia()==castOther.getNoCia()) || ( this.getNoCia()!=null && castOther.getNoCia()!=null && this.getNoCia().equals(castOther.getNoCia()) ) )
 && ( (this.getNoFactu()==castOther.getNoFactu()) || ( this.getNoFactu()!=null && castOther.getNoFactu()!=null && this.getNoFactu().equals(castOther.getNoFactu()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNoCia() == null ? 0 : this.getNoCia().hashCode() );
         result = 37 * result + ( getNoFactu() == null ? 0 : this.getNoFactu().hashCode() );
         return result;
   }   


}


