package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arfaflch generated by hbm2java
 */
@Entity
@Table(name="ARFAFLCH"
    ,schema="DESA46"
)
public class Arfaflch  implements java.io.Serializable {


     private ArfaflchId id;
     private String centrod;
     private String periodo;
     private String bodega;
     private String clase;
     private String categoria;
     private String noArti;
     private BigDecimal pedido;
     private BigDecimal porcDesc;
     private BigDecimal precio;
     private BigDecimal descuento;
     private BigDecimal total;
     private String IVen;
     private BigDecimal IVenN;
     private String tipoPrecio;
     private BigDecimal unDevol;
     private String tipoOferta;
     private String artiOfe;
     private BigDecimal cantOfe;
     private String protOfe;
     private BigDecimal cantAprobada;
     private BigDecimal cantFacturada;
     private BigDecimal ofeEntregada;
     private BigDecimal impIncluido;
     private BigDecimal impEspecial;
     private String curva;
     private Integer cantidadBultos;

    public Arfaflch() {
    }

	
    public Arfaflch(ArfaflchId id) {
        this.id = id;
    }
    public Arfaflch(ArfaflchId id, String centrod, String periodo, String bodega, String clase, String categoria, String noArti, BigDecimal pedido, BigDecimal porcDesc, BigDecimal precio, BigDecimal descuento, BigDecimal total, String IVen, BigDecimal IVenN, String tipoPrecio, BigDecimal unDevol, String tipoOferta, String artiOfe, BigDecimal cantOfe, String protOfe, BigDecimal cantAprobada, BigDecimal cantFacturada, BigDecimal ofeEntregada, BigDecimal impIncluido, BigDecimal impEspecial, String curva, Integer cantidadBultos) {
       this.id = id;
       this.centrod = centrod;
       this.periodo = periodo;
       this.bodega = bodega;
       this.clase = clase;
       this.categoria = categoria;
       this.noArti = noArti;
       this.pedido = pedido;
       this.porcDesc = porcDesc;
       this.precio = precio;
       this.descuento = descuento;
       this.total = total;
       this.IVen = IVen;
       this.IVenN = IVenN;
       this.tipoPrecio = tipoPrecio;
       this.unDevol = unDevol;
       this.tipoOferta = tipoOferta;
       this.artiOfe = artiOfe;
       this.cantOfe = cantOfe;
       this.protOfe = protOfe;
       this.cantAprobada = cantAprobada;
       this.cantFacturada = cantFacturada;
       this.ofeEntregada = ofeEntregada;
       this.impIncluido = impIncluido;
       this.impEspecial = impEspecial;
       this.curva = curva;
       this.cantidadBultos = cantidadBultos;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", length=2) ), 
        @AttributeOverride(name="noFactu", column=@Column(name="NO_FACTU", length=19) ), 
        @AttributeOverride(name="noLinea", column=@Column(name="NO_LINEA", precision=5, scale=0) ) } )
    public ArfaflchId getId() {
        return this.id;
    }
    
    public void setId(ArfaflchId id) {
        this.id = id;
    }

    
    @Column(name="CENTROD", length=2)
    public String getCentrod() {
        return this.centrod;
    }
    
    public void setCentrod(String centrod) {
        this.centrod = centrod;
    }

    
    @Column(name="PERIODO", length=4)
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }

    
    @Column(name="BODEGA", length=4)
    public String getBodega() {
        return this.bodega;
    }
    
    public void setBodega(String bodega) {
        this.bodega = bodega;
    }

    
    @Column(name="CLASE", length=3)
    public String getClase() {
        return this.clase;
    }
    
    public void setClase(String clase) {
        this.clase = clase;
    }

    
    @Column(name="CATEGORIA", length=3)
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    
    @Column(name="NO_ARTI", length=30)
    public String getNoArti() {
        return this.noArti;
    }
    
    public void setNoArti(String noArti) {
        this.noArti = noArti;
    }

    
    @Column(name="PEDIDO", precision=8)
    public BigDecimal getPedido() {
        return this.pedido;
    }
    
    public void setPedido(BigDecimal pedido) {
        this.pedido = pedido;
    }

    
    @Column(name="PORC_DESC", precision=6)
    public BigDecimal getPorcDesc() {
        return this.porcDesc;
    }
    
    public void setPorcDesc(BigDecimal porcDesc) {
        this.porcDesc = porcDesc;
    }

    
    @Column(name="PRECIO", precision=12)
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }

    
    @Column(name="DESCUENTO", precision=17)
    public BigDecimal getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(BigDecimal descuento) {
        this.descuento = descuento;
    }

    
    @Column(name="TOTAL", precision=17)
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    
    @Column(name="I_VEN", length=1)
    public String getIVen() {
        return this.IVen;
    }
    
    public void setIVen(String IVen) {
        this.IVen = IVen;
    }

    
    @Column(name="I_VEN_N", precision=17)
    public BigDecimal getIVenN() {
        return this.IVenN;
    }
    
    public void setIVenN(BigDecimal IVenN) {
        this.IVenN = IVenN;
    }

    
    @Column(name="TIPO_PRECIO", length=2)
    public String getTipoPrecio() {
        return this.tipoPrecio;
    }
    
    public void setTipoPrecio(String tipoPrecio) {
        this.tipoPrecio = tipoPrecio;
    }

    
    @Column(name="UN_DEVOL", precision=8)
    public BigDecimal getUnDevol() {
        return this.unDevol;
    }
    
    public void setUnDevol(BigDecimal unDevol) {
        this.unDevol = unDevol;
    }

    
    @Column(name="TIPO_OFERTA", length=1)
    public String getTipoOferta() {
        return this.tipoOferta;
    }
    
    public void setTipoOferta(String tipoOferta) {
        this.tipoOferta = tipoOferta;
    }

    
    @Column(name="ARTI_OFE", length=9)
    public String getArtiOfe() {
        return this.artiOfe;
    }
    
    public void setArtiOfe(String artiOfe) {
        this.artiOfe = artiOfe;
    }

    
    @Column(name="CANT_OFE", precision=8)
    public BigDecimal getCantOfe() {
        return this.cantOfe;
    }
    
    public void setCantOfe(BigDecimal cantOfe) {
        this.cantOfe = cantOfe;
    }

    
    @Column(name="PROT_OFE", length=1)
    public String getProtOfe() {
        return this.protOfe;
    }
    
    public void setProtOfe(String protOfe) {
        this.protOfe = protOfe;
    }

    
    @Column(name="CANT_APROBADA", precision=8)
    public BigDecimal getCantAprobada() {
        return this.cantAprobada;
    }
    
    public void setCantAprobada(BigDecimal cantAprobada) {
        this.cantAprobada = cantAprobada;
    }

    
    @Column(name="CANT_FACTURADA", precision=8)
    public BigDecimal getCantFacturada() {
        return this.cantFacturada;
    }
    
    public void setCantFacturada(BigDecimal cantFacturada) {
        this.cantFacturada = cantFacturada;
    }

    
    @Column(name="OFE_ENTREGADA", precision=8)
    public BigDecimal getOfeEntregada() {
        return this.ofeEntregada;
    }
    
    public void setOfeEntregada(BigDecimal ofeEntregada) {
        this.ofeEntregada = ofeEntregada;
    }

    
    @Column(name="IMP_INCLUIDO", precision=17)
    public BigDecimal getImpIncluido() {
        return this.impIncluido;
    }
    
    public void setImpIncluido(BigDecimal impIncluido) {
        this.impIncluido = impIncluido;
    }

    
    @Column(name="IMP_ESPECIAL", precision=17)
    public BigDecimal getImpEspecial() {
        return this.impEspecial;
    }
    
    public void setImpEspecial(BigDecimal impEspecial) {
        this.impEspecial = impEspecial;
    }

    
    @Column(name="CURVA", length=4)
    public String getCurva() {
        return this.curva;
    }
    
    public void setCurva(String curva) {
        this.curva = curva;
    }

    
    @Column(name="CANTIDAD_BULTOS", precision=6, scale=0)
    public Integer getCantidadBultos() {
        return this.cantidadBultos;
    }
    
    public void setCantidadBultos(Integer cantidadBultos) {
        this.cantidadBultos = cantidadBultos;
    }




}


