package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arfaev generated by hbm2java
 */
@Entity
@Table(name="ARFAEV"
    ,schema="DESA46"
)
public class Arfaev  implements java.io.Serializable {


     private ArfaevId id;
     private Byte mes;
     private BigDecimal ventaUnidades;
     private BigDecimal devolUnidades;
     private BigDecimal promoUnidades;
     private BigDecimal costoVenta;
     private BigDecimal ventaDinero;
     private BigDecimal costoDevol;
     private BigDecimal devolDinero;
     private BigDecimal costoPromo;
     private BigDecimal descuento;
     private BigDecimal impuesto;
     private String moneda;
     private BigDecimal costoVentaDol;
     private BigDecimal ventaDineroDol;
     private BigDecimal costoDevolDol;
     private BigDecimal devolDineroDol;
     private BigDecimal costoPromoDol;
     private BigDecimal descuentoDol;
     private BigDecimal impuestoDol;
     private BigDecimal costoVentaRes;
     private BigDecimal ventaDineroRes;
     private BigDecimal costoDevolRes;
     private BigDecimal devolDineroRes;
     private BigDecimal impuestoRes;

    public Arfaev() {
    }

	
    public Arfaev(ArfaevId id) {
        this.id = id;
    }
    public Arfaev(ArfaevId id, Byte mes, BigDecimal ventaUnidades, BigDecimal devolUnidades, BigDecimal promoUnidades, BigDecimal costoVenta, BigDecimal ventaDinero, BigDecimal costoDevol, BigDecimal devolDinero, BigDecimal costoPromo, BigDecimal descuento, BigDecimal impuesto, String moneda, BigDecimal costoVentaDol, BigDecimal ventaDineroDol, BigDecimal costoDevolDol, BigDecimal devolDineroDol, BigDecimal costoPromoDol, BigDecimal descuentoDol, BigDecimal impuestoDol, BigDecimal costoVentaRes, BigDecimal ventaDineroRes, BigDecimal costoDevolRes, BigDecimal devolDineroRes, BigDecimal impuestoRes) {
       this.id = id;
       this.mes = mes;
       this.ventaUnidades = ventaUnidades;
       this.devolUnidades = devolUnidades;
       this.promoUnidades = promoUnidades;
       this.costoVenta = costoVenta;
       this.ventaDinero = ventaDinero;
       this.costoDevol = costoDevol;
       this.devolDinero = devolDinero;
       this.costoPromo = costoPromo;
       this.descuento = descuento;
       this.impuesto = impuesto;
       this.moneda = moneda;
       this.costoVentaDol = costoVentaDol;
       this.ventaDineroDol = ventaDineroDol;
       this.costoDevolDol = costoDevolDol;
       this.devolDineroDol = devolDineroDol;
       this.costoPromoDol = costoPromoDol;
       this.descuentoDol = descuentoDol;
       this.impuestoDol = impuestoDol;
       this.costoVentaRes = costoVentaRes;
       this.ventaDineroRes = ventaDineroRes;
       this.costoDevolRes = costoDevolRes;
       this.devolDineroRes = devolDineroRes;
       this.impuestoRes = impuestoRes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="centro", column=@Column(name="CENTRO", nullable=false, length=2) ), 
        @AttributeOverride(name="clase", column=@Column(name="CLASE", nullable=false, length=3) ), 
        @AttributeOverride(name="categoria", column=@Column(name="CATEGORIA", nullable=false, length=3) ), 
        @AttributeOverride(name="articulo", column=@Column(name="ARTICULO", nullable=false, length=30) ), 
        @AttributeOverride(name="grupo", column=@Column(name="GRUPO", nullable=false, length=2) ), 
        @AttributeOverride(name="noCliente", column=@Column(name="NO_CLIENTE", nullable=false, length=15) ), 
        @AttributeOverride(name="vendedor", column=@Column(name="VENDEDOR", nullable=false, length=4) ), 
        @AttributeOverride(name="ruta", column=@Column(name="RUTA", nullable=false, length=4) ), 
        @AttributeOverride(name="semana", column=@Column(name="SEMANA", nullable=false, length=2) ), 
        @AttributeOverride(name="indSem", column=@Column(name="IND_SEM", nullable=false, length=1) ), 
        @AttributeOverride(name="ano", column=@Column(name="ANO", nullable=false, length=4) ) } )
    public ArfaevId getId() {
        return this.id;
    }
    
    public void setId(ArfaevId id) {
        this.id = id;
    }

    
    @Column(name="MES", precision=2, scale=0)
    public Byte getMes() {
        return this.mes;
    }
    
    public void setMes(Byte mes) {
        this.mes = mes;
    }

    
    @Column(name="VENTA_UNIDADES", precision=17)
    public BigDecimal getVentaUnidades() {
        return this.ventaUnidades;
    }
    
    public void setVentaUnidades(BigDecimal ventaUnidades) {
        this.ventaUnidades = ventaUnidades;
    }

    
    @Column(name="DEVOL_UNIDADES", precision=17)
    public BigDecimal getDevolUnidades() {
        return this.devolUnidades;
    }
    
    public void setDevolUnidades(BigDecimal devolUnidades) {
        this.devolUnidades = devolUnidades;
    }

    
    @Column(name="PROMO_UNIDADES", precision=17)
    public BigDecimal getPromoUnidades() {
        return this.promoUnidades;
    }
    
    public void setPromoUnidades(BigDecimal promoUnidades) {
        this.promoUnidades = promoUnidades;
    }

    
    @Column(name="COSTO_VENTA", precision=17)
    public BigDecimal getCostoVenta() {
        return this.costoVenta;
    }
    
    public void setCostoVenta(BigDecimal costoVenta) {
        this.costoVenta = costoVenta;
    }

    
    @Column(name="VENTA_DINERO", precision=17)
    public BigDecimal getVentaDinero() {
        return this.ventaDinero;
    }
    
    public void setVentaDinero(BigDecimal ventaDinero) {
        this.ventaDinero = ventaDinero;
    }

    
    @Column(name="COSTO_DEVOL", precision=17)
    public BigDecimal getCostoDevol() {
        return this.costoDevol;
    }
    
    public void setCostoDevol(BigDecimal costoDevol) {
        this.costoDevol = costoDevol;
    }

    
    @Column(name="DEVOL_DINERO", precision=17)
    public BigDecimal getDevolDinero() {
        return this.devolDinero;
    }
    
    public void setDevolDinero(BigDecimal devolDinero) {
        this.devolDinero = devolDinero;
    }

    
    @Column(name="COSTO_PROMO", precision=17)
    public BigDecimal getCostoPromo() {
        return this.costoPromo;
    }
    
    public void setCostoPromo(BigDecimal costoPromo) {
        this.costoPromo = costoPromo;
    }

    
    @Column(name="DESCUENTO", precision=17)
    public BigDecimal getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(BigDecimal descuento) {
        this.descuento = descuento;
    }

    
    @Column(name="IMPUESTO", precision=17)
    public BigDecimal getImpuesto() {
        return this.impuesto;
    }
    
    public void setImpuesto(BigDecimal impuesto) {
        this.impuesto = impuesto;
    }

    
    @Column(name="MONEDA", length=1)
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }

    
    @Column(name="COSTO_VENTA_DOL", precision=17)
    public BigDecimal getCostoVentaDol() {
        return this.costoVentaDol;
    }
    
    public void setCostoVentaDol(BigDecimal costoVentaDol) {
        this.costoVentaDol = costoVentaDol;
    }

    
    @Column(name="VENTA_DINERO_DOL", precision=17)
    public BigDecimal getVentaDineroDol() {
        return this.ventaDineroDol;
    }
    
    public void setVentaDineroDol(BigDecimal ventaDineroDol) {
        this.ventaDineroDol = ventaDineroDol;
    }

    
    @Column(name="COSTO_DEVOL_DOL", precision=17)
    public BigDecimal getCostoDevolDol() {
        return this.costoDevolDol;
    }
    
    public void setCostoDevolDol(BigDecimal costoDevolDol) {
        this.costoDevolDol = costoDevolDol;
    }

    
    @Column(name="DEVOL_DINERO_DOL", precision=17)
    public BigDecimal getDevolDineroDol() {
        return this.devolDineroDol;
    }
    
    public void setDevolDineroDol(BigDecimal devolDineroDol) {
        this.devolDineroDol = devolDineroDol;
    }

    
    @Column(name="COSTO_PROMO_DOL", precision=17)
    public BigDecimal getCostoPromoDol() {
        return this.costoPromoDol;
    }
    
    public void setCostoPromoDol(BigDecimal costoPromoDol) {
        this.costoPromoDol = costoPromoDol;
    }

    
    @Column(name="DESCUENTO_DOL", precision=17)
    public BigDecimal getDescuentoDol() {
        return this.descuentoDol;
    }
    
    public void setDescuentoDol(BigDecimal descuentoDol) {
        this.descuentoDol = descuentoDol;
    }

    
    @Column(name="IMPUESTO_DOL", precision=17)
    public BigDecimal getImpuestoDol() {
        return this.impuestoDol;
    }
    
    public void setImpuestoDol(BigDecimal impuestoDol) {
        this.impuestoDol = impuestoDol;
    }

    
    @Column(name="COSTO_VENTA_RES", precision=30)
    public BigDecimal getCostoVentaRes() {
        return this.costoVentaRes;
    }
    
    public void setCostoVentaRes(BigDecimal costoVentaRes) {
        this.costoVentaRes = costoVentaRes;
    }

    
    @Column(name="VENTA_DINERO_RES", precision=30)
    public BigDecimal getVentaDineroRes() {
        return this.ventaDineroRes;
    }
    
    public void setVentaDineroRes(BigDecimal ventaDineroRes) {
        this.ventaDineroRes = ventaDineroRes;
    }

    
    @Column(name="COSTO_DEVOL_RES", precision=30)
    public BigDecimal getCostoDevolRes() {
        return this.costoDevolRes;
    }
    
    public void setCostoDevolRes(BigDecimal costoDevolRes) {
        this.costoDevolRes = costoDevolRes;
    }

    
    @Column(name="DEVOL_DINERO_RES", precision=30)
    public BigDecimal getDevolDineroRes() {
        return this.devolDineroRes;
    }
    
    public void setDevolDineroRes(BigDecimal devolDineroRes) {
        this.devolDineroRes = devolDineroRes;
    }

    
    @Column(name="IMPUESTO_RES", precision=30)
    public BigDecimal getImpuestoRes() {
        return this.impuestoRes;
    }
    
    public void setImpuestoRes(BigDecimal impuestoRes) {
        this.impuestoRes = impuestoRes;
    }




}


