package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arfamc generated by hbm2java
 */
@Entity
@Table(name="ARFAMC"
    ,schema="DESA46"
)
public class Arfamc  implements java.io.Serializable {


     private String noCia;
     private String nombre;
     private String dir1;
     private String dir2;
     private BigDecimal impuesto;
     private BigDecimal porcDesc;
     private String manejoLote;
     private String indOferta;
     private String indLiquida;
     private String tipoPrecioPres;
     private String indSeguridad;
     private String codDiario;
     private String codDiarioInv;
     private String docDebitoCxc;
     private String docCreditoCxc;
     private String conceptoCkPos;
     private String tipoDocComi;
     private Date tstamp;
     private String indArtAutomatico;
     private String formularioArt;

    public Arfamc() {
    }

	
    public Arfamc(String noCia) {
        this.noCia = noCia;
    }
    public Arfamc(String noCia, String nombre, String dir1, String dir2, BigDecimal impuesto, BigDecimal porcDesc, String manejoLote, String indOferta, String indLiquida, String tipoPrecioPres, String indSeguridad, String codDiario, String codDiarioInv, String docDebitoCxc, String docCreditoCxc, String conceptoCkPos, String tipoDocComi, Date tstamp, String indArtAutomatico, String formularioArt) {
       this.noCia = noCia;
       this.nombre = nombre;
       this.dir1 = dir1;
       this.dir2 = dir2;
       this.impuesto = impuesto;
       this.porcDesc = porcDesc;
       this.manejoLote = manejoLote;
       this.indOferta = indOferta;
       this.indLiquida = indLiquida;
       this.tipoPrecioPres = tipoPrecioPres;
       this.indSeguridad = indSeguridad;
       this.codDiario = codDiario;
       this.codDiarioInv = codDiarioInv;
       this.docDebitoCxc = docDebitoCxc;
       this.docCreditoCxc = docCreditoCxc;
       this.conceptoCkPos = conceptoCkPos;
       this.tipoDocComi = tipoDocComi;
       this.tstamp = tstamp;
       this.indArtAutomatico = indArtAutomatico;
       this.formularioArt = formularioArt;
    }
   
     @Id 

    
    @Column(name="NO_CIA", unique=true, nullable=false, length=2)
    public String getNoCia() {
        return this.noCia;
    }
    
    public void setNoCia(String noCia) {
        this.noCia = noCia;
    }

    
    @Column(name="NOMBRE", length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="DIR1", length=37)
    public String getDir1() {
        return this.dir1;
    }
    
    public void setDir1(String dir1) {
        this.dir1 = dir1;
    }

    
    @Column(name="DIR2", length=37)
    public String getDir2() {
        return this.dir2;
    }
    
    public void setDir2(String dir2) {
        this.dir2 = dir2;
    }

    
    @Column(name="IMPUESTO", precision=6)
    public BigDecimal getImpuesto() {
        return this.impuesto;
    }
    
    public void setImpuesto(BigDecimal impuesto) {
        this.impuesto = impuesto;
    }

    
    @Column(name="PORC_DESC", precision=6)
    public BigDecimal getPorcDesc() {
        return this.porcDesc;
    }
    
    public void setPorcDesc(BigDecimal porcDesc) {
        this.porcDesc = porcDesc;
    }

    
    @Column(name="MANEJO_LOTE", length=1)
    public String getManejoLote() {
        return this.manejoLote;
    }
    
    public void setManejoLote(String manejoLote) {
        this.manejoLote = manejoLote;
    }

    
    @Column(name="IND_OFERTA", length=1)
    public String getIndOferta() {
        return this.indOferta;
    }
    
    public void setIndOferta(String indOferta) {
        this.indOferta = indOferta;
    }

    
    @Column(name="IND_LIQUIDA", length=1)
    public String getIndLiquida() {
        return this.indLiquida;
    }
    
    public void setIndLiquida(String indLiquida) {
        this.indLiquida = indLiquida;
    }

    
    @Column(name="TIPO_PRECIO_PRES", length=2)
    public String getTipoPrecioPres() {
        return this.tipoPrecioPres;
    }
    
    public void setTipoPrecioPres(String tipoPrecioPres) {
        this.tipoPrecioPres = tipoPrecioPres;
    }

    
    @Column(name="IND_SEGURIDAD", length=1)
    public String getIndSeguridad() {
        return this.indSeguridad;
    }
    
    public void setIndSeguridad(String indSeguridad) {
        this.indSeguridad = indSeguridad;
    }

    
    @Column(name="COD_DIARIO", length=5)
    public String getCodDiario() {
        return this.codDiario;
    }
    
    public void setCodDiario(String codDiario) {
        this.codDiario = codDiario;
    }

    
    @Column(name="COD_DIARIO_INV", length=5)
    public String getCodDiarioInv() {
        return this.codDiarioInv;
    }
    
    public void setCodDiarioInv(String codDiarioInv) {
        this.codDiarioInv = codDiarioInv;
    }

    
    @Column(name="DOC_DEBITO_CXC", length=2)
    public String getDocDebitoCxc() {
        return this.docDebitoCxc;
    }
    
    public void setDocDebitoCxc(String docDebitoCxc) {
        this.docDebitoCxc = docDebitoCxc;
    }

    
    @Column(name="DOC_CREDITO_CXC", length=2)
    public String getDocCreditoCxc() {
        return this.docCreditoCxc;
    }
    
    public void setDocCreditoCxc(String docCreditoCxc) {
        this.docCreditoCxc = docCreditoCxc;
    }

    
    @Column(name="CONCEPTO_CK_POS", length=2)
    public String getConceptoCkPos() {
        return this.conceptoCkPos;
    }
    
    public void setConceptoCkPos(String conceptoCkPos) {
        this.conceptoCkPos = conceptoCkPos;
    }

    
    @Column(name="TIPO_DOC_COMI", length=2)
    public String getTipoDocComi() {
        return this.tipoDocComi;
    }
    
    public void setTipoDocComi(String tipoDocComi) {
        this.tipoDocComi = tipoDocComi;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TSTAMP", length=7)
    public Date getTstamp() {
        return this.tstamp;
    }
    
    public void setTstamp(Date tstamp) {
        this.tstamp = tstamp;
    }

    
    @Column(name="IND_ART_AUTOMATICO", length=1)
    public String getIndArtAutomatico() {
        return this.indArtAutomatico;
    }
    
    public void setIndArtAutomatico(String indArtAutomatico) {
        this.indArtAutomatico = indArtAutomatico;
    }

    
    @Column(name="FORMULARIO_ART", length=10)
    public String getFormularioArt() {
        return this.formularioArt;
    }
    
    public void setFormularioArt(String formularioArt) {
        this.formularioArt = formularioArt;
    }




}


