package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArfaflTaId generated by hbm2java
 */
@Embeddable
public class ArfaflTaId  implements java.io.Serializable {


     private String noCia;
     private String noFactu;
     private int noLinea;
     private BigDecimal talla;

    public ArfaflTaId() {
    }

    public ArfaflTaId(String noCia, String noFactu, int noLinea, BigDecimal talla) {
       this.noCia = noCia;
       this.noFactu = noFactu;
       this.noLinea = noLinea;
       this.talla = talla;
    }
   


    @Column(name="NO_CIA", nullable=false, length=2)
    public String getNoCia() {
        return this.noCia;
    }
    
    public void setNoCia(String noCia) {
        this.noCia = noCia;
    }


    @Column(name="NO_FACTU", nullable=false, length=12)
    public String getNoFactu() {
        return this.noFactu;
    }
    
    public void setNoFactu(String noFactu) {
        this.noFactu = noFactu;
    }


    @Column(name="NO_LINEA", nullable=false, precision=5, scale=0)
    public int getNoLinea() {
        return this.noLinea;
    }
    
    public void setNoLinea(int noLinea) {
        this.noLinea = noLinea;
    }


    @Column(name="TALLA", nullable=false, precision=4, scale=1)
    public BigDecimal getTalla() {
        return this.talla;
    }
    
    public void setTalla(BigDecimal talla) {
        this.talla = talla;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArfaflTaId) ) return false;
		 ArfaflTaId castOther = ( ArfaflTaId ) other; 
         
		 return ( (this.getNoCia()==castOther.getNoCia()) || ( this.getNoCia()!=null && castOther.getNoCia()!=null && this.getNoCia().equals(castOther.getNoCia()) ) )
 && ( (this.getNoFactu()==castOther.getNoFactu()) || ( this.getNoFactu()!=null && castOther.getNoFactu()!=null && this.getNoFactu().equals(castOther.getNoFactu()) ) )
 && (this.getNoLinea()==castOther.getNoLinea())
 && ( (this.getTalla()==castOther.getTalla()) || ( this.getTalla()!=null && castOther.getTalla()!=null && this.getTalla().equals(castOther.getTalla()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNoCia() == null ? 0 : this.getNoCia().hashCode() );
         result = 37 * result + ( getNoFactu() == null ? 0 : this.getNoFactu().hashCode() );
         result = 37 * result + this.getNoLinea();
         result = 37 * result + ( getTalla() == null ? 0 : this.getTalla().hashCode() );
         return result;
   }   


}


