package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arfact generated by hbm2java
 */
@Entity
@Table(name="ARFACT"
    ,schema="DESA46"
)
public class Arfact  implements java.io.Serializable {


     private ArfactId id;
     private String tipoMov;
     private String descripcion;
     private String afectaSaldo;
     private String indFacDev;
     private String liquidacion;
     private String anulaFactu;
     private String obsequio;
     private Short maxLinea;
     private String pedido;
     private String formularioCtrl;
     private String msgDoc1;
     private String msgDoc2;
     private String msgDoc3;
     private String msgDoc4;
     private String msgDoc5;

    public Arfact() {
    }

	
    public Arfact(ArfactId id) {
        this.id = id;
    }
    public Arfact(ArfactId id, String tipoMov, String descripcion, String afectaSaldo, String indFacDev, String liquidacion, String anulaFactu, String obsequio, Short maxLinea, String pedido, String formularioCtrl, String msgDoc1, String msgDoc2, String msgDoc3, String msgDoc4, String msgDoc5) {
       this.id = id;
       this.tipoMov = tipoMov;
       this.descripcion = descripcion;
       this.afectaSaldo = afectaSaldo;
       this.indFacDev = indFacDev;
       this.liquidacion = liquidacion;
       this.anulaFactu = anulaFactu;
       this.obsequio = obsequio;
       this.maxLinea = maxLinea;
       this.pedido = pedido;
       this.formularioCtrl = formularioCtrl;
       this.msgDoc1 = msgDoc1;
       this.msgDoc2 = msgDoc2;
       this.msgDoc3 = msgDoc3;
       this.msgDoc4 = msgDoc4;
       this.msgDoc5 = msgDoc5;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="tipo", column=@Column(name="TIPO", nullable=false, length=2) ) } )
    public ArfactId getId() {
        return this.id;
    }
    
    public void setId(ArfactId id) {
        this.id = id;
    }

    
    @Column(name="TIPO_MOV", length=1)
    public String getTipoMov() {
        return this.tipoMov;
    }
    
    public void setTipoMov(String tipoMov) {
        this.tipoMov = tipoMov;
    }

    
    @Column(name="DESCRIPCION", length=35)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="AFECTA_SALDO", length=1)
    public String getAfectaSaldo() {
        return this.afectaSaldo;
    }
    
    public void setAfectaSaldo(String afectaSaldo) {
        this.afectaSaldo = afectaSaldo;
    }

    
    @Column(name="IND_FAC_DEV", length=1)
    public String getIndFacDev() {
        return this.indFacDev;
    }
    
    public void setIndFacDev(String indFacDev) {
        this.indFacDev = indFacDev;
    }

    
    @Column(name="LIQUIDACION", length=1)
    public String getLiquidacion() {
        return this.liquidacion;
    }
    
    public void setLiquidacion(String liquidacion) {
        this.liquidacion = liquidacion;
    }

    
    @Column(name="ANULA_FACTU", length=1)
    public String getAnulaFactu() {
        return this.anulaFactu;
    }
    
    public void setAnulaFactu(String anulaFactu) {
        this.anulaFactu = anulaFactu;
    }

    
    @Column(name="OBSEQUIO", length=1)
    public String getObsequio() {
        return this.obsequio;
    }
    
    public void setObsequio(String obsequio) {
        this.obsequio = obsequio;
    }

    
    @Column(name="MAX_LINEA", precision=3, scale=0)
    public Short getMaxLinea() {
        return this.maxLinea;
    }
    
    public void setMaxLinea(Short maxLinea) {
        this.maxLinea = maxLinea;
    }

    
    @Column(name="PEDIDO", length=1)
    public String getPedido() {
        return this.pedido;
    }
    
    public void setPedido(String pedido) {
        this.pedido = pedido;
    }

    
    @Column(name="FORMULARIO_CTRL", length=10)
    public String getFormularioCtrl() {
        return this.formularioCtrl;
    }
    
    public void setFormularioCtrl(String formularioCtrl) {
        this.formularioCtrl = formularioCtrl;
    }

    
    @Column(name="MSG_DOC1", length=100)
    public String getMsgDoc1() {
        return this.msgDoc1;
    }
    
    public void setMsgDoc1(String msgDoc1) {
        this.msgDoc1 = msgDoc1;
    }

    
    @Column(name="MSG_DOC2", length=100)
    public String getMsgDoc2() {
        return this.msgDoc2;
    }
    
    public void setMsgDoc2(String msgDoc2) {
        this.msgDoc2 = msgDoc2;
    }

    
    @Column(name="MSG_DOC3", length=100)
    public String getMsgDoc3() {
        return this.msgDoc3;
    }
    
    public void setMsgDoc3(String msgDoc3) {
        this.msgDoc3 = msgDoc3;
    }

    
    @Column(name="MSG_DOC4", length=100)
    public String getMsgDoc4() {
        return this.msgDoc4;
    }
    
    public void setMsgDoc4(String msgDoc4) {
        this.msgDoc4 = msgDoc4;
    }

    
    @Column(name="MSG_DOC5", length=100)
    public String getMsgDoc5() {
        return this.msgDoc5;
    }
    
    public void setMsgDoc5(String msgDoc5) {
        this.msgDoc5 = msgDoc5;
    }




}


