package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arfaflh generated by hbm2java
 */
@Entity
@Table(name="ARFAFLH"
    ,schema="DESA46"
)
public class Arfaflh  implements java.io.Serializable {


     private ArfaflhId id;
     private String centrod;
     private String tipoDoc;
     private String periodo;
     private String ruta;
     private String bodega;
     private String clase;
     private String categoria;
     private String noArti;
     private BigDecimal pedido;
     private BigDecimal porcDesc;
     private BigDecimal costo;
     private BigDecimal precio;
     private BigDecimal descuento;
     private BigDecimal total;
     private String IVen;
     private BigDecimal IVenN;
     private String tipoPrecio;
     private BigDecimal unDevol;
     private String artiOfe;
     private BigDecimal cantOfe;
     private BigDecimal costoOfe;
     private String protOfe;
     private String tipoOferta;
     private Short noLineaD;
     private BigDecimal impIncluido;
     private BigDecimal impEspecial;
     private Integer cantidadBultos;
     private String curva;
     private Short noLineaPed;

    public Arfaflh() {
    }

	
    public Arfaflh(ArfaflhId id) {
        this.id = id;
    }
    public Arfaflh(ArfaflhId id, String centrod, String tipoDoc, String periodo, String ruta, String bodega, String clase, String categoria, String noArti, BigDecimal pedido, BigDecimal porcDesc, BigDecimal costo, BigDecimal precio, BigDecimal descuento, BigDecimal total, String IVen, BigDecimal IVenN, String tipoPrecio, BigDecimal unDevol, String artiOfe, BigDecimal cantOfe, BigDecimal costoOfe, String protOfe, String tipoOferta, Short noLineaD, BigDecimal impIncluido, BigDecimal impEspecial, Integer cantidadBultos, String curva, Short noLineaPed) {
       this.id = id;
       this.centrod = centrod;
       this.tipoDoc = tipoDoc;
       this.periodo = periodo;
       this.ruta = ruta;
       this.bodega = bodega;
       this.clase = clase;
       this.categoria = categoria;
       this.noArti = noArti;
       this.pedido = pedido;
       this.porcDesc = porcDesc;
       this.costo = costo;
       this.precio = precio;
       this.descuento = descuento;
       this.total = total;
       this.IVen = IVen;
       this.IVenN = IVenN;
       this.tipoPrecio = tipoPrecio;
       this.unDevol = unDevol;
       this.artiOfe = artiOfe;
       this.cantOfe = cantOfe;
       this.costoOfe = costoOfe;
       this.protOfe = protOfe;
       this.tipoOferta = tipoOferta;
       this.noLineaD = noLineaD;
       this.impIncluido = impIncluido;
       this.impEspecial = impEspecial;
       this.cantidadBultos = cantidadBultos;
       this.curva = curva;
       this.noLineaPed = noLineaPed;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noFactu", column=@Column(name="NO_FACTU", nullable=false, length=19) ), 
        @AttributeOverride(name="noLinea", column=@Column(name="NO_LINEA", nullable=false, precision=5, scale=0) ) } )
    public ArfaflhId getId() {
        return this.id;
    }
    
    public void setId(ArfaflhId id) {
        this.id = id;
    }

    
    @Column(name="CENTROD", length=2)
    public String getCentrod() {
        return this.centrod;
    }
    
    public void setCentrod(String centrod) {
        this.centrod = centrod;
    }

    
    @Column(name="TIPO_DOC", length=2)
    public String getTipoDoc() {
        return this.tipoDoc;
    }
    
    public void setTipoDoc(String tipoDoc) {
        this.tipoDoc = tipoDoc;
    }

    
    @Column(name="PERIODO", length=4)
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }

    
    @Column(name="RUTA", length=4)
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }

    
    @Column(name="BODEGA", length=4)
    public String getBodega() {
        return this.bodega;
    }
    
    public void setBodega(String bodega) {
        this.bodega = bodega;
    }

    
    @Column(name="CLASE", length=3)
    public String getClase() {
        return this.clase;
    }
    
    public void setClase(String clase) {
        this.clase = clase;
    }

    
    @Column(name="CATEGORIA", length=3)
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    
    @Column(name="NO_ARTI", length=30)
    public String getNoArti() {
        return this.noArti;
    }
    
    public void setNoArti(String noArti) {
        this.noArti = noArti;
    }

    
    @Column(name="PEDIDO", precision=8)
    public BigDecimal getPedido() {
        return this.pedido;
    }
    
    public void setPedido(BigDecimal pedido) {
        this.pedido = pedido;
    }

    
    @Column(name="PORC_DESC", precision=6)
    public BigDecimal getPorcDesc() {
        return this.porcDesc;
    }
    
    public void setPorcDesc(BigDecimal porcDesc) {
        this.porcDesc = porcDesc;
    }

    
    @Column(name="COSTO", precision=22, scale=6)
    public BigDecimal getCosto() {
        return this.costo;
    }
    
    public void setCosto(BigDecimal costo) {
        this.costo = costo;
    }

    
    @Column(name="PRECIO", precision=22, scale=6)
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }

    
    @Column(name="DESCUENTO", precision=17)
    public BigDecimal getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(BigDecimal descuento) {
        this.descuento = descuento;
    }

    
    @Column(name="TOTAL", precision=17)
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    
    @Column(name="I_VEN", length=1)
    public String getIVen() {
        return this.IVen;
    }
    
    public void setIVen(String IVen) {
        this.IVen = IVen;
    }

    
    @Column(name="I_VEN_N", precision=17)
    public BigDecimal getIVenN() {
        return this.IVenN;
    }
    
    public void setIVenN(BigDecimal IVenN) {
        this.IVenN = IVenN;
    }

    
    @Column(name="TIPO_PRECIO", length=2)
    public String getTipoPrecio() {
        return this.tipoPrecio;
    }
    
    public void setTipoPrecio(String tipoPrecio) {
        this.tipoPrecio = tipoPrecio;
    }

    
    @Column(name="UN_DEVOL", precision=8)
    public BigDecimal getUnDevol() {
        return this.unDevol;
    }
    
    public void setUnDevol(BigDecimal unDevol) {
        this.unDevol = unDevol;
    }

    
    @Column(name="ARTI_OFE", length=15)
    public String getArtiOfe() {
        return this.artiOfe;
    }
    
    public void setArtiOfe(String artiOfe) {
        this.artiOfe = artiOfe;
    }

    
    @Column(name="CANT_OFE", precision=8)
    public BigDecimal getCantOfe() {
        return this.cantOfe;
    }
    
    public void setCantOfe(BigDecimal cantOfe) {
        this.cantOfe = cantOfe;
    }

    
    @Column(name="COSTO_OFE", precision=12)
    public BigDecimal getCostoOfe() {
        return this.costoOfe;
    }
    
    public void setCostoOfe(BigDecimal costoOfe) {
        this.costoOfe = costoOfe;
    }

    
    @Column(name="PROT_OFE", length=1)
    public String getProtOfe() {
        return this.protOfe;
    }
    
    public void setProtOfe(String protOfe) {
        this.protOfe = protOfe;
    }

    
    @Column(name="TIPO_OFERTA", length=1)
    public String getTipoOferta() {
        return this.tipoOferta;
    }
    
    public void setTipoOferta(String tipoOferta) {
        this.tipoOferta = tipoOferta;
    }

    
    @Column(name="NO_LINEA_D", precision=3, scale=0)
    public Short getNoLineaD() {
        return this.noLineaD;
    }
    
    public void setNoLineaD(Short noLineaD) {
        this.noLineaD = noLineaD;
    }

    
    @Column(name="IMP_INCLUIDO", precision=17)
    public BigDecimal getImpIncluido() {
        return this.impIncluido;
    }
    
    public void setImpIncluido(BigDecimal impIncluido) {
        this.impIncluido = impIncluido;
    }

    
    @Column(name="IMP_ESPECIAL", precision=17)
    public BigDecimal getImpEspecial() {
        return this.impEspecial;
    }
    
    public void setImpEspecial(BigDecimal impEspecial) {
        this.impEspecial = impEspecial;
    }

    
    @Column(name="CANTIDAD_BULTOS", precision=6, scale=0)
    public Integer getCantidadBultos() {
        return this.cantidadBultos;
    }
    
    public void setCantidadBultos(Integer cantidadBultos) {
        this.cantidadBultos = cantidadBultos;
    }

    
    @Column(name="CURVA", length=4)
    public String getCurva() {
        return this.curva;
    }
    
    public void setCurva(String curva) {
        this.curva = curva;
    }

    
    @Column(name="NO_LINEA_PED", precision=3, scale=0)
    public Short getNoLineaPed() {
        return this.noLineaPed;
    }
    
    public void setNoLineaPed(Short noLineaPed) {
        this.noLineaPed = noLineaPed;
    }




}


