package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Argect generated by hbm2java
 */
@Entity
@Table(name="ARGECT"
    ,schema="DESA46"
)
public class Argect  implements java.io.Serializable {


     private String codigoCondicion;
     private String descripcion;
     private BigDecimal maxPorcDesc;

    public Argect() {
    }

	
    public Argect(String codigoCondicion) {
        this.codigoCondicion = codigoCondicion;
    }
    public Argect(String codigoCondicion, String descripcion, BigDecimal maxPorcDesc) {
       this.codigoCondicion = codigoCondicion;
       this.descripcion = descripcion;
       this.maxPorcDesc = maxPorcDesc;
    }
   
     @Id 

    
    @Column(name="CODIGO_CONDICION", unique=true, nullable=false, length=3)
    public String getCodigoCondicion() {
        return this.codigoCondicion;
    }
    
    public void setCodigoCondicion(String codigoCondicion) {
        this.codigoCondicion = codigoCondicion;
    }

    
    @Column(name="DESCRIPCION", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="MAX_PORC_DESC", precision=5)
    public BigDecimal getMaxPorcDesc() {
        return this.maxPorcDesc;
    }
    
    public void setMaxPorcDesc(BigDecimal maxPorcDesc) {
        this.maxPorcDesc = maxPorcDesc;
    }




}


