package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Argemod generated by hbm2java
 */
@Entity
@Table(name="ARGEMOD"
    ,schema="DESA46"
)
public class Argemod  implements java.io.Serializable {


     private String modulo;
     private String descripcion;

    public Argemod() {
    }

	
    public Argemod(String modulo) {
        this.modulo = modulo;
    }
    public Argemod(String modulo, String descripcion) {
       this.modulo = modulo;
       this.descripcion = descripcion;
    }
   
     @Id 

    
    @Column(name="MODULO", unique=true, nullable=false, length=2)
    public String getModulo() {
        return this.modulo;
    }
    
    public void setModulo(String modulo) {
        this.modulo = modulo;
    }

    
    @Column(name="DESCRIPCION", length=40)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


