package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArgeacId generated by hbm2java
 */
@Embeddable
public class ArgeacId  implements java.io.Serializable {


     private String sector;
     private String actividad;
     private String pais;
     private String provincia;
     private String canton;

    public ArgeacId() {
    }

    public ArgeacId(String sector, String actividad, String pais, String provincia, String canton) {
       this.sector = sector;
       this.actividad = actividad;
       this.pais = pais;
       this.provincia = provincia;
       this.canton = canton;
    }
   


    @Column(name="SECTOR", nullable=false, length=2)
    public String getSector() {
        return this.sector;
    }
    
    public void setSector(String sector) {
        this.sector = sector;
    }


    @Column(name="ACTIVIDAD", nullable=false, length=4)
    public String getActividad() {
        return this.actividad;
    }
    
    public void setActividad(String actividad) {
        this.actividad = actividad;
    }


    @Column(name="PAIS", nullable=false, length=6)
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }


    @Column(name="PROVINCIA", nullable=false, length=6)
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }


    @Column(name="CANTON", nullable=false, length=6)
    public String getCanton() {
        return this.canton;
    }
    
    public void setCanton(String canton) {
        this.canton = canton;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArgeacId) ) return false;
		 ArgeacId castOther = ( ArgeacId ) other; 
         
		 return ( (this.getSector()==castOther.getSector()) || ( this.getSector()!=null && castOther.getSector()!=null && this.getSector().equals(castOther.getSector()) ) )
 && ( (this.getActividad()==castOther.getActividad()) || ( this.getActividad()!=null && castOther.getActividad()!=null && this.getActividad().equals(castOther.getActividad()) ) )
 && ( (this.getPais()==castOther.getPais()) || ( this.getPais()!=null && castOther.getPais()!=null && this.getPais().equals(castOther.getPais()) ) )
 && ( (this.getProvincia()==castOther.getProvincia()) || ( this.getProvincia()!=null && castOther.getProvincia()!=null && this.getProvincia().equals(castOther.getProvincia()) ) )
 && ( (this.getCanton()==castOther.getCanton()) || ( this.getCanton()!=null && castOther.getCanton()!=null && this.getCanton().equals(castOther.getCanton()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSector() == null ? 0 : this.getSector().hashCode() );
         result = 37 * result + ( getActividad() == null ? 0 : this.getActividad().hashCode() );
         result = 37 * result + ( getPais() == null ? 0 : this.getPais().hashCode() );
         result = 37 * result + ( getProvincia() == null ? 0 : this.getProvincia().hashCode() );
         result = 37 * result + ( getCanton() == null ? 0 : this.getCanton().hashCode() );
         return result;
   }   


}


