package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArgeimpoTxt generated by hbm2java
 */
@Entity
@Table(name="ARGEIMPO_TXT"
    ,schema="DESA46"
)
public class ArgeimpoTxt  implements java.io.Serializable {


     private ArgeimpoTxtId id;
     private Date timeStamp;
     private String hilera;

    public ArgeimpoTxt() {
    }

	
    public ArgeimpoTxt(ArgeimpoTxtId id) {
        this.id = id;
    }
    public ArgeimpoTxt(ArgeimpoTxtId id, Date timeStamp, String hilera) {
       this.id = id;
       this.timeStamp = timeStamp;
       this.hilera = hilera;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="ID", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="numLinea", column=@Column(name="NUM_LINEA", nullable=false, precision=4, scale=0) ) } )
    public ArgeimpoTxtId getId() {
        return this.id;
    }
    
    public void setId(ArgeimpoTxtId id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TIME_STAMP", length=7)
    public Date getTimeStamp() {
        return this.timeStamp;
    }
    
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    
    @Column(name="HILERA", length=400)
    public String getHilera() {
        return this.hilera;
    }
    
    public void setHilera(String hilera) {
        this.hilera = hilera;
    }




}


