package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Argedis generated by hbm2java
 */
@Entity
@Table(name="ARGEDIS"
    ,schema="DESA46"
)
public class Argedis  implements java.io.Serializable {


     private ArgedisId id;
     private String descripcion;

    public Argedis() {
    }

	
    public Argedis(ArgedisId id) {
        this.id = id;
    }
    public Argedis(ArgedisId id, String descripcion) {
       this.id = id;
       this.descripcion = descripcion;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pais", column=@Column(name="PAIS", nullable=false, length=6) ), 
        @AttributeOverride(name="provincia", column=@Column(name="PROVINCIA", nullable=false, length=6) ), 
        @AttributeOverride(name="canton", column=@Column(name="CANTON", nullable=false, length=6) ), 
        @AttributeOverride(name="distrito", column=@Column(name="DISTRITO", nullable=false, length=2) ) } )
    public ArgedisId getId() {
        return this.id;
    }
    
    public void setId(ArgedisId id) {
        this.id = id;
    }

    
    @Column(name="DESCRIPCION", length=25)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


