package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Argeac generated by hbm2java
 */
@Entity
@Table(name="ARGEAC"
    ,schema="DESA46"
)
public class Argeac  implements java.io.Serializable {


     private ArgeacId id;
     private String descripcion;

    public Argeac() {
    }

	
    public Argeac(ArgeacId id) {
        this.id = id;
    }
    public Argeac(ArgeacId id, String descripcion) {
       this.id = id;
       this.descripcion = descripcion;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="sector", column=@Column(name="SECTOR", nullable=false, length=2) ), 
        @AttributeOverride(name="actividad", column=@Column(name="ACTIVIDAD", nullable=false, length=4) ), 
        @AttributeOverride(name="pais", column=@Column(name="PAIS", nullable=false, length=6) ), 
        @AttributeOverride(name="provincia", column=@Column(name="PROVINCIA", nullable=false, length=6) ), 
        @AttributeOverride(name="canton", column=@Column(name="CANTON", nullable=false, length=6) ) } )
    public ArgeacId getId() {
        return this.id;
    }
    
    public void setId(ArgeacId id) {
        this.id = id;
    }

    
    @Column(name="DESCRIPCION", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


