package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Argepro generated by hbm2java
 */
@Entity
@Table(name="ARGEPRO"
    ,schema="DESA46"
)
public class Argepro  implements java.io.Serializable {


     private ArgeproId id;
     private String descripcion;

    public Argepro() {
    }

	
    public Argepro(ArgeproId id) {
        this.id = id;
    }
    public Argepro(ArgeproId id, String descripcion) {
       this.id = id;
       this.descripcion = descripcion;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pais", column=@Column(name="PAIS", nullable=false, length=6) ), 
        @AttributeOverride(name="provincia", column=@Column(name="PROVINCIA", nullable=false, length=6) ) } )
    public ArgeproId getId() {
        return this.id;
    }
    
    public void setId(ArgeproId id) {
        this.id = id;
    }

    
    @Column(name="DESCRIPCION", length=25)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


