package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Argetb generated by hbm2java
 */
@Entity
@Table(name="ARGETB"
    ,schema="DESA46"
)
public class Argetb  implements java.io.Serializable {


     private String banco;
     private String descripcion;
     private String codigoTercero;

    public Argetb() {
    }

	
    public Argetb(String banco) {
        this.banco = banco;
    }
    public Argetb(String banco, String descripcion, String codigoTercero) {
       this.banco = banco;
       this.descripcion = descripcion;
       this.codigoTercero = codigoTercero;
    }
   
     @Id 

    
    @Column(name="BANCO", unique=true, nullable=false, length=2)
    public String getBanco() {
        return this.banco;
    }
    
    public void setBanco(String banco) {
        this.banco = banco;
    }

    
    @Column(name="DESCRIPCION", length=60)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="CODIGO_TERCERO", length=18)
    public String getCodigoTercero() {
        return this.codigoTercero;
    }
    
    public void setCodigoTercero(String codigoTercero) {
        this.codigoTercero = codigoTercero;
    }




}


