package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArgeproId generated by hbm2java
 */
@Embeddable
public class ArgeproId  implements java.io.Serializable {


     private String pais;
     private String provincia;

    public ArgeproId() {
    }

    public ArgeproId(String pais, String provincia) {
       this.pais = pais;
       this.provincia = provincia;
    }
   


    @Column(name="PAIS", nullable=false, length=6)
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }


    @Column(name="PROVINCIA", nullable=false, length=6)
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArgeproId) ) return false;
		 ArgeproId castOther = ( ArgeproId ) other; 
         
		 return ( (this.getPais()==castOther.getPais()) || ( this.getPais()!=null && castOther.getPais()!=null && this.getPais().equals(castOther.getPais()) ) )
 && ( (this.getProvincia()==castOther.getProvincia()) || ( this.getProvincia()!=null && castOther.getProvincia()!=null && this.getProvincia().equals(castOther.getProvincia()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPais() == null ? 0 : this.getPais().hashCode() );
         result = 37 * result + ( getProvincia() == null ? 0 : this.getProvincia().hashCode() );
         return result;
   }   


}


