package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ArinmaTa generated by hbm2java
 */
@Entity
@Table(name="ARINMA_TA"
    ,schema="DESA46"
)
public class ArinmaTa  implements java.io.Serializable {


     private ArinmaTaId id;
     private BigDecimal salAntUn;
     private BigDecimal compUn;
     private BigDecimal otrsUn;
     private BigDecimal ventUn;
     private BigDecimal consUn;
     private BigDecimal salPendUn;
     private BigDecimal entPendUn;
     private BigDecimal pedidosPend;
     private BigDecimal salAntMo;
     private BigDecimal compMon;
     private BigDecimal otrsMon;
     private BigDecimal ventMon;
     private BigDecimal consMon;
     private BigDecimal costoUni;
     private BigDecimal ultCosto;
     private BigDecimal tomFisic;
     private BigDecimal existPrep;

    public ArinmaTa() {
    }

	
    public ArinmaTa(ArinmaTaId id) {
        this.id = id;
    }
    public ArinmaTa(ArinmaTaId id, BigDecimal salAntUn, BigDecimal compUn, BigDecimal otrsUn, BigDecimal ventUn, BigDecimal consUn, BigDecimal salPendUn, BigDecimal entPendUn, BigDecimal pedidosPend, BigDecimal salAntMo, BigDecimal compMon, BigDecimal otrsMon, BigDecimal ventMon, BigDecimal consMon, BigDecimal costoUni, BigDecimal ultCosto, BigDecimal tomFisic, BigDecimal existPrep) {
       this.id = id;
       this.salAntUn = salAntUn;
       this.compUn = compUn;
       this.otrsUn = otrsUn;
       this.ventUn = ventUn;
       this.consUn = consUn;
       this.salPendUn = salPendUn;
       this.entPendUn = entPendUn;
       this.pedidosPend = pedidosPend;
       this.salAntMo = salAntMo;
       this.compMon = compMon;
       this.otrsMon = otrsMon;
       this.ventMon = ventMon;
       this.consMon = consMon;
       this.costoUni = costoUni;
       this.ultCosto = ultCosto;
       this.tomFisic = tomFisic;
       this.existPrep = existPrep;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="bodega", column=@Column(name="BODEGA", nullable=false, length=4) ), 
        @AttributeOverride(name="clase", column=@Column(name="CLASE", nullable=false, length=3) ), 
        @AttributeOverride(name="categoria", column=@Column(name="CATEGORIA", nullable=false, length=3) ), 
        @AttributeOverride(name="noArti", column=@Column(name="NO_ARTI", nullable=false, length=30) ), 
        @AttributeOverride(name="talla", column=@Column(name="TALLA", nullable=false, precision=4, scale=1) ) } )
    public ArinmaTaId getId() {
        return this.id;
    }
    
    public void setId(ArinmaTaId id) {
        this.id = id;
    }

    
    @Column(name="SAL_ANT_UN", precision=12)
    public BigDecimal getSalAntUn() {
        return this.salAntUn;
    }
    
    public void setSalAntUn(BigDecimal salAntUn) {
        this.salAntUn = salAntUn;
    }

    
    @Column(name="COMP_UN", precision=12)
    public BigDecimal getCompUn() {
        return this.compUn;
    }
    
    public void setCompUn(BigDecimal compUn) {
        this.compUn = compUn;
    }

    
    @Column(name="OTRS_UN", precision=12)
    public BigDecimal getOtrsUn() {
        return this.otrsUn;
    }
    
    public void setOtrsUn(BigDecimal otrsUn) {
        this.otrsUn = otrsUn;
    }

    
    @Column(name="VENT_UN", precision=12)
    public BigDecimal getVentUn() {
        return this.ventUn;
    }
    
    public void setVentUn(BigDecimal ventUn) {
        this.ventUn = ventUn;
    }

    
    @Column(name="CONS_UN", precision=12)
    public BigDecimal getConsUn() {
        return this.consUn;
    }
    
    public void setConsUn(BigDecimal consUn) {
        this.consUn = consUn;
    }

    
    @Column(name="SAL_PEND_UN", precision=12)
    public BigDecimal getSalPendUn() {
        return this.salPendUn;
    }
    
    public void setSalPendUn(BigDecimal salPendUn) {
        this.salPendUn = salPendUn;
    }

    
    @Column(name="ENT_PEND_UN", precision=12)
    public BigDecimal getEntPendUn() {
        return this.entPendUn;
    }
    
    public void setEntPendUn(BigDecimal entPendUn) {
        this.entPendUn = entPendUn;
    }

    
    @Column(name="PEDIDOS_PEND", precision=12)
    public BigDecimal getPedidosPend() {
        return this.pedidosPend;
    }
    
    public void setPedidosPend(BigDecimal pedidosPend) {
        this.pedidosPend = pedidosPend;
    }

    
    @Column(name="SAL_ANT_MO", precision=22)
    public BigDecimal getSalAntMo() {
        return this.salAntMo;
    }
    
    public void setSalAntMo(BigDecimal salAntMo) {
        this.salAntMo = salAntMo;
    }

    
    @Column(name="COMP_MON", precision=22)
    public BigDecimal getCompMon() {
        return this.compMon;
    }
    
    public void setCompMon(BigDecimal compMon) {
        this.compMon = compMon;
    }

    
    @Column(name="OTRS_MON", precision=22)
    public BigDecimal getOtrsMon() {
        return this.otrsMon;
    }
    
    public void setOtrsMon(BigDecimal otrsMon) {
        this.otrsMon = otrsMon;
    }

    
    @Column(name="VENT_MON", precision=22)
    public BigDecimal getVentMon() {
        return this.ventMon;
    }
    
    public void setVentMon(BigDecimal ventMon) {
        this.ventMon = ventMon;
    }

    
    @Column(name="CONS_MON", precision=22)
    public BigDecimal getConsMon() {
        return this.consMon;
    }
    
    public void setConsMon(BigDecimal consMon) {
        this.consMon = consMon;
    }

    
    @Column(name="COSTO_UNI", precision=22, scale=6)
    public BigDecimal getCostoUni() {
        return this.costoUni;
    }
    
    public void setCostoUni(BigDecimal costoUni) {
        this.costoUni = costoUni;
    }

    
    @Column(name="ULT_COSTO", precision=22, scale=6)
    public BigDecimal getUltCosto() {
        return this.ultCosto;
    }
    
    public void setUltCosto(BigDecimal ultCosto) {
        this.ultCosto = ultCosto;
    }

    
    @Column(name="TOM_FISIC", precision=12)
    public BigDecimal getTomFisic() {
        return this.tomFisic;
    }
    
    public void setTomFisic(BigDecimal tomFisic) {
        this.tomFisic = tomFisic;
    }

    
    @Column(name="EXIST_PREP", precision=12)
    public BigDecimal getExistPrep() {
        return this.existPrep;
    }
    
    public void setExistPrep(BigDecimal existPrep) {
        this.existPrep = existPrep;
    }




}


