package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArinhaId generated by hbm2java
 */
@Embeddable
public class ArinhaId  implements java.io.Serializable {


     private String noCia;
     private String centro;
     private short ano;
     private byte semana;
     private String indSem;
     private String bodega;
     private String clase;
     private String categoria;
     private String noArti;

    public ArinhaId() {
    }

    public ArinhaId(String noCia, String centro, short ano, byte semana, String indSem, String bodega, String clase, String categoria, String noArti) {
       this.noCia = noCia;
       this.centro = centro;
       this.ano = ano;
       this.semana = semana;
       this.indSem = indSem;
       this.bodega = bodega;
       this.clase = clase;
       this.categoria = categoria;
       this.noArti = noArti;
    }
   


    @Column(name="NO_CIA", nullable=false, length=2)
    public String getNoCia() {
        return this.noCia;
    }
    
    public void setNoCia(String noCia) {
        this.noCia = noCia;
    }


    @Column(name="CENTRO", nullable=false, length=2)
    public String getCentro() {
        return this.centro;
    }
    
    public void setCentro(String centro) {
        this.centro = centro;
    }


    @Column(name="ANO", nullable=false, precision=4, scale=0)
    public short getAno() {
        return this.ano;
    }
    
    public void setAno(short ano) {
        this.ano = ano;
    }


    @Column(name="SEMANA", nullable=false, precision=2, scale=0)
    public byte getSemana() {
        return this.semana;
    }
    
    public void setSemana(byte semana) {
        this.semana = semana;
    }


    @Column(name="IND_SEM", nullable=false, length=1)
    public String getIndSem() {
        return this.indSem;
    }
    
    public void setIndSem(String indSem) {
        this.indSem = indSem;
    }


    @Column(name="BODEGA", nullable=false, length=4)
    public String getBodega() {
        return this.bodega;
    }
    
    public void setBodega(String bodega) {
        this.bodega = bodega;
    }


    @Column(name="CLASE", nullable=false, length=3)
    public String getClase() {
        return this.clase;
    }
    
    public void setClase(String clase) {
        this.clase = clase;
    }


    @Column(name="CATEGORIA", nullable=false, length=3)
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }


    @Column(name="NO_ARTI", nullable=false, length=30)
    public String getNoArti() {
        return this.noArti;
    }
    
    public void setNoArti(String noArti) {
        this.noArti = noArti;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArinhaId) ) return false;
		 ArinhaId castOther = ( ArinhaId ) other; 
         
		 return ( (this.getNoCia()==castOther.getNoCia()) || ( this.getNoCia()!=null && castOther.getNoCia()!=null && this.getNoCia().equals(castOther.getNoCia()) ) )
 && ( (this.getCentro()==castOther.getCentro()) || ( this.getCentro()!=null && castOther.getCentro()!=null && this.getCentro().equals(castOther.getCentro()) ) )
 && (this.getAno()==castOther.getAno())
 && (this.getSemana()==castOther.getSemana())
 && ( (this.getIndSem()==castOther.getIndSem()) || ( this.getIndSem()!=null && castOther.getIndSem()!=null && this.getIndSem().equals(castOther.getIndSem()) ) )
 && ( (this.getBodega()==castOther.getBodega()) || ( this.getBodega()!=null && castOther.getBodega()!=null && this.getBodega().equals(castOther.getBodega()) ) )
 && ( (this.getClase()==castOther.getClase()) || ( this.getClase()!=null && castOther.getClase()!=null && this.getClase().equals(castOther.getClase()) ) )
 && ( (this.getCategoria()==castOther.getCategoria()) || ( this.getCategoria()!=null && castOther.getCategoria()!=null && this.getCategoria().equals(castOther.getCategoria()) ) )
 && ( (this.getNoArti()==castOther.getNoArti()) || ( this.getNoArti()!=null && castOther.getNoArti()!=null && this.getNoArti().equals(castOther.getNoArti()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNoCia() == null ? 0 : this.getNoCia().hashCode() );
         result = 37 * result + ( getCentro() == null ? 0 : this.getCentro().hashCode() );
         result = 37 * result + this.getAno();
         result = 37 * result + this.getSemana();
         result = 37 * result + ( getIndSem() == null ? 0 : this.getIndSem().hashCode() );
         result = 37 * result + ( getBodega() == null ? 0 : this.getBodega().hashCode() );
         result = 37 * result + ( getClase() == null ? 0 : this.getClase().hashCode() );
         result = 37 * result + ( getCategoria() == null ? 0 : this.getCategoria().hashCode() );
         result = 37 * result + ( getNoArti() == null ? 0 : this.getNoArti().hashCode() );
         return result;
   }   


}


