package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arincat generated by hbm2java
 */
@Entity
@Table(name="ARINCAT"
    ,schema="DESA46"
)
public class Arincat  implements java.io.Serializable {


     private ArincatId id;
     private String descripcion;
     private String talla;

    public Arincat() {
    }

	
    public Arincat(ArincatId id) {
        this.id = id;
    }
    public Arincat(ArincatId id, String descripcion, String talla) {
       this.id = id;
       this.descripcion = descripcion;
       this.talla = talla;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="clase", column=@Column(name="CLASE", nullable=false, length=3) ), 
        @AttributeOverride(name="codigo", column=@Column(name="CODIGO", nullable=false, length=3) ) } )
    public ArincatId getId() {
        return this.id;
    }
    
    public void setId(ArincatId id) {
        this.id = id;
    }

    
    @Column(name="DESCRIPCION", length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="TALLA", length=1)
    public String getTalla() {
        return this.talla;
    }
    
    public void setTalla(String talla) {
        this.talla = talla;
    }




}


