package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArinclId generated by hbm2java
 */
@Embeddable
public class ArinclId  implements java.io.Serializable {


     private String noCia;
     private String noArti;
     private String tipoClasif;
     private String codClasif;

    public ArinclId() {
    }

    public ArinclId(String noCia, String noArti, String tipoClasif, String codClasif) {
       this.noCia = noCia;
       this.noArti = noArti;
       this.tipoClasif = tipoClasif;
       this.codClasif = codClasif;
    }
   


    @Column(name="NO_CIA", nullable=false, length=2)
    public String getNoCia() {
        return this.noCia;
    }
    
    public void setNoCia(String noCia) {
        this.noCia = noCia;
    }


    @Column(name="NO_ARTI", nullable=false, length=30)
    public String getNoArti() {
        return this.noArti;
    }
    
    public void setNoArti(String noArti) {
        this.noArti = noArti;
    }


    @Column(name="TIPO_CLASIF", nullable=false, length=2)
    public String getTipoClasif() {
        return this.tipoClasif;
    }
    
    public void setTipoClasif(String tipoClasif) {
        this.tipoClasif = tipoClasif;
    }


    @Column(name="COD_CLASIF", nullable=false, length=15)
    public String getCodClasif() {
        return this.codClasif;
    }
    
    public void setCodClasif(String codClasif) {
        this.codClasif = codClasif;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArinclId) ) return false;
		 ArinclId castOther = ( ArinclId ) other; 
         
		 return ( (this.getNoCia()==castOther.getNoCia()) || ( this.getNoCia()!=null && castOther.getNoCia()!=null && this.getNoCia().equals(castOther.getNoCia()) ) )
 && ( (this.getNoArti()==castOther.getNoArti()) || ( this.getNoArti()!=null && castOther.getNoArti()!=null && this.getNoArti().equals(castOther.getNoArti()) ) )
 && ( (this.getTipoClasif()==castOther.getTipoClasif()) || ( this.getTipoClasif()!=null && castOther.getTipoClasif()!=null && this.getTipoClasif().equals(castOther.getTipoClasif()) ) )
 && ( (this.getCodClasif()==castOther.getCodClasif()) || ( this.getCodClasif()!=null && castOther.getCodClasif()!=null && this.getCodClasif().equals(castOther.getCodClasif()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNoCia() == null ? 0 : this.getNoCia().hashCode() );
         result = 37 * result + ( getNoArti() == null ? 0 : this.getNoArti().hashCode() );
         result = 37 * result + ( getTipoClasif() == null ? 0 : this.getTipoClasif().hashCode() );
         result = 37 * result + ( getCodClasif() == null ? 0 : this.getCodClasif().hashCode() );
         return result;
   }   


}


