package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ArinmlOc generated by hbm2java
 */
@Entity
@Table(name="ARINML_OC"
    ,schema="DESA46"
)
public class ArinmlOc  implements java.io.Serializable {


     private ArinmlOcId id;
     private String centro;
     private String tipoDoc;
     private String periodo;
     private String ruta;
     private Short lineaExt;
     private String bodega;
     private String clase;
     private String categoria;
     private String noArti;
     private String indIv;
     private BigDecimal unidades;
     private BigDecimal monto;
     private BigDecimal descuentoL;
     private BigDecimal impuestoL;
     private BigDecimal tipoCambio;
     private BigDecimal montoDol;
     private String indOferta;
     private String noOrden;
     private Byte lineaOrden;
     private String centroCosto;
     private BigDecimal impuestoLIncluido;
     private String unidadEmpaque;
     private BigDecimal cantidadEmpaque;
     private String codigoAlterno;
     private String codCurva;
     private BigDecimal montoRc;
     private BigDecimal descRc;
     private String codUbicacion;
     private String bodegaDestino;
     private BigDecimal unidadesRecep;
     private String noRefeDocu;
     private String noCiaDestino;
     private BigDecimal undTemp;
     private BigDecimal bultos;
     private BigDecimal cantidadCurva;
     private BigDecimal montoAntRc;
     private String centroReq;
     private BigDecimal unidadesDev;
     private BigDecimal montoDev;
     private String lote;
     private BigDecimal bultosRec;
     private BigDecimal montoRes;

    public ArinmlOc() {
    }

	
    public ArinmlOc(ArinmlOcId id) {
        this.id = id;
    }
    public ArinmlOc(ArinmlOcId id, String centro, String tipoDoc, String periodo, String ruta, Short lineaExt, String bodega, String clase, String categoria, String noArti, String indIv, BigDecimal unidades, BigDecimal monto, BigDecimal descuentoL, BigDecimal impuestoL, BigDecimal tipoCambio, BigDecimal montoDol, String indOferta, String noOrden, Byte lineaOrden, String centroCosto, BigDecimal impuestoLIncluido, String unidadEmpaque, BigDecimal cantidadEmpaque, String codigoAlterno, String codCurva, BigDecimal montoRc, BigDecimal descRc, String codUbicacion, String bodegaDestino, BigDecimal unidadesRecep, String noRefeDocu, String noCiaDestino, BigDecimal undTemp, BigDecimal bultos, BigDecimal cantidadCurva, BigDecimal montoAntRc, String centroReq, BigDecimal unidadesDev, BigDecimal montoDev, String lote, BigDecimal bultosRec, BigDecimal montoRes) {
       this.id = id;
       this.centro = centro;
       this.tipoDoc = tipoDoc;
       this.periodo = periodo;
       this.ruta = ruta;
       this.lineaExt = lineaExt;
       this.bodega = bodega;
       this.clase = clase;
       this.categoria = categoria;
       this.noArti = noArti;
       this.indIv = indIv;
       this.unidades = unidades;
       this.monto = monto;
       this.descuentoL = descuentoL;
       this.impuestoL = impuestoL;
       this.tipoCambio = tipoCambio;
       this.montoDol = montoDol;
       this.indOferta = indOferta;
       this.noOrden = noOrden;
       this.lineaOrden = lineaOrden;
       this.centroCosto = centroCosto;
       this.impuestoLIncluido = impuestoLIncluido;
       this.unidadEmpaque = unidadEmpaque;
       this.cantidadEmpaque = cantidadEmpaque;
       this.codigoAlterno = codigoAlterno;
       this.codCurva = codCurva;
       this.montoRc = montoRc;
       this.descRc = descRc;
       this.codUbicacion = codUbicacion;
       this.bodegaDestino = bodegaDestino;
       this.unidadesRecep = unidadesRecep;
       this.noRefeDocu = noRefeDocu;
       this.noCiaDestino = noCiaDestino;
       this.undTemp = undTemp;
       this.bultos = bultos;
       this.cantidadCurva = cantidadCurva;
       this.montoAntRc = montoAntRc;
       this.centroReq = centroReq;
       this.unidadesDev = unidadesDev;
       this.montoDev = montoDev;
       this.lote = lote;
       this.bultosRec = bultosRec;
       this.montoRes = montoRes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noDocu", column=@Column(name="NO_DOCU", nullable=false, length=12) ), 
        @AttributeOverride(name="linea", column=@Column(name="LINEA", nullable=false, precision=3, scale=0) ) } )
    public ArinmlOcId getId() {
        return this.id;
    }
    
    public void setId(ArinmlOcId id) {
        this.id = id;
    }

    
    @Column(name="CENTRO", length=2)
    public String getCentro() {
        return this.centro;
    }
    
    public void setCentro(String centro) {
        this.centro = centro;
    }

    
    @Column(name="TIPO_DOC", length=2)
    public String getTipoDoc() {
        return this.tipoDoc;
    }
    
    public void setTipoDoc(String tipoDoc) {
        this.tipoDoc = tipoDoc;
    }

    
    @Column(name="PERIODO", length=4)
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }

    
    @Column(name="RUTA", length=4)
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }

    
    @Column(name="LINEA_EXT", precision=3, scale=0)
    public Short getLineaExt() {
        return this.lineaExt;
    }
    
    public void setLineaExt(Short lineaExt) {
        this.lineaExt = lineaExt;
    }

    
    @Column(name="BODEGA", length=4)
    public String getBodega() {
        return this.bodega;
    }
    
    public void setBodega(String bodega) {
        this.bodega = bodega;
    }

    
    @Column(name="CLASE", length=3)
    public String getClase() {
        return this.clase;
    }
    
    public void setClase(String clase) {
        this.clase = clase;
    }

    
    @Column(name="CATEGORIA", length=3)
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    
    @Column(name="NO_ARTI", length=30)
    public String getNoArti() {
        return this.noArti;
    }
    
    public void setNoArti(String noArti) {
        this.noArti = noArti;
    }

    
    @Column(name="IND_IV", length=1)
    public String getIndIv() {
        return this.indIv;
    }
    
    public void setIndIv(String indIv) {
        this.indIv = indIv;
    }

    
    @Column(name="UNIDADES", precision=12)
    public BigDecimal getUnidades() {
        return this.unidades;
    }
    
    public void setUnidades(BigDecimal unidades) {
        this.unidades = unidades;
    }

    
    @Column(name="MONTO", precision=17)
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

    
    @Column(name="DESCUENTO_L", precision=17)
    public BigDecimal getDescuentoL() {
        return this.descuentoL;
    }
    
    public void setDescuentoL(BigDecimal descuentoL) {
        this.descuentoL = descuentoL;
    }

    
    @Column(name="IMPUESTO_L", precision=17)
    public BigDecimal getImpuestoL() {
        return this.impuestoL;
    }
    
    public void setImpuestoL(BigDecimal impuestoL) {
        this.impuestoL = impuestoL;
    }

    
    @Column(name="TIPO_CAMBIO", precision=17, scale=4)
    public BigDecimal getTipoCambio() {
        return this.tipoCambio;
    }
    
    public void setTipoCambio(BigDecimal tipoCambio) {
        this.tipoCambio = tipoCambio;
    }

    
    @Column(name="MONTO_DOL", precision=17)
    public BigDecimal getMontoDol() {
        return this.montoDol;
    }
    
    public void setMontoDol(BigDecimal montoDol) {
        this.montoDol = montoDol;
    }

    
    @Column(name="IND_OFERTA", length=1)
    public String getIndOferta() {
        return this.indOferta;
    }
    
    public void setIndOferta(String indOferta) {
        this.indOferta = indOferta;
    }

    
    @Column(name="NO_ORDEN", length=8)
    public String getNoOrden() {
        return this.noOrden;
    }
    
    public void setNoOrden(String noOrden) {
        this.noOrden = noOrden;
    }

    
    @Column(name="LINEA_ORDEN", precision=2, scale=0)
    public Byte getLineaOrden() {
        return this.lineaOrden;
    }
    
    public void setLineaOrden(Byte lineaOrden) {
        this.lineaOrden = lineaOrden;
    }

    
    @Column(name="CENTRO_COSTO", length=9)
    public String getCentroCosto() {
        return this.centroCosto;
    }
    
    public void setCentroCosto(String centroCosto) {
        this.centroCosto = centroCosto;
    }

    
    @Column(name="IMPUESTO_L_INCLUIDO", precision=17)
    public BigDecimal getImpuestoLIncluido() {
        return this.impuestoLIncluido;
    }
    
    public void setImpuestoLIncluido(BigDecimal impuestoLIncluido) {
        this.impuestoLIncluido = impuestoLIncluido;
    }

    
    @Column(name="UNIDAD_EMPAQUE", length=2)
    public String getUnidadEmpaque() {
        return this.unidadEmpaque;
    }
    
    public void setUnidadEmpaque(String unidadEmpaque) {
        this.unidadEmpaque = unidadEmpaque;
    }

    
    @Column(name="CANTIDAD_EMPAQUE", precision=12)
    public BigDecimal getCantidadEmpaque() {
        return this.cantidadEmpaque;
    }
    
    public void setCantidadEmpaque(BigDecimal cantidadEmpaque) {
        this.cantidadEmpaque = cantidadEmpaque;
    }

    
    @Column(name="CODIGO_ALTERNO", length=30)
    public String getCodigoAlterno() {
        return this.codigoAlterno;
    }
    
    public void setCodigoAlterno(String codigoAlterno) {
        this.codigoAlterno = codigoAlterno;
    }

    
    @Column(name="COD_CURVA", length=4)
    public String getCodCurva() {
        return this.codCurva;
    }
    
    public void setCodCurva(String codCurva) {
        this.codCurva = codCurva;
    }

    
    @Column(name="MONTO_RC", precision=17)
    public BigDecimal getMontoRc() {
        return this.montoRc;
    }
    
    public void setMontoRc(BigDecimal montoRc) {
        this.montoRc = montoRc;
    }

    
    @Column(name="DESC_RC", precision=17)
    public BigDecimal getDescRc() {
        return this.descRc;
    }
    
    public void setDescRc(BigDecimal descRc) {
        this.descRc = descRc;
    }

    
    @Column(name="COD_UBICACION", length=10)
    public String getCodUbicacion() {
        return this.codUbicacion;
    }
    
    public void setCodUbicacion(String codUbicacion) {
        this.codUbicacion = codUbicacion;
    }

    
    @Column(name="BODEGA_DESTINO", length=4)
    public String getBodegaDestino() {
        return this.bodegaDestino;
    }
    
    public void setBodegaDestino(String bodegaDestino) {
        this.bodegaDestino = bodegaDestino;
    }

    
    @Column(name="UNIDADES_RECEP", precision=12)
    public BigDecimal getUnidadesRecep() {
        return this.unidadesRecep;
    }
    
    public void setUnidadesRecep(BigDecimal unidadesRecep) {
        this.unidadesRecep = unidadesRecep;
    }

    
    @Column(name="NO_REFE_DOCU", length=12)
    public String getNoRefeDocu() {
        return this.noRefeDocu;
    }
    
    public void setNoRefeDocu(String noRefeDocu) {
        this.noRefeDocu = noRefeDocu;
    }

    
    @Column(name="NO_CIA_DESTINO", length=2)
    public String getNoCiaDestino() {
        return this.noCiaDestino;
    }
    
    public void setNoCiaDestino(String noCiaDestino) {
        this.noCiaDestino = noCiaDestino;
    }

    
    @Column(name="UND_TEMP", precision=17)
    public BigDecimal getUndTemp() {
        return this.undTemp;
    }
    
    public void setUndTemp(BigDecimal undTemp) {
        this.undTemp = undTemp;
    }

    
    @Column(name="BULTOS", precision=17)
    public BigDecimal getBultos() {
        return this.bultos;
    }
    
    public void setBultos(BigDecimal bultos) {
        this.bultos = bultos;
    }

    
    @Column(name="CANTIDAD_CURVA", precision=17)
    public BigDecimal getCantidadCurva() {
        return this.cantidadCurva;
    }
    
    public void setCantidadCurva(BigDecimal cantidadCurva) {
        this.cantidadCurva = cantidadCurva;
    }

    
    @Column(name="MONTO_ANT_RC", precision=17)
    public BigDecimal getMontoAntRc() {
        return this.montoAntRc;
    }
    
    public void setMontoAntRc(BigDecimal montoAntRc) {
        this.montoAntRc = montoAntRc;
    }

    
    @Column(name="CENTRO_REQ", length=9)
    public String getCentroReq() {
        return this.centroReq;
    }
    
    public void setCentroReq(String centroReq) {
        this.centroReq = centroReq;
    }

    
    @Column(name="UNIDADES_DEV", precision=12)
    public BigDecimal getUnidadesDev() {
        return this.unidadesDev;
    }
    
    public void setUnidadesDev(BigDecimal unidadesDev) {
        this.unidadesDev = unidadesDev;
    }

    
    @Column(name="MONTO_DEV", precision=17)
    public BigDecimal getMontoDev() {
        return this.montoDev;
    }
    
    public void setMontoDev(BigDecimal montoDev) {
        this.montoDev = montoDev;
    }

    
    @Column(name="LOTE", length=30)
    public String getLote() {
        return this.lote;
    }
    
    public void setLote(String lote) {
        this.lote = lote;
    }

    
    @Column(name="BULTOS_REC", precision=17)
    public BigDecimal getBultosRec() {
        return this.bultosRec;
    }
    
    public void setBultosRec(BigDecimal bultosRec) {
        this.bultosRec = bultosRec;
    }

    
    @Column(name="MONTO_RES", precision=30)
    public BigDecimal getMontoRes() {
        return this.montoRes;
    }
    
    public void setMontoRes(BigDecimal montoRes) {
        this.montoRes = montoRes;
    }




}


