package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArinmeAj generated by hbm2java
 */
@Entity
@Table(name="ARINME_AJ"
    ,schema="DESA46"
)
public class ArinmeAj  implements java.io.Serializable {


     private ArinmeAjId id;
     private String centro;
     private String tipoDoc;
     private String periodo;
     private String ruta;
     private String estado;
     private Date fecha;
     private String noFisico;
     private String serieFisico;
     private String conduce;
     private String noProve;
     private String tipoRefe;
     private String noRefe;
     private String serieRefe;
     private String noDocuRefe;
     private BigDecimal impVentas;
     private BigDecimal descuento;
     private BigDecimal movTot;
     private BigDecimal totArtIv;
     private String observ1;
     private BigDecimal tipoCambio;
     private BigDecimal impEspecial;
     private BigDecimal impIncluido;
     private Date fechaAplicacion;
     private BigDecimal totalGid;
     private String tmovimi;
     private String stCxp;
     private String moneda;
     private Date fechaReg;
     private Date fechaDoc;
     private Date fechaVence;
     private BigDecimal totalRet;
     private String tipoMoneda;
     private Date fechaTc;
     private String aprobacion;
     private BigDecimal porcRet;
     private String ordenCompra;
     private String estadoRec;
     private String noRefeDocu;
     private String noCiaDestino;
     private BigDecimal descC;
     private BigDecimal descP;
     private Short plazoC;
     private Short plazoP;
     private String aprReqisicion;
     private String usuarioReq;
     private String nomUsuario;
     private String noCp;
     private String noDevCom;
     private String marca;

    public ArinmeAj() {
    }

	
    public ArinmeAj(ArinmeAjId id) {
        this.id = id;
    }
    public ArinmeAj(ArinmeAjId id, String centro, String tipoDoc, String periodo, String ruta, String estado, Date fecha, String noFisico, String serieFisico, String conduce, String noProve, String tipoRefe, String noRefe, String serieRefe, String noDocuRefe, BigDecimal impVentas, BigDecimal descuento, BigDecimal movTot, BigDecimal totArtIv, String observ1, BigDecimal tipoCambio, BigDecimal impEspecial, BigDecimal impIncluido, Date fechaAplicacion, BigDecimal totalGid, String tmovimi, String stCxp, String moneda, Date fechaReg, Date fechaDoc, Date fechaVence, BigDecimal totalRet, String tipoMoneda, Date fechaTc, String aprobacion, BigDecimal porcRet, String ordenCompra, String estadoRec, String noRefeDocu, String noCiaDestino, BigDecimal descC, BigDecimal descP, Short plazoC, Short plazoP, String aprReqisicion, String usuarioReq, String nomUsuario, String noCp, String noDevCom, String marca) {
       this.id = id;
       this.centro = centro;
       this.tipoDoc = tipoDoc;
       this.periodo = periodo;
       this.ruta = ruta;
       this.estado = estado;
       this.fecha = fecha;
       this.noFisico = noFisico;
       this.serieFisico = serieFisico;
       this.conduce = conduce;
       this.noProve = noProve;
       this.tipoRefe = tipoRefe;
       this.noRefe = noRefe;
       this.serieRefe = serieRefe;
       this.noDocuRefe = noDocuRefe;
       this.impVentas = impVentas;
       this.descuento = descuento;
       this.movTot = movTot;
       this.totArtIv = totArtIv;
       this.observ1 = observ1;
       this.tipoCambio = tipoCambio;
       this.impEspecial = impEspecial;
       this.impIncluido = impIncluido;
       this.fechaAplicacion = fechaAplicacion;
       this.totalGid = totalGid;
       this.tmovimi = tmovimi;
       this.stCxp = stCxp;
       this.moneda = moneda;
       this.fechaReg = fechaReg;
       this.fechaDoc = fechaDoc;
       this.fechaVence = fechaVence;
       this.totalRet = totalRet;
       this.tipoMoneda = tipoMoneda;
       this.fechaTc = fechaTc;
       this.aprobacion = aprobacion;
       this.porcRet = porcRet;
       this.ordenCompra = ordenCompra;
       this.estadoRec = estadoRec;
       this.noRefeDocu = noRefeDocu;
       this.noCiaDestino = noCiaDestino;
       this.descC = descC;
       this.descP = descP;
       this.plazoC = plazoC;
       this.plazoP = plazoP;
       this.aprReqisicion = aprReqisicion;
       this.usuarioReq = usuarioReq;
       this.nomUsuario = nomUsuario;
       this.noCp = noCp;
       this.noDevCom = noDevCom;
       this.marca = marca;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noDocu", column=@Column(name="NO_DOCU", nullable=false, length=12) ) } )
    public ArinmeAjId getId() {
        return this.id;
    }
    
    public void setId(ArinmeAjId id) {
        this.id = id;
    }

    
    @Column(name="CENTRO", length=2)
    public String getCentro() {
        return this.centro;
    }
    
    public void setCentro(String centro) {
        this.centro = centro;
    }

    
    @Column(name="TIPO_DOC", length=2)
    public String getTipoDoc() {
        return this.tipoDoc;
    }
    
    public void setTipoDoc(String tipoDoc) {
        this.tipoDoc = tipoDoc;
    }

    
    @Column(name="PERIODO", length=4)
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }

    
    @Column(name="RUTA", length=4)
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }

    
    @Column(name="ESTADO", length=1)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", length=7)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="NO_FISICO", length=12)
    public String getNoFisico() {
        return this.noFisico;
    }
    
    public void setNoFisico(String noFisico) {
        this.noFisico = noFisico;
    }

    
    @Column(name="SERIE_FISICO", length=15)
    public String getSerieFisico() {
        return this.serieFisico;
    }
    
    public void setSerieFisico(String serieFisico) {
        this.serieFisico = serieFisico;
    }

    
    @Column(name="CONDUCE", length=10)
    public String getConduce() {
        return this.conduce;
    }
    
    public void setConduce(String conduce) {
        this.conduce = conduce;
    }

    
    @Column(name="NO_PROVE", length=15)
    public String getNoProve() {
        return this.noProve;
    }
    
    public void setNoProve(String noProve) {
        this.noProve = noProve;
    }

    
    @Column(name="TIPO_REFE", length=2)
    public String getTipoRefe() {
        return this.tipoRefe;
    }
    
    public void setTipoRefe(String tipoRefe) {
        this.tipoRefe = tipoRefe;
    }

    
    @Column(name="NO_REFE", length=12)
    public String getNoRefe() {
        return this.noRefe;
    }
    
    public void setNoRefe(String noRefe) {
        this.noRefe = noRefe;
    }

    
    @Column(name="SERIE_REFE", length=15)
    public String getSerieRefe() {
        return this.serieRefe;
    }
    
    public void setSerieRefe(String serieRefe) {
        this.serieRefe = serieRefe;
    }

    
    @Column(name="NO_DOCU_REFE", length=12)
    public String getNoDocuRefe() {
        return this.noDocuRefe;
    }
    
    public void setNoDocuRefe(String noDocuRefe) {
        this.noDocuRefe = noDocuRefe;
    }

    
    @Column(name="IMP_VENTAS", precision=17)
    public BigDecimal getImpVentas() {
        return this.impVentas;
    }
    
    public void setImpVentas(BigDecimal impVentas) {
        this.impVentas = impVentas;
    }

    
    @Column(name="DESCUENTO", precision=17)
    public BigDecimal getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(BigDecimal descuento) {
        this.descuento = descuento;
    }

    
    @Column(name="MOV_TOT", precision=17)
    public BigDecimal getMovTot() {
        return this.movTot;
    }
    
    public void setMovTot(BigDecimal movTot) {
        this.movTot = movTot;
    }

    
    @Column(name="TOT_ART_IV", precision=17)
    public BigDecimal getTotArtIv() {
        return this.totArtIv;
    }
    
    public void setTotArtIv(BigDecimal totArtIv) {
        this.totArtIv = totArtIv;
    }

    
    @Column(name="OBSERV1", length=250)
    public String getObserv1() {
        return this.observ1;
    }
    
    public void setObserv1(String observ1) {
        this.observ1 = observ1;
    }

    
    @Column(name="TIPO_CAMBIO", precision=17, scale=4)
    public BigDecimal getTipoCambio() {
        return this.tipoCambio;
    }
    
    public void setTipoCambio(BigDecimal tipoCambio) {
        this.tipoCambio = tipoCambio;
    }

    
    @Column(name="IMP_ESPECIAL", precision=17)
    public BigDecimal getImpEspecial() {
        return this.impEspecial;
    }
    
    public void setImpEspecial(BigDecimal impEspecial) {
        this.impEspecial = impEspecial;
    }

    
    @Column(name="IMP_INCLUIDO", precision=17)
    public BigDecimal getImpIncluido() {
        return this.impIncluido;
    }
    
    public void setImpIncluido(BigDecimal impIncluido) {
        this.impIncluido = impIncluido;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_APLICACION", length=7)
    public Date getFechaAplicacion() {
        return this.fechaAplicacion;
    }
    
    public void setFechaAplicacion(Date fechaAplicacion) {
        this.fechaAplicacion = fechaAplicacion;
    }

    
    @Column(name="TOTAL_GID", precision=17)
    public BigDecimal getTotalGid() {
        return this.totalGid;
    }
    
    public void setTotalGid(BigDecimal totalGid) {
        this.totalGid = totalGid;
    }

    
    @Column(name="TMOVIMI", length=1)
    public String getTmovimi() {
        return this.tmovimi;
    }
    
    public void setTmovimi(String tmovimi) {
        this.tmovimi = tmovimi;
    }

    
    @Column(name="ST_CXP", length=1)
    public String getStCxp() {
        return this.stCxp;
    }
    
    public void setStCxp(String stCxp) {
        this.stCxp = stCxp;
    }

    
    @Column(name="MONEDA", length=3)
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_REG", length=7)
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_DOC", length=7)
    public Date getFechaDoc() {
        return this.fechaDoc;
    }
    
    public void setFechaDoc(Date fechaDoc) {
        this.fechaDoc = fechaDoc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_VENCE", length=7)
    public Date getFechaVence() {
        return this.fechaVence;
    }
    
    public void setFechaVence(Date fechaVence) {
        this.fechaVence = fechaVence;
    }

    
    @Column(name="TOTAL_RET", precision=17)
    public BigDecimal getTotalRet() {
        return this.totalRet;
    }
    
    public void setTotalRet(BigDecimal totalRet) {
        this.totalRet = totalRet;
    }

    
    @Column(name="TIPO_MONEDA", length=4)
    public String getTipoMoneda() {
        return this.tipoMoneda;
    }
    
    public void setTipoMoneda(String tipoMoneda) {
        this.tipoMoneda = tipoMoneda;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_TC", length=7)
    public Date getFechaTc() {
        return this.fechaTc;
    }
    
    public void setFechaTc(Date fechaTc) {
        this.fechaTc = fechaTc;
    }

    
    @Column(name="APROBACION", length=1)
    public String getAprobacion() {
        return this.aprobacion;
    }
    
    public void setAprobacion(String aprobacion) {
        this.aprobacion = aprobacion;
    }

    
    @Column(name="PORC_RET", precision=17)
    public BigDecimal getPorcRet() {
        return this.porcRet;
    }
    
    public void setPorcRet(BigDecimal porcRet) {
        this.porcRet = porcRet;
    }

    
    @Column(name="ORDEN_COMPRA", length=12)
    public String getOrdenCompra() {
        return this.ordenCompra;
    }
    
    public void setOrdenCompra(String ordenCompra) {
        this.ordenCompra = ordenCompra;
    }

    
    @Column(name="ESTADO_REC", length=1)
    public String getEstadoRec() {
        return this.estadoRec;
    }
    
    public void setEstadoRec(String estadoRec) {
        this.estadoRec = estadoRec;
    }

    
    @Column(name="NO_REFE_DOCU", length=12)
    public String getNoRefeDocu() {
        return this.noRefeDocu;
    }
    
    public void setNoRefeDocu(String noRefeDocu) {
        this.noRefeDocu = noRefeDocu;
    }

    
    @Column(name="NO_CIA_DESTINO", length=2)
    public String getNoCiaDestino() {
        return this.noCiaDestino;
    }
    
    public void setNoCiaDestino(String noCiaDestino) {
        this.noCiaDestino = noCiaDestino;
    }

    
    @Column(name="DESC_C", precision=5)
    public BigDecimal getDescC() {
        return this.descC;
    }
    
    public void setDescC(BigDecimal descC) {
        this.descC = descC;
    }

    
    @Column(name="DESC_P", precision=5)
    public BigDecimal getDescP() {
        return this.descP;
    }
    
    public void setDescP(BigDecimal descP) {
        this.descP = descP;
    }

    
    @Column(name="PLAZO_C", precision=3, scale=0)
    public Short getPlazoC() {
        return this.plazoC;
    }
    
    public void setPlazoC(Short plazoC) {
        this.plazoC = plazoC;
    }

    
    @Column(name="PLAZO_P", precision=3, scale=0)
    public Short getPlazoP() {
        return this.plazoP;
    }
    
    public void setPlazoP(Short plazoP) {
        this.plazoP = plazoP;
    }

    
    @Column(name="APR_REQISICION", length=1)
    public String getAprReqisicion() {
        return this.aprReqisicion;
    }
    
    public void setAprReqisicion(String aprReqisicion) {
        this.aprReqisicion = aprReqisicion;
    }

    
    @Column(name="USUARIO_REQ", length=50)
    public String getUsuarioReq() {
        return this.usuarioReq;
    }
    
    public void setUsuarioReq(String usuarioReq) {
        this.usuarioReq = usuarioReq;
    }

    
    @Column(name="NOM_USUARIO", length=200)
    public String getNomUsuario() {
        return this.nomUsuario;
    }
    
    public void setNomUsuario(String nomUsuario) {
        this.nomUsuario = nomUsuario;
    }

    
    @Column(name="NO_CP", length=12)
    public String getNoCp() {
        return this.noCp;
    }
    
    public void setNoCp(String noCp) {
        this.noCp = noCp;
    }

    
    @Column(name="NO_DEV_COM", length=12)
    public String getNoDevCom() {
        return this.noDevCom;
    }
    
    public void setNoDevCom(String noDevCom) {
        this.noDevCom = noDevCom;
    }

    
    @Column(name="MARCA", length=1)
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }




}


