package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arinmt generated by hbm2java
 */
@Entity
@Table(name="ARINMT"
    ,schema="DESA46"
)
public class Arinmt  implements java.io.Serializable {


     private ArinmtId id;
     private String centro;
     private String tipoDoc;
     private String ano;
     private String ruta;
     private String bodega;
     private String clase;
     private String categoria;
     private String noArti;
     private BigDecimal unidades;
     private BigDecimal venta;
     private BigDecimal descuento;
     private BigDecimal costoUni;
     private BigDecimal costoInd;

    public Arinmt() {
    }

	
    public Arinmt(ArinmtId id) {
        this.id = id;
    }
    public Arinmt(ArinmtId id, String centro, String tipoDoc, String ano, String ruta, String bodega, String clase, String categoria, String noArti, BigDecimal unidades, BigDecimal venta, BigDecimal descuento, BigDecimal costoUni, BigDecimal costoInd) {
       this.id = id;
       this.centro = centro;
       this.tipoDoc = tipoDoc;
       this.ano = ano;
       this.ruta = ruta;
       this.bodega = bodega;
       this.clase = clase;
       this.categoria = categoria;
       this.noArti = noArti;
       this.unidades = unidades;
       this.venta = venta;
       this.descuento = descuento;
       this.costoUni = costoUni;
       this.costoInd = costoInd;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noDocu", column=@Column(name="NO_DOCU", nullable=false, length=12) ), 
        @AttributeOverride(name="noLinea", column=@Column(name="NO_LINEA", nullable=false, precision=3, scale=0) ), 
        @AttributeOverride(name="ubicacion", column=@Column(name="UBICACION", nullable=false, length=10) ), 
        @AttributeOverride(name="noLote", column=@Column(name="NO_LOTE", nullable=false, length=30) ), 
        @AttributeOverride(name="talla", column=@Column(name="TALLA", nullable=false, precision=4, scale=1) ) } )
    public ArinmtId getId() {
        return this.id;
    }
    
    public void setId(ArinmtId id) {
        this.id = id;
    }

    
    @Column(name="CENTRO", length=2)
    public String getCentro() {
        return this.centro;
    }
    
    public void setCentro(String centro) {
        this.centro = centro;
    }

    
    @Column(name="TIPO_DOC", length=2)
    public String getTipoDoc() {
        return this.tipoDoc;
    }
    
    public void setTipoDoc(String tipoDoc) {
        this.tipoDoc = tipoDoc;
    }

    
    @Column(name="ANO", length=4)
    public String getAno() {
        return this.ano;
    }
    
    public void setAno(String ano) {
        this.ano = ano;
    }

    
    @Column(name="RUTA", length=4)
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }

    
    @Column(name="BODEGA", length=4)
    public String getBodega() {
        return this.bodega;
    }
    
    public void setBodega(String bodega) {
        this.bodega = bodega;
    }

    
    @Column(name="CLASE", length=3)
    public String getClase() {
        return this.clase;
    }
    
    public void setClase(String clase) {
        this.clase = clase;
    }

    
    @Column(name="CATEGORIA", length=3)
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    
    @Column(name="NO_ARTI", length=30)
    public String getNoArti() {
        return this.noArti;
    }
    
    public void setNoArti(String noArti) {
        this.noArti = noArti;
    }

    
    @Column(name="UNIDADES", precision=17)
    public BigDecimal getUnidades() {
        return this.unidades;
    }
    
    public void setUnidades(BigDecimal unidades) {
        this.unidades = unidades;
    }

    
    @Column(name="VENTA", precision=22)
    public BigDecimal getVenta() {
        return this.venta;
    }
    
    public void setVenta(BigDecimal venta) {
        this.venta = venta;
    }

    
    @Column(name="DESCUENTO", precision=22)
    public BigDecimal getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(BigDecimal descuento) {
        this.descuento = descuento;
    }

    
    @Column(name="COSTO_UNI", precision=22)
    public BigDecimal getCostoUni() {
        return this.costoUni;
    }
    
    public void setCostoUni(BigDecimal costoUni) {
        this.costoUni = costoUni;
    }

    
    @Column(name="COSTO_IND", precision=22)
    public BigDecimal getCostoInd() {
        return this.costoInd;
    }
    
    public void setCostoInd(BigDecimal costoInd) {
        this.costoInd = costoInd;
    }




}


