package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArinmtId generated by hbm2java
 */
@Embeddable
public class ArinmtId  implements java.io.Serializable {


     private String noCia;
     private String noDocu;
     private short noLinea;
     private String ubicacion;
     private String noLote;
     private BigDecimal talla;

    public ArinmtId() {
    }

    public ArinmtId(String noCia, String noDocu, short noLinea, String ubicacion, String noLote, BigDecimal talla) {
       this.noCia = noCia;
       this.noDocu = noDocu;
       this.noLinea = noLinea;
       this.ubicacion = ubicacion;
       this.noLote = noLote;
       this.talla = talla;
    }
   


    @Column(name="NO_CIA", nullable=false, length=2)
    public String getNoCia() {
        return this.noCia;
    }
    
    public void setNoCia(String noCia) {
        this.noCia = noCia;
    }


    @Column(name="NO_DOCU", nullable=false, length=12)
    public String getNoDocu() {
        return this.noDocu;
    }
    
    public void setNoDocu(String noDocu) {
        this.noDocu = noDocu;
    }


    @Column(name="NO_LINEA", nullable=false, precision=3, scale=0)
    public short getNoLinea() {
        return this.noLinea;
    }
    
    public void setNoLinea(short noLinea) {
        this.noLinea = noLinea;
    }


    @Column(name="UBICACION", nullable=false, length=10)
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }


    @Column(name="NO_LOTE", nullable=false, length=30)
    public String getNoLote() {
        return this.noLote;
    }
    
    public void setNoLote(String noLote) {
        this.noLote = noLote;
    }


    @Column(name="TALLA", nullable=false, precision=4, scale=1)
    public BigDecimal getTalla() {
        return this.talla;
    }
    
    public void setTalla(BigDecimal talla) {
        this.talla = talla;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArinmtId) ) return false;
		 ArinmtId castOther = ( ArinmtId ) other; 
         
		 return ( (this.getNoCia()==castOther.getNoCia()) || ( this.getNoCia()!=null && castOther.getNoCia()!=null && this.getNoCia().equals(castOther.getNoCia()) ) )
 && ( (this.getNoDocu()==castOther.getNoDocu()) || ( this.getNoDocu()!=null && castOther.getNoDocu()!=null && this.getNoDocu().equals(castOther.getNoDocu()) ) )
 && (this.getNoLinea()==castOther.getNoLinea())
 && ( (this.getUbicacion()==castOther.getUbicacion()) || ( this.getUbicacion()!=null && castOther.getUbicacion()!=null && this.getUbicacion().equals(castOther.getUbicacion()) ) )
 && ( (this.getNoLote()==castOther.getNoLote()) || ( this.getNoLote()!=null && castOther.getNoLote()!=null && this.getNoLote().equals(castOther.getNoLote()) ) )
 && ( (this.getTalla()==castOther.getTalla()) || ( this.getTalla()!=null && castOther.getTalla()!=null && this.getTalla().equals(castOther.getTalla()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNoCia() == null ? 0 : this.getNoCia().hashCode() );
         result = 37 * result + ( getNoDocu() == null ? 0 : this.getNoDocu().hashCode() );
         result = 37 * result + this.getNoLinea();
         result = 37 * result + ( getUbicacion() == null ? 0 : this.getUbicacion().hashCode() );
         result = 37 * result + ( getNoLote() == null ? 0 : this.getNoLote().hashCode() );
         result = 37 * result + ( getTalla() == null ? 0 : this.getTalla().hashCode() );
         return result;
   }   


}


