package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arinmn generated by hbm2java
 */
@Entity
@Table(name="ARINMN"
    ,schema="DESA46"
)
public class Arinmn  implements java.io.Serializable {


     private ArinmnId id;
     private String centro;
     private String tipoDoc;
     private String ano;
     private String ruta;
     private String bodega;
     private String clase;
     private String categoria;
     private String noArti;
     private BigDecimal costoUni;
     private Date fecha;
     private BigDecimal unidades;
     private BigDecimal monto;
     private BigDecimal costo;
     private BigDecimal costoAnt;
     private String vendedor;
     private BigDecimal venta;
     private BigDecimal descuento;
     private String indOferta;
     private String tipoRefe;
     private String noRefe;
     private String conduce;
     private String observ1;
     private String noProve;
     private Date timeStamp;
     private Byte mes;
     private String periodoProce;
     private Byte semana;
     private String centroCosto;
     private BigDecimal cantidadRecibida;
     private String bodega2;
     private String razon;
     private Date tstamp;
     private BigDecimal pedidoOriginal;
     private BigDecimal costoUniRes;
     private BigDecimal montoRes;
     private BigDecimal costoRes;
     private BigDecimal costoAntRes;

    public Arinmn() {
    }

	
    public Arinmn(ArinmnId id) {
        this.id = id;
    }
    public Arinmn(ArinmnId id, String centro, String tipoDoc, String ano, String ruta, String bodega, String clase, String categoria, String noArti, BigDecimal costoUni, Date fecha, BigDecimal unidades, BigDecimal monto, BigDecimal costo, BigDecimal costoAnt, String vendedor, BigDecimal venta, BigDecimal descuento, String indOferta, String tipoRefe, String noRefe, String conduce, String observ1, String noProve, Date timeStamp, Byte mes, String periodoProce, Byte semana, String centroCosto, BigDecimal cantidadRecibida, String bodega2, String razon, Date tstamp, BigDecimal pedidoOriginal, BigDecimal costoUniRes, BigDecimal montoRes, BigDecimal costoRes, BigDecimal costoAntRes) {
       this.id = id;
       this.centro = centro;
       this.tipoDoc = tipoDoc;
       this.ano = ano;
       this.ruta = ruta;
       this.bodega = bodega;
       this.clase = clase;
       this.categoria = categoria;
       this.noArti = noArti;
       this.costoUni = costoUni;
       this.fecha = fecha;
       this.unidades = unidades;
       this.monto = monto;
       this.costo = costo;
       this.costoAnt = costoAnt;
       this.vendedor = vendedor;
       this.venta = venta;
       this.descuento = descuento;
       this.indOferta = indOferta;
       this.tipoRefe = tipoRefe;
       this.noRefe = noRefe;
       this.conduce = conduce;
       this.observ1 = observ1;
       this.noProve = noProve;
       this.timeStamp = timeStamp;
       this.mes = mes;
       this.periodoProce = periodoProce;
       this.semana = semana;
       this.centroCosto = centroCosto;
       this.cantidadRecibida = cantidadRecibida;
       this.bodega2 = bodega2;
       this.razon = razon;
       this.tstamp = tstamp;
       this.pedidoOriginal = pedidoOriginal;
       this.costoUniRes = costoUniRes;
       this.montoRes = montoRes;
       this.costoRes = costoRes;
       this.costoAntRes = costoAntRes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noDocu", column=@Column(name="NO_DOCU", nullable=false, length=12) ), 
        @AttributeOverride(name="noLinea", column=@Column(name="NO_LINEA", nullable=false, precision=4, scale=0) ) } )
    public ArinmnId getId() {
        return this.id;
    }
    
    public void setId(ArinmnId id) {
        this.id = id;
    }

    
    @Column(name="CENTRO", length=2)
    public String getCentro() {
        return this.centro;
    }
    
    public void setCentro(String centro) {
        this.centro = centro;
    }

    
    @Column(name="TIPO_DOC", length=2)
    public String getTipoDoc() {
        return this.tipoDoc;
    }
    
    public void setTipoDoc(String tipoDoc) {
        this.tipoDoc = tipoDoc;
    }

    
    @Column(name="ANO", length=4)
    public String getAno() {
        return this.ano;
    }
    
    public void setAno(String ano) {
        this.ano = ano;
    }

    
    @Column(name="RUTA", length=4)
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }

    
    @Column(name="BODEGA", length=4)
    public String getBodega() {
        return this.bodega;
    }
    
    public void setBodega(String bodega) {
        this.bodega = bodega;
    }

    
    @Column(name="CLASE", length=3)
    public String getClase() {
        return this.clase;
    }
    
    public void setClase(String clase) {
        this.clase = clase;
    }

    
    @Column(name="CATEGORIA", length=3)
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    
    @Column(name="NO_ARTI", length=30)
    public String getNoArti() {
        return this.noArti;
    }
    
    public void setNoArti(String noArti) {
        this.noArti = noArti;
    }

    
    @Column(name="COSTO_UNI", precision=22, scale=6)
    public BigDecimal getCostoUni() {
        return this.costoUni;
    }
    
    public void setCostoUni(BigDecimal costoUni) {
        this.costoUni = costoUni;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", length=7)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="UNIDADES", precision=17)
    public BigDecimal getUnidades() {
        return this.unidades;
    }
    
    public void setUnidades(BigDecimal unidades) {
        this.unidades = unidades;
    }

    
    @Column(name="MONTO", precision=22)
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

    
    @Column(name="COSTO", precision=22)
    public BigDecimal getCosto() {
        return this.costo;
    }
    
    public void setCosto(BigDecimal costo) {
        this.costo = costo;
    }

    
    @Column(name="COSTO_ANT", precision=22)
    public BigDecimal getCostoAnt() {
        return this.costoAnt;
    }
    
    public void setCostoAnt(BigDecimal costoAnt) {
        this.costoAnt = costoAnt;
    }

    
    @Column(name="VENDEDOR", length=4)
    public String getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(String vendedor) {
        this.vendedor = vendedor;
    }

    
    @Column(name="VENTA", precision=22)
    public BigDecimal getVenta() {
        return this.venta;
    }
    
    public void setVenta(BigDecimal venta) {
        this.venta = venta;
    }

    
    @Column(name="DESCUENTO", precision=22)
    public BigDecimal getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(BigDecimal descuento) {
        this.descuento = descuento;
    }

    
    @Column(name="IND_OFERTA", length=1)
    public String getIndOferta() {
        return this.indOferta;
    }
    
    public void setIndOferta(String indOferta) {
        this.indOferta = indOferta;
    }

    
    @Column(name="TIPO_REFE", length=2)
    public String getTipoRefe() {
        return this.tipoRefe;
    }
    
    public void setTipoRefe(String tipoRefe) {
        this.tipoRefe = tipoRefe;
    }

    
    @Column(name="NO_REFE", length=12)
    public String getNoRefe() {
        return this.noRefe;
    }
    
    public void setNoRefe(String noRefe) {
        this.noRefe = noRefe;
    }

    
    @Column(name="CONDUCE", length=10)
    public String getConduce() {
        return this.conduce;
    }
    
    public void setConduce(String conduce) {
        this.conduce = conduce;
    }

    
    @Column(name="OBSERV1", length=250)
    public String getObserv1() {
        return this.observ1;
    }
    
    public void setObserv1(String observ1) {
        this.observ1 = observ1;
    }

    
    @Column(name="NO_PROVE", length=15)
    public String getNoProve() {
        return this.noProve;
    }
    
    public void setNoProve(String noProve) {
        this.noProve = noProve;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TIME_STAMP", length=7)
    public Date getTimeStamp() {
        return this.timeStamp;
    }
    
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    
    @Column(name="MES", precision=2, scale=0)
    public Byte getMes() {
        return this.mes;
    }
    
    public void setMes(Byte mes) {
        this.mes = mes;
    }

    
    @Column(name="PERIODO_PROCE", length=7)
    public String getPeriodoProce() {
        return this.periodoProce;
    }
    
    public void setPeriodoProce(String periodoProce) {
        this.periodoProce = periodoProce;
    }

    
    @Column(name="SEMANA", precision=2, scale=0)
    public Byte getSemana() {
        return this.semana;
    }
    
    public void setSemana(Byte semana) {
        this.semana = semana;
    }

    
    @Column(name="CENTRO_COSTO", length=9)
    public String getCentroCosto() {
        return this.centroCosto;
    }
    
    public void setCentroCosto(String centroCosto) {
        this.centroCosto = centroCosto;
    }

    
    @Column(name="CANTIDAD_RECIBIDA", precision=12)
    public BigDecimal getCantidadRecibida() {
        return this.cantidadRecibida;
    }
    
    public void setCantidadRecibida(BigDecimal cantidadRecibida) {
        this.cantidadRecibida = cantidadRecibida;
    }

    
    @Column(name="BODEGA2", length=4)
    public String getBodega2() {
        return this.bodega2;
    }
    
    public void setBodega2(String bodega2) {
        this.bodega2 = bodega2;
    }

    
    @Column(name="RAZON", length=4)
    public String getRazon() {
        return this.razon;
    }
    
    public void setRazon(String razon) {
        this.razon = razon;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TSTAMP", length=7)
    public Date getTstamp() {
        return this.tstamp;
    }
    
    public void setTstamp(Date tstamp) {
        this.tstamp = tstamp;
    }

    
    @Column(name="PEDIDO_ORIGINAL", precision=12)
    public BigDecimal getPedidoOriginal() {
        return this.pedidoOriginal;
    }
    
    public void setPedidoOriginal(BigDecimal pedidoOriginal) {
        this.pedidoOriginal = pedidoOriginal;
    }

    
    @Column(name="COSTO_UNI_RES", precision=30)
    public BigDecimal getCostoUniRes() {
        return this.costoUniRes;
    }
    
    public void setCostoUniRes(BigDecimal costoUniRes) {
        this.costoUniRes = costoUniRes;
    }

    
    @Column(name="MONTO_RES", precision=30)
    public BigDecimal getMontoRes() {
        return this.montoRes;
    }
    
    public void setMontoRes(BigDecimal montoRes) {
        this.montoRes = montoRes;
    }

    
    @Column(name="COSTO_RES", precision=30)
    public BigDecimal getCostoRes() {
        return this.costoRes;
    }
    
    public void setCostoRes(BigDecimal costoRes) {
        this.costoRes = costoRes;
    }

    
    @Column(name="COSTO_ANT_RES", precision=30)
    public BigDecimal getCostoAntRes() {
        return this.costoAntRes;
    }
    
    public void setCostoAntRes(BigDecimal costoAntRes) {
        this.costoAntRes = costoAntRes;
    }




}


