package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArinecId generated by hbm2java
 */
@Embeddable
public class ArinecId  implements java.io.Serializable {


     private String codCurva;
     private BigDecimal talla;

    public ArinecId() {
    }

    public ArinecId(String codCurva, BigDecimal talla) {
       this.codCurva = codCurva;
       this.talla = talla;
    }
   


    @Column(name="COD_CURVA", nullable=false, length=4)
    public String getCodCurva() {
        return this.codCurva;
    }
    
    public void setCodCurva(String codCurva) {
        this.codCurva = codCurva;
    }


    @Column(name="TALLA", nullable=false, precision=4, scale=1)
    public BigDecimal getTalla() {
        return this.talla;
    }
    
    public void setTalla(BigDecimal talla) {
        this.talla = talla;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArinecId) ) return false;
		 ArinecId castOther = ( ArinecId ) other; 
         
		 return ( (this.getCodCurva()==castOther.getCodCurva()) || ( this.getCodCurva()!=null && castOther.getCodCurva()!=null && this.getCodCurva().equals(castOther.getCodCurva()) ) )
 && ( (this.getTalla()==castOther.getTalla()) || ( this.getTalla()!=null && castOther.getTalla()!=null && this.getTalla().equals(castOther.getTalla()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodCurva() == null ? 0 : this.getCodCurva().hashCode() );
         result = 37 * result + ( getTalla() == null ? 0 : this.getTalla().hashCode() );
         return result;
   }   


}


