package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Arinii generated by hbm2java
 */
@Entity
@Table(name="ARINII"
    ,schema="DESA46"
)
public class Arinii  implements java.io.Serializable {


     private String idRazon;
     private String tipoMov;
     private String interface_;
     private String descripcion;

    public Arinii() {
    }

	
    public Arinii(String idRazon) {
        this.idRazon = idRazon;
    }
    public Arinii(String idRazon, String tipoMov, String interface_, String descripcion) {
       this.idRazon = idRazon;
       this.tipoMov = tipoMov;
       this.interface_ = interface_;
       this.descripcion = descripcion;
    }
   
     @Id 

    
    @Column(name="ID_RAZON", unique=true, nullable=false, length=2)
    public String getIdRazon() {
        return this.idRazon;
    }
    
    public void setIdRazon(String idRazon) {
        this.idRazon = idRazon;
    }

    
    @Column(name="TIPO_MOV", length=1)
    public String getTipoMov() {
        return this.tipoMov;
    }
    
    public void setTipoMov(String tipoMov) {
        this.tipoMov = tipoMov;
    }

    
    @Column(name="INTERFACE", length=2)
    public String getInterface_() {
        return this.interface_;
    }
    
    public void setInterface_(String interface_) {
        this.interface_ = interface_;
    }

    
    @Column(name="DESCRIPCION", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


