package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arinbo generated by hbm2java
 */
@Entity
@Table(name="ARINBO"
    ,schema="DESA46"
)
public class Arinbo  implements java.io.Serializable {


     private ArinboId id;
     private String descripcion;
     private String tipobodega;
     private String centro;
     private String vendedor;
     private String codigoEstado;
     private String esTienda;
     private Date tstamp;

    public Arinbo() {
    }

	
    public Arinbo(ArinboId id) {
        this.id = id;
    }
    public Arinbo(ArinboId id, String descripcion, String tipobodega, String centro, String vendedor, String codigoEstado, String esTienda, Date tstamp) {
       this.id = id;
       this.descripcion = descripcion;
       this.tipobodega = tipobodega;
       this.centro = centro;
       this.vendedor = vendedor;
       this.codigoEstado = codigoEstado;
       this.esTienda = esTienda;
       this.tstamp = tstamp;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="codigo", column=@Column(name="CODIGO", nullable=false, length=4) ) } )
    public ArinboId getId() {
        return this.id;
    }
    
    public void setId(ArinboId id) {
        this.id = id;
    }

    
    @Column(name="DESCRIPCION", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="TIPOBODEGA", length=1)
    public String getTipobodega() {
        return this.tipobodega;
    }
    
    public void setTipobodega(String tipobodega) {
        this.tipobodega = tipobodega;
    }

    
    @Column(name="CENTRO", length=2)
    public String getCentro() {
        return this.centro;
    }
    
    public void setCentro(String centro) {
        this.centro = centro;
    }

    
    @Column(name="VENDEDOR", length=4)
    public String getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(String vendedor) {
        this.vendedor = vendedor;
    }

    
    @Column(name="CODIGO_ESTADO", length=4)
    public String getCodigoEstado() {
        return this.codigoEstado;
    }
    
    public void setCodigoEstado(String codigoEstado) {
        this.codigoEstado = codigoEstado;
    }

    
    @Column(name="ES_TIENDA", length=1)
    public String getEsTienda() {
        return this.esTienda;
    }
    
    public void setEsTienda(String esTienda) {
        this.esTienda = esTienda;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TSTAMP", length=7)
    public Date getTstamp() {
        return this.tstamp;
    }
    
    public void setTstamp(Date tstamp) {
        this.tstamp = tstamp;
    }




}


