package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arinrelacion generated by hbm2java
 */
@Entity
@Table(name="ARINRELACION"
    ,schema="DESA46"
)
public class Arinrelacion  implements java.io.Serializable {


     private ArinrelacionId id;
     private String modelo;
     private String color;
     private String escala;
     private BigDecimal cantidadempaque;
     private String nomModelo;
     private String nomColor;
     private String nomEscala;
     private String catalogo;
     private String marca;
     private BigDecimal pvp;
     private BigDecimal oferta;
     private BigDecimal inventario;
     private String tipoInv;
     private String status;
     private String demActiva;
     private BigDecimal demAsignada;
     private Date fechaRelacion;
     private BigDecimal demReasignada;
     private String descripcion;
     private BigDecimal pvpRes;

    public Arinrelacion() {
    }

	
    public Arinrelacion(ArinrelacionId id) {
        this.id = id;
    }
    public Arinrelacion(ArinrelacionId id, String modelo, String color, String escala, BigDecimal cantidadempaque, String nomModelo, String nomColor, String nomEscala, String catalogo, String marca, BigDecimal pvp, BigDecimal oferta, BigDecimal inventario, String tipoInv, String status, String demActiva, BigDecimal demAsignada, Date fechaRelacion, BigDecimal demReasignada, String descripcion, BigDecimal pvpRes) {
       this.id = id;
       this.modelo = modelo;
       this.color = color;
       this.escala = escala;
       this.cantidadempaque = cantidadempaque;
       this.nomModelo = nomModelo;
       this.nomColor = nomColor;
       this.nomEscala = nomEscala;
       this.catalogo = catalogo;
       this.marca = marca;
       this.pvp = pvp;
       this.oferta = oferta;
       this.inventario = inventario;
       this.tipoInv = tipoInv;
       this.status = status;
       this.demActiva = demActiva;
       this.demAsignada = demAsignada;
       this.fechaRelacion = fechaRelacion;
       this.demReasignada = demReasignada;
       this.descripcion = descripcion;
       this.pvpRes = pvpRes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=3) ), 
        @AttributeOverride(name="noArti", column=@Column(name="NO_ARTI", nullable=false, length=30) ), 
        @AttributeOverride(name="vendedor", column=@Column(name="VENDEDOR", nullable=false, length=3) ), 
        @AttributeOverride(name="barra", column=@Column(name="BARRA", nullable=false, length=24) ) } )
    public ArinrelacionId getId() {
        return this.id;
    }
    
    public void setId(ArinrelacionId id) {
        this.id = id;
    }

    
    @Column(name="MODELO", length=15)
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    
    @Column(name="COLOR", length=4)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }

    
    @Column(name="ESCALA", length=5)
    public String getEscala() {
        return this.escala;
    }
    
    public void setEscala(String escala) {
        this.escala = escala;
    }

    
    @Column(name="CANTIDADEMPAQUE", precision=22, scale=0)
    public BigDecimal getCantidadempaque() {
        return this.cantidadempaque;
    }
    
    public void setCantidadempaque(BigDecimal cantidadempaque) {
        this.cantidadempaque = cantidadempaque;
    }

    
    @Column(name="NOM_MODELO", length=35)
    public String getNomModelo() {
        return this.nomModelo;
    }
    
    public void setNomModelo(String nomModelo) {
        this.nomModelo = nomModelo;
    }

    
    @Column(name="NOM_COLOR", length=30)
    public String getNomColor() {
        return this.nomColor;
    }
    
    public void setNomColor(String nomColor) {
        this.nomColor = nomColor;
    }

    
    @Column(name="NOM_ESCALA", length=30)
    public String getNomEscala() {
        return this.nomEscala;
    }
    
    public void setNomEscala(String nomEscala) {
        this.nomEscala = nomEscala;
    }

    
    @Column(name="CATALOGO", length=30)
    public String getCatalogo() {
        return this.catalogo;
    }
    
    public void setCatalogo(String catalogo) {
        this.catalogo = catalogo;
    }

    
    @Column(name="MARCA", length=3)
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }

    
    @Column(name="PVP", precision=22, scale=0)
    public BigDecimal getPvp() {
        return this.pvp;
    }
    
    public void setPvp(BigDecimal pvp) {
        this.pvp = pvp;
    }

    
    @Column(name="OFERTA", precision=22, scale=0)
    public BigDecimal getOferta() {
        return this.oferta;
    }
    
    public void setOferta(BigDecimal oferta) {
        this.oferta = oferta;
    }

    
    @Column(name="INVENTARIO", precision=22, scale=0)
    public BigDecimal getInventario() {
        return this.inventario;
    }
    
    public void setInventario(BigDecimal inventario) {
        this.inventario = inventario;
    }

    
    @Column(name="TIPO_INV", length=1)
    public String getTipoInv() {
        return this.tipoInv;
    }
    
    public void setTipoInv(String tipoInv) {
        this.tipoInv = tipoInv;
    }

    
    @Column(name="STATUS", length=3)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="DEM_ACTIVA", length=3)
    public String getDemActiva() {
        return this.demActiva;
    }
    
    public void setDemActiva(String demActiva) {
        this.demActiva = demActiva;
    }

    
    @Column(name="DEM_ASIGNADA", precision=22, scale=0)
    public BigDecimal getDemAsignada() {
        return this.demAsignada;
    }
    
    public void setDemAsignada(BigDecimal demAsignada) {
        this.demAsignada = demAsignada;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_RELACION", length=7)
    public Date getFechaRelacion() {
        return this.fechaRelacion;
    }
    
    public void setFechaRelacion(Date fechaRelacion) {
        this.fechaRelacion = fechaRelacion;
    }

    
    @Column(name="DEM_REASIGNADA", precision=22, scale=0)
    public BigDecimal getDemReasignada() {
        return this.demReasignada;
    }
    
    public void setDemReasignada(BigDecimal demReasignada) {
        this.demReasignada = demReasignada;
    }

    
    @Column(name="DESCRIPCION", length=80)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="PVP_RES", precision=30)
    public BigDecimal getPvpRes() {
        return this.pvpRes;
    }
    
    public void setPvpRes(BigDecimal pvpRes) {
        this.pvpRes = pvpRes;
    }




}


