package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arinlo generated by hbm2java
 */
@Entity
@Table(name="ARINLO"
    ,schema="DESA46"
)
public class Arinlo  implements java.io.Serializable {


     private ArinloId id;
     private BigDecimal saldoUnidad;
     private BigDecimal saldoContable;
     private BigDecimal saldoMonto;
     private BigDecimal salidaPend;
     private BigDecimal costoLote;
     private String procesoToma;
     private BigDecimal existPrep;
     private BigDecimal costoPrep;
     private BigDecimal tomFisic;
     private Date fechaEntrada;
     private Date fechaVence;
     private Date fechaFinCuarentena;
     private Long noConteo;
     private BigDecimal costoInd;
     private BigDecimal costoUni;
     private BigDecimal saldoMontoRes;
     private BigDecimal costoLoteRes;
     private BigDecimal costoIndRes;
     private BigDecimal costoUniRes;

    public Arinlo() {
    }

	
    public Arinlo(ArinloId id) {
        this.id = id;
    }
    public Arinlo(ArinloId id, BigDecimal saldoUnidad, BigDecimal saldoContable, BigDecimal saldoMonto, BigDecimal salidaPend, BigDecimal costoLote, String procesoToma, BigDecimal existPrep, BigDecimal costoPrep, BigDecimal tomFisic, Date fechaEntrada, Date fechaVence, Date fechaFinCuarentena, Long noConteo, BigDecimal costoInd, BigDecimal costoUni, BigDecimal saldoMontoRes, BigDecimal costoLoteRes, BigDecimal costoIndRes, BigDecimal costoUniRes) {
       this.id = id;
       this.saldoUnidad = saldoUnidad;
       this.saldoContable = saldoContable;
       this.saldoMonto = saldoMonto;
       this.salidaPend = salidaPend;
       this.costoLote = costoLote;
       this.procesoToma = procesoToma;
       this.existPrep = existPrep;
       this.costoPrep = costoPrep;
       this.tomFisic = tomFisic;
       this.fechaEntrada = fechaEntrada;
       this.fechaVence = fechaVence;
       this.fechaFinCuarentena = fechaFinCuarentena;
       this.noConteo = noConteo;
       this.costoInd = costoInd;
       this.costoUni = costoUni;
       this.saldoMontoRes = saldoMontoRes;
       this.costoLoteRes = costoLoteRes;
       this.costoIndRes = costoIndRes;
       this.costoUniRes = costoUniRes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="bodega", column=@Column(name="BODEGA", nullable=false, length=4) ), 
        @AttributeOverride(name="clase", column=@Column(name="CLASE", nullable=false, length=3) ), 
        @AttributeOverride(name="categoria", column=@Column(name="CATEGORIA", nullable=false, length=3) ), 
        @AttributeOverride(name="noArti", column=@Column(name="NO_ARTI", nullable=false, length=30) ), 
        @AttributeOverride(name="noLote", column=@Column(name="NO_LOTE", nullable=false, length=30) ), 
        @AttributeOverride(name="ubicacion", column=@Column(name="UBICACION", nullable=false, length=10) ), 
        @AttributeOverride(name="talla", column=@Column(name="TALLA", nullable=false, precision=4, scale=1) ) } )
    public ArinloId getId() {
        return this.id;
    }
    
    public void setId(ArinloId id) {
        this.id = id;
    }

    
    @Column(name="SALDO_UNIDAD", precision=17)
    public BigDecimal getSaldoUnidad() {
        return this.saldoUnidad;
    }
    
    public void setSaldoUnidad(BigDecimal saldoUnidad) {
        this.saldoUnidad = saldoUnidad;
    }

    
    @Column(name="SALDO_CONTABLE", precision=17)
    public BigDecimal getSaldoContable() {
        return this.saldoContable;
    }
    
    public void setSaldoContable(BigDecimal saldoContable) {
        this.saldoContable = saldoContable;
    }

    
    @Column(name="SALDO_MONTO", precision=22)
    public BigDecimal getSaldoMonto() {
        return this.saldoMonto;
    }
    
    public void setSaldoMonto(BigDecimal saldoMonto) {
        this.saldoMonto = saldoMonto;
    }

    
    @Column(name="SALIDA_PEND", precision=17)
    public BigDecimal getSalidaPend() {
        return this.salidaPend;
    }
    
    public void setSalidaPend(BigDecimal salidaPend) {
        this.salidaPend = salidaPend;
    }

    
    @Column(name="COSTO_LOTE", precision=22)
    public BigDecimal getCostoLote() {
        return this.costoLote;
    }
    
    public void setCostoLote(BigDecimal costoLote) {
        this.costoLote = costoLote;
    }

    
    @Column(name="PROCESO_TOMA", length=1)
    public String getProcesoToma() {
        return this.procesoToma;
    }
    
    public void setProcesoToma(String procesoToma) {
        this.procesoToma = procesoToma;
    }

    
    @Column(name="EXIST_PREP", precision=22)
    public BigDecimal getExistPrep() {
        return this.existPrep;
    }
    
    public void setExistPrep(BigDecimal existPrep) {
        this.existPrep = existPrep;
    }

    
    @Column(name="COSTO_PREP", precision=25, scale=6)
    public BigDecimal getCostoPrep() {
        return this.costoPrep;
    }
    
    public void setCostoPrep(BigDecimal costoPrep) {
        this.costoPrep = costoPrep;
    }

    
    @Column(name="TOM_FISIC", precision=15)
    public BigDecimal getTomFisic() {
        return this.tomFisic;
    }
    
    public void setTomFisic(BigDecimal tomFisic) {
        this.tomFisic = tomFisic;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_ENTRADA", length=7)
    public Date getFechaEntrada() {
        return this.fechaEntrada;
    }
    
    public void setFechaEntrada(Date fechaEntrada) {
        this.fechaEntrada = fechaEntrada;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_VENCE", length=7)
    public Date getFechaVence() {
        return this.fechaVence;
    }
    
    public void setFechaVence(Date fechaVence) {
        this.fechaVence = fechaVence;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_FIN_CUARENTENA", length=7)
    public Date getFechaFinCuarentena() {
        return this.fechaFinCuarentena;
    }
    
    public void setFechaFinCuarentena(Date fechaFinCuarentena) {
        this.fechaFinCuarentena = fechaFinCuarentena;
    }

    
    @Column(name="NO_CONTEO", precision=12, scale=0)
    public Long getNoConteo() {
        return this.noConteo;
    }
    
    public void setNoConteo(Long noConteo) {
        this.noConteo = noConteo;
    }

    
    @Column(name="COSTO_IND", precision=22)
    public BigDecimal getCostoInd() {
        return this.costoInd;
    }
    
    public void setCostoInd(BigDecimal costoInd) {
        this.costoInd = costoInd;
    }

    
    @Column(name="COSTO_UNI", precision=22)
    public BigDecimal getCostoUni() {
        return this.costoUni;
    }
    
    public void setCostoUni(BigDecimal costoUni) {
        this.costoUni = costoUni;
    }

    
    @Column(name="SALDO_MONTO_RES", precision=30)
    public BigDecimal getSaldoMontoRes() {
        return this.saldoMontoRes;
    }
    
    public void setSaldoMontoRes(BigDecimal saldoMontoRes) {
        this.saldoMontoRes = saldoMontoRes;
    }

    
    @Column(name="COSTO_LOTE_RES", precision=30)
    public BigDecimal getCostoLoteRes() {
        return this.costoLoteRes;
    }
    
    public void setCostoLoteRes(BigDecimal costoLoteRes) {
        this.costoLoteRes = costoLoteRes;
    }

    
    @Column(name="COSTO_IND_RES", precision=30)
    public BigDecimal getCostoIndRes() {
        return this.costoIndRes;
    }
    
    public void setCostoIndRes(BigDecimal costoIndRes) {
        this.costoIndRes = costoIndRes;
    }

    
    @Column(name="COSTO_UNI_RES", precision=30)
    public BigDecimal getCostoUniRes() {
        return this.costoUniRes;
    }
    
    public void setCostoUniRes(BigDecimal costoUniRes) {
        this.costoUniRes = costoUniRes;
    }




}


