package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Aringt generated by hbm2java
 */
@Entity
@Table(name="ARINGT"
    ,schema="DESA46"
)
public class Aringt  implements java.io.Serializable {


     private String grupoTalla;
     private String descripcion;

    public Aringt() {
    }

	
    public Aringt(String grupoTalla) {
        this.grupoTalla = grupoTalla;
    }
    public Aringt(String grupoTalla, String descripcion) {
       this.grupoTalla = grupoTalla;
       this.descripcion = descripcion;
    }
   
     @Id 

    
    @Column(name="GRUPO_TALLA", unique=true, nullable=false, length=20)
    public String getGrupoTalla() {
        return this.grupoTalla;
    }
    
    public void setGrupoTalla(String grupoTalla) {
        this.grupoTalla = grupoTalla;
    }

    
    @Column(name="DESCRIPCION", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


