package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ArinmlUb generated by hbm2java
 */
@Entity
@Table(name="ARINML_UB"
    ,schema="DESA46"
)
public class ArinmlUb  implements java.io.Serializable {


     private ArinmlUbId id;
     private BigDecimal cantidad;
     private String codUbicacionDestino;
     private BigDecimal unidadesRecep;
     private BigDecimal costo;
     private String noRefeDocu;
     private String noCiaDestino;
     private BigDecimal undTemp;
     private BigDecimal cantidadDev;
     private BigDecimal monto;

    public ArinmlUb() {
    }

	
    public ArinmlUb(ArinmlUbId id) {
        this.id = id;
    }
    public ArinmlUb(ArinmlUbId id, BigDecimal cantidad, String codUbicacionDestino, BigDecimal unidadesRecep, BigDecimal costo, String noRefeDocu, String noCiaDestino, BigDecimal undTemp, BigDecimal cantidadDev, BigDecimal monto) {
       this.id = id;
       this.cantidad = cantidad;
       this.codUbicacionDestino = codUbicacionDestino;
       this.unidadesRecep = unidadesRecep;
       this.costo = costo;
       this.noRefeDocu = noRefeDocu;
       this.noCiaDestino = noCiaDestino;
       this.undTemp = undTemp;
       this.cantidadDev = cantidadDev;
       this.monto = monto;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="tipoDoc", column=@Column(name="TIPO_DOC", nullable=false, length=2) ), 
        @AttributeOverride(name="noDocu", column=@Column(name="NO_DOCU", nullable=false, length=12) ), 
        @AttributeOverride(name="linea", column=@Column(name="LINEA", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="bodega", column=@Column(name="BODEGA", nullable=false, length=5) ), 
        @AttributeOverride(name="noArti", column=@Column(name="NO_ARTI", nullable=false, length=30) ), 
        @AttributeOverride(name="codUbicacion", column=@Column(name="COD_UBICACION", nullable=false, length=10) ), 
        @AttributeOverride(name="noLote", column=@Column(name="NO_LOTE", nullable=false, length=30) ), 
        @AttributeOverride(name="talla", column=@Column(name="TALLA", nullable=false, precision=4, scale=1) ) } )
    public ArinmlUbId getId() {
        return this.id;
    }
    
    public void setId(ArinmlUbId id) {
        this.id = id;
    }

    
    @Column(name="CANTIDAD", precision=17)
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="COD_UBICACION_DESTINO", length=10)
    public String getCodUbicacionDestino() {
        return this.codUbicacionDestino;
    }
    
    public void setCodUbicacionDestino(String codUbicacionDestino) {
        this.codUbicacionDestino = codUbicacionDestino;
    }

    
    @Column(name="UNIDADES_RECEP", precision=17)
    public BigDecimal getUnidadesRecep() {
        return this.unidadesRecep;
    }
    
    public void setUnidadesRecep(BigDecimal unidadesRecep) {
        this.unidadesRecep = unidadesRecep;
    }

    
    @Column(name="COSTO", precision=17)
    public BigDecimal getCosto() {
        return this.costo;
    }
    
    public void setCosto(BigDecimal costo) {
        this.costo = costo;
    }

    
    @Column(name="NO_REFE_DOCU", length=12)
    public String getNoRefeDocu() {
        return this.noRefeDocu;
    }
    
    public void setNoRefeDocu(String noRefeDocu) {
        this.noRefeDocu = noRefeDocu;
    }

    
    @Column(name="NO_CIA_DESTINO", length=2)
    public String getNoCiaDestino() {
        return this.noCiaDestino;
    }
    
    public void setNoCiaDestino(String noCiaDestino) {
        this.noCiaDestino = noCiaDestino;
    }

    
    @Column(name="UND_TEMP", precision=17)
    public BigDecimal getUndTemp() {
        return this.undTemp;
    }
    
    public void setUndTemp(BigDecimal undTemp) {
        this.undTemp = undTemp;
    }

    
    @Column(name="CANTIDAD_DEV", precision=17)
    public BigDecimal getCantidadDev() {
        return this.cantidadDev;
    }
    
    public void setCantidadDev(BigDecimal cantidadDev) {
        this.cantidadDev = cantidadDev;
    }

    
    @Column(name="MONTO", precision=22, scale=6)
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }




}


