package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arincl generated by hbm2java
 */
@Entity
@Table(name="ARINCL"
    ,schema="DESA46"
)
public class Arincl  implements java.io.Serializable {


     private ArinclId id;
     private Date tstamp;
     private String descTipo;
     private String descCod;
     private String descArti;

    public Arincl() {
    }

	
    public Arincl(ArinclId id) {
        this.id = id;
    }
    public Arincl(ArinclId id, Date tstamp, String descTipo, String descCod, String descArti) {
       this.id = id;
       this.tstamp = tstamp;
       this.descTipo = descTipo;
       this.descCod = descCod;
       this.descArti = descArti;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noArti", column=@Column(name="NO_ARTI", nullable=false, length=30) ), 
        @AttributeOverride(name="tipoClasif", column=@Column(name="TIPO_CLASIF", nullable=false, length=2) ), 
        @AttributeOverride(name="codClasif", column=@Column(name="COD_CLASIF", nullable=false, length=15) ) } )
    public ArinclId getId() {
        return this.id;
    }
    
    public void setId(ArinclId id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TSTAMP", length=7)
    public Date getTstamp() {
        return this.tstamp;
    }
    
    public void setTstamp(Date tstamp) {
        this.tstamp = tstamp;
    }

    
    @Column(name="DESC_TIPO", length=30)
    public String getDescTipo() {
        return this.descTipo;
    }
    
    public void setDescTipo(String descTipo) {
        this.descTipo = descTipo;
    }

    
    @Column(name="DESC_COD", length=30)
    public String getDescCod() {
        return this.descCod;
    }
    
    public void setDescCod(String descCod) {
        this.descCod = descCod;
    }

    
    @Column(name="DESC_ARTI", length=200)
    public String getDescArti() {
        return this.descArti;
    }
    
    public void setDescArti(String descArti) {
        this.descArti = descArti;
    }




}


