package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arindp generated by hbm2java
 */
@Entity
@Table(name="ARINDP"
    ,schema="DESA46"
)
public class Arindp  implements java.io.Serializable {


     private ArindpId id;
     private String descripcion;
     private Date tstamp;

    public Arindp() {
    }

	
    public Arindp(ArindpId id) {
        this.id = id;
    }
    public Arindp(ArindpId id, String descripcion, Date tstamp) {
       this.id = id;
       this.descripcion = descripcion;
       this.tstamp = tstamp;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="tipo", column=@Column(name="TIPO", nullable=false, length=2) ) } )
    public ArindpId getId() {
        return this.id;
    }
    
    public void setId(ArindpId id) {
        this.id = id;
    }

    
    @Column(name="DESCRIPCION", length=20)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TSTAMP", length=7)
    public Date getTstamp() {
        return this.tstamp;
    }
    
    public void setTstamp(Date tstamp) {
        this.tstamp = tstamp;
    }




}


