package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arinec generated by hbm2java
 */
@Entity
@Table(name="ARINEC"
    ,schema="DESA46"
)
public class Arinec  implements java.io.Serializable {


     private ArinecId id;
     private BigDecimal unidades;

    public Arinec() {
    }

	
    public Arinec(ArinecId id) {
        this.id = id;
    }
    public Arinec(ArinecId id, BigDecimal unidades) {
       this.id = id;
       this.unidades = unidades;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="codCurva", column=@Column(name="COD_CURVA", nullable=false, length=4) ), 
        @AttributeOverride(name="talla", column=@Column(name="TALLA", nullable=false, precision=4, scale=1) ) } )
    public ArinecId getId() {
        return this.id;
    }
    
    public void setId(ArinecId id) {
        this.id = id;
    }

    
    @Column(name="UNIDADES", precision=12)
    public BigDecimal getUnidades() {
        return this.unidades;
    }
    
    public void setUnidades(BigDecimal unidades) {
        this.unidades = unidades;
    }




}


