package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arinservicios generated by hbm2java
 */
@Entity
@Table(name="ARINSERVICIOS"
    ,schema="DESA46"
)
public class Arinservicios  implements java.io.Serializable {


     private ArinserviciosId id;
     private String nombre;
     private String ccDebito;
     private String debito;
     private String ccCredito;
     private String credito;

    public Arinservicios() {
    }

	
    public Arinservicios(ArinserviciosId id) {
        this.id = id;
    }
    public Arinservicios(ArinserviciosId id, String nombre, String ccDebito, String debito, String ccCredito, String credito) {
       this.id = id;
       this.nombre = nombre;
       this.ccDebito = ccDebito;
       this.debito = debito;
       this.ccCredito = ccCredito;
       this.credito = credito;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="codServi", column=@Column(name="COD_SERVI", nullable=false, length=30) ) } )
    public ArinserviciosId getId() {
        return this.id;
    }
    
    public void setId(ArinserviciosId id) {
        this.id = id;
    }

    
    @Column(name="NOMBRE", length=500)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="CC_DEBITO", length=9)
    public String getCcDebito() {
        return this.ccDebito;
    }
    
    public void setCcDebito(String ccDebito) {
        this.ccDebito = ccDebito;
    }

    
    @Column(name="DEBITO", length=15)
    public String getDebito() {
        return this.debito;
    }
    
    public void setDebito(String debito) {
        this.debito = debito;
    }

    
    @Column(name="CC_CREDITO", length=9)
    public String getCcCredito() {
        return this.ccCredito;
    }
    
    public void setCcCredito(String ccCredito) {
        this.ccCredito = ccCredito;
    }

    
    @Column(name="CREDITO", length=15)
    public String getCredito() {
        return this.credito;
    }
    
    public void setCredito(String credito) {
        this.credito = credito;
    }




}


