package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arinca generated by hbm2java
 */
@Entity
@Table(name="ARINCA"
    ,schema="DESA46"
)
public class Arinca  implements java.io.Serializable {


     private ArincaId id;
     private String descripcion;
     private String controlEstad;
     private String tipoFactura;

    public Arinca() {
    }

	
    public Arinca(ArincaId id) {
        this.id = id;
    }
    public Arinca(ArincaId id, String descripcion, String controlEstad, String tipoFactura) {
       this.id = id;
       this.descripcion = descripcion;
       this.controlEstad = controlEstad;
       this.tipoFactura = tipoFactura;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="codigo", column=@Column(name="CODIGO", nullable=false, length=3) ) } )
    public ArincaId getId() {
        return this.id;
    }
    
    public void setId(ArincaId id) {
        this.id = id;
    }

    
    @Column(name="DESCRIPCION", length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="CONTROL_ESTAD", length=1)
    public String getControlEstad() {
        return this.controlEstad;
    }
    
    public void setControlEstad(String controlEstad) {
        this.controlEstad = controlEstad;
    }

    
    @Column(name="TIPO_FACTURA", length=1)
    public String getTipoFactura() {
        return this.tipoFactura;
    }
    
    public void setTipoFactura(String tipoFactura) {
        this.tipoFactura = tipoFactura;
    }




}


