package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArintbId generated by hbm2java
 */
@Embeddable
public class ArintbId  implements java.io.Serializable {


     private String noCia;
     private String tipoCodigo;
     private String codigo;
     private String periodo;

    public ArintbId() {
    }

    public ArintbId(String noCia, String tipoCodigo, String codigo, String periodo) {
       this.noCia = noCia;
       this.tipoCodigo = tipoCodigo;
       this.codigo = codigo;
       this.periodo = periodo;
    }
   


    @Column(name="NO_CIA", nullable=false, length=2)
    public String getNoCia() {
        return this.noCia;
    }
    
    public void setNoCia(String noCia) {
        this.noCia = noCia;
    }


    @Column(name="TIPO_CODIGO", nullable=false, length=1)
    public String getTipoCodigo() {
        return this.tipoCodigo;
    }
    
    public void setTipoCodigo(String tipoCodigo) {
        this.tipoCodigo = tipoCodigo;
    }


    @Column(name="CODIGO", nullable=false, length=4)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }


    @Column(name="PERIODO", nullable=false, length=4)
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArintbId) ) return false;
		 ArintbId castOther = ( ArintbId ) other; 
         
		 return ( (this.getNoCia()==castOther.getNoCia()) || ( this.getNoCia()!=null && castOther.getNoCia()!=null && this.getNoCia().equals(castOther.getNoCia()) ) )
 && ( (this.getTipoCodigo()==castOther.getTipoCodigo()) || ( this.getTipoCodigo()!=null && castOther.getTipoCodigo()!=null && this.getTipoCodigo().equals(castOther.getTipoCodigo()) ) )
 && ( (this.getCodigo()==castOther.getCodigo()) || ( this.getCodigo()!=null && castOther.getCodigo()!=null && this.getCodigo().equals(castOther.getCodigo()) ) )
 && ( (this.getPeriodo()==castOther.getPeriodo()) || ( this.getPeriodo()!=null && castOther.getPeriodo()!=null && this.getPeriodo().equals(castOther.getPeriodo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNoCia() == null ? 0 : this.getNoCia().hashCode() );
         result = 37 * result + ( getTipoCodigo() == null ? 0 : this.getTipoCodigo().hashCode() );
         result = 37 * result + ( getCodigo() == null ? 0 : this.getCodigo().hashCode() );
         result = 37 * result + ( getPeriodo() == null ? 0 : this.getPeriodo().hashCode() );
         return result;
   }   


}


