package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arinia generated by hbm2java
 */
@Entity
@Table(name="ARINIA"
    ,schema="DESA46"
)
public class Arinia  implements java.io.Serializable {


     private AriniaId id;
     private String afectaCompra;
     private String afectaVenta;

    public Arinia() {
    }

	
    public Arinia(AriniaId id) {
        this.id = id;
    }
    public Arinia(AriniaId id, String afectaCompra, String afectaVenta) {
       this.id = id;
       this.afectaCompra = afectaCompra;
       this.afectaVenta = afectaVenta;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="clase", column=@Column(name="CLASE", nullable=false, length=3) ), 
        @AttributeOverride(name="categoria", column=@Column(name="CATEGORIA", nullable=false, length=3) ), 
        @AttributeOverride(name="noArti", column=@Column(name="NO_ARTI", nullable=false, length=30) ), 
        @AttributeOverride(name="clave", column=@Column(name="CLAVE", nullable=false, length=2) ) } )
    public AriniaId getId() {
        return this.id;
    }
    
    public void setId(AriniaId id) {
        this.id = id;
    }

    
    @Column(name="AFECTA_COMPRA", length=1)
    public String getAfectaCompra() {
        return this.afectaCompra;
    }
    
    public void setAfectaCompra(String afectaCompra) {
        this.afectaCompra = afectaCompra;
    }

    
    @Column(name="AFECTA_VENTA", length=1)
    public String getAfectaVenta() {
        return this.afectaVenta;
    }
    
    public void setAfectaVenta(String afectaVenta) {
        this.afectaVenta = afectaVenta;
    }




}


