package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arinmeh generated by hbm2java
 */
@Entity
@Table(name="ARINMEH"
    ,schema="DESA46"
)
public class Arinmeh  implements java.io.Serializable {


     private ArinmehId id;
     private String centro;
     private String tipoDoc;
     private String periodo;
     private String ruta;
     private Date fecha;
     private String noFisico;
     private String serieFisico;
     private String conduce;
     private String noProve;
     private String tipoRefe;
     private String noRefe;
     private String serieRefe;
     private String noDocuRefe;
     private BigDecimal impVentas;
     private BigDecimal descuento;
     private BigDecimal movTot;
     private BigDecimal totArtIv;
     private String observ1;
     private BigDecimal tipoCambio;
     private Byte mes;
     private Byte semana;
     private String indSem;
     private Date fechaAplicacion;
     private Date tstamp;
     private String noTraslado;
     private BigDecimal movTotRes;

    public Arinmeh() {
    }

	
    public Arinmeh(ArinmehId id) {
        this.id = id;
    }
    public Arinmeh(ArinmehId id, String centro, String tipoDoc, String periodo, String ruta, Date fecha, String noFisico, String serieFisico, String conduce, String noProve, String tipoRefe, String noRefe, String serieRefe, String noDocuRefe, BigDecimal impVentas, BigDecimal descuento, BigDecimal movTot, BigDecimal totArtIv, String observ1, BigDecimal tipoCambio, Byte mes, Byte semana, String indSem, Date fechaAplicacion, Date tstamp, String noTraslado, BigDecimal movTotRes) {
       this.id = id;
       this.centro = centro;
       this.tipoDoc = tipoDoc;
       this.periodo = periodo;
       this.ruta = ruta;
       this.fecha = fecha;
       this.noFisico = noFisico;
       this.serieFisico = serieFisico;
       this.conduce = conduce;
       this.noProve = noProve;
       this.tipoRefe = tipoRefe;
       this.noRefe = noRefe;
       this.serieRefe = serieRefe;
       this.noDocuRefe = noDocuRefe;
       this.impVentas = impVentas;
       this.descuento = descuento;
       this.movTot = movTot;
       this.totArtIv = totArtIv;
       this.observ1 = observ1;
       this.tipoCambio = tipoCambio;
       this.mes = mes;
       this.semana = semana;
       this.indSem = indSem;
       this.fechaAplicacion = fechaAplicacion;
       this.tstamp = tstamp;
       this.noTraslado = noTraslado;
       this.movTotRes = movTotRes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noDocu", column=@Column(name="NO_DOCU", nullable=false, length=12) ) } )
    public ArinmehId getId() {
        return this.id;
    }
    
    public void setId(ArinmehId id) {
        this.id = id;
    }

    
    @Column(name="CENTRO", length=2)
    public String getCentro() {
        return this.centro;
    }
    
    public void setCentro(String centro) {
        this.centro = centro;
    }

    
    @Column(name="TIPO_DOC", length=2)
    public String getTipoDoc() {
        return this.tipoDoc;
    }
    
    public void setTipoDoc(String tipoDoc) {
        this.tipoDoc = tipoDoc;
    }

    
    @Column(name="PERIODO", length=4)
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }

    
    @Column(name="RUTA", length=4)
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", length=7)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="NO_FISICO", length=12)
    public String getNoFisico() {
        return this.noFisico;
    }
    
    public void setNoFisico(String noFisico) {
        this.noFisico = noFisico;
    }

    
    @Column(name="SERIE_FISICO", length=15)
    public String getSerieFisico() {
        return this.serieFisico;
    }
    
    public void setSerieFisico(String serieFisico) {
        this.serieFisico = serieFisico;
    }

    
    @Column(name="CONDUCE", length=10)
    public String getConduce() {
        return this.conduce;
    }
    
    public void setConduce(String conduce) {
        this.conduce = conduce;
    }

    
    @Column(name="NO_PROVE", length=15)
    public String getNoProve() {
        return this.noProve;
    }
    
    public void setNoProve(String noProve) {
        this.noProve = noProve;
    }

    
    @Column(name="TIPO_REFE", length=2)
    public String getTipoRefe() {
        return this.tipoRefe;
    }
    
    public void setTipoRefe(String tipoRefe) {
        this.tipoRefe = tipoRefe;
    }

    
    @Column(name="NO_REFE", length=12)
    public String getNoRefe() {
        return this.noRefe;
    }
    
    public void setNoRefe(String noRefe) {
        this.noRefe = noRefe;
    }

    
    @Column(name="SERIE_REFE", length=15)
    public String getSerieRefe() {
        return this.serieRefe;
    }
    
    public void setSerieRefe(String serieRefe) {
        this.serieRefe = serieRefe;
    }

    
    @Column(name="NO_DOCU_REFE", length=12)
    public String getNoDocuRefe() {
        return this.noDocuRefe;
    }
    
    public void setNoDocuRefe(String noDocuRefe) {
        this.noDocuRefe = noDocuRefe;
    }

    
    @Column(name="IMP_VENTAS", precision=22)
    public BigDecimal getImpVentas() {
        return this.impVentas;
    }
    
    public void setImpVentas(BigDecimal impVentas) {
        this.impVentas = impVentas;
    }

    
    @Column(name="DESCUENTO", precision=22)
    public BigDecimal getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(BigDecimal descuento) {
        this.descuento = descuento;
    }

    
    @Column(name="MOV_TOT", precision=22)
    public BigDecimal getMovTot() {
        return this.movTot;
    }
    
    public void setMovTot(BigDecimal movTot) {
        this.movTot = movTot;
    }

    
    @Column(name="TOT_ART_IV", precision=22)
    public BigDecimal getTotArtIv() {
        return this.totArtIv;
    }
    
    public void setTotArtIv(BigDecimal totArtIv) {
        this.totArtIv = totArtIv;
    }

    
    @Column(name="OBSERV1", length=250)
    public String getObserv1() {
        return this.observ1;
    }
    
    public void setObserv1(String observ1) {
        this.observ1 = observ1;
    }

    
    @Column(name="TIPO_CAMBIO", precision=22, scale=4)
    public BigDecimal getTipoCambio() {
        return this.tipoCambio;
    }
    
    public void setTipoCambio(BigDecimal tipoCambio) {
        this.tipoCambio = tipoCambio;
    }

    
    @Column(name="MES", precision=2, scale=0)
    public Byte getMes() {
        return this.mes;
    }
    
    public void setMes(Byte mes) {
        this.mes = mes;
    }

    
    @Column(name="SEMANA", precision=2, scale=0)
    public Byte getSemana() {
        return this.semana;
    }
    
    public void setSemana(Byte semana) {
        this.semana = semana;
    }

    
    @Column(name="IND_SEM", length=1)
    public String getIndSem() {
        return this.indSem;
    }
    
    public void setIndSem(String indSem) {
        this.indSem = indSem;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_APLICACION", length=7)
    public Date getFechaAplicacion() {
        return this.fechaAplicacion;
    }
    
    public void setFechaAplicacion(Date fechaAplicacion) {
        this.fechaAplicacion = fechaAplicacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TSTAMP", length=7)
    public Date getTstamp() {
        return this.tstamp;
    }
    
    public void setTstamp(Date tstamp) {
        this.tstamp = tstamp;
    }

    
    @Column(name="NO_TRASLADO", length=12)
    public String getNoTraslado() {
        return this.noTraslado;
    }
    
    public void setNoTraslado(String noTraslado) {
        this.noTraslado = noTraslado;
    }

    
    @Column(name="MOV_TOT_RES", precision=30)
    public BigDecimal getMovTotRes() {
        return this.movTotRes;
    }
    
    public void setMovTotRes(BigDecimal movTotRes) {
        this.movTotRes = movTotRes;
    }




}


