package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arincd generated by hbm2java
 */
@Entity
@Table(name="ARINCD"
    ,schema="DESA46"
)
public class Arincd  implements java.io.Serializable {


     private ArincdId id;
     private String nombre;
     private Short anoProce;
     private Byte mesProce;
     private String semanaProce;
     private String indicadorSem;
     private Date diaProceso;
     private Short anoProceCxc;
     private Byte mesProceCxc;
     private String semanaProceCxc;
     private String indicadorSemCxc;
     private Date diaProcesoCxc;
     private Short anoProceFact;
     private Byte mesProceFact;
     private String semanaProceFact;
     private Date diaProcesoFact;
     private String indicadorSemFact;
     private String generaAprobExacto;
     private String formulario;
     private String indCierrePendientePv;
     private Short anoProcePv;
     private Byte mesProcePv;
     private Date diaProcesoPv;
     private String codFormuApartado;
     private String codFormuEnvio;
     private String direccion;
     private Date diaProxCierre;
     private String telefono;
     private String centroCosto;
     private String ctaCxcApdo;

    public Arincd() {
    }

	
    public Arincd(ArincdId id) {
        this.id = id;
    }
    public Arincd(ArincdId id, String nombre, Short anoProce, Byte mesProce, String semanaProce, String indicadorSem, Date diaProceso, Short anoProceCxc, Byte mesProceCxc, String semanaProceCxc, String indicadorSemCxc, Date diaProcesoCxc, Short anoProceFact, Byte mesProceFact, String semanaProceFact, Date diaProcesoFact, String indicadorSemFact, String generaAprobExacto, String formulario, String indCierrePendientePv, Short anoProcePv, Byte mesProcePv, Date diaProcesoPv, String codFormuApartado, String codFormuEnvio, String direccion, Date diaProxCierre, String telefono, String centroCosto, String ctaCxcApdo) {
       this.id = id;
       this.nombre = nombre;
       this.anoProce = anoProce;
       this.mesProce = mesProce;
       this.semanaProce = semanaProce;
       this.indicadorSem = indicadorSem;
       this.diaProceso = diaProceso;
       this.anoProceCxc = anoProceCxc;
       this.mesProceCxc = mesProceCxc;
       this.semanaProceCxc = semanaProceCxc;
       this.indicadorSemCxc = indicadorSemCxc;
       this.diaProcesoCxc = diaProcesoCxc;
       this.anoProceFact = anoProceFact;
       this.mesProceFact = mesProceFact;
       this.semanaProceFact = semanaProceFact;
       this.diaProcesoFact = diaProcesoFact;
       this.indicadorSemFact = indicadorSemFact;
       this.generaAprobExacto = generaAprobExacto;
       this.formulario = formulario;
       this.indCierrePendientePv = indCierrePendientePv;
       this.anoProcePv = anoProcePv;
       this.mesProcePv = mesProcePv;
       this.diaProcesoPv = diaProcesoPv;
       this.codFormuApartado = codFormuApartado;
       this.codFormuEnvio = codFormuEnvio;
       this.direccion = direccion;
       this.diaProxCierre = diaProxCierre;
       this.telefono = telefono;
       this.centroCosto = centroCosto;
       this.ctaCxcApdo = ctaCxcApdo;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="centro", column=@Column(name="CENTRO", nullable=false, length=2) ) } )
    public ArincdId getId() {
        return this.id;
    }
    
    public void setId(ArincdId id) {
        this.id = id;
    }

    
    @Column(name="NOMBRE", length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="ANO_PROCE", precision=4, scale=0)
    public Short getAnoProce() {
        return this.anoProce;
    }
    
    public void setAnoProce(Short anoProce) {
        this.anoProce = anoProce;
    }

    
    @Column(name="MES_PROCE", precision=2, scale=0)
    public Byte getMesProce() {
        return this.mesProce;
    }
    
    public void setMesProce(Byte mesProce) {
        this.mesProce = mesProce;
    }

    
    @Column(name="SEMANA_PROCE", length=2)
    public String getSemanaProce() {
        return this.semanaProce;
    }
    
    public void setSemanaProce(String semanaProce) {
        this.semanaProce = semanaProce;
    }

    
    @Column(name="INDICADOR_SEM", length=1)
    public String getIndicadorSem() {
        return this.indicadorSem;
    }
    
    public void setIndicadorSem(String indicadorSem) {
        this.indicadorSem = indicadorSem;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DIA_PROCESO", length=7)
    public Date getDiaProceso() {
        return this.diaProceso;
    }
    
    public void setDiaProceso(Date diaProceso) {
        this.diaProceso = diaProceso;
    }

    
    @Column(name="ANO_PROCE_CXC", precision=4, scale=0)
    public Short getAnoProceCxc() {
        return this.anoProceCxc;
    }
    
    public void setAnoProceCxc(Short anoProceCxc) {
        this.anoProceCxc = anoProceCxc;
    }

    
    @Column(name="MES_PROCE_CXC", precision=2, scale=0)
    public Byte getMesProceCxc() {
        return this.mesProceCxc;
    }
    
    public void setMesProceCxc(Byte mesProceCxc) {
        this.mesProceCxc = mesProceCxc;
    }

    
    @Column(name="SEMANA_PROCE_CXC", length=2)
    public String getSemanaProceCxc() {
        return this.semanaProceCxc;
    }
    
    public void setSemanaProceCxc(String semanaProceCxc) {
        this.semanaProceCxc = semanaProceCxc;
    }

    
    @Column(name="INDICADOR_SEM_CXC", length=1)
    public String getIndicadorSemCxc() {
        return this.indicadorSemCxc;
    }
    
    public void setIndicadorSemCxc(String indicadorSemCxc) {
        this.indicadorSemCxc = indicadorSemCxc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DIA_PROCESO_CXC", length=7)
    public Date getDiaProcesoCxc() {
        return this.diaProcesoCxc;
    }
    
    public void setDiaProcesoCxc(Date diaProcesoCxc) {
        this.diaProcesoCxc = diaProcesoCxc;
    }

    
    @Column(name="ANO_PROCE_FACT", precision=4, scale=0)
    public Short getAnoProceFact() {
        return this.anoProceFact;
    }
    
    public void setAnoProceFact(Short anoProceFact) {
        this.anoProceFact = anoProceFact;
    }

    
    @Column(name="MES_PROCE_FACT", precision=2, scale=0)
    public Byte getMesProceFact() {
        return this.mesProceFact;
    }
    
    public void setMesProceFact(Byte mesProceFact) {
        this.mesProceFact = mesProceFact;
    }

    
    @Column(name="SEMANA_PROCE_FACT", length=2)
    public String getSemanaProceFact() {
        return this.semanaProceFact;
    }
    
    public void setSemanaProceFact(String semanaProceFact) {
        this.semanaProceFact = semanaProceFact;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DIA_PROCESO_FACT", length=7)
    public Date getDiaProcesoFact() {
        return this.diaProcesoFact;
    }
    
    public void setDiaProcesoFact(Date diaProcesoFact) {
        this.diaProcesoFact = diaProcesoFact;
    }

    
    @Column(name="INDICADOR_SEM_FACT", length=1)
    public String getIndicadorSemFact() {
        return this.indicadorSemFact;
    }
    
    public void setIndicadorSemFact(String indicadorSemFact) {
        this.indicadorSemFact = indicadorSemFact;
    }

    
    @Column(name="GENERA_APROB_EXACTO", length=1)
    public String getGeneraAprobExacto() {
        return this.generaAprobExacto;
    }
    
    public void setGeneraAprobExacto(String generaAprobExacto) {
        this.generaAprobExacto = generaAprobExacto;
    }

    
    @Column(name="FORMULARIO", length=2)
    public String getFormulario() {
        return this.formulario;
    }
    
    public void setFormulario(String formulario) {
        this.formulario = formulario;
    }

    
    @Column(name="IND_CIERRE_PENDIENTE_PV", length=1)
    public String getIndCierrePendientePv() {
        return this.indCierrePendientePv;
    }
    
    public void setIndCierrePendientePv(String indCierrePendientePv) {
        this.indCierrePendientePv = indCierrePendientePv;
    }

    
    @Column(name="ANO_PROCE_PV", precision=4, scale=0)
    public Short getAnoProcePv() {
        return this.anoProcePv;
    }
    
    public void setAnoProcePv(Short anoProcePv) {
        this.anoProcePv = anoProcePv;
    }

    
    @Column(name="MES_PROCE_PV", precision=2, scale=0)
    public Byte getMesProcePv() {
        return this.mesProcePv;
    }
    
    public void setMesProcePv(Byte mesProcePv) {
        this.mesProcePv = mesProcePv;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DIA_PROCESO_PV", length=7)
    public Date getDiaProcesoPv() {
        return this.diaProcesoPv;
    }
    
    public void setDiaProcesoPv(Date diaProcesoPv) {
        this.diaProcesoPv = diaProcesoPv;
    }

    
    @Column(name="COD_FORMU_APARTADO", length=12)
    public String getCodFormuApartado() {
        return this.codFormuApartado;
    }
    
    public void setCodFormuApartado(String codFormuApartado) {
        this.codFormuApartado = codFormuApartado;
    }

    
    @Column(name="COD_FORMU_ENVIO", length=12)
    public String getCodFormuEnvio() {
        return this.codFormuEnvio;
    }
    
    public void setCodFormuEnvio(String codFormuEnvio) {
        this.codFormuEnvio = codFormuEnvio;
    }

    
    @Column(name="DIRECCION", length=50)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DIA_PROX_CIERRE", length=7)
    public Date getDiaProxCierre() {
        return this.diaProxCierre;
    }
    
    public void setDiaProxCierre(Date diaProxCierre) {
        this.diaProxCierre = diaProxCierre;
    }

    
    @Column(name="TELEFONO", length=15)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="CENTRO_COSTO", length=9)
    public String getCentroCosto() {
        return this.centroCosto;
    }
    
    public void setCentroCosto(String centroCosto) {
        this.centroCosto = centroCosto;
    }

    
    @Column(name="CTA_CXC_APDO", length=15)
    public String getCtaCxcApdo() {
        return this.ctaCxcApdo;
    }
    
    public void setCtaCxcApdo(String ctaCxcApdo) {
        this.ctaCxcApdo = ctaCxcApdo;
    }




}


