package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arinvtm generated by hbm2java
 */
@Entity
@Table(name="ARINVTM"
    ,schema="DESA46"
)
public class Arinvtm  implements java.io.Serializable {


     private ArinvtmId id;
     private String descri;
     private String movimi;
     private String consum;
     private String compra;
     private String ventas;
     private String trasla;
     private String ajuste;
     private String ajusteFt;
     private String regMov;
     private String manifiesto;
     private String produccion;
     private String trasladoV;
     private String interface_;
     private String idRazon;
     private String ctaContrapartida;
     private String formulario;

    public Arinvtm() {
    }

	
    public Arinvtm(ArinvtmId id) {
        this.id = id;
    }
    public Arinvtm(ArinvtmId id, String descri, String movimi, String consum, String compra, String ventas, String trasla, String ajuste, String ajusteFt, String regMov, String manifiesto, String produccion, String trasladoV, String interface_, String idRazon, String ctaContrapartida, String formulario) {
       this.id = id;
       this.descri = descri;
       this.movimi = movimi;
       this.consum = consum;
       this.compra = compra;
       this.ventas = ventas;
       this.trasla = trasla;
       this.ajuste = ajuste;
       this.ajusteFt = ajusteFt;
       this.regMov = regMov;
       this.manifiesto = manifiesto;
       this.produccion = produccion;
       this.trasladoV = trasladoV;
       this.interface_ = interface_;
       this.idRazon = idRazon;
       this.ctaContrapartida = ctaContrapartida;
       this.formulario = formulario;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="tipoM", column=@Column(name="TIPO_M", nullable=false, length=2) ) } )
    public ArinvtmId getId() {
        return this.id;
    }
    
    public void setId(ArinvtmId id) {
        this.id = id;
    }

    
    @Column(name="DESCRI", length=20)
    public String getDescri() {
        return this.descri;
    }
    
    public void setDescri(String descri) {
        this.descri = descri;
    }

    
    @Column(name="MOVIMI", length=1)
    public String getMovimi() {
        return this.movimi;
    }
    
    public void setMovimi(String movimi) {
        this.movimi = movimi;
    }

    
    @Column(name="CONSUM", length=1)
    public String getConsum() {
        return this.consum;
    }
    
    public void setConsum(String consum) {
        this.consum = consum;
    }

    
    @Column(name="COMPRA", length=1)
    public String getCompra() {
        return this.compra;
    }
    
    public void setCompra(String compra) {
        this.compra = compra;
    }

    
    @Column(name="VENTAS", length=1)
    public String getVentas() {
        return this.ventas;
    }
    
    public void setVentas(String ventas) {
        this.ventas = ventas;
    }

    
    @Column(name="TRASLA", length=1)
    public String getTrasla() {
        return this.trasla;
    }
    
    public void setTrasla(String trasla) {
        this.trasla = trasla;
    }

    
    @Column(name="AJUSTE", length=1)
    public String getAjuste() {
        return this.ajuste;
    }
    
    public void setAjuste(String ajuste) {
        this.ajuste = ajuste;
    }

    
    @Column(name="AJUSTE_FT", length=1)
    public String getAjusteFt() {
        return this.ajusteFt;
    }
    
    public void setAjusteFt(String ajusteFt) {
        this.ajusteFt = ajusteFt;
    }

    
    @Column(name="REG_MOV", length=1)
    public String getRegMov() {
        return this.regMov;
    }
    
    public void setRegMov(String regMov) {
        this.regMov = regMov;
    }

    
    @Column(name="MANIFIESTO", length=1)
    public String getManifiesto() {
        return this.manifiesto;
    }
    
    public void setManifiesto(String manifiesto) {
        this.manifiesto = manifiesto;
    }

    
    @Column(name="PRODUCCION", length=1)
    public String getProduccion() {
        return this.produccion;
    }
    
    public void setProduccion(String produccion) {
        this.produccion = produccion;
    }

    
    @Column(name="TRASLADO_V", length=1)
    public String getTrasladoV() {
        return this.trasladoV;
    }
    
    public void setTrasladoV(String trasladoV) {
        this.trasladoV = trasladoV;
    }

    
    @Column(name="INTERFACE", length=2)
    public String getInterface_() {
        return this.interface_;
    }
    
    public void setInterface_(String interface_) {
        this.interface_ = interface_;
    }

    
    @Column(name="ID_RAZON", length=2)
    public String getIdRazon() {
        return this.idRazon;
    }
    
    public void setIdRazon(String idRazon) {
        this.idRazon = idRazon;
    }

    
    @Column(name="CTA_CONTRAPARTIDA", length=15)
    public String getCtaContrapartida() {
        return this.ctaContrapartida;
    }
    
    public void setCtaContrapartida(String ctaContrapartida) {
        this.ctaContrapartida = ctaContrapartida;
    }

    
    @Column(name="FORMULARIO", length=10)
    public String getFormulario() {
        return this.formulario;
    }
    
    public void setFormulario(String formulario) {
        this.formulario = formulario;
    }




}


