package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arincc generated by hbm2java
 */
@Entity
@Table(name="ARINCC"
    ,schema="DESA46"
)
public class Arincc  implements java.io.Serializable {


     private ArinccId id;
     private String ccDebito;
     private String debito;
     private String origDebito;
     private String ccCredito;
     private String credito;
     private String origCredito;
     private String interface_;

    public Arincc() {
    }

	
    public Arincc(ArinccId id) {
        this.id = id;
    }
    public Arincc(ArinccId id, String ccDebito, String debito, String origDebito, String ccCredito, String credito, String origCredito, String interface_) {
       this.id = id;
       this.ccDebito = ccDebito;
       this.debito = debito;
       this.origDebito = origDebito;
       this.ccCredito = ccCredito;
       this.credito = credito;
       this.origCredito = origCredito;
       this.interface_ = interface_;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="grupo", column=@Column(name="GRUPO", nullable=false, length=6) ), 
        @AttributeOverride(name="tipoDoc", column=@Column(name="TIPO_DOC", nullable=false, length=15) ) } )
    public ArinccId getId() {
        return this.id;
    }
    
    public void setId(ArinccId id) {
        this.id = id;
    }

    
    @Column(name="CC_DEBITO", length=15)
    public String getCcDebito() {
        return this.ccDebito;
    }
    
    public void setCcDebito(String ccDebito) {
        this.ccDebito = ccDebito;
    }

    
    @Column(name="DEBITO", length=15)
    public String getDebito() {
        return this.debito;
    }
    
    public void setDebito(String debito) {
        this.debito = debito;
    }

    
    @Column(name="ORIG_DEBITO", length=50)
    public String getOrigDebito() {
        return this.origDebito;
    }
    
    public void setOrigDebito(String origDebito) {
        this.origDebito = origDebito;
    }

    
    @Column(name="CC_CREDITO", length=15)
    public String getCcCredito() {
        return this.ccCredito;
    }
    
    public void setCcCredito(String ccCredito) {
        this.ccCredito = ccCredito;
    }

    
    @Column(name="CREDITO", length=15)
    public String getCredito() {
        return this.credito;
    }
    
    public void setCredito(String credito) {
        this.credito = credito;
    }

    
    @Column(name="ORIG_CREDITO", length=50)
    public String getOrigCredito() {
        return this.origCredito;
    }
    
    public void setOrigCredito(String origCredito) {
        this.origCredito = origCredito;
    }

    
    @Column(name="INTERFACE", length=2)
    public String getInterface_() {
        return this.interface_;
    }
    
    public void setInterface_(String interface_) {
        this.interface_ = interface_;
    }




}


