package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Arplmod generated by hbm2java
 */
@Entity
@Table(name="ARPLMOD"
    ,schema="DESA46"
    , uniqueConstraints = @UniqueConstraint(columnNames="MODULO") 
)
public class Arplmod  implements java.io.Serializable {


     private ArplmodId id;
     private String correlativo;
     private String usuario;
     private String fecha;

    public Arplmod() {
    }

	
    public Arplmod(ArplmodId id) {
        this.id = id;
    }
    public Arplmod(ArplmodId id, String correlativo, String usuario, String fecha) {
       this.id = id;
       this.correlativo = correlativo;
       this.usuario = usuario;
       this.fecha = fecha;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="modulo", column=@Column(name="MODULO", unique=true, nullable=false, length=50) ) } )
    public ArplmodId getId() {
        return this.id;
    }
    
    public void setId(ArplmodId id) {
        this.id = id;
    }

    
    @Column(name="CORRELATIVO", length=10)
    public String getCorrelativo() {
        return this.correlativo;
    }
    
    public void setCorrelativo(String correlativo) {
        this.correlativo = correlativo;
    }

    
    @Column(name="USUARIO", length=50)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="FECHA", length=50)
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }




}


