package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArplcalDetId generated by hbm2java
 */
@Embeddable
public class ArplcalDetId  implements java.io.Serializable {


     private String noCia;
     private String codCal;
     private Date fecha;
     private String dia;

    public ArplcalDetId() {
    }

    public ArplcalDetId(String noCia, String codCal, Date fecha, String dia) {
       this.noCia = noCia;
       this.codCal = codCal;
       this.fecha = fecha;
       this.dia = dia;
    }
   


    @Column(name="NO_CIA", nullable=false, length=2)
    public String getNoCia() {
        return this.noCia;
    }
    
    public void setNoCia(String noCia) {
        this.noCia = noCia;
    }


    @Column(name="COD_CAL", nullable=false, length=10)
    public String getCodCal() {
        return this.codCal;
    }
    
    public void setCodCal(String codCal) {
        this.codCal = codCal;
    }


    @Column(name="FECHA", nullable=false, length=7)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }


    @Column(name="DIA", nullable=false, length=20)
    public String getDia() {
        return this.dia;
    }
    
    public void setDia(String dia) {
        this.dia = dia;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArplcalDetId) ) return false;
		 ArplcalDetId castOther = ( ArplcalDetId ) other; 
         
		 return ( (this.getNoCia()==castOther.getNoCia()) || ( this.getNoCia()!=null && castOther.getNoCia()!=null && this.getNoCia().equals(castOther.getNoCia()) ) )
 && ( (this.getCodCal()==castOther.getCodCal()) || ( this.getCodCal()!=null && castOther.getCodCal()!=null && this.getCodCal().equals(castOther.getCodCal()) ) )
 && ( (this.getFecha()==castOther.getFecha()) || ( this.getFecha()!=null && castOther.getFecha()!=null && this.getFecha().equals(castOther.getFecha()) ) )
 && ( (this.getDia()==castOther.getDia()) || ( this.getDia()!=null && castOther.getDia()!=null && this.getDia().equals(castOther.getDia()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNoCia() == null ? 0 : this.getNoCia().hashCode() );
         result = 37 * result + ( getCodCal() == null ? 0 : this.getCodCal().hashCode() );
         result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
         result = 37 * result + ( getDia() == null ? 0 : this.getDia().hashCode() );
         return result;
   }   


}


