package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ArplTipMov generated by hbm2java
 */
@Entity
@Table(name="ARPL_TIP_MOV"
    ,schema="DESA46"
)
public class ArplTipMov  implements java.io.Serializable {


     private String noTm;
     private String descrTm;

    public ArplTipMov() {
    }

	
    public ArplTipMov(String noTm) {
        this.noTm = noTm;
    }
    public ArplTipMov(String noTm, String descrTm) {
       this.noTm = noTm;
       this.descrTm = descrTm;
    }
   
     @Id 

    
    @Column(name="NO_TM", unique=true, nullable=false, length=5)
    public String getNoTm() {
        return this.noTm;
    }
    
    public void setNoTm(String noTm) {
        this.noTm = noTm;
    }

    
    @Column(name="DESCR_TM", length=100)
    public String getDescrTm() {
        return this.descrTm;
    }
    
    public void setDescrTm(String descrTm) {
        this.descrTm = descrTm;
    }




}


