package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arplsper generated by hbm2java
 */
@Entity
@Table(name="ARPLSPER"
    ,schema="DESA46"
)
public class Arplsper  implements java.io.Serializable {


     private ArplsperId id;
     private Date fechaPermiso;
     private String tipoPermiso;
     private String detaPermiso;
     private Date horaSalida;
     private Date horaRegreso;
     private String solicitPor;
     private String autoriPor;
     private String remun;
     private String estado;

    public Arplsper() {
    }

	
    public Arplsper(ArplsperId id) {
        this.id = id;
    }
    public Arplsper(ArplsperId id, Date fechaPermiso, String tipoPermiso, String detaPermiso, Date horaSalida, Date horaRegreso, String solicitPor, String autoriPor, String remun, String estado) {
       this.id = id;
       this.fechaPermiso = fechaPermiso;
       this.tipoPermiso = tipoPermiso;
       this.detaPermiso = detaPermiso;
       this.horaSalida = horaSalida;
       this.horaRegreso = horaRegreso;
       this.solicitPor = solicitPor;
       this.autoriPor = autoriPor;
       this.remun = remun;
       this.estado = estado;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noEmple", column=@Column(name="NO_EMPLE", nullable=false, length=10) ), 
        @AttributeOverride(name="noSolper", column=@Column(name="NO_SOLPER", nullable=false, length=5) ), 
        @AttributeOverride(name="diaSolicitud", column=@Column(name="DIA_SOLICITUD", nullable=false, length=7) ) } )
    public ArplsperId getId() {
        return this.id;
    }
    
    public void setId(ArplsperId id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_PERMISO", length=7)
    public Date getFechaPermiso() {
        return this.fechaPermiso;
    }
    
    public void setFechaPermiso(Date fechaPermiso) {
        this.fechaPermiso = fechaPermiso;
    }

    
    @Column(name="TIPO_PERMISO", length=5)
    public String getTipoPermiso() {
        return this.tipoPermiso;
    }
    
    public void setTipoPermiso(String tipoPermiso) {
        this.tipoPermiso = tipoPermiso;
    }

    
    @Column(name="DETA_PERMISO", length=200)
    public String getDetaPermiso() {
        return this.detaPermiso;
    }
    
    public void setDetaPermiso(String detaPermiso) {
        this.detaPermiso = detaPermiso;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="HORA_SALIDA", length=7)
    public Date getHoraSalida() {
        return this.horaSalida;
    }
    
    public void setHoraSalida(Date horaSalida) {
        this.horaSalida = horaSalida;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="HORA_REGRESO", length=7)
    public Date getHoraRegreso() {
        return this.horaRegreso;
    }
    
    public void setHoraRegreso(Date horaRegreso) {
        this.horaRegreso = horaRegreso;
    }

    
    @Column(name="SOLICIT_POR", length=50)
    public String getSolicitPor() {
        return this.solicitPor;
    }
    
    public void setSolicitPor(String solicitPor) {
        this.solicitPor = solicitPor;
    }

    
    @Column(name="AUTORI_POR", length=50)
    public String getAutoriPor() {
        return this.autoriPor;
    }
    
    public void setAutoriPor(String autoriPor) {
        this.autoriPor = autoriPor;
    }

    
    @Column(name="REMUN", length=1)
    public String getRemun() {
        return this.remun;
    }
    
    public void setRemun(String remun) {
        this.remun = remun;
    }

    
    @Column(name="ESTADO", length=50)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


