package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arplgr generated by hbm2java
 */
@Entity
@Table(name="ARPLGR"
    ,schema="DESA46"
)
public class Arplgr  implements java.io.Serializable {


     private ArplgrId id;
     private String desAcumgr;
     private String stAcumgr;

    public Arplgr() {
    }

	
    public Arplgr(ArplgrId id) {
        this.id = id;
    }
    public Arplgr(ArplgrId id, String desAcumgr, String stAcumgr) {
       this.id = id;
       this.desAcumgr = desAcumgr;
       this.stAcumgr = stAcumgr;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noAcumgr", column=@Column(name="NO_ACUMGR", nullable=false, length=10) ) } )
    public ArplgrId getId() {
        return this.id;
    }
    
    public void setId(ArplgrId id) {
        this.id = id;
    }

    
    @Column(name="DES_ACUMGR", length=100)
    public String getDesAcumgr() {
        return this.desAcumgr;
    }
    
    public void setDesAcumgr(String desAcumgr) {
        this.desAcumgr = desAcumgr;
    }

    
    @Column(name="ST_ACUMGR", length=1)
    public String getStAcumgr() {
        return this.stAcumgr;
    }
    
    public void setStAcumgr(String stAcumgr) {
        this.stAcumgr = stAcumgr;
    }




}


