package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arplme generated by hbm2java
 */
@Entity
@Table(name="ARPLME"
    ,schema="DESA46"
)
public class Arplme  implements java.io.Serializable {


     private ArplmeId id;
     private String tipoEmp;
     private String nombre;
     private String nombrePila;
     private String apePat;
     private String apeMat;
     private String estado;
     private String estadoProp;
     private String cedula;
     private String ciudadCedula;
     private String nacion;
     private String asegu;
     private String afp;
     private String nivel;
     private String subNivel;
     private String formaPago;
     private String idCta;
     private String tipoCta;
     private String numCuenta;
     private String sangre;
     private String telefono;
     private String notifica;
     private String telNoti;
     private String direccion;
     private String apartado;
     private String cc1;
     private String cc2;
     private String cc3;
     private Date FIngreso;
     private Date FEgreso;
     private Date FFinContrato;
     private Date FReingreso;
     private String condicion;
     private String ECivil;
     private String noHora;
     private Date FNacimi;
     private String lugarNac;
     private String servMilitar;
     private String categoria;
     private String titulo;
     private String titProvNal;
     private String tarjeta;
     private String procesaTarj;
     private String licencia;
     private String area;
     private String depto;
     private String division;
     private String seccion;
     private String puesto;
     private String sexo;
     private BigDecimal saldoIvaDol;
     private String acumulaVacac;
     private Short plazoVacac;
     private BigDecimal porcAdelanto;
     private String ultAcc;
     private String ganaExtras;
     private String tipoSeguro;
     private String observIns;
     private BigDecimal adeImpsal;
     private String etiqueta1;
     private String valor1;
     private String etiqueta2;
     private String valor2;
     private String usuarioBd;
     private BigDecimal salBaseRecibo;
     private String rif;
     private String tipoPersona;
     private Date FIniVac;
     private Date FFinVac;
     private Date nuevaFIngreso;
     private BigDecimal diasDisfrute;
     private BigDecimal diasAdic;
     private BigDecimal diasConvenio;
     private BigDecimal diasBono;
     private BigDecimal diasAdicBono;
     private String liquidado;
     private String ubicGeo;
     private Date FUltCambSal;
     private Byte perVacComp;
     private BigDecimal phAnterior;
     private String deVacaciones;

    public Arplme() {
    }

	
    public Arplme(ArplmeId id) {
        this.id = id;
    }
    public Arplme(ArplmeId id, String tipoEmp, String nombre, String nombrePila, String apePat, String apeMat, String estado, String estadoProp, String cedula, String ciudadCedula, String nacion, String asegu, String afp, String nivel, String subNivel, String formaPago, String idCta, String tipoCta, String numCuenta, String sangre, String telefono, String notifica, String telNoti, String direccion, String apartado, String cc1, String cc2, String cc3, Date FIngreso, Date FEgreso, Date FFinContrato, Date FReingreso, String condicion, String ECivil, String noHora, Date FNacimi, String lugarNac, String servMilitar, String categoria, String titulo, String titProvNal, String tarjeta, String procesaTarj, String licencia, String area, String depto, String division, String seccion, String puesto, String sexo, BigDecimal saldoIvaDol, String acumulaVacac, Short plazoVacac, BigDecimal porcAdelanto, String ultAcc, String ganaExtras, String tipoSeguro, String observIns, BigDecimal adeImpsal, String etiqueta1, String valor1, String etiqueta2, String valor2, String usuarioBd, BigDecimal salBaseRecibo, String rif, String tipoPersona, Date FIniVac, Date FFinVac, Date nuevaFIngreso, BigDecimal diasDisfrute, BigDecimal diasAdic, BigDecimal diasConvenio, BigDecimal diasBono, BigDecimal diasAdicBono, String liquidado, String ubicGeo, Date FUltCambSal, Byte perVacComp, BigDecimal phAnterior, String deVacaciones) {
       this.id = id;
       this.tipoEmp = tipoEmp;
       this.nombre = nombre;
       this.nombrePila = nombrePila;
       this.apePat = apePat;
       this.apeMat = apeMat;
       this.estado = estado;
       this.estadoProp = estadoProp;
       this.cedula = cedula;
       this.ciudadCedula = ciudadCedula;
       this.nacion = nacion;
       this.asegu = asegu;
       this.afp = afp;
       this.nivel = nivel;
       this.subNivel = subNivel;
       this.formaPago = formaPago;
       this.idCta = idCta;
       this.tipoCta = tipoCta;
       this.numCuenta = numCuenta;
       this.sangre = sangre;
       this.telefono = telefono;
       this.notifica = notifica;
       this.telNoti = telNoti;
       this.direccion = direccion;
       this.apartado = apartado;
       this.cc1 = cc1;
       this.cc2 = cc2;
       this.cc3 = cc3;
       this.FIngreso = FIngreso;
       this.FEgreso = FEgreso;
       this.FFinContrato = FFinContrato;
       this.FReingreso = FReingreso;
       this.condicion = condicion;
       this.ECivil = ECivil;
       this.noHora = noHora;
       this.FNacimi = FNacimi;
       this.lugarNac = lugarNac;
       this.servMilitar = servMilitar;
       this.categoria = categoria;
       this.titulo = titulo;
       this.titProvNal = titProvNal;
       this.tarjeta = tarjeta;
       this.procesaTarj = procesaTarj;
       this.licencia = licencia;
       this.area = area;
       this.depto = depto;
       this.division = division;
       this.seccion = seccion;
       this.puesto = puesto;
       this.sexo = sexo;
       this.saldoIvaDol = saldoIvaDol;
       this.acumulaVacac = acumulaVacac;
       this.plazoVacac = plazoVacac;
       this.porcAdelanto = porcAdelanto;
       this.ultAcc = ultAcc;
       this.ganaExtras = ganaExtras;
       this.tipoSeguro = tipoSeguro;
       this.observIns = observIns;
       this.adeImpsal = adeImpsal;
       this.etiqueta1 = etiqueta1;
       this.valor1 = valor1;
       this.etiqueta2 = etiqueta2;
       this.valor2 = valor2;
       this.usuarioBd = usuarioBd;
       this.salBaseRecibo = salBaseRecibo;
       this.rif = rif;
       this.tipoPersona = tipoPersona;
       this.FIniVac = FIniVac;
       this.FFinVac = FFinVac;
       this.nuevaFIngreso = nuevaFIngreso;
       this.diasDisfrute = diasDisfrute;
       this.diasAdic = diasAdic;
       this.diasConvenio = diasConvenio;
       this.diasBono = diasBono;
       this.diasAdicBono = diasAdicBono;
       this.liquidado = liquidado;
       this.ubicGeo = ubicGeo;
       this.FUltCambSal = FUltCambSal;
       this.perVacComp = perVacComp;
       this.phAnterior = phAnterior;
       this.deVacaciones = deVacaciones;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="codpla", column=@Column(name="CODPLA", nullable=false, length=100) ), 
        @AttributeOverride(name="noEmple", column=@Column(name="NO_EMPLE", nullable=false, length=10) ) } )
    public ArplmeId getId() {
        return this.id;
    }
    
    public void setId(ArplmeId id) {
        this.id = id;
    }

    
    @Column(name="TIPO_EMP", length=2)
    public String getTipoEmp() {
        return this.tipoEmp;
    }
    
    public void setTipoEmp(String tipoEmp) {
        this.tipoEmp = tipoEmp;
    }

    
    @Column(name="NOMBRE", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="NOMBRE_PILA", length=20)
    public String getNombrePila() {
        return this.nombrePila;
    }
    
    public void setNombrePila(String nombrePila) {
        this.nombrePila = nombrePila;
    }

    
    @Column(name="APE_PAT", length=20)
    public String getApePat() {
        return this.apePat;
    }
    
    public void setApePat(String apePat) {
        this.apePat = apePat;
    }

    
    @Column(name="APE_MAT", length=25)
    public String getApeMat() {
        return this.apeMat;
    }
    
    public void setApeMat(String apeMat) {
        this.apeMat = apeMat;
    }

    
    @Column(name="ESTADO", length=1)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="ESTADO_PROP", length=1)
    public String getEstadoProp() {
        return this.estadoProp;
    }
    
    public void setEstadoProp(String estadoProp) {
        this.estadoProp = estadoProp;
    }

    
    @Column(name="CEDULA", length=12)
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }

    
    @Column(name="CIUDAD_CEDULA", length=4)
    public String getCiudadCedula() {
        return this.ciudadCedula;
    }
    
    public void setCiudadCedula(String ciudadCedula) {
        this.ciudadCedula = ciudadCedula;
    }

    
    @Column(name="NACION", length=1)
    public String getNacion() {
        return this.nacion;
    }
    
    public void setNacion(String nacion) {
        this.nacion = nacion;
    }

    
    @Column(name="ASEGU", length=15)
    public String getAsegu() {
        return this.asegu;
    }
    
    public void setAsegu(String asegu) {
        this.asegu = asegu;
    }

    
    @Column(name="AFP", length=2)
    public String getAfp() {
        return this.afp;
    }
    
    public void setAfp(String afp) {
        this.afp = afp;
    }

    
    @Column(name="NIVEL", length=6)
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }

    
    @Column(name="SUB_NIVEL", length=2)
    public String getSubNivel() {
        return this.subNivel;
    }
    
    public void setSubNivel(String subNivel) {
        this.subNivel = subNivel;
    }

    
    @Column(name="FORMA_PAGO", length=1)
    public String getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(String formaPago) {
        this.formaPago = formaPago;
    }

    
    @Column(name="ID_CTA", length=2)
    public String getIdCta() {
        return this.idCta;
    }
    
    public void setIdCta(String idCta) {
        this.idCta = idCta;
    }

    
    @Column(name="TIPO_CTA", length=1)
    public String getTipoCta() {
        return this.tipoCta;
    }
    
    public void setTipoCta(String tipoCta) {
        this.tipoCta = tipoCta;
    }

    
    @Column(name="NUM_CUENTA", length=20)
    public String getNumCuenta() {
        return this.numCuenta;
    }
    
    public void setNumCuenta(String numCuenta) {
        this.numCuenta = numCuenta;
    }

    
    @Column(name="SANGRE", length=4)
    public String getSangre() {
        return this.sangre;
    }
    
    public void setSangre(String sangre) {
        this.sangre = sangre;
    }

    
    @Column(name="TELEFONO", length=9)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="NOTIFICA", length=30)
    public String getNotifica() {
        return this.notifica;
    }
    
    public void setNotifica(String notifica) {
        this.notifica = notifica;
    }

    
    @Column(name="TEL_NOTI", length=9)
    public String getTelNoti() {
        return this.telNoti;
    }
    
    public void setTelNoti(String telNoti) {
        this.telNoti = telNoti;
    }

    
    @Column(name="DIRECCION", length=50)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="APARTADO", length=20)
    public String getApartado() {
        return this.apartado;
    }
    
    public void setApartado(String apartado) {
        this.apartado = apartado;
    }

    
    @Column(name="CC_1", length=3)
    public String getCc1() {
        return this.cc1;
    }
    
    public void setCc1(String cc1) {
        this.cc1 = cc1;
    }

    
    @Column(name="CC_2", length=3)
    public String getCc2() {
        return this.cc2;
    }
    
    public void setCc2(String cc2) {
        this.cc2 = cc2;
    }

    
    @Column(name="CC_3", length=3)
    public String getCc3() {
        return this.cc3;
    }
    
    public void setCc3(String cc3) {
        this.cc3 = cc3;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="F_INGRESO", length=7)
    public Date getFIngreso() {
        return this.FIngreso;
    }
    
    public void setFIngreso(Date FIngreso) {
        this.FIngreso = FIngreso;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="F_EGRESO", length=7)
    public Date getFEgreso() {
        return this.FEgreso;
    }
    
    public void setFEgreso(Date FEgreso) {
        this.FEgreso = FEgreso;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="F_FIN_CONTRATO", length=7)
    public Date getFFinContrato() {
        return this.FFinContrato;
    }
    
    public void setFFinContrato(Date FFinContrato) {
        this.FFinContrato = FFinContrato;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="F_REINGRESO", length=7)
    public Date getFReingreso() {
        return this.FReingreso;
    }
    
    public void setFReingreso(Date FReingreso) {
        this.FReingreso = FReingreso;
    }

    
    @Column(name="CONDICION", length=1)
    public String getCondicion() {
        return this.condicion;
    }
    
    public void setCondicion(String condicion) {
        this.condicion = condicion;
    }

    
    @Column(name="E_CIVIL", length=1)
    public String getECivil() {
        return this.ECivil;
    }
    
    public void setECivil(String ECivil) {
        this.ECivil = ECivil;
    }

    
    @Column(name="NO_HORA", length=3)
    public String getNoHora() {
        return this.noHora;
    }
    
    public void setNoHora(String noHora) {
        this.noHora = noHora;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="F_NACIMI", length=7)
    public Date getFNacimi() {
        return this.FNacimi;
    }
    
    public void setFNacimi(Date FNacimi) {
        this.FNacimi = FNacimi;
    }

    
    @Column(name="LUGAR_NAC", length=20)
    public String getLugarNac() {
        return this.lugarNac;
    }
    
    public void setLugarNac(String lugarNac) {
        this.lugarNac = lugarNac;
    }

    
    @Column(name="SERV_MILITAR", length=10)
    public String getServMilitar() {
        return this.servMilitar;
    }
    
    public void setServMilitar(String servMilitar) {
        this.servMilitar = servMilitar;
    }

    
    @Column(name="CATEGORIA", length=2)
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    
    @Column(name="TITULO", length=4)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    
    @Column(name="TIT_PROV_NAL", length=10)
    public String getTitProvNal() {
        return this.titProvNal;
    }
    
    public void setTitProvNal(String titProvNal) {
        this.titProvNal = titProvNal;
    }

    
    @Column(name="TARJETA", length=1)
    public String getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(String tarjeta) {
        this.tarjeta = tarjeta;
    }

    
    @Column(name="PROCESA_TARJ", length=1)
    public String getProcesaTarj() {
        return this.procesaTarj;
    }
    
    public void setProcesaTarj(String procesaTarj) {
        this.procesaTarj = procesaTarj;
    }

    
    @Column(name="LICENCIA", length=2)
    public String getLicencia() {
        return this.licencia;
    }
    
    public void setLicencia(String licencia) {
        this.licencia = licencia;
    }

    
    @Column(name="AREA", length=2)
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }

    
    @Column(name="DEPTO", length=5)
    public String getDepto() {
        return this.depto;
    }
    
    public void setDepto(String depto) {
        this.depto = depto;
    }

    
    @Column(name="DIVISION", length=3)
    public String getDivision() {
        return this.division;
    }
    
    public void setDivision(String division) {
        this.division = division;
    }

    
    @Column(name="SECCION", length=2)
    public String getSeccion() {
        return this.seccion;
    }
    
    public void setSeccion(String seccion) {
        this.seccion = seccion;
    }

    
    @Column(name="PUESTO", length=4)
    public String getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }

    
    @Column(name="SEXO", length=1)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    
    @Column(name="SALDO_IVA_DOL", precision=14, scale=6)
    public BigDecimal getSaldoIvaDol() {
        return this.saldoIvaDol;
    }
    
    public void setSaldoIvaDol(BigDecimal saldoIvaDol) {
        this.saldoIvaDol = saldoIvaDol;
    }

    
    @Column(name="ACUMULA_VACAC", length=1)
    public String getAcumulaVacac() {
        return this.acumulaVacac;
    }
    
    public void setAcumulaVacac(String acumulaVacac) {
        this.acumulaVacac = acumulaVacac;
    }

    
    @Column(name="PLAZO_VACAC", precision=3, scale=0)
    public Short getPlazoVacac() {
        return this.plazoVacac;
    }
    
    public void setPlazoVacac(Short plazoVacac) {
        this.plazoVacac = plazoVacac;
    }

    
    @Column(name="PORC_ADELANTO", precision=5)
    public BigDecimal getPorcAdelanto() {
        return this.porcAdelanto;
    }
    
    public void setPorcAdelanto(BigDecimal porcAdelanto) {
        this.porcAdelanto = porcAdelanto;
    }

    
    @Column(name="ULT_ACC", length=8)
    public String getUltAcc() {
        return this.ultAcc;
    }
    
    public void setUltAcc(String ultAcc) {
        this.ultAcc = ultAcc;
    }

    
    @Column(name="GANA_EXTRAS", length=1)
    public String getGanaExtras() {
        return this.ganaExtras;
    }
    
    public void setGanaExtras(String ganaExtras) {
        this.ganaExtras = ganaExtras;
    }

    
    @Column(name="TIPO_SEGURO", length=1)
    public String getTipoSeguro() {
        return this.tipoSeguro;
    }
    
    public void setTipoSeguro(String tipoSeguro) {
        this.tipoSeguro = tipoSeguro;
    }

    
    @Column(name="OBSERV_INS", length=40)
    public String getObservIns() {
        return this.observIns;
    }
    
    public void setObservIns(String observIns) {
        this.observIns = observIns;
    }

    
    @Column(name="ADE_IMPSAL", precision=10)
    public BigDecimal getAdeImpsal() {
        return this.adeImpsal;
    }
    
    public void setAdeImpsal(BigDecimal adeImpsal) {
        this.adeImpsal = adeImpsal;
    }

    
    @Column(name="ETIQUETA1", length=50)
    public String getEtiqueta1() {
        return this.etiqueta1;
    }
    
    public void setEtiqueta1(String etiqueta1) {
        this.etiqueta1 = etiqueta1;
    }

    
    @Column(name="VALOR1", length=30)
    public String getValor1() {
        return this.valor1;
    }
    
    public void setValor1(String valor1) {
        this.valor1 = valor1;
    }

    
    @Column(name="ETIQUETA2", length=50)
    public String getEtiqueta2() {
        return this.etiqueta2;
    }
    
    public void setEtiqueta2(String etiqueta2) {
        this.etiqueta2 = etiqueta2;
    }

    
    @Column(name="VALOR2", length=30)
    public String getValor2() {
        return this.valor2;
    }
    
    public void setValor2(String valor2) {
        this.valor2 = valor2;
    }

    
    @Column(name="USUARIO_BD", length=20)
    public String getUsuarioBd() {
        return this.usuarioBd;
    }
    
    public void setUsuarioBd(String usuarioBd) {
        this.usuarioBd = usuarioBd;
    }

    
    @Column(name="SAL_BASE_RECIBO", precision=10)
    public BigDecimal getSalBaseRecibo() {
        return this.salBaseRecibo;
    }
    
    public void setSalBaseRecibo(BigDecimal salBaseRecibo) {
        this.salBaseRecibo = salBaseRecibo;
    }

    
    @Column(name="RIF", length=15)
    public String getRif() {
        return this.rif;
    }
    
    public void setRif(String rif) {
        this.rif = rif;
    }

    
    @Column(name="TIPO_PERSONA", length=3)
    public String getTipoPersona() {
        return this.tipoPersona;
    }
    
    public void setTipoPersona(String tipoPersona) {
        this.tipoPersona = tipoPersona;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="F_INI_VAC", length=7)
    public Date getFIniVac() {
        return this.FIniVac;
    }
    
    public void setFIniVac(Date FIniVac) {
        this.FIniVac = FIniVac;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="F_FIN_VAC", length=7)
    public Date getFFinVac() {
        return this.FFinVac;
    }
    
    public void setFFinVac(Date FFinVac) {
        this.FFinVac = FFinVac;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NUEVA_F_INGRESO", length=7)
    public Date getNuevaFIngreso() {
        return this.nuevaFIngreso;
    }
    
    public void setNuevaFIngreso(Date nuevaFIngreso) {
        this.nuevaFIngreso = nuevaFIngreso;
    }

    
    @Column(name="DIAS_DISFRUTE", precision=5)
    public BigDecimal getDiasDisfrute() {
        return this.diasDisfrute;
    }
    
    public void setDiasDisfrute(BigDecimal diasDisfrute) {
        this.diasDisfrute = diasDisfrute;
    }

    
    @Column(name="DIAS_ADIC", precision=5)
    public BigDecimal getDiasAdic() {
        return this.diasAdic;
    }
    
    public void setDiasAdic(BigDecimal diasAdic) {
        this.diasAdic = diasAdic;
    }

    
    @Column(name="DIAS_CONVENIO", precision=5)
    public BigDecimal getDiasConvenio() {
        return this.diasConvenio;
    }
    
    public void setDiasConvenio(BigDecimal diasConvenio) {
        this.diasConvenio = diasConvenio;
    }

    
    @Column(name="DIAS_BONO", precision=5)
    public BigDecimal getDiasBono() {
        return this.diasBono;
    }
    
    public void setDiasBono(BigDecimal diasBono) {
        this.diasBono = diasBono;
    }

    
    @Column(name="DIAS_ADIC_BONO", precision=5)
    public BigDecimal getDiasAdicBono() {
        return this.diasAdicBono;
    }
    
    public void setDiasAdicBono(BigDecimal diasAdicBono) {
        this.diasAdicBono = diasAdicBono;
    }

    
    @Column(name="LIQUIDADO", length=1)
    public String getLiquidado() {
        return this.liquidado;
    }
    
    public void setLiquidado(String liquidado) {
        this.liquidado = liquidado;
    }

    
    @Column(name="UBIC_GEO", length=6)
    public String getUbicGeo() {
        return this.ubicGeo;
    }
    
    public void setUbicGeo(String ubicGeo) {
        this.ubicGeo = ubicGeo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="F_ULT_CAMB_SAL", length=7)
    public Date getFUltCambSal() {
        return this.FUltCambSal;
    }
    
    public void setFUltCambSal(Date FUltCambSal) {
        this.FUltCambSal = FUltCambSal;
    }

    
    @Column(name="PER_VAC_COMP", precision=2, scale=0)
    public Byte getPerVacComp() {
        return this.perVacComp;
    }
    
    public void setPerVacComp(Byte perVacComp) {
        this.perVacComp = perVacComp;
    }

    
    @Column(name="PH_ANTERIOR", precision=15)
    public BigDecimal getPhAnterior() {
        return this.phAnterior;
    }
    
    public void setPhAnterior(BigDecimal phAnterior) {
        this.phAnterior = phAnterior;
    }

    
    @Column(name="DE_VACACIONES", length=1)
    public String getDeVacaciones() {
        return this.deVacaciones;
    }
    
    public void setDeVacaciones(String deVacaciones) {
        this.deVacaciones = deVacaciones;
    }




}


