package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArplelnomDet generated by hbm2java
 */
@Entity
@Table(name="ARPLELNOM_DET"
    ,schema="DESA46"
)
public class ArplelnomDet  implements java.io.Serializable {


     private ArplelnomDetId id;
     private String totHoras;
     private String dias;
     private BigDecimal monto;
     private BigDecimal totAsig;
     private BigDecimal totDed;
     private BigDecimal totNeto;
     private Date fechReg;
     private String userReg;

    public ArplelnomDet() {
    }

	
    public ArplelnomDet(ArplelnomDetId id) {
        this.id = id;
    }
    public ArplelnomDet(ArplelnomDetId id, String totHoras, String dias, BigDecimal monto, BigDecimal totAsig, BigDecimal totDed, BigDecimal totNeto, Date fechReg, String userReg) {
       this.id = id;
       this.totHoras = totHoras;
       this.dias = dias;
       this.monto = monto;
       this.totAsig = totAsig;
       this.totDed = totDed;
       this.totNeto = totNeto;
       this.fechReg = fechReg;
       this.userReg = userReg;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noElnom", column=@Column(name="NO_ELNOM", nullable=false, length=10) ), 
        @AttributeOverride(name="codpla", column=@Column(name="CODPLA", nullable=false, length=2) ), 
        @AttributeOverride(name="tipoEmp", column=@Column(name="TIPO_EMP", nullable=false, length=2) ), 
        @AttributeOverride(name="noEmple", column=@Column(name="NO_EMPLE", nullable=false, length=10) ), 
        @AttributeOverride(name="noCpto", column=@Column(name="NO_CPTO", nullable=false, length=10) ) } )
    public ArplelnomDetId getId() {
        return this.id;
    }
    
    public void setId(ArplelnomDetId id) {
        this.id = id;
    }

    
    @Column(name="TOT_HORAS", length=10)
    public String getTotHoras() {
        return this.totHoras;
    }
    
    public void setTotHoras(String totHoras) {
        this.totHoras = totHoras;
    }

    
    @Column(name="DIAS", length=10)
    public String getDias() {
        return this.dias;
    }
    
    public void setDias(String dias) {
        this.dias = dias;
    }

    
    @Column(name="MONTO", precision=12)
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

    
    @Column(name="TOT_ASIG", precision=12)
    public BigDecimal getTotAsig() {
        return this.totAsig;
    }
    
    public void setTotAsig(BigDecimal totAsig) {
        this.totAsig = totAsig;
    }

    
    @Column(name="TOT_DED", precision=12)
    public BigDecimal getTotDed() {
        return this.totDed;
    }
    
    public void setTotDed(BigDecimal totDed) {
        this.totDed = totDed;
    }

    
    @Column(name="TOT_NETO", precision=12)
    public BigDecimal getTotNeto() {
        return this.totNeto;
    }
    
    public void setTotNeto(BigDecimal totNeto) {
        this.totNeto = totNeto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECH_REG", length=7)
    public Date getFechReg() {
        return this.fechReg;
    }
    
    public void setFechReg(Date fechReg) {
        this.fechReg = fechReg;
    }

    
    @Column(name="USER_REG", length=30)
    public String getUserReg() {
        return this.userReg;
    }
    
    public void setUserReg(String userReg) {
        this.userReg = userReg;
    }




}


