package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arplpgd generated by hbm2java
 */
@Entity
@Table(name="ARPLPGD"
    ,schema="DESA46"
)
public class Arplpgd  implements java.io.Serializable {


     private String parametroId;
     private String grupoParametro;
     private String etiqueta;
     private String tipoDato;
     private String datoCaracter;
     private BigDecimal datoNumerico;
     private Date datoDate;
     private String formatMask;
     private String datoMinimo;
     private String datoMaximo;
     private String requerido;
     private String modificable;
     private String soloEtiqueta;
     private Short noLinea;

    public Arplpgd() {
    }

	
    public Arplpgd(String parametroId) {
        this.parametroId = parametroId;
    }
    public Arplpgd(String parametroId, String grupoParametro, String etiqueta, String tipoDato, String datoCaracter, BigDecimal datoNumerico, Date datoDate, String formatMask, String datoMinimo, String datoMaximo, String requerido, String modificable, String soloEtiqueta, Short noLinea) {
       this.parametroId = parametroId;
       this.grupoParametro = grupoParametro;
       this.etiqueta = etiqueta;
       this.tipoDato = tipoDato;
       this.datoCaracter = datoCaracter;
       this.datoNumerico = datoNumerico;
       this.datoDate = datoDate;
       this.formatMask = formatMask;
       this.datoMinimo = datoMinimo;
       this.datoMaximo = datoMaximo;
       this.requerido = requerido;
       this.modificable = modificable;
       this.soloEtiqueta = soloEtiqueta;
       this.noLinea = noLinea;
    }
   
     @Id 

    
    @Column(name="PARAMETRO_ID", unique=true, nullable=false, length=16)
    public String getParametroId() {
        return this.parametroId;
    }
    
    public void setParametroId(String parametroId) {
        this.parametroId = parametroId;
    }

    
    @Column(name="GRUPO_PARAMETRO", length=10)
    public String getGrupoParametro() {
        return this.grupoParametro;
    }
    
    public void setGrupoParametro(String grupoParametro) {
        this.grupoParametro = grupoParametro;
    }

    
    @Column(name="ETIQUETA", length=40)
    public String getEtiqueta() {
        return this.etiqueta;
    }
    
    public void setEtiqueta(String etiqueta) {
        this.etiqueta = etiqueta;
    }

    
    @Column(name="TIPO_DATO", length=1)
    public String getTipoDato() {
        return this.tipoDato;
    }
    
    public void setTipoDato(String tipoDato) {
        this.tipoDato = tipoDato;
    }

    
    @Column(name="DATO_CARACTER", length=30)
    public String getDatoCaracter() {
        return this.datoCaracter;
    }
    
    public void setDatoCaracter(String datoCaracter) {
        this.datoCaracter = datoCaracter;
    }

    
    @Column(name="DATO_NUMERICO", precision=17, scale=4)
    public BigDecimal getDatoNumerico() {
        return this.datoNumerico;
    }
    
    public void setDatoNumerico(BigDecimal datoNumerico) {
        this.datoNumerico = datoNumerico;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATO_DATE", length=7)
    public Date getDatoDate() {
        return this.datoDate;
    }
    
    public void setDatoDate(Date datoDate) {
        this.datoDate = datoDate;
    }

    
    @Column(name="FORMAT_MASK", length=20)
    public String getFormatMask() {
        return this.formatMask;
    }
    
    public void setFormatMask(String formatMask) {
        this.formatMask = formatMask;
    }

    
    @Column(name="DATO_MINIMO", length=40)
    public String getDatoMinimo() {
        return this.datoMinimo;
    }
    
    public void setDatoMinimo(String datoMinimo) {
        this.datoMinimo = datoMinimo;
    }

    
    @Column(name="DATO_MAXIMO", length=20)
    public String getDatoMaximo() {
        return this.datoMaximo;
    }
    
    public void setDatoMaximo(String datoMaximo) {
        this.datoMaximo = datoMaximo;
    }

    
    @Column(name="REQUERIDO", length=1)
    public String getRequerido() {
        return this.requerido;
    }
    
    public void setRequerido(String requerido) {
        this.requerido = requerido;
    }

    
    @Column(name="MODIFICABLE", length=1)
    public String getModificable() {
        return this.modificable;
    }
    
    public void setModificable(String modificable) {
        this.modificable = modificable;
    }

    
    @Column(name="SOLO_ETIQUETA", length=1)
    public String getSoloEtiqueta() {
        return this.soloEtiqueta;
    }
    
    public void setSoloEtiqueta(String soloEtiqueta) {
        this.soloEtiqueta = soloEtiqueta;
    }

    
    @Column(name="NO_LINEA", precision=3, scale=0)
    public Short getNoLinea() {
        return this.noLinea;
    }
    
    public void setNoLinea(Short noLinea) {
        this.noLinea = noLinea;
    }




}


