package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arplmovimi generated by hbm2java
 */
@Entity
@Table(name="ARPLMOVIMI"
    ,schema="DESA46"
)
public class Arplmovimi  implements java.io.Serializable {


     private ArplmovimiId id;

    public Arplmovimi() {
    }

    public Arplmovimi(ArplmovimiId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="codigo", column=@Column(name="CODIGO", nullable=false, length=10) ), 
        @AttributeOverride(name="desMovimiento", column=@Column(name="DES_MOVIMIENTO", nullable=false, length=200) ) } )
    public ArplmovimiId getId() {
        return this.id;
    }
    
    public void setId(ArplmovimiId id) {
        this.id = id;
    }




}


