package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ArplconstDet generated by hbm2java
 */
@Entity
@Table(name="ARPLCONST_DET"
    ,schema="DESA46"
)
public class ArplconstDet  implements java.io.Serializable {


     private ArplconstDetId id;
     private BigDecimal valor;

    public ArplconstDet() {
    }

	
    public ArplconstDet(ArplconstDetId id) {
        this.id = id;
    }
    public ArplconstDet(ArplconstDetId id, BigDecimal valor) {
       this.id = id;
       this.valor = valor;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noConst", column=@Column(name="NO_CONST", nullable=false, length=10) ), 
        @AttributeOverride(name="noEmple", column=@Column(name="NO_EMPLE", nullable=false, length=5) ) } )
    public ArplconstDetId getId() {
        return this.id;
    }
    
    public void setId(ArplconstDetId id) {
        this.id = id;
    }

    
    @Column(name="VALOR", precision=12)
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }




}


