package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arplte generated by hbm2java
 */
@Entity
@Table(name="ARPLTE"
    ,schema="DESA46"
)
public class Arplte  implements java.io.Serializable {


     private ArplteId id;
     private String descrip;
     private Integer NHoras;
     private Byte diasTrab;
     private Short horxmes;
     private String claseEmp;
     private String jornada;
     private String tipoCalculoVac;
     private String sabadoEsDescanso;
     private String domingoEsDescanso;

    public Arplte() {
    }

	
    public Arplte(ArplteId id, String jornada, String tipoCalculoVac, String sabadoEsDescanso, String domingoEsDescanso) {
        this.id = id;
        this.jornada = jornada;
        this.tipoCalculoVac = tipoCalculoVac;
        this.sabadoEsDescanso = sabadoEsDescanso;
        this.domingoEsDescanso = domingoEsDescanso;
    }
    public Arplte(ArplteId id, String descrip, Integer NHoras, Byte diasTrab, Short horxmes, String claseEmp, String jornada, String tipoCalculoVac, String sabadoEsDescanso, String domingoEsDescanso) {
       this.id = id;
       this.descrip = descrip;
       this.NHoras = NHoras;
       this.diasTrab = diasTrab;
       this.horxmes = horxmes;
       this.claseEmp = claseEmp;
       this.jornada = jornada;
       this.tipoCalculoVac = tipoCalculoVac;
       this.sabadoEsDescanso = sabadoEsDescanso;
       this.domingoEsDescanso = domingoEsDescanso;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="tipoEmp", column=@Column(name="TIPO_EMP", nullable=false, length=2) ) } )
    public ArplteId getId() {
        return this.id;
    }
    
    public void setId(ArplteId id) {
        this.id = id;
    }

    
    @Column(name="DESCRIP", length=30)
    public String getDescrip() {
        return this.descrip;
    }
    
    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }

    
    @Column(name="N_HORAS", precision=5, scale=0)
    public Integer getNHoras() {
        return this.NHoras;
    }
    
    public void setNHoras(Integer NHoras) {
        this.NHoras = NHoras;
    }

    
    @Column(name="DIAS_TRAB", precision=2, scale=0)
    public Byte getDiasTrab() {
        return this.diasTrab;
    }
    
    public void setDiasTrab(Byte diasTrab) {
        this.diasTrab = diasTrab;
    }

    
    @Column(name="HORXMES", precision=4, scale=0)
    public Short getHorxmes() {
        return this.horxmes;
    }
    
    public void setHorxmes(Short horxmes) {
        this.horxmes = horxmes;
    }

    
    @Column(name="CLASE_EMP", length=1)
    public String getClaseEmp() {
        return this.claseEmp;
    }
    
    public void setClaseEmp(String claseEmp) {
        this.claseEmp = claseEmp;
    }

    
    @Column(name="JORNADA", nullable=false, length=1)
    public String getJornada() {
        return this.jornada;
    }
    
    public void setJornada(String jornada) {
        this.jornada = jornada;
    }

    
    @Column(name="TIPO_CALCULO_VAC", nullable=false, length=1)
    public String getTipoCalculoVac() {
        return this.tipoCalculoVac;
    }
    
    public void setTipoCalculoVac(String tipoCalculoVac) {
        this.tipoCalculoVac = tipoCalculoVac;
    }

    
    @Column(name="SABADO_ES_DESCANSO", nullable=false, length=1)
    public String getSabadoEsDescanso() {
        return this.sabadoEsDescanso;
    }
    
    public void setSabadoEsDescanso(String sabadoEsDescanso) {
        this.sabadoEsDescanso = sabadoEsDescanso;
    }

    
    @Column(name="DOMINGO_ES_DESCANSO", nullable=false, length=1)
    public String getDomingoEsDescanso() {
        return this.domingoEsDescanso;
    }
    
    public void setDomingoEsDescanso(String domingoEsDescanso) {
        this.domingoEsDescanso = domingoEsDescanso;
    }




}


