package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arplasisp generated by hbm2java
 */
@Entity
@Table(name="ARPLASISP"
    ,schema="DESA46"
)
public class Arplasisp  implements java.io.Serializable {


     private ArplasispId id;
     private Date entrada;
     private Date salida;
     private Date horaExtDiurna;
     private Date horaExtNocturna;
     private Date retardos;
     private String feriado;
     private String sabado;
     private String domingo;
     private String vacaciones;
     private Date horaSalPermiso;
     private Date horaEntPermiso;

    public Arplasisp() {
    }

	
    public Arplasisp(ArplasispId id) {
        this.id = id;
    }
    public Arplasisp(ArplasispId id, Date entrada, Date salida, Date horaExtDiurna, Date horaExtNocturna, Date retardos, String feriado, String sabado, String domingo, String vacaciones, Date horaSalPermiso, Date horaEntPermiso) {
       this.id = id;
       this.entrada = entrada;
       this.salida = salida;
       this.horaExtDiurna = horaExtDiurna;
       this.horaExtNocturna = horaExtNocturna;
       this.retardos = retardos;
       this.feriado = feriado;
       this.sabado = sabado;
       this.domingo = domingo;
       this.vacaciones = vacaciones;
       this.horaSalPermiso = horaSalPermiso;
       this.horaEntPermiso = horaEntPermiso;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noEmple", column=@Column(name="NO_EMPLE", nullable=false, length=10) ), 
        @AttributeOverride(name="dia", column=@Column(name="DIA", nullable=false, length=7) ) } )
    public ArplasispId getId() {
        return this.id;
    }
    
    public void setId(ArplasispId id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ENTRADA", length=7)
    public Date getEntrada() {
        return this.entrada;
    }
    
    public void setEntrada(Date entrada) {
        this.entrada = entrada;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="SALIDA", length=7)
    public Date getSalida() {
        return this.salida;
    }
    
    public void setSalida(Date salida) {
        this.salida = salida;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="HORA_EXT_DIURNA", length=7)
    public Date getHoraExtDiurna() {
        return this.horaExtDiurna;
    }
    
    public void setHoraExtDiurna(Date horaExtDiurna) {
        this.horaExtDiurna = horaExtDiurna;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="HORA_EXT_NOCTURNA", length=7)
    public Date getHoraExtNocturna() {
        return this.horaExtNocturna;
    }
    
    public void setHoraExtNocturna(Date horaExtNocturna) {
        this.horaExtNocturna = horaExtNocturna;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RETARDOS", length=7)
    public Date getRetardos() {
        return this.retardos;
    }
    
    public void setRetardos(Date retardos) {
        this.retardos = retardos;
    }

    
    @Column(name="FERIADO", length=1)
    public String getFeriado() {
        return this.feriado;
    }
    
    public void setFeriado(String feriado) {
        this.feriado = feriado;
    }

    
    @Column(name="SABADO", length=1)
    public String getSabado() {
        return this.sabado;
    }
    
    public void setSabado(String sabado) {
        this.sabado = sabado;
    }

    
    @Column(name="DOMINGO", length=1)
    public String getDomingo() {
        return this.domingo;
    }
    
    public void setDomingo(String domingo) {
        this.domingo = domingo;
    }

    
    @Column(name="VACACIONES", length=1)
    public String getVacaciones() {
        return this.vacaciones;
    }
    
    public void setVacaciones(String vacaciones) {
        this.vacaciones = vacaciones;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="HORA_SAL_PERMISO", length=7)
    public Date getHoraSalPermiso() {
        return this.horaSalPermiso;
    }
    
    public void setHoraSalPermiso(Date horaSalPermiso) {
        this.horaSalPermiso = horaSalPermiso;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="HORA_ENT_PERMISO", length=7)
    public Date getHoraEntPermiso() {
        return this.horaEntPermiso;
    }
    
    public void setHoraEntPermiso(Date horaEntPermiso) {
        this.horaEntPermiso = horaEntPermiso;
    }




}


