package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arplmd generated by hbm2java
 */
@Entity
@Table(name="ARPLMD"
    ,schema="DESA46"
)
public class Arplmd  implements java.io.Serializable {


     private ArplmdId id;
     private String descri;
     private String tipo;
     private String indivi;
     private BigDecimal monto;
     private String aplicaQuinta;
     private String estado;
     private String soloCia;
     private String aplicaA;
     private String cuentaPasivo;
     private String cuentaGasto;
     private Short prioridad;
     private String cuandoAplica;
     private String abrev;
     private String otrasDed;
     private String aplicaRenta;
     private String aplicaIncap;
     private String tipoRefe;
     private String grupoIng;
     private String formulaId;
     private String indCalculo;
     private String comentario;
     private String codAnticipo;
     private String reintegrable;
     private String beneficiario;
     private String cuandoSeReintegra;
     private String codigoRetencion;

    public Arplmd() {
    }

	
    public Arplmd(ArplmdId id, String soloCia) {
        this.id = id;
        this.soloCia = soloCia;
    }
    public Arplmd(ArplmdId id, String descri, String tipo, String indivi, BigDecimal monto, String aplicaQuinta, String estado, String soloCia, String aplicaA, String cuentaPasivo, String cuentaGasto, Short prioridad, String cuandoAplica, String abrev, String otrasDed, String aplicaRenta, String aplicaIncap, String tipoRefe, String grupoIng, String formulaId, String indCalculo, String comentario, String codAnticipo, String reintegrable, String beneficiario, String cuandoSeReintegra, String codigoRetencion) {
       this.id = id;
       this.descri = descri;
       this.tipo = tipo;
       this.indivi = indivi;
       this.monto = monto;
       this.aplicaQuinta = aplicaQuinta;
       this.estado = estado;
       this.soloCia = soloCia;
       this.aplicaA = aplicaA;
       this.cuentaPasivo = cuentaPasivo;
       this.cuentaGasto = cuentaGasto;
       this.prioridad = prioridad;
       this.cuandoAplica = cuandoAplica;
       this.abrev = abrev;
       this.otrasDed = otrasDed;
       this.aplicaRenta = aplicaRenta;
       this.aplicaIncap = aplicaIncap;
       this.tipoRefe = tipoRefe;
       this.grupoIng = grupoIng;
       this.formulaId = formulaId;
       this.indCalculo = indCalculo;
       this.comentario = comentario;
       this.codAnticipo = codAnticipo;
       this.reintegrable = reintegrable;
       this.beneficiario = beneficiario;
       this.cuandoSeReintegra = cuandoSeReintegra;
       this.codigoRetencion = codigoRetencion;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noDedu", column=@Column(name="NO_DEDU", nullable=false, length=3) ) } )
    public ArplmdId getId() {
        return this.id;
    }
    
    public void setId(ArplmdId id) {
        this.id = id;
    }

    
    @Column(name="DESCRI", length=40)
    public String getDescri() {
        return this.descri;
    }
    
    public void setDescri(String descri) {
        this.descri = descri;
    }

    
    @Column(name="TIPO", length=1)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="INDIVI", length=1)
    public String getIndivi() {
        return this.indivi;
    }
    
    public void setIndivi(String indivi) {
        this.indivi = indivi;
    }

    
    @Column(name="MONTO", precision=12, scale=4)
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

    
    @Column(name="APLICA_QUINTA", length=1)
    public String getAplicaQuinta() {
        return this.aplicaQuinta;
    }
    
    public void setAplicaQuinta(String aplicaQuinta) {
        this.aplicaQuinta = aplicaQuinta;
    }

    
    @Column(name="ESTADO", length=1)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="SOLO_CIA", nullable=false, length=1)
    public String getSoloCia() {
        return this.soloCia;
    }
    
    public void setSoloCia(String soloCia) {
        this.soloCia = soloCia;
    }

    
    @Column(name="APLICA_A", length=4)
    public String getAplicaA() {
        return this.aplicaA;
    }
    
    public void setAplicaA(String aplicaA) {
        this.aplicaA = aplicaA;
    }

    
    @Column(name="CUENTA_PASIVO", length=15)
    public String getCuentaPasivo() {
        return this.cuentaPasivo;
    }
    
    public void setCuentaPasivo(String cuentaPasivo) {
        this.cuentaPasivo = cuentaPasivo;
    }

    
    @Column(name="CUENTA_GASTO", length=15)
    public String getCuentaGasto() {
        return this.cuentaGasto;
    }
    
    public void setCuentaGasto(String cuentaGasto) {
        this.cuentaGasto = cuentaGasto;
    }

    
    @Column(name="PRIORIDAD", precision=3, scale=0)
    public Short getPrioridad() {
        return this.prioridad;
    }
    
    public void setPrioridad(Short prioridad) {
        this.prioridad = prioridad;
    }

    
    @Column(name="CUANDO_APLICA", length=1)
    public String getCuandoAplica() {
        return this.cuandoAplica;
    }
    
    public void setCuandoAplica(String cuandoAplica) {
        this.cuandoAplica = cuandoAplica;
    }

    
    @Column(name="ABREV", length=5)
    public String getAbrev() {
        return this.abrev;
    }
    
    public void setAbrev(String abrev) {
        this.abrev = abrev;
    }

    
    @Column(name="OTRAS_DED", length=3)
    public String getOtrasDed() {
        return this.otrasDed;
    }
    
    public void setOtrasDed(String otrasDed) {
        this.otrasDed = otrasDed;
    }

    
    @Column(name="APLICA_RENTA", length=1)
    public String getAplicaRenta() {
        return this.aplicaRenta;
    }
    
    public void setAplicaRenta(String aplicaRenta) {
        this.aplicaRenta = aplicaRenta;
    }

    
    @Column(name="APLICA_INCAP", length=1)
    public String getAplicaIncap() {
        return this.aplicaIncap;
    }
    
    public void setAplicaIncap(String aplicaIncap) {
        this.aplicaIncap = aplicaIncap;
    }

    
    @Column(name="TIPO_REFE", length=2)
    public String getTipoRefe() {
        return this.tipoRefe;
    }
    
    public void setTipoRefe(String tipoRefe) {
        this.tipoRefe = tipoRefe;
    }

    
    @Column(name="GRUPO_ING", length=2)
    public String getGrupoIng() {
        return this.grupoIng;
    }
    
    public void setGrupoIng(String grupoIng) {
        this.grupoIng = grupoIng;
    }

    
    @Column(name="FORMULA_ID", length=10)
    public String getFormulaId() {
        return this.formulaId;
    }
    
    public void setFormulaId(String formulaId) {
        this.formulaId = formulaId;
    }

    
    @Column(name="IND_CALCULO", length=1)
    public String getIndCalculo() {
        return this.indCalculo;
    }
    
    public void setIndCalculo(String indCalculo) {
        this.indCalculo = indCalculo;
    }

    
    @Column(name="COMENTARIO", length=600)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    
    @Column(name="COD_ANTICIPO", length=3)
    public String getCodAnticipo() {
        return this.codAnticipo;
    }
    
    public void setCodAnticipo(String codAnticipo) {
        this.codAnticipo = codAnticipo;
    }

    
    @Column(name="REINTEGRABLE", length=1)
    public String getReintegrable() {
        return this.reintegrable;
    }
    
    public void setReintegrable(String reintegrable) {
        this.reintegrable = reintegrable;
    }

    
    @Column(name="BENEFICIARIO", length=60)
    public String getBeneficiario() {
        return this.beneficiario;
    }
    
    public void setBeneficiario(String beneficiario) {
        this.beneficiario = beneficiario;
    }

    
    @Column(name="CUANDO_SE_REINTEGRA", length=1)
    public String getCuandoSeReintegra() {
        return this.cuandoSeReintegra;
    }
    
    public void setCuandoSeReintegra(String cuandoSeReintegra) {
        this.cuandoSeReintegra = cuandoSeReintegra;
    }

    
    @Column(name="CODIGO_RETENCION", length=2)
    public String getCodigoRetencion() {
        return this.codigoRetencion;
    }
    
    public void setCodigoRetencion(String codigoRetencion) {
        this.codigoRetencion = codigoRetencion;
    }




}


