package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Arplpan generated by hbm2java
 */
@Entity
@Table(name="ARPLPAN"
    ,schema="DESA46"
)
public class Arplpan  implements java.io.Serializable {


     private byte anoAnt;
     private BigDecimal porcentaje;
     private Byte diasVac;
     private BigDecimal porcProviVac;
     private BigDecimal montoAnt;
     private Byte diasBonoVac;

    public Arplpan() {
    }

	
    public Arplpan(byte anoAnt) {
        this.anoAnt = anoAnt;
    }
    public Arplpan(byte anoAnt, BigDecimal porcentaje, Byte diasVac, BigDecimal porcProviVac, BigDecimal montoAnt, Byte diasBonoVac) {
       this.anoAnt = anoAnt;
       this.porcentaje = porcentaje;
       this.diasVac = diasVac;
       this.porcProviVac = porcProviVac;
       this.montoAnt = montoAnt;
       this.diasBonoVac = diasBonoVac;
    }
   
     @Id 

    
    @Column(name="ANO_ANT", unique=true, nullable=false, precision=2, scale=0)
    public byte getAnoAnt() {
        return this.anoAnt;
    }
    
    public void setAnoAnt(byte anoAnt) {
        this.anoAnt = anoAnt;
    }

    
    @Column(name="PORCENTAJE", precision=5)
    public BigDecimal getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(BigDecimal porcentaje) {
        this.porcentaje = porcentaje;
    }

    
    @Column(name="DIAS_VAC", precision=2, scale=0)
    public Byte getDiasVac() {
        return this.diasVac;
    }
    
    public void setDiasVac(Byte diasVac) {
        this.diasVac = diasVac;
    }

    
    @Column(name="PORC_PROVI_VAC", precision=7, scale=4)
    public BigDecimal getPorcProviVac() {
        return this.porcProviVac;
    }
    
    public void setPorcProviVac(BigDecimal porcProviVac) {
        this.porcProviVac = porcProviVac;
    }

    
    @Column(name="MONTO_ANT", precision=17)
    public BigDecimal getMontoAnt() {
        return this.montoAnt;
    }
    
    public void setMontoAnt(BigDecimal montoAnt) {
        this.montoAnt = montoAnt;
    }

    
    @Column(name="DIAS_BONO_VAC", precision=2, scale=0)
    public Byte getDiasBonoVac() {
        return this.diasBonoVac;
    }
    
    public void setDiasBonoVac(Byte diasBonoVac) {
        this.diasBonoVac = diasBonoVac;
    }




}


