package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arplcp generated by hbm2java
 */
@Entity
@Table(name="ARPLCP"
    ,schema="DESA46"
)
public class Arplcp  implements java.io.Serializable {


     private ArplcpId id;
     private String tipla;
     private String salarial;
     private String descri;
     private Short anoProce;
     private Byte mesProce;
     private Byte noPlani;
     private Date FDesde;
     private Date FHasta;
     private Date FTarjDesde;
     private Date FTarjHasta;
     private Date FCalculo;
     private String tipoEmp;
     private String cuentaPxp;
     private String estado;
     private String indCkAct;
     private BigDecimal redondeo;
     private BigDecimal tcCalculo;
     private String noAsiento;
     private Short diasHabiles;
     private String ultimaPlanilla;
     private String indIngModif;
     private String ctaBcoReintegros;
     private String codProviUtil;
     private String codProviVac;
     private String ctaAjusteSso;
     private String cc1Sso;
     private String cc2Sso;
     private String cc3Sso;
     private BigDecimal totalCheque;
     private BigDecimal totalTransferencia;
     private String manejaComisiones;

    public Arplcp() {
    }

	
    public Arplcp(ArplcpId id, String ultimaPlanilla, String indIngModif) {
        this.id = id;
        this.ultimaPlanilla = ultimaPlanilla;
        this.indIngModif = indIngModif;
    }
    public Arplcp(ArplcpId id, String tipla, String salarial, String descri, Short anoProce, Byte mesProce, Byte noPlani, Date FDesde, Date FHasta, Date FTarjDesde, Date FTarjHasta, Date FCalculo, String tipoEmp, String cuentaPxp, String estado, String indCkAct, BigDecimal redondeo, BigDecimal tcCalculo, String noAsiento, Short diasHabiles, String ultimaPlanilla, String indIngModif, String ctaBcoReintegros, String codProviUtil, String codProviVac, String ctaAjusteSso, String cc1Sso, String cc2Sso, String cc3Sso, BigDecimal totalCheque, BigDecimal totalTransferencia, String manejaComisiones) {
       this.id = id;
       this.tipla = tipla;
       this.salarial = salarial;
       this.descri = descri;
       this.anoProce = anoProce;
       this.mesProce = mesProce;
       this.noPlani = noPlani;
       this.FDesde = FDesde;
       this.FHasta = FHasta;
       this.FTarjDesde = FTarjDesde;
       this.FTarjHasta = FTarjHasta;
       this.FCalculo = FCalculo;
       this.tipoEmp = tipoEmp;
       this.cuentaPxp = cuentaPxp;
       this.estado = estado;
       this.indCkAct = indCkAct;
       this.redondeo = redondeo;
       this.tcCalculo = tcCalculo;
       this.noAsiento = noAsiento;
       this.diasHabiles = diasHabiles;
       this.ultimaPlanilla = ultimaPlanilla;
       this.indIngModif = indIngModif;
       this.ctaBcoReintegros = ctaBcoReintegros;
       this.codProviUtil = codProviUtil;
       this.codProviVac = codProviVac;
       this.ctaAjusteSso = ctaAjusteSso;
       this.cc1Sso = cc1Sso;
       this.cc2Sso = cc2Sso;
       this.cc3Sso = cc3Sso;
       this.totalCheque = totalCheque;
       this.totalTransferencia = totalTransferencia;
       this.manejaComisiones = manejaComisiones;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="codpla", column=@Column(name="CODPLA", nullable=false, length=10) ) } )
    public ArplcpId getId() {
        return this.id;
    }
    
    public void setId(ArplcpId id) {
        this.id = id;
    }

    
    @Column(name="TIPLA", length=2)
    public String getTipla() {
        return this.tipla;
    }
    
    public void setTipla(String tipla) {
        this.tipla = tipla;
    }

    
    @Column(name="SALARIAL", length=1)
    public String getSalarial() {
        return this.salarial;
    }
    
    public void setSalarial(String salarial) {
        this.salarial = salarial;
    }

    
    @Column(name="DESCRI", length=30)
    public String getDescri() {
        return this.descri;
    }
    
    public void setDescri(String descri) {
        this.descri = descri;
    }

    
    @Column(name="ANO_PROCE", precision=4, scale=0)
    public Short getAnoProce() {
        return this.anoProce;
    }
    
    public void setAnoProce(Short anoProce) {
        this.anoProce = anoProce;
    }

    
    @Column(name="MES_PROCE", precision=2, scale=0)
    public Byte getMesProce() {
        return this.mesProce;
    }
    
    public void setMesProce(Byte mesProce) {
        this.mesProce = mesProce;
    }

    
    @Column(name="NO_PLANI", precision=2, scale=0)
    public Byte getNoPlani() {
        return this.noPlani;
    }
    
    public void setNoPlani(Byte noPlani) {
        this.noPlani = noPlani;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="F_DESDE", length=7)
    public Date getFDesde() {
        return this.FDesde;
    }
    
    public void setFDesde(Date FDesde) {
        this.FDesde = FDesde;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="F_HASTA", length=7)
    public Date getFHasta() {
        return this.FHasta;
    }
    
    public void setFHasta(Date FHasta) {
        this.FHasta = FHasta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="F_TARJ_DESDE", length=7)
    public Date getFTarjDesde() {
        return this.FTarjDesde;
    }
    
    public void setFTarjDesde(Date FTarjDesde) {
        this.FTarjDesde = FTarjDesde;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="F_TARJ_HASTA", length=7)
    public Date getFTarjHasta() {
        return this.FTarjHasta;
    }
    
    public void setFTarjHasta(Date FTarjHasta) {
        this.FTarjHasta = FTarjHasta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="F_CALCULO", length=7)
    public Date getFCalculo() {
        return this.FCalculo;
    }
    
    public void setFCalculo(Date FCalculo) {
        this.FCalculo = FCalculo;
    }

    
    @Column(name="TIPO_EMP", length=2)
    public String getTipoEmp() {
        return this.tipoEmp;
    }
    
    public void setTipoEmp(String tipoEmp) {
        this.tipoEmp = tipoEmp;
    }

    
    @Column(name="CUENTA_PXP", length=15)
    public String getCuentaPxp() {
        return this.cuentaPxp;
    }
    
    public void setCuentaPxp(String cuentaPxp) {
        this.cuentaPxp = cuentaPxp;
    }

    
    @Column(name="ESTADO", length=1)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="IND_CK_ACT", length=1)
    public String getIndCkAct() {
        return this.indCkAct;
    }
    
    public void setIndCkAct(String indCkAct) {
        this.indCkAct = indCkAct;
    }

    
    @Column(name="REDONDEO", precision=7)
    public BigDecimal getRedondeo() {
        return this.redondeo;
    }
    
    public void setRedondeo(BigDecimal redondeo) {
        this.redondeo = redondeo;
    }

    
    @Column(name="TC_CALCULO", precision=7)
    public BigDecimal getTcCalculo() {
        return this.tcCalculo;
    }
    
    public void setTcCalculo(BigDecimal tcCalculo) {
        this.tcCalculo = tcCalculo;
    }

    
    @Column(name="NO_ASIENTO", length=6)
    public String getNoAsiento() {
        return this.noAsiento;
    }
    
    public void setNoAsiento(String noAsiento) {
        this.noAsiento = noAsiento;
    }

    
    @Column(name="DIAS_HABILES", precision=3, scale=0)
    public Short getDiasHabiles() {
        return this.diasHabiles;
    }
    
    public void setDiasHabiles(Short diasHabiles) {
        this.diasHabiles = diasHabiles;
    }

    
    @Column(name="ULTIMA_PLANILLA", nullable=false, length=1)
    public String getUltimaPlanilla() {
        return this.ultimaPlanilla;
    }
    
    public void setUltimaPlanilla(String ultimaPlanilla) {
        this.ultimaPlanilla = ultimaPlanilla;
    }

    
    @Column(name="IND_ING_MODIF", nullable=false, length=1)
    public String getIndIngModif() {
        return this.indIngModif;
    }
    
    public void setIndIngModif(String indIngModif) {
        this.indIngModif = indIngModif;
    }

    
    @Column(name="CTA_BCO_REINTEGROS", length=15)
    public String getCtaBcoReintegros() {
        return this.ctaBcoReintegros;
    }
    
    public void setCtaBcoReintegros(String ctaBcoReintegros) {
        this.ctaBcoReintegros = ctaBcoReintegros;
    }

    
    @Column(name="COD_PROVI_UTIL", length=3)
    public String getCodProviUtil() {
        return this.codProviUtil;
    }
    
    public void setCodProviUtil(String codProviUtil) {
        this.codProviUtil = codProviUtil;
    }

    
    @Column(name="COD_PROVI_VAC", length=3)
    public String getCodProviVac() {
        return this.codProviVac;
    }
    
    public void setCodProviVac(String codProviVac) {
        this.codProviVac = codProviVac;
    }

    
    @Column(name="CTA_AJUSTE_SSO", length=15)
    public String getCtaAjusteSso() {
        return this.ctaAjusteSso;
    }
    
    public void setCtaAjusteSso(String ctaAjusteSso) {
        this.ctaAjusteSso = ctaAjusteSso;
    }

    
    @Column(name="CC1_SSO", length=3)
    public String getCc1Sso() {
        return this.cc1Sso;
    }
    
    public void setCc1Sso(String cc1Sso) {
        this.cc1Sso = cc1Sso;
    }

    
    @Column(name="CC2_SSO", length=3)
    public String getCc2Sso() {
        return this.cc2Sso;
    }
    
    public void setCc2Sso(String cc2Sso) {
        this.cc2Sso = cc2Sso;
    }

    
    @Column(name="CC3_SSO", length=3)
    public String getCc3Sso() {
        return this.cc3Sso;
    }
    
    public void setCc3Sso(String cc3Sso) {
        this.cc3Sso = cc3Sso;
    }

    
    @Column(name="TOTAL_CHEQUE", precision=15)
    public BigDecimal getTotalCheque() {
        return this.totalCheque;
    }
    
    public void setTotalCheque(BigDecimal totalCheque) {
        this.totalCheque = totalCheque;
    }

    
    @Column(name="TOTAL_TRANSFERENCIA", precision=15)
    public BigDecimal getTotalTransferencia() {
        return this.totalTransferencia;
    }
    
    public void setTotalTransferencia(BigDecimal totalTransferencia) {
        this.totalTransferencia = totalTransferencia;
    }

    
    @Column(name="MANEJA_COMISIONES", length=1)
    public String getManejaComisiones() {
        return this.manejaComisiones;
    }
    
    public void setManejaComisiones(String manejaComisiones) {
        this.manejaComisiones = manejaComisiones;
    }




}


