package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arplmi generated by hbm2java
 */
@Entity
@Table(name="ARPLMI"
    ,schema="DESA46"
)
public class Arplmi  implements java.io.Serializable {


     private ArplmiId id;
     private String usoInterno;
     private String descri;
     private String tipo;
     private String estado;
     private String tipoIng;
     private BigDecimal tasaMult;
     private String abrev;
     private String depSalHora;
     private String otrosIngresos;
     private String apartirDe;
     private String grupoIng;
     private Short prioridad;
     private String cuandoAplica;
     private String aplicaA;
     private String formulaId;
     private String indCalculo;
     private String cuentaContable;
     private String comentario;
     private String indivi;
     private String esExtra;
     private String variable;

    public Arplmi() {
    }

	
    public Arplmi(ArplmiId id) {
        this.id = id;
    }
    public Arplmi(ArplmiId id, String usoInterno, String descri, String tipo, String estado, String tipoIng, BigDecimal tasaMult, String abrev, String depSalHora, String otrosIngresos, String apartirDe, String grupoIng, Short prioridad, String cuandoAplica, String aplicaA, String formulaId, String indCalculo, String cuentaContable, String comentario, String indivi, String esExtra, String variable) {
       this.id = id;
       this.usoInterno = usoInterno;
       this.descri = descri;
       this.tipo = tipo;
       this.estado = estado;
       this.tipoIng = tipoIng;
       this.tasaMult = tasaMult;
       this.abrev = abrev;
       this.depSalHora = depSalHora;
       this.otrosIngresos = otrosIngresos;
       this.apartirDe = apartirDe;
       this.grupoIng = grupoIng;
       this.prioridad = prioridad;
       this.cuandoAplica = cuandoAplica;
       this.aplicaA = aplicaA;
       this.formulaId = formulaId;
       this.indCalculo = indCalculo;
       this.cuentaContable = cuentaContable;
       this.comentario = comentario;
       this.indivi = indivi;
       this.esExtra = esExtra;
       this.variable = variable;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noIngre", column=@Column(name="NO_INGRE", nullable=false, length=3) ) } )
    public ArplmiId getId() {
        return this.id;
    }
    
    public void setId(ArplmiId id) {
        this.id = id;
    }

    
    @Column(name="USO_INTERNO", length=1)
    public String getUsoInterno() {
        return this.usoInterno;
    }
    
    public void setUsoInterno(String usoInterno) {
        this.usoInterno = usoInterno;
    }

    
    @Column(name="DESCRI", length=25)
    public String getDescri() {
        return this.descri;
    }
    
    public void setDescri(String descri) {
        this.descri = descri;
    }

    
    @Column(name="TIPO", length=1)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="ESTADO", length=1)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="TIPO_ING", length=2)
    public String getTipoIng() {
        return this.tipoIng;
    }
    
    public void setTipoIng(String tipoIng) {
        this.tipoIng = tipoIng;
    }

    
    @Column(name="TASA_MULT", precision=12, scale=4)
    public BigDecimal getTasaMult() {
        return this.tasaMult;
    }
    
    public void setTasaMult(BigDecimal tasaMult) {
        this.tasaMult = tasaMult;
    }

    
    @Column(name="ABREV", length=5)
    public String getAbrev() {
        return this.abrev;
    }
    
    public void setAbrev(String abrev) {
        this.abrev = abrev;
    }

    
    @Column(name="DEP_SAL_HORA", length=2)
    public String getDepSalHora() {
        return this.depSalHora;
    }
    
    public void setDepSalHora(String depSalHora) {
        this.depSalHora = depSalHora;
    }

    
    @Column(name="OTROS_INGRESOS", length=3)
    public String getOtrosIngresos() {
        return this.otrosIngresos;
    }
    
    public void setOtrosIngresos(String otrosIngresos) {
        this.otrosIngresos = otrosIngresos;
    }

    
    @Column(name="APARTIR_DE", length=3)
    public String getApartirDe() {
        return this.apartirDe;
    }
    
    public void setApartirDe(String apartirDe) {
        this.apartirDe = apartirDe;
    }

    
    @Column(name="GRUPO_ING", length=2)
    public String getGrupoIng() {
        return this.grupoIng;
    }
    
    public void setGrupoIng(String grupoIng) {
        this.grupoIng = grupoIng;
    }

    
    @Column(name="PRIORIDAD", precision=3, scale=0)
    public Short getPrioridad() {
        return this.prioridad;
    }
    
    public void setPrioridad(Short prioridad) {
        this.prioridad = prioridad;
    }

    
    @Column(name="CUANDO_APLICA", length=1)
    public String getCuandoAplica() {
        return this.cuandoAplica;
    }
    
    public void setCuandoAplica(String cuandoAplica) {
        this.cuandoAplica = cuandoAplica;
    }

    
    @Column(name="APLICA_A", length=4)
    public String getAplicaA() {
        return this.aplicaA;
    }
    
    public void setAplicaA(String aplicaA) {
        this.aplicaA = aplicaA;
    }

    
    @Column(name="FORMULA_ID", length=10)
    public String getFormulaId() {
        return this.formulaId;
    }
    
    public void setFormulaId(String formulaId) {
        this.formulaId = formulaId;
    }

    
    @Column(name="IND_CALCULO", length=1)
    public String getIndCalculo() {
        return this.indCalculo;
    }
    
    public void setIndCalculo(String indCalculo) {
        this.indCalculo = indCalculo;
    }

    
    @Column(name="CUENTA_CONTABLE", length=15)
    public String getCuentaContable() {
        return this.cuentaContable;
    }
    
    public void setCuentaContable(String cuentaContable) {
        this.cuentaContable = cuentaContable;
    }

    
    @Column(name="COMENTARIO", length=600)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    
    @Column(name="INDIVI", length=1)
    public String getIndivi() {
        return this.indivi;
    }
    
    public void setIndivi(String indivi) {
        this.indivi = indivi;
    }

    
    @Column(name="ES_EXTRA", length=1)
    public String getEsExtra() {
        return this.esExtra;
    }
    
    public void setEsExtra(String esExtra) {
        this.esExtra = esExtra;
    }

    
    @Column(name="VARIABLE", length=1)
    public String getVariable() {
        return this.variable;
    }
    
    public void setVariable(String variable) {
        this.variable = variable;
    }




}


