package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arpltper generated by hbm2java
 */
@Entity
@Table(name="ARPLTPER"
    ,schema="DESA46"
)
public class Arpltper  implements java.io.Serializable {


     private ArpltperId id;
     private String descTp;

    public Arpltper() {
    }

	
    public Arpltper(ArpltperId id) {
        this.id = id;
    }
    public Arpltper(ArpltperId id, String descTp) {
       this.id = id;
       this.descTp = descTp;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="codTp", column=@Column(name="COD_TP", nullable=false, length=2) ) } )
    public ArpltperId getId() {
        return this.id;
    }
    
    public void setId(ArpltperId id) {
        this.id = id;
    }

    
    @Column(name="DESC_TP", length=100)
    public String getDescTp() {
        return this.descTp;
    }
    
    public void setDescTp(String descTp) {
        this.descTp = descTp;
    }




}


