package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Arpltit generated by hbm2java
 */
@Entity
@Table(name="ARPLTIT"
    ,schema="DESA46"
)
public class Arpltit  implements java.io.Serializable {


     private String titulo;
     private String descripcion;

    public Arpltit() {
    }

	
    public Arpltit(String titulo) {
        this.titulo = titulo;
    }
    public Arpltit(String titulo, String descripcion) {
       this.titulo = titulo;
       this.descripcion = descripcion;
    }
   
     @Id 

    
    @Column(name="TITULO", unique=true, nullable=false, length=4)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    
    @Column(name="DESCRIPCION", length=25)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


