package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Arplcpto generated by hbm2java
 */
@Entity
@Table(name="ARPLCPTO"
    ,schema="DESA46"
)
public class Arplcpto  implements java.io.Serializable {


     private ArplcptoId id;
     private String descri;
     private String estado;
     private String usoInterno;
     private String historico;
     private String stConcepto;
     private String salidaRecibo;
     private String cuentaContable;
     private String preliminarr;
     private String preliminarf;
     private String elaboracion;

    public Arplcpto() {
    }

	
    public Arplcpto(ArplcptoId id) {
        this.id = id;
    }
    public Arplcpto(ArplcptoId id, String descri, String estado, String usoInterno, String historico, String stConcepto, String salidaRecibo, String cuentaContable, String preliminarr, String preliminarf, String elaboracion) {
       this.id = id;
       this.descri = descri;
       this.estado = estado;
       this.usoInterno = usoInterno;
       this.historico = historico;
       this.stConcepto = stConcepto;
       this.salidaRecibo = salidaRecibo;
       this.cuentaContable = cuentaContable;
       this.preliminarr = preliminarr;
       this.preliminarf = preliminarf;
       this.elaboracion = elaboracion;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="noCpto", column=@Column(name="NO_CPTO", nullable=false, length=10) ), 
        @AttributeOverride(name="tipoMov", column=@Column(name="TIPO_MOV", nullable=false, length=10) ), 
        @AttributeOverride(name="tipo", column=@Column(name="TIPO", nullable=false, length=1) ) } )
    public ArplcptoId getId() {
        return this.id;
    }
    
    public void setId(ArplcptoId id) {
        this.id = id;
    }

    
    @Column(name="DESCRI", length=200)
    public String getDescri() {
        return this.descri;
    }
    
    public void setDescri(String descri) {
        this.descri = descri;
    }

    
    @Column(name="ESTADO", length=1)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="USO_INTERNO", length=1)
    public String getUsoInterno() {
        return this.usoInterno;
    }
    
    public void setUsoInterno(String usoInterno) {
        this.usoInterno = usoInterno;
    }

    
    @Column(name="HISTORICO", length=1)
    public String getHistorico() {
        return this.historico;
    }
    
    public void setHistorico(String historico) {
        this.historico = historico;
    }

    
    @Column(name="ST_CONCEPTO", length=1)
    public String getStConcepto() {
        return this.stConcepto;
    }
    
    public void setStConcepto(String stConcepto) {
        this.stConcepto = stConcepto;
    }

    
    @Column(name="SALIDA_RECIBO", length=200)
    public String getSalidaRecibo() {
        return this.salidaRecibo;
    }
    
    public void setSalidaRecibo(String salidaRecibo) {
        this.salidaRecibo = salidaRecibo;
    }

    
    @Column(name="CUENTA_CONTABLE", length=15)
    public String getCuentaContable() {
        return this.cuentaContable;
    }
    
    public void setCuentaContable(String cuentaContable) {
        this.cuentaContable = cuentaContable;
    }

    
    @Column(name="PRELIMINARR", length=500)
    public String getPreliminarr() {
        return this.preliminarr;
    }
    
    public void setPreliminarr(String preliminarr) {
        this.preliminarr = preliminarr;
    }

    
    @Column(name="PRELIMINARF", length=500)
    public String getPreliminarf() {
        return this.preliminarf;
    }
    
    public void setPreliminarf(String preliminarf) {
        this.preliminarf = preliminarf;
    }

    
    @Column(name="ELABORACION", length=1)
    public String getElaboracion() {
        return this.elaboracion;
    }
    
    public void setElaboracion(String elaboracion) {
        this.elaboracion = elaboracion;
    }




}


