package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ccatalogo generated by hbm2java
 */
@Entity
@Table(name="CCATALOGO"
    ,schema="DESA46"
)
public class Ccatalogo  implements java.io.Serializable {


     private String catalogo;

    public Ccatalogo() {
    }

    public Ccatalogo(String catalogo) {
       this.catalogo = catalogo;
    }
   
     @Id 

    
    @Column(name="CATALOGO", unique=true, nullable=false, length=100)
    public String getCatalogo() {
        return this.catalogo;
    }
    
    public void setCatalogo(String catalogo) {
        this.catalogo = catalogo;
    }




}


