package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Conceptos generated by hbm2java
 */
@Entity
@Table(name="CONCEPTOS"
    ,schema="DESA46"
)
public class Conceptos  implements java.io.Serializable {


     private ConceptosId id;
     private String descripcion;

    public Conceptos() {
    }

	
    public Conceptos(ConceptosId id) {
        this.id = id;
    }
    public Conceptos(ConceptosId id, String descripcion) {
       this.id = id;
       this.descripcion = descripcion;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="concepto", column=@Column(name="CONCEPTO", nullable=false, length=2) ) } )
    public ConceptosId getId() {
        return this.id;
    }
    
    public void setId(ConceptosId id) {
        this.id = id;
    }

    
    @Column(name="DESCRIPCION", length=40)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


