package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ConceptosId generated by hbm2java
 */
@Embeddable
public class ConceptosId  implements java.io.Serializable {


     private String noCia;
     private String concepto;

    public ConceptosId() {
    }

    public ConceptosId(String noCia, String concepto) {
       this.noCia = noCia;
       this.concepto = concepto;
    }
   


    @Column(name="NO_CIA", nullable=false, length=2)
    public String getNoCia() {
        return this.noCia;
    }
    
    public void setNoCia(String noCia) {
        this.noCia = noCia;
    }


    @Column(name="CONCEPTO", nullable=false, length=2)
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ConceptosId) ) return false;
		 ConceptosId castOther = ( ConceptosId ) other; 
         
		 return ( (this.getNoCia()==castOther.getNoCia()) || ( this.getNoCia()!=null && castOther.getNoCia()!=null && this.getNoCia().equals(castOther.getNoCia()) ) )
 && ( (this.getConcepto()==castOther.getConcepto()) || ( this.getConcepto()!=null && castOther.getConcepto()!=null && this.getConcepto().equals(castOther.getConcepto()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNoCia() == null ? 0 : this.getNoCia().hashCode() );
         result = 37 * result + ( getConcepto() == null ? 0 : this.getConcepto().hashCode() );
         return result;
   }   


}


