package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ControlFormu generated by hbm2java
 */
@Entity
@Table(name="CONTROL_FORMU"
    ,schema="DESA46"
)
public class ControlFormu  implements java.io.Serializable {


     private ControlFormuId id;
     private Long siguiente;
     private String serie;
     private String nombreReporte;
     private String impresora;
     private Long numInicial;
     private Long numFinal;
     private String modulo;
     private String indReseteo;
     private Integer reservados;
     private String descripcion;
     private Date fecAutorizacion;
     private String activo;

    public ControlFormu() {
    }

	
    public ControlFormu(ControlFormuId id) {
        this.id = id;
    }
    public ControlFormu(ControlFormuId id, Long siguiente, String serie, String nombreReporte, String impresora, Long numInicial, Long numFinal, String modulo, String indReseteo, Integer reservados, String descripcion, Date fecAutorizacion, String activo) {
       this.id = id;
       this.siguiente = siguiente;
       this.serie = serie;
       this.nombreReporte = nombreReporte;
       this.impresora = impresora;
       this.numInicial = numInicial;
       this.numFinal = numFinal;
       this.modulo = modulo;
       this.indReseteo = indReseteo;
       this.reservados = reservados;
       this.descripcion = descripcion;
       this.fecAutorizacion = fecAutorizacion;
       this.activo = activo;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="formulario", column=@Column(name="FORMULARIO", nullable=false, length=10) ) } )
    public ControlFormuId getId() {
        return this.id;
    }
    
    public void setId(ControlFormuId id) {
        this.id = id;
    }

    
    @Column(name="SIGUIENTE", precision=10, scale=0)
    public Long getSiguiente() {
        return this.siguiente;
    }
    
    public void setSiguiente(Long siguiente) {
        this.siguiente = siguiente;
    }

    
    @Column(name="SERIE", length=15)
    public String getSerie() {
        return this.serie;
    }
    
    public void setSerie(String serie) {
        this.serie = serie;
    }

    
    @Column(name="NOMBRE_REPORTE", length=40)
    public String getNombreReporte() {
        return this.nombreReporte;
    }
    
    public void setNombreReporte(String nombreReporte) {
        this.nombreReporte = nombreReporte;
    }

    
    @Column(name="IMPRESORA")
    public String getImpresora() {
        return this.impresora;
    }
    
    public void setImpresora(String impresora) {
        this.impresora = impresora;
    }

    
    @Column(name="NUM_INICIAL", precision=10, scale=0)
    public Long getNumInicial() {
        return this.numInicial;
    }
    
    public void setNumInicial(Long numInicial) {
        this.numInicial = numInicial;
    }

    
    @Column(name="NUM_FINAL", precision=10, scale=0)
    public Long getNumFinal() {
        return this.numFinal;
    }
    
    public void setNumFinal(Long numFinal) {
        this.numFinal = numFinal;
    }

    
    @Column(name="MODULO", length=2)
    public String getModulo() {
        return this.modulo;
    }
    
    public void setModulo(String modulo) {
        this.modulo = modulo;
    }

    
    @Column(name="IND_RESETEO", length=2)
    public String getIndReseteo() {
        return this.indReseteo;
    }
    
    public void setIndReseteo(String indReseteo) {
        this.indReseteo = indReseteo;
    }

    
    @Column(name="RESERVADOS", precision=5, scale=0)
    public Integer getReservados() {
        return this.reservados;
    }
    
    public void setReservados(Integer reservados) {
        this.reservados = reservados;
    }

    
    @Column(name="DESCRIPCION", length=40)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FEC_AUTORIZACION", length=7)
    public Date getFecAutorizacion() {
        return this.fecAutorizacion;
    }
    
    public void setFecAutorizacion(Date fecAutorizacion) {
        this.fecAutorizacion = fecAutorizacion;
    }

    
    @Column(name="ACTIVO", length=1)
    public String getActivo() {
        return this.activo;
    }
    
    public void setActivo(String activo) {
        this.activo = activo;
    }




}


