package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EncDespacho generated by hbm2java
 */
@Entity
@Table(name="ENC_DESPACHO"
    ,schema="DESA46"
)
public class EncDespacho  implements java.io.Serializable {


     private long noDespacho;
     private String noCliente;
     private String noCia;

    public EncDespacho() {
    }

	
    public EncDespacho(long noDespacho) {
        this.noDespacho = noDespacho;
    }
    public EncDespacho(long noDespacho, String noCliente, String noCia) {
       this.noDespacho = noDespacho;
       this.noCliente = noCliente;
       this.noCia = noCia;
    }
   
     @Id 

    
    @Column(name="NO_DESPACHO", unique=true, nullable=false, precision=17, scale=0)
    public long getNoDespacho() {
        return this.noDespacho;
    }
    
    public void setNoDespacho(long noDespacho) {
        this.noDespacho = noDespacho;
    }

    
    @Column(name="NO_CLIENTE", length=15)
    public String getNoCliente() {
        return this.noCliente;
    }
    
    public void setNoCliente(String noCliente) {
        this.noCliente = noCliente;
    }

    
    @Column(name="NO_CIA", length=2)
    public String getNoCia() {
        return this.noCia;
    }
    
    public void setNoCia(String noCia) {
        this.noCia = noCia;
    }




}


