package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EncTransporte generated by hbm2java
 */
@Entity
@Table(name="ENC_TRANSPORTE"
    ,schema="DESA46"
)
public class EncTransporte  implements java.io.Serializable {


     private long numero;
     private Date fecha;
     private String chofer;
     private String ayudante1;
     private String ayudante2;
     private String vehiculo;
     private Long guia;
     private String zonas;
     private String observacion;
     private String status;
     private String noCia;
     private String ciaTransporte;
     private String almacenes;

    public EncTransporte() {
    }

	
    public EncTransporte(long numero) {
        this.numero = numero;
    }
    public EncTransporte(long numero, Date fecha, String chofer, String ayudante1, String ayudante2, String vehiculo, Long guia, String zonas, String observacion, String status, String noCia, String ciaTransporte, String almacenes) {
       this.numero = numero;
       this.fecha = fecha;
       this.chofer = chofer;
       this.ayudante1 = ayudante1;
       this.ayudante2 = ayudante2;
       this.vehiculo = vehiculo;
       this.guia = guia;
       this.zonas = zonas;
       this.observacion = observacion;
       this.status = status;
       this.noCia = noCia;
       this.ciaTransporte = ciaTransporte;
       this.almacenes = almacenes;
    }
   
     @Id 

    
    @Column(name="NUMERO", unique=true, nullable=false, precision=17, scale=0)
    public long getNumero() {
        return this.numero;
    }
    
    public void setNumero(long numero) {
        this.numero = numero;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", length=7)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="CHOFER", length=10)
    public String getChofer() {
        return this.chofer;
    }
    
    public void setChofer(String chofer) {
        this.chofer = chofer;
    }

    
    @Column(name="AYUDANTE1", length=10)
    public String getAyudante1() {
        return this.ayudante1;
    }
    
    public void setAyudante1(String ayudante1) {
        this.ayudante1 = ayudante1;
    }

    
    @Column(name="AYUDANTE2", length=10)
    public String getAyudante2() {
        return this.ayudante2;
    }
    
    public void setAyudante2(String ayudante2) {
        this.ayudante2 = ayudante2;
    }

    
    @Column(name="VEHICULO", length=10)
    public String getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(String vehiculo) {
        this.vehiculo = vehiculo;
    }

    
    @Column(name="GUIA", precision=17, scale=0)
    public Long getGuia() {
        return this.guia;
    }
    
    public void setGuia(Long guia) {
        this.guia = guia;
    }

    
    @Column(name="ZONAS", length=10)
    public String getZonas() {
        return this.zonas;
    }
    
    public void setZonas(String zonas) {
        this.zonas = zonas;
    }

    
    @Column(name="OBSERVACION", length=500)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    
    @Column(name="STATUS", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="NO_CIA", length=2)
    public String getNoCia() {
        return this.noCia;
    }
    
    public void setNoCia(String noCia) {
        this.noCia = noCia;
    }

    
    @Column(name="CIA_TRANSPORTE", length=10)
    public String getCiaTransporte() {
        return this.ciaTransporte;
    }
    
    public void setCiaTransporte(String ciaTransporte) {
        this.ciaTransporte = ciaTransporte;
    }

    
    @Column(name="ALMACENES", length=10)
    public String getAlmacenes() {
        return this.almacenes;
    }
    
    public void setAlmacenes(String almacenes) {
        this.almacenes = almacenes;
    }




}


