package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Grupos generated by hbm2java
 */
@Entity
@Table(name="GRUPOS"
    ,schema="DESA46"
)
public class Grupos  implements java.io.Serializable {


     private GruposId id;
     private String descripcion;
     private String metodoCosto;
     private String indProdServ;

    public Grupos() {
    }

	
    public Grupos(GruposId id) {
        this.id = id;
    }
    public Grupos(GruposId id, String descripcion, String metodoCosto, String indProdServ) {
       this.id = id;
       this.descripcion = descripcion;
       this.metodoCosto = metodoCosto;
       this.indProdServ = indProdServ;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ), 
        @AttributeOverride(name="grupo", column=@Column(name="GRUPO", nullable=false, length=6) ) } )
    public GruposId getId() {
        return this.id;
    }
    
    public void setId(GruposId id) {
        this.id = id;
    }

    
    @Column(name="DESCRIPCION", length=30)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="METODO_COSTO", length=1)
    public String getMetodoCosto() {
        return this.metodoCosto;
    }
    
    public void setMetodoCosto(String metodoCosto) {
        this.metodoCosto = metodoCosto;
    }

    
    @Column(name="IND_PROD_SERV", length=1)
    public String getIndProdServ() {
        return this.indProdServ;
    }
    
    public void setIndProdServ(String indProdServ) {
        this.indProdServ = indProdServ;
    }




}


