package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ManTransporte generated by hbm2java
 */
@Entity
@Table(name="MAN_TRANSPORTE"
    ,schema="DESA46"
)
public class ManTransporte  implements java.io.Serializable {


     private String codTransporte;
     private String descripcion;
     private String tipo;

    public ManTransporte() {
    }

	
    public ManTransporte(String codTransporte) {
        this.codTransporte = codTransporte;
    }
    public ManTransporte(String codTransporte, String descripcion, String tipo) {
       this.codTransporte = codTransporte;
       this.descripcion = descripcion;
       this.tipo = tipo;
    }
   
     @Id 

    
    @Column(name="COD_TRANSPORTE", unique=true, nullable=false, length=10)
    public String getCodTransporte() {
        return this.codTransporte;
    }
    
    public void setCodTransporte(String codTransporte) {
        this.codTransporte = codTransporte;
    }

    
    @Column(name="DESCRIPCION", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="TIPO", length=1)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


