package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MovEfe generated by hbm2java
 */
@Entity
@Table(name="MOV_EFE"
    ,schema="DESA46"
)
public class MovEfe  implements java.io.Serializable {


     private MovEfeId id;
     private Date fechaDoc;
     private Date fecha;
     private String referencia;
     private String descripcion;
     private String tipoMov;
     private BigDecimal monto;
     private String status;
     private String usuario;
     private String anoCurso;
     private String mesCurso;

    public MovEfe() {
    }

	
    public MovEfe(MovEfeId id) {
        this.id = id;
    }
    public MovEfe(MovEfeId id, Date fechaDoc, Date fecha, String referencia, String descripcion, String tipoMov, BigDecimal monto, String status, String usuario, String anoCurso, String mesCurso) {
       this.id = id;
       this.fechaDoc = fechaDoc;
       this.fecha = fecha;
       this.referencia = referencia;
       this.descripcion = descripcion;
       this.tipoMov = tipoMov;
       this.monto = monto;
       this.status = status;
       this.usuario = usuario;
       this.anoCurso = anoCurso;
       this.mesCurso = mesCurso;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="operacion", column=@Column(name="OPERACION", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="noCia", column=@Column(name="NO_CIA", nullable=false, length=2) ) } )
    public MovEfeId getId() {
        return this.id;
    }
    
    public void setId(MovEfeId id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_DOC", length=7)
    public Date getFechaDoc() {
        return this.fechaDoc;
    }
    
    public void setFechaDoc(Date fechaDoc) {
        this.fechaDoc = fechaDoc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", length=7)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="REFERENCIA", length=20)
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }

    
    @Column(name="DESCRIPCION", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="TIPO_MOV", length=1)
    public String getTipoMov() {
        return this.tipoMov;
    }
    
    public void setTipoMov(String tipoMov) {
        this.tipoMov = tipoMov;
    }

    
    @Column(name="MONTO", precision=17)
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

    
    @Column(name="STATUS", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="USUARIO", length=20)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="ANO_CURSO", length=4)
    public String getAnoCurso() {
        return this.anoCurso;
    }
    
    public void setAnoCurso(String anoCurso) {
        this.anoCurso = anoCurso;
    }

    
    @Column(name="MES_CURSO", length=2)
    public String getMesCurso() {
        return this.mesCurso;
    }
    
    public void setMesCurso(String mesCurso) {
        this.mesCurso = mesCurso;
    }




}


