package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MovEfeId generated by hbm2java
 */
@Embeddable
public class MovEfeId  implements java.io.Serializable {


     private long operacion;
     private String noCia;

    public MovEfeId() {
    }

    public MovEfeId(long operacion, String noCia) {
       this.operacion = operacion;
       this.noCia = noCia;
    }
   


    @Column(name="OPERACION", nullable=false, precision=10, scale=0)
    public long getOperacion() {
        return this.operacion;
    }
    
    public void setOperacion(long operacion) {
        this.operacion = operacion;
    }


    @Column(name="NO_CIA", nullable=false, length=2)
    public String getNoCia() {
        return this.noCia;
    }
    
    public void setNoCia(String noCia) {
        this.noCia = noCia;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MovEfeId) ) return false;
		 MovEfeId castOther = ( MovEfeId ) other; 
         
		 return (this.getOperacion()==castOther.getOperacion())
 && ( (this.getNoCia()==castOther.getNoCia()) || ( this.getNoCia()!=null && castOther.getNoCia()!=null && this.getNoCia().equals(castOther.getNoCia()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getOperacion();
         result = 37 * result + ( getNoCia() == null ? 0 : this.getNoCia().hashCode() );
         return result;
   }   


}


