package com.nafsolver.entity;
// Generated 15/06/2019 08:00:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuCiaId generated by hbm2java
 */
@Embeddable
public class UsuCiaId  implements java.io.Serializable {


     private String noCia;
     private String idUsu;
     private String modulo;

    public UsuCiaId() {
    }

    public UsuCiaId(String noCia, String idUsu, String modulo) {
       this.noCia = noCia;
       this.idUsu = idUsu;
       this.modulo = modulo;
    }
   


    @Column(name="NO_CIA", nullable=false, length=2)
    public String getNoCia() {
        return this.noCia;
    }
    
    public void setNoCia(String noCia) {
        this.noCia = noCia;
    }


    @Column(name="ID_USU", nullable=false, length=30)
    public String getIdUsu() {
        return this.idUsu;
    }
    
    public void setIdUsu(String idUsu) {
        this.idUsu = idUsu;
    }


    @Column(name="MODULO", nullable=false, length=2)
    public String getModulo() {
        return this.modulo;
    }
    
    public void setModulo(String modulo) {
        this.modulo = modulo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuCiaId) ) return false;
		 UsuCiaId castOther = ( UsuCiaId ) other; 
         
		 return ( (this.getNoCia()==castOther.getNoCia()) || ( this.getNoCia()!=null && castOther.getNoCia()!=null && this.getNoCia().equals(castOther.getNoCia()) ) )
 && ( (this.getIdUsu()==castOther.getIdUsu()) || ( this.getIdUsu()!=null && castOther.getIdUsu()!=null && this.getIdUsu().equals(castOther.getIdUsu()) ) )
 && ( (this.getModulo()==castOther.getModulo()) || ( this.getModulo()!=null && castOther.getModulo()!=null && this.getModulo().equals(castOther.getModulo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNoCia() == null ? 0 : this.getNoCia().hashCode() );
         result = 37 * result + ( getIdUsu() == null ? 0 : this.getIdUsu().hashCode() );
         result = 37 * result + ( getModulo() == null ? 0 : this.getModulo().hashCode() );
         return result;
   }   


}


